SMTStabilizer API: stabilizer::api::SMTStabilizerOptions Class Reference
stabilizer::api::SMTStabilizerOptions Class Reference
Public options for the SMTStabilizer API.
#include <stabilizer_api.h>
Public Member Functions
SMTStabilizerOptions ()=default
void set_rewrite (bool rewrite) noexcept
bool get_rewrite () const noexcept
void set_context_propagation (bool value) noexcept
bool get_context_propagation () const noexcept
void set_subgraph_pruning (bool value) noexcept
bool get_subgraph_pruning () const noexcept
Private Attributes
bool d_rewrite = true
bool d_context_propagation = true
bool d_subgraph_pruning = true
Detailed Description
Public options for the SMTStabilizer API.
This type is intentionally independent from parser::GlobalOptions so that external users can control only the stable API surface.
The default configuration keeps the current behavior of the command-line tool: rewrite is enabled, context propagation is enabled, and subgraph pruning is enabled.
Definition at line 41 of file stabilizer_api.h.
Constructor & Destructor Documentation
SMTStabilizerOptions()
stabilizer::api::SMTStabilizerOptions::SMTStabilizerOptions () default
Member Function Documentation
get_context_propagation()
bool stabilizer::api::SMTStabilizerOptions::get_context_propagation () const inline noexcept
Return whether context propagation is enabled in the kernel stage.
Definition at line 53 of file stabilizer_api.h.
References d_context_propagation.
Referenced by stabilizer::api::SMTStabilizer::run_pipeline(), stabilizer_get_context_propagation(), and stabilizer_options_get_context_propagation().
get_rewrite()
bool stabilizer::api::SMTStabilizerOptions::get_rewrite () const inline noexcept
Return whether parser-side rewrite normalization is enabled.
Definition at line 48 of file stabilizer_api.h.
References d_rewrite.
Referenced by stabilizer::api::SMTStabilizer::configure_parser(), stabilizer_get_rewrite(), and stabilizer_options_get_rewrite().
get_subgraph_pruning()
bool stabilizer::api::SMTStabilizerOptions::get_subgraph_pruning () const inline noexcept
Return whether subgraph pruning is enabled in the kernel stage.
Definition at line 58 of file stabilizer_api.h.
References d_subgraph_pruning.
Referenced by stabilizer::api::SMTStabilizer::run_pipeline(), stabilizer_get_subgraph_pruning(), and stabilizer_options_get_subgraph_pruning().
set_context_propagation()
void stabilizer::api::SMTStabilizerOptions::set_context_propagation (bool value) inline noexcept
Enable or disable context propagation in the kernel stage.
Definition at line 51 of file stabilizer_api.h.
References d_context_propagation.
Referenced by stabilizer_options_set_context_propagation().
set_rewrite()
void stabilizer::api::SMTStabilizerOptions::set_rewrite (bool rewrite) inline noexcept
Enable or disable parser-side rewrite normalization.
Definition at line 46 of file stabilizer_api.h.
References d_rewrite.
Referenced by stabilizer_options_set_rewrite().
set_subgraph_pruning()
void stabilizer::api::SMTStabilizerOptions::set_subgraph_pruning (bool value) inline noexcept
Enable or disable subgraph pruning in the kernel stage.
Definition at line 56 of file stabilizer_api.h.
References d_subgraph_pruning.
Referenced by stabilizer_options_set_subgraph_pruning().
Member Data Documentation
d_context_propagation
bool stabilizer::api::SMTStabilizerOptions::d_context_propagation = true private
Definition at line 62 of file stabilizer_api.h.
Referenced by get_context_propagation(), and set_context_propagation().
d_rewrite
bool stabilizer::api::SMTStabilizerOptions::d_rewrite = true private
Definition at line 61 of file stabilizer_api.h.
Referenced by get_rewrite(), and set_rewrite().
d_subgraph_pruning
bool stabilizer::api::SMTStabilizerOptions::d_subgraph_pruning = true private
Definition at line 63 of file stabilizer_api.h.
Referenced by get_subgraph_pruning(), and set_subgraph_pruning().
The documentation for this class was generated from the following file:
src/api/stabilizer_api.h