SMTStabilizer API: stabilizer::parser::Parser Class Reference
stabilizer::parser::Parser Class Reference
#include <parser.h>
Classes
struct DTConstructorDecl
struct DTSelectorDecl
struct DTTypeDecl
Public Member Functions
Parser (const std::string &filename)
Constructor with filename.
Parser ()
Default constructor.
~Parser ()
Destructor.
void replaceAssertions (const std::vector< std::shared_ptr< DAGNode >> &new_assertions)
std::shared_ptr< DAGNode > mkUFVNode (const std::string &name, const std::shared_ptr< Sort > &sort)
std::shared_ptr< DAGNode > rebuildLetBindings (const std::shared_ptr< DAGNode > &root)
std::unordered_map< std::string, size_t > & getTempVarNames ()
std::unordered_map< std::string, size_t > & getVarNames ()
std::unordered_map< std::string, std::shared_ptr< DAGNode > > & getFunKeyMap ()
std::vector< std::string > & getFunctionNames ()
std::unordered_map< std::string, std::shared_ptr< Sort > > & getSortNames ()
std::vector< std::vector< DTTypeDecl > > & getDatatypeBlocks ()
void clear_let_key_map ()
bool parse (const std::string &filename)
Parse SMT-LIB2 file.
bool parseStr (const std::string &constraint)
Parse a constraint.
bool assert (const std::string &constraint)
Assert a constraint.
bool assert (std::shared_ptr< DAGNode > node)
Assert a constraint.
std::shared_ptr< DAGNode > mkExpr (const std::string &expression)
Create a DAG node from a string expression.
std::vector< std::shared_ptr< DAGNode > > getAssertions () const
Get all assertions.
std::unordered_map< std::string, std::unordered_set< size_t > > getGroupedAssertions () const
Get grouped assertions.
std::vector< std::vector< std::shared_ptr< DAGNode > > > getAssumptions () const
Get assumptions.
std::vector< std::shared_ptr< DAGNode > > getSoftAssertions () const
Get soft assertions.
std::vector< std::shared_ptr< DAGNode > > getSoftWeights () const
Get soft assertion weights.
std::unordered_map< std::string, std::unordered_set< size_t > > getGroupedSoftAssertions () const
Get grouped soft assertions.
void setOption (const std::string &key, const std::string &value)
Set global options.
void setOption (const std::string &key, const int &value)
void setOption (const std::string &key, const double &value)
void setOption (const std::string &key, const bool &value)
std::shared_ptr< GlobalOptions > getOptions () const
Get global options.
std::vector< std::shared_ptr< DAGNode > > getVariables () const
Get variables.
std::vector< std::shared_ptr< DAGNode > > getDeclaredVariables () const
Get declared variables.
bool isDeclaredVariable (const std::string &var_name) const
Check if a variable is declared.
std::shared_ptr< DAGNode > getVariable (const std::string &var_name)
Get variable.
std::vector< std::shared_ptr< DAGNode > > getFunctions () const
Get functions.
bool isDeclaredFunction (const std::string &func_name) const
Check if a function is declared.
std::shared_ptr< Sort > getSort (const std::vector< std::shared_ptr< DAGNode >> &params)
Get sort.
std::shared_ptr< Sort > getSort (std::shared_ptr< DAGNode > param)
Get sort.
std::shared_ptr< Sort > getSort (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Get sort.
std::shared_ptr< Sort > getSort (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > m)
Get sort.
NODE_KIND getKind (const std::string &s)
Get kind.
NODE_KIND getKind (const std::shared_ptr< DAGNode > &node)
Get kind.
RESULT_TYPE getResultType ()
Get result type.
std::shared_ptr< DAGNode > getResult ()
Get result.
RESULT_TYPE checkSat ()
Check satisfiability.
size_t getNodeCount ()
Get node count.
std::shared_ptr< DAGNode > mkOper (const std::shared_ptr< Sort > &sort, const NODE_KIND &t, std::shared_ptr< DAGNode > p)
Create an operation.
std::shared_ptr< DAGNode > mkOper (const std::shared_ptr< Sort > &sort, const NODE_KIND &t, std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an operation.
std::shared_ptr< DAGNode > mkOper (const std::shared_ptr< Sort > &sort, const NODE_KIND &t, std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > m, std::shared_ptr< DAGNode > r)
Create an operation.
std::shared_ptr< DAGNode > mkOper (const std::shared_ptr< Sort > &sort, const NODE_KIND &t, const std::vector< std::shared_ptr< DAGNode >> &p)
Create an operation.
std::shared_ptr< DAGNode > rewrite (NODE_KIND &t, std::shared_ptr< DAGNode > &p)
Rewrite unary operation node when simplification rule applies.
std::shared_ptr< DAGNode > rewrite (NODE_KIND &t, std::shared_ptr< DAGNode > &l, std::shared_ptr< DAGNode > &r)
Rewrite binary operation node when simplification rule applies.
std::shared_ptr< DAGNode > rewrite (NODE_KIND &t, std::shared_ptr< DAGNode > &l, std::shared_ptr< DAGNode > &m, std::shared_ptr< DAGNode > &r)
Rewrite ternary operation node when simplification rule applies.
std::shared_ptr< DAGNode > rewrite (NODE_KIND &t, std::shared_ptr< DAGNode > &l, std::shared_ptr< DAGNode > &ml, std::shared_ptr< DAGNode > &mr, std::shared_ptr< DAGNode > &r)
Rewrite four-operand operation node when simplification rule applies.
std::shared_ptr< DAGNode > rewrite (NODE_KIND &t, std::vector< std::shared_ptr< DAGNode >> &p)
Rewrite variadic operation node when simplification rule applies.
std::shared_ptr< DAGNode > rewrite_oper (NODE_KIND &t, std::vector< std::shared_ptr< DAGNode >> &p)
Core operation rewrite helper used before node-manager creation.
std::unique_ptr< NodeManager > getNodeManager ()
void rebuild_node_manager ()
std::shared_ptr< DAGNode > mkNode (std::shared_ptr< Sort > sort, NODE_KIND t, std::string name, std::vector< std::shared_ptr< DAGNode >> params)
std::shared_ptr< DAGNode > mkFuncDec (const std::string &name, const std::vector< std::shared_ptr< Sort >> &params, std::shared_ptr< Sort > out_sort)
Create a function declaration.
std::shared_ptr< DAGNode > mkFuncDef (const std::string &name, const std::vector< std::shared_ptr< DAGNode >> &params, std::shared_ptr< Sort > out_sort, std::shared_ptr< DAGNode > body)
Create a function definition.
std::shared_ptr< DAGNode > mkFuncRec (const std::string &name, const std::vector< std::shared_ptr< DAGNode >> &params, std::shared_ptr< Sort > out_sort, std::shared_ptr< DAGNode > body)
Create a recursive function definition.
std::shared_ptr< DAGNode > mkApplyRecFunc (std::shared_ptr< DAGNode > fun, const std::vector< std::shared_ptr< DAGNode >> &params)
Create a recursive function application.
std::shared_ptr< DAGNode > mkPattern (const std::shared_ptr< Sort > &sort, const std::string &name, const std::vector< std::shared_ptr< DAGNode >> &params)
std::shared_ptr< DAGNode > mkNoPattern (const std::shared_ptr< Sort > &sort, const std::string &name, std::shared_ptr< DAGNode > param)
std::shared_ptr< DAGNode > mkWeight (const std::shared_ptr< Sort > &sort, const std::string &name, std::shared_ptr< DAGNode > weight)
std::shared_ptr< DAGNode > mkAttribute (const std::shared_ptr< Sort > &sort, const std::string &name, const std::vector< std::shared_ptr< DAGNode >> &params)
std::shared_ptr< DAGNode > mkApplyUF (const std::shared_ptr< Sort > &sort, const std::string &name, const std::vector< std::shared_ptr< DAGNode >> &params)
Apply an uninterpreted function.
std::shared_ptr< Sort > mkSortDec (const std::string &name, const size_t &arity)
Create a sort declaration.
std::shared_ptr< Sort > mkSortDef (const std::string &name, const std::vector< std::shared_ptr< Sort >> &params, std::shared_ptr< Sort > out_sort)
Create a sort definition.
std::shared_ptr< Sort > mkIntSort ()
Create an integer sort.
std::shared_ptr< Sort > mkRealSort ()
Create a real sort.
std::shared_ptr< Sort > mkBoolSort ()
Create a boolean sort.
std::shared_ptr< Sort > mkStrSort ()
Create a string sort.
std::shared_ptr< Sort > mkRegSort ()
Create a regular expression sort.
std::shared_ptr< Sort > mkRoundingModeSort ()
Create a rounding mode sort.
std::shared_ptr< Sort > mkNatSort ()
Create a natural sort.
std::shared_ptr< Sort > mkBVSort (const size_t &width)
Create a bit-vector sort.
std::shared_ptr< Sort > mkFPSort (const size_t &e, const size_t &s)
Create a floating-point sort.
std::shared_ptr< Sort > mkArraySort (std::shared_ptr< Sort > index, std::shared_ptr< Sort > elem)
Create an array sort.
std::shared_ptr< DAGNode > declareVar (const std::string &name, const std::string &sort)
Declare a variable.
std::shared_ptr< DAGNode > declareVar (const std::string &name, const std::shared_ptr< Sort > &sort)
Declare a variable.
std::shared_ptr< DAGNode > mkTrue ()
Create a true node.
std::shared_ptr< DAGNode > mkFalse ()
Create a false node.
std::shared_ptr< DAGNode > mkUnknown ()
Create an unknown node.
std::shared_ptr< DAGNode > mkEq (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an equality node.
std::shared_ptr< DAGNode > mkDistinct (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a distinct node.
std::shared_ptr< DAGNode > mkConstInt (const std::string &v)
Create an integer constant from string.
std::shared_ptr< DAGNode > mkConstInt (const int &v)
Create an integer constant.
std::shared_ptr< DAGNode > mkConstInt (const Integer &v)
Create an integer constant.
std::shared_ptr< DAGNode > mkConstInt (const Number &v)
Create a real constant from number.
std::shared_ptr< DAGNode > mkConstReal (const std::string &v)
Create a real constant from string.
std::shared_ptr< DAGNode > mkConstReal (const Real &v)
Create a real constant.
std::shared_ptr< DAGNode > mkConstReal (const double &v)
Create a real constant from double.
std::shared_ptr< DAGNode > mkConstReal (const Integer &v)
Create a real constant from integer.
std::shared_ptr< DAGNode > mkConstReal (const Number &v)
Create a real constant from number.
std::shared_ptr< DAGNode > mkConstStr (const std::string &v)
Create a string constant.
std::shared_ptr< DAGNode > mkConstBv (const std::string &v, const size_t &width)
Create a bit-vector constant.
std::shared_ptr< DAGNode > mkConstFp (const std::string &v, const size_t &e, const size_t &s)
Create a floating-point constant.
std::shared_ptr< DAGNode > mkConstFP (const std::string &fp_expr)
Create a floating-point constant from expression.
std::shared_ptr< DAGNode > mkConstReg (const std::string &v)
Create a regular expression constant.
std::shared_ptr< DAGNode > mkRoundingMode (const std::string &mode)
Create a rounding mode constant.
std::shared_ptr< DAGNode > mkVarRoundingMode (const std::string &name)
Create a rounding mode variable.
std::shared_ptr< DAGNode > mkVar (const std::shared_ptr< Sort > &sort, const std::string &name)
Create a variable.
std::shared_ptr< DAGNode > mkPlaceholderVar (const std::string &name)
std::shared_ptr< DAGNode > mkTempVar (const std::shared_ptr< Sort > &sort)
Create a temporary variable.
std::shared_ptr< DAGNode > mkVarBool (const std::string &name)
Create a boolean variable.
std::shared_ptr< DAGNode > mkVarInt (const std::string &name)
Create an integer variable.
std::shared_ptr< DAGNode > mkVarReal (const std::string &name)
Create a real variable.
std::shared_ptr< DAGNode > mkVarBv (const std::string &name, const size_t &width)
Create a bit-vector variable.
std::shared_ptr< DAGNode > mkVarFp (const std::string &name, const size_t &e, const size_t &s)
Create a floating-point variable.
std::shared_ptr< DAGNode > mkVarStr (const std::string &name)
Create a string variable.
std::shared_ptr< DAGNode > mkVarReg (const std::string &name)
Create a regular expression variable.
std::shared_ptr< DAGNode > mkFunParamVar (std::shared_ptr< Sort > sort, const std::string &name)
Create a function parameter variable.
std::shared_ptr< DAGNode > mkArray (const std::string &name, std::shared_ptr< Sort > index, std::shared_ptr< Sort > elem)
Create an array.
std::shared_ptr< DAGNode > mkConstArray (std::shared_ptr< Sort > sort, std::shared_ptr< DAGNode > value)
Create a constant array node.
std::shared_ptr< DAGNode > mkNot (std::shared_ptr< DAGNode > param)
Create a not node.
std::shared_ptr< DAGNode > mkAnd (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an and node.
std::shared_ptr< DAGNode > mkOr (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an or node.
std::shared_ptr< DAGNode > mkImplies (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an implies node.
std::shared_ptr< DAGNode > mkXor (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an xor node.
std::shared_ptr< DAGNode > mkIte (std::shared_ptr< DAGNode > cond, std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an ite node.
std::shared_ptr< DAGNode > mkIte (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an ite node.
std::shared_ptr< DAGNode > mkAdd (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an add node.
std::shared_ptr< DAGNode > mkMul (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an mul node.
std::shared_ptr< DAGNode > mkIand (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an iand node.
std::shared_ptr< DAGNode > mkPow2 (std::shared_ptr< DAGNode > param)
Create an pow2 node.
std::shared_ptr< DAGNode > mkPow (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an pow node.
std::shared_ptr< DAGNode > mkSub (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an sub node.
std::shared_ptr< DAGNode > mkNeg (std::shared_ptr< DAGNode > param)
Create an neg node.
std::shared_ptr< DAGNode > mkDiv (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an div node.
std::shared_ptr< DAGNode > mkDivInt (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an div node.
std::shared_ptr< DAGNode > mkDivReal (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an div node.
std::shared_ptr< DAGNode > mkMod (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an mod node.
std::shared_ptr< DAGNode > mkAbs (std::shared_ptr< DAGNode > param)
Create an abs node.
std::shared_ptr< DAGNode > mkSqrt (std::shared_ptr< DAGNode > param)
Create an sqrt node.
std::shared_ptr< DAGNode > mkSafeSqrt (std::shared_ptr< DAGNode > param)
Create an safeSqrt node.
std::shared_ptr< DAGNode > mkCeil (std::shared_ptr< DAGNode > param)
Create an ceil node.
std::shared_ptr< DAGNode > mkFloor (std::shared_ptr< DAGNode > param)
Create an floor node.
std::shared_ptr< DAGNode > mkRound (std::shared_ptr< DAGNode > param)
Create an round node.
std::shared_ptr< DAGNode > mkExp (std::shared_ptr< DAGNode > param)
Create an exp node.
std::shared_ptr< DAGNode > mkLn (std::shared_ptr< DAGNode > param)
Create an ln node.
std::shared_ptr< DAGNode > mkLg (std::shared_ptr< DAGNode > param)
Create an lg/log10 node.
std::shared_ptr< DAGNode > mkLb (std::shared_ptr< DAGNode > param)
Create an lb/log2 node.
std::shared_ptr< DAGNode > mkLog (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an log node.
std::shared_ptr< DAGNode > mkSin (std::shared_ptr< DAGNode > param)
Create an sin node.
std::shared_ptr< DAGNode > mkCos (std::shared_ptr< DAGNode > param)
Create an cos node.
std::shared_ptr< DAGNode > mkSec (std::shared_ptr< DAGNode > param)
Create an sec node.
std::shared_ptr< DAGNode > mkCsc (std::shared_ptr< DAGNode > param)
Create an csc node.
std::shared_ptr< DAGNode > mkTan (std::shared_ptr< DAGNode > param)
Create an tan node.
std::shared_ptr< DAGNode > mkCot (std::shared_ptr< DAGNode > param)
Create a cot node.
std::shared_ptr< DAGNode > mkAsin (std::shared_ptr< DAGNode > param)
Create an asin node.
std::shared_ptr< DAGNode > mkAcos (std::shared_ptr< DAGNode > param)
Create an acos node.
std::shared_ptr< DAGNode > mkAsec (std::shared_ptr< DAGNode > param)
Create an asec node.
std::shared_ptr< DAGNode > mkAcsc (std::shared_ptr< DAGNode > param)
Create an acsc node.
std::shared_ptr< DAGNode > mkAtan (std::shared_ptr< DAGNode > param)
Create an atan node.
std::shared_ptr< DAGNode > mkAcot (std::shared_ptr< DAGNode > param)
Create an acot node.
std::shared_ptr< DAGNode > mkSinh (std::shared_ptr< DAGNode > param)
Create a sinh node.
std::shared_ptr< DAGNode > mkCosh (std::shared_ptr< DAGNode > param)
Create a cosh node.
std::shared_ptr< DAGNode > mkTanh (std::shared_ptr< DAGNode > param)
Create a tanh node.
std::shared_ptr< DAGNode > mkSech (std::shared_ptr< DAGNode > param)
Create a sech node.
std::shared_ptr< DAGNode > mkCsch (std::shared_ptr< DAGNode > param)
Create a csch node.
std::shared_ptr< DAGNode > mkCoth (std::shared_ptr< DAGNode > param)
Create a coth node.
std::shared_ptr< DAGNode > mkAsinh (std::shared_ptr< DAGNode > param)
Create an asinh node.
std::shared_ptr< DAGNode > mkAcosh (std::shared_ptr< DAGNode > param)
Create an acosh node.
std::shared_ptr< DAGNode > mkAtanh (std::shared_ptr< DAGNode > param)
Create an atanh node.
std::shared_ptr< DAGNode > mkAsech (std::shared_ptr< DAGNode > param)
Create an asech node.
std::shared_ptr< DAGNode > mkAcsch (std::shared_ptr< DAGNode > param)
Create an acsch node.
std::shared_ptr< DAGNode > mkAcoth (std::shared_ptr< DAGNode > param)
Create an acoth node.
std::shared_ptr< DAGNode > mkAtan2 (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an atan2 node.
std::shared_ptr< DAGNode > mkLe (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a le node.
std::shared_ptr< DAGNode > mkLt (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a lt node.
std::shared_ptr< DAGNode > mkGe (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a ge node.
std::shared_ptr< DAGNode > mkGt (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a gt node.
std::shared_ptr< DAGNode > mkToInt (std::shared_ptr< DAGNode > param)
Create a to_int node.
std::shared_ptr< DAGNode > mkToReal (std::shared_ptr< DAGNode > param)
Create a to_real node.
std::shared_ptr< DAGNode > mkIsInt (std::shared_ptr< DAGNode > param)
Create a is_int node.
std::shared_ptr< DAGNode > mkIsDivisible (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a is_divisible node.
std::shared_ptr< DAGNode > mkIsPrime (std::shared_ptr< DAGNode > param)
Create a is_prime node.
std::shared_ptr< DAGNode > mkIsEven (std::shared_ptr< DAGNode > param)
Create a is_even node.
std::shared_ptr< DAGNode > mkIsOdd (std::shared_ptr< DAGNode > param)
Create a is_odd node.
std::shared_ptr< DAGNode > mkPi ()
Create a pi node.
std::shared_ptr< DAGNode > mkE ()
Create a e node.
std::shared_ptr< DAGNode > mkInfinity (std::shared_ptr< Sort > sort)
Create a infinity node.
std::shared_ptr< DAGNode > mkPosInfinity (std::shared_ptr< Sort > sort=nullptr)
Create a positive infinity node.
std::shared_ptr< DAGNode > mkNegInfinity (std::shared_ptr< Sort > sort=nullptr)
Create a negative infinity node.
std::shared_ptr< DAGNode > mkNaN (std::shared_ptr< Sort > sort=nullptr)
Create a NaN node.
std::shared_ptr< DAGNode > mkEpsilon ()
Create a epsilon node.
std::shared_ptr< DAGNode > mkPosEpsilon ()
Create a positive epsilon node.
std::shared_ptr< DAGNode > mkNegEpsilon ()
Create a negative epsilon node.
std::shared_ptr< DAGNode > mkGcd (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a gcd node.
std::shared_ptr< DAGNode > mkLcm (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a lcm node.
std::shared_ptr< DAGNode > mkFact (std::shared_ptr< DAGNode > param)
Create a factorial node.
std::shared_ptr< DAGNode > mkBvNot (std::shared_ptr< DAGNode > param)
Create a bitvector not node.
std::shared_ptr< DAGNode > mkBvAnd (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a bitvector and node.
std::shared_ptr< DAGNode > mkBvOr (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a bitvector or node.
std::shared_ptr< DAGNode > mkBvXor (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a bitvector xor node.
std::shared_ptr< DAGNode > mkBvNand (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector nand node.
std::shared_ptr< DAGNode > mkBvNor (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector nor node.
std::shared_ptr< DAGNode > mkBvComp (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a bitvector comparison node.
std::shared_ptr< DAGNode > mkBvXnor (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector xnor node.
std::shared_ptr< DAGNode > mkBvNeg (std::shared_ptr< DAGNode > param)
Create a bitvector negation node.
std::shared_ptr< DAGNode > mkBvAdd (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a bitvector addition node.
std::shared_ptr< DAGNode > mkBvSub (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector subtraction node.
std::shared_ptr< DAGNode > mkBvMul (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a bitvector multiplication node.
std::shared_ptr< DAGNode > mkBvUdiv (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned division node.
std::shared_ptr< DAGNode > mkBvUrem (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned remainder node.
std::shared_ptr< DAGNode > mkBvUmod (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned modulo node.
std::shared_ptr< DAGNode > mkBvSdiv (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed division node.
std::shared_ptr< DAGNode > mkBvSrem (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed remainder node.
std::shared_ptr< DAGNode > mkBvSmod (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed modulo node.
std::shared_ptr< DAGNode > mkBvShl (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector shift left node.
std::shared_ptr< DAGNode > mkBvLshr (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector logical shift right node.
std::shared_ptr< DAGNode > mkBvAshr (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector arithmetic shift right node.
std::shared_ptr< DAGNode > mkBvConcat (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a bitvector concatenation node.
std::shared_ptr< DAGNode > mkBvExtract (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
Create a bitvector extract node.
std::shared_ptr< DAGNode > mkBvRepeat (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector repeat node.
std::shared_ptr< DAGNode > mkBvZeroExt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector zero extension node.
std::shared_ptr< DAGNode > mkBvSignExt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector sign extension node.
std::shared_ptr< DAGNode > mkBvRotateLeft (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector rotate left node.
std::shared_ptr< DAGNode > mkBvRotateRight (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector rotate right node.
std::shared_ptr< DAGNode > mkBvUlt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned less than node.
std::shared_ptr< DAGNode > mkBvUle (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned less than or equal node.
std::shared_ptr< DAGNode > mkBvUgt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned greater than node.
std::shared_ptr< DAGNode > mkBvUge (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned greater than or equal node.
std::shared_ptr< DAGNode > mkBvSlt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed less than node.
std::shared_ptr< DAGNode > mkBvSle (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed less than or equal node.
std::shared_ptr< DAGNode > mkBvSgt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed greater than node.
std::shared_ptr< DAGNode > mkBvSge (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed greater than or equal node.
std::shared_ptr< DAGNode > mkBvToNat (std::shared_ptr< DAGNode > param)
Create a bitvector to natural number conversion node.
std::shared_ptr< DAGNode > mkNatToBv (std::shared_ptr< DAGNode > param, std::shared_ptr< DAGNode > width)
Create a natural number to bitvector conversion node.
std::shared_ptr< DAGNode > mkBvToInt (std::shared_ptr< DAGNode > param)
Create a bitvector to integer conversion node.
std::shared_ptr< DAGNode > mkUbvToInt (std::shared_ptr< DAGNode > param)
std::shared_ptr< DAGNode > mkSbvToInt (std::shared_ptr< DAGNode > param)
std::shared_ptr< DAGNode > mkIntToBv (std::shared_ptr< DAGNode > param, std::shared_ptr< DAGNode > width)
Create an integer to bitvector conversion node.
std::shared_ptr< DAGNode > mkFpAdd (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a floating-point addition node.
std::shared_ptr< DAGNode > mkFpSub (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a floating-point subtraction node.
std::shared_ptr< DAGNode > mkFpMul (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a floating-point multiplication node.
std::shared_ptr< DAGNode > mkFpDiv (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a floating-point division node.
std::shared_ptr< DAGNode > mkFpAbs (std::shared_ptr< DAGNode > param)
Create a floating-point absolute value node.
std::shared_ptr< DAGNode > mkFpNeg (std::shared_ptr< DAGNode > param)
Create a floating-point negation node.
std::shared_ptr< DAGNode > mkFpRem (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a floating-point remainder node.
std::shared_ptr< DAGNode > mkFpFma (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a floating-point fused multiply-add node.
std::shared_ptr< DAGNode > mkFpSqrt (std::shared_ptr< DAGNode > rm, std::shared_ptr< DAGNode > param)
Create a floating-point square root node.
std::shared_ptr< DAGNode > mkFpSqrt (std::shared_ptr< DAGNode > param)
std::shared_ptr< DAGNode > mkFpRoundToIntegral (std::shared_ptr< DAGNode > rm, std::shared_ptr< DAGNode > param)
Create a floating-point round to integral node.
std::shared_ptr< DAGNode > mkFpRoundToIntegral (std::shared_ptr< DAGNode > param)
std::shared_ptr< DAGNode > mkFpMin (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a floating-point minimum node.
std::shared_ptr< DAGNode > mkFpMax (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a floating-point maximum node.
std::shared_ptr< DAGNode > mkFpLe (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a floating-point less than or equal node.
std::shared_ptr< DAGNode > mkFpLt (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a floating-point less than node.
std::shared_ptr< DAGNode > mkFpGe (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a floating-point greater than or equal node.
std::shared_ptr< DAGNode > mkFpGt (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a floating-point greater than node.
std::shared_ptr< DAGNode > mkFpEq (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a floating-point equality node.
std::shared_ptr< DAGNode > mkFpToUbv (std::shared_ptr< DAGNode > rm, std::shared_ptr< DAGNode > param, std::shared_ptr< DAGNode > size)
Create a floating-point to unsigned bitvector conversion node.
std::shared_ptr< DAGNode > mkFpToSbv (std::shared_ptr< DAGNode > rm, std::shared_ptr< DAGNode > param, std::shared_ptr< DAGNode > size)
Create a floating-point to signed bitvector conversion node.
std::shared_ptr< DAGNode > mkFpToReal (std::shared_ptr< DAGNode > param)
Create a floating-point to real conversion node.
std::shared_ptr< DAGNode > mkToFp (std::shared_ptr< DAGNode > eb, std::shared_ptr< DAGNode > sb, std::shared_ptr< DAGNode > rm, std::shared_ptr< DAGNode > param)
Create a value to floating-point conversion node.
std::shared_ptr< DAGNode > mkToFp (std::shared_ptr< DAGNode > eb, std::shared_ptr< DAGNode > sb, std::shared_ptr< DAGNode > param)
std::shared_ptr< DAGNode > mkToFpUnsigned (std::shared_ptr< DAGNode > eb, std::shared_ptr< DAGNode > sb, std::shared_ptr< DAGNode > rm, std::shared_ptr< DAGNode > param)
std::shared_ptr< DAGNode > mkFpConst (std::shared_ptr< DAGNode > sign, std::shared_ptr< DAGNode > exp, std::shared_ptr< DAGNode > mant)
std::shared_ptr< DAGNode > mkRootObj (std::shared_ptr< DAGNode > expr, int index)
std::shared_ptr< DAGNode > mkRootOfWithInterval (const std::vector< std::shared_ptr< DAGNode >> &coeffs, std::shared_ptr< DAGNode > lower_bound, std::shared_ptr< DAGNode > upper_bound)
std::shared_ptr< DAGNode > mkFpIsNormal (std::shared_ptr< DAGNode > param)
Create a floating-point is-normal check node.
std::shared_ptr< DAGNode > mkFpIsSubnormal (std::shared_ptr< DAGNode > param)
Create a floating-point is-subnormal check node.
std::shared_ptr< DAGNode > mkFpIsZero (std::shared_ptr< DAGNode > param)
Create a floating-point is-zero check node.
std::shared_ptr< DAGNode > mkFpIsInf (std::shared_ptr< DAGNode > param)
Create a floating-point is-infinity check node.
std::shared_ptr< DAGNode > mkFpIsNaN (std::shared_ptr< DAGNode > param)
Create a floating-point is-NaN check node.
std::shared_ptr< DAGNode > mkFpIsNeg (std::shared_ptr< DAGNode > param)
Create a floating-point is-negative check node.
std::shared_ptr< DAGNode > mkFpIsPos (std::shared_ptr< DAGNode > param)
Create a floating-point is-positive check node.
std::shared_ptr< DAGNode > mkSelect (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an array select node.
std::shared_ptr< DAGNode > mkStore (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create an array store node.
std::shared_ptr< DAGNode > mkStrLen (std::shared_ptr< DAGNode > param)
Create a string length node.
std::shared_ptr< DAGNode > mkStrConcat (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a string concatenation node.
std::shared_ptr< DAGNode > mkStrSubstr (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
Create a string substring node.
std::shared_ptr< DAGNode > mkStrPrefixof (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string prefix check node.
std::shared_ptr< DAGNode > mkStrSuffixof (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string suffix check node.
std::shared_ptr< DAGNode > mkStrIndexof (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
Create a string index-of node.
std::shared_ptr< DAGNode > mkStrCharat (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string char-at node.
std::shared_ptr< DAGNode > mkStrUpdate (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string update node.
std::shared_ptr< DAGNode > mkStrReplace (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string replace node.
std::shared_ptr< DAGNode > mkStrReplaceAll (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string replace-all node.
std::shared_ptr< DAGNode > mkStrReplaceReg (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string replace-regex node.
std::shared_ptr< DAGNode > mkStrReplaceRegAll (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string replace-regex-all node.
std::shared_ptr< DAGNode > mkStrIndexofReg (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string indexof-regex node.
std::shared_ptr< DAGNode > mkStrToLower (std::shared_ptr< DAGNode > param)
Create a string to-lower node.
std::shared_ptr< DAGNode > mkStrToUpper (std::shared_ptr< DAGNode > param)
Create a string to-upper node.
std::shared_ptr< DAGNode > mkStrRev (std::shared_ptr< DAGNode > param)
Create a string reverse node.
std::shared_ptr< DAGNode > mkStrSplit (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string split node.
std::shared_ptr< DAGNode > mkStrSplitAt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
std::shared_ptr< DAGNode > mkStrSplitRest (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
std::shared_ptr< DAGNode > mkStrNumSplits (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
std::shared_ptr< DAGNode > mkStrSplitAtRe (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
std::shared_ptr< DAGNode > mkStrSplitRestRe (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
std::shared_ptr< DAGNode > mkStrNumSplitsRe (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
std::shared_ptr< DAGNode > mkStrLt (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a string less-than node.
std::shared_ptr< DAGNode > mkStrLe (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a string less-than-or-equal node.
std::shared_ptr< DAGNode > mkStrGt (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a string greater-than node.
std::shared_ptr< DAGNode > mkStrGe (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a string greater-than-or-equal node.
std::shared_ptr< DAGNode > mkStrInReg (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string in-regex check node.
std::shared_ptr< DAGNode > mkStrContains (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string contains check node.
std::shared_ptr< DAGNode > mkStrIsDigit (std::shared_ptr< DAGNode > param)
Create a string is-digit check node.
std::shared_ptr< DAGNode > mkStrFromInt (std::shared_ptr< DAGNode > param)
Create a string from-integer conversion node.
std::shared_ptr< DAGNode > mkStrToInt (std::shared_ptr< DAGNode > param)
Create a string to-integer conversion node.
std::shared_ptr< DAGNode > mkStrToReg (std::shared_ptr< DAGNode > param)
Create a string to-regex conversion node.
std::shared_ptr< DAGNode > mkStrToCode (std::shared_ptr< DAGNode > param)
Create a string to-code conversion node.
std::shared_ptr< DAGNode > mkStrFromCode (std::shared_ptr< DAGNode > param)
Create a string from-code conversion node.
std::shared_ptr< DAGNode > mkRegNone ()
Create a regex none node.
std::shared_ptr< DAGNode > mkRegAll ()
Create a regex all node.
std::shared_ptr< DAGNode > mkRegAllChar ()
Create a regex allchar node.
std::shared_ptr< DAGNode > mkRegConcat (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a regex concatenation node.
std::shared_ptr< DAGNode > mkRegUnion (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a regex union node.
std::shared_ptr< DAGNode > mkRegInter (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a regex intersection node.
std::shared_ptr< DAGNode > mkRegDiff (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a regex difference node.
std::shared_ptr< DAGNode > mkRegStar (std::shared_ptr< DAGNode > param)
Create a regex star node.
std::shared_ptr< DAGNode > mkRegPlus (std::shared_ptr< DAGNode > param)
Create a regex plus node.
std::shared_ptr< DAGNode > mkRegOpt (std::shared_ptr< DAGNode > param)
Create a regex option node.
std::shared_ptr< DAGNode > mkRegRange (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a regex range node.
std::shared_ptr< DAGNode > mkRegRepeat (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a regex repeat node.
std::shared_ptr< DAGNode > mkRegLoop (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
Create a regex loop node.
std::shared_ptr< DAGNode > mkRegComplement (std::shared_ptr< DAGNode > param)
Create a regex complement node.
std::shared_ptr< DAGNode > mkReplaceReg (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string replace-regex node.
std::shared_ptr< DAGNode > mkReplaceRegAll (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string replace-all-regex node.
std::shared_ptr< DAGNode > mkIndexofReg (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string index-of-regex node.
std::shared_ptr< DAGNode > mkMax (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a max node.
std::shared_ptr< DAGNode > mkMin (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a min node.
std::shared_ptr< DAGNode > mkLet (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a let node.
std::shared_ptr< DAGNode > mkQuantVar (const std::string &name, std::shared_ptr< Sort > sort)
Create a quantifier variable node.
std::shared_ptr< DAGNode > mkForall (const std::vector< std::shared_ptr< DAGNode >> &params)
Create a forall node.
std::shared_ptr< DAGNode > mkExists (const std::vector< std::shared_ptr< DAGNode >> &params)
Create an exists node.
std::shared_ptr< DAGNode > mkApplyFunc (std::shared_ptr< DAGNode > fun, const std::vector< std::shared_ptr< DAGNode >> &params)
Create a function application node.
bool parseSmtlib2File (const std::string filename)
Parse an SMT-LIB2 file.
int getArity (NODE_KIND k) const
Get the arity of a node kind.
NODE_KIND getAddOp (std::shared_ptr< Sort > sort)
Get the add operator for a sort.
NODE_KIND getNegatedKind (NODE_KIND kind)
Get the opposite kind of a node kind.
std::shared_ptr< DAGNode > getZero (std::shared_ptr< Sort > sort)
Get the zero for a sort.
std::shared_ptr< DAGNode > substitute (std::shared_ptr< DAGNode > expr, std::unordered_map< std::string, std::shared_ptr< DAGNode >> &params)
Substitute variables in an expression.
std::shared_ptr< DAGNode > applyFun (std::shared_ptr< DAGNode > fun, const std::vector< std::shared_ptr< DAGNode >> &params)
Apply a function to a list of parameters.
void setEvaluatePrecision (mpfr_prec_t precision)
Set the precision for evaluation.
mpfr_prec_t getEvaluatePrecision () const
Get the precision for evaluation.
void setEvaluateUseFloating (bool use_floating)
Set the use floating for evaluation.
bool getEvaluateUseFloating () const
Get the use floating for evaluation.
Real toReal (std::shared_ptr< DAGNode > expr)
Convert an expression to a real.
Integer toInt (std::shared_ptr< DAGNode > expr)
Convert an expression to an integer.
bool isZero (std::shared_ptr< DAGNode > expr)
Check if an expression is zero.
bool isOne (std::shared_ptr< DAGNode > expr)
Check if an expression is one.
bool isOnes (std::shared_ptr< DAGNode > expr)
std::shared_ptr< DAGNode > expandLet (std::shared_ptr< DAGNode > expr)
Expand a let expression.
std::vector< std::shared_ptr< DAGNode > > getSplitLemmas ()
Get the split lemmas.
std::shared_ptr< DAGNode > remove (std::shared_ptr< DAGNode > expr, const std::unordered_set< std::shared_ptr< DAGNode >> &nodes)
Remove all the nodes in the expression.
std::shared_ptr< DAGNode > rename (std::shared_ptr< DAGNode > expr, const std::string &new_name)
Rename a node.
std::string toString (std::shared_ptr< DAGNode > expr)
Print an expression.
std::string toString (const NODE_KIND &kind)
Print a node kind.
std::string toString (std::shared_ptr< Sort > sort)
Print a sort.
std::string optionToString ()
Print the options.
std::string dumpSMT2 ()
Dump the SMT2 representation of the parsed expressions.
std::string dumpSMT2 (const std::string &filename)
Dump the SMT2 representation of the parsed expressions to a file.
std::shared_ptr< DAGNode > mkApplyDTFun (const std::shared_ptr< Sort > &sort, const std::string &name, const std::vector< std::shared_ptr< DAGNode >> &params)
size_t removeFuns (const std::vector< std::string > &funcNames)
Remove functions by name.
void ensureNumberValue (std::shared_ptr< DAGNode > expr)
ensure the expression is a number
Static Public Member Functions
static bool isCommutative (NODE_KIND t)
Check whether an operation kind is treated as commutative.
static std::vector< std::shared_ptr< DAGNode > > sortParams (const std::vector< std::shared_ptr< DAGNode >> &p)
Return sorted operand list for deterministic commutative handling.
Public Attributes
std::vector< std::shared_ptr< DAGNode > > assertions
std::unordered_map< std::string, std::unordered_set< size_t > > assertion_groups
std::unordered_map< std::string, std::shared_ptr< DAGNode > > named_assertions
std::vector< std::pair< std::shared_ptr< DAGNode >, std::vector< std::vector< std::shared_ptr< DAGNode > > > > > pattern_assertions
std::vector< std::vector< std::shared_ptr< DAGNode > > > assumptions
std::vector< std::shared_ptr< DAGNode > > soft_assertions
std::vector< std::shared_ptr< DAGNode > > soft_weights
std::unordered_map< std::string, std::unordered_set< size_t > > soft_assertion_groups
std::vector< std::shared_ptr< DAGNode > > split_lemmas
Private Member Functions
std::string getSymbol ()
void scanToNextSymbol ()
void parseLpar ()
void parseRpar ()
void skipToRpar ()
std::string peekSymbol ()
CMD_TYPE parseCommand ()
KEYWORD parseKeyword ()
std::shared_ptr< Sort > parseSort ()
std::shared_ptr< DAGNode > parseExpr ()
std::shared_ptr< DAGNode > parseConstFunc (const std::string &s)
std::shared_ptr< DAGNode > parseOper (const std::string &s, const std::vector< std::shared_ptr< DAGNode >> &func_args, const std::vector< std::shared_ptr< DAGNode >> &oper_params)
std::vector< std::shared_ptr< DAGNode > > parseParams ()
std::shared_ptr< DAGNode > parsePreservingLet ()
std::shared_ptr< DAGNode > parseLet ()
std::shared_ptr< DAGNode > mkLetBindVar (const std::string &name, const std::shared_ptr< DAGNode > &expr)
std::shared_ptr< DAGNode > mkLetBindVarList (const std::vector< std::shared_ptr< DAGNode >> &bind_vars)
std::shared_ptr< DAGNode > mkLetChain (const std::vector< std::shared_ptr< DAGNode >> &bind_var_lists, const std::shared_ptr< DAGNode > &body)
std::string parseGroup ()
std::string parseWeight ()
std::shared_ptr< DAGNode > parseQuant (const std::string &type)
KEYWORD attemptParseKeywords ()
std::shared_ptr< DAGNode > mkInternalOper (const std::shared_ptr< Sort > &sort, const NODE_KIND &t, const std::vector< std::shared_ptr< DAGNode >> &p)
std::shared_ptr< DAGNode > bindLetVar (const std::string &key, std::shared_ptr< DAGNode > expr)
std::shared_ptr< DAGNode > bindFunVar (const std::string &key, std::shared_ptr< DAGNode > expr)
std::shared_ptr< DAGNode > substitute (std::shared_ptr< DAGNode > expr, std::unordered_map< std::string, std::shared_ptr< DAGNode >> &params, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> &visited)
std::shared_ptr< DAGNode > applyFunPostOrder (std::shared_ptr< DAGNode > node, std::unordered_map< std::string, std::shared_ptr< DAGNode >> &params)
std::shared_ptr< DAGNode > replaceAtoms (std::shared_ptr< DAGNode > expr, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> &atom_map, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> &visited, bool &is_changed)
std::shared_ptr< DAGNode > replaceNodes (std::shared_ptr< DAGNode > expr, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> &node_map, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> &visited, bool &is_changed)
std::shared_ptr< DAGNode > toCNF (std::shared_ptr< DAGNode > expr)
std::shared_ptr< DAGNode > toTseitinCNF (std::shared_ptr< DAGNode > expr, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> &visited, std::vector< std::shared_ptr< DAGNode >> &clauses)
std::shared_ptr< DAGNode > toTseitinXor (std::shared_ptr< DAGNode > a, std::shared_ptr< DAGNode > b, std::vector< std::shared_ptr< DAGNode >> &clauses)
std::shared_ptr< DAGNode > toTseitinEq (std::shared_ptr< DAGNode > a, std::shared_ptr< DAGNode > b, std::vector< std::shared_ptr< DAGNode >> &clauses)
std::shared_ptr< DAGNode > toTseitinDistinct (std::shared_ptr< DAGNode > a, std::shared_ptr< DAGNode > b, std::vector< std::shared_ptr< DAGNode >> &clauses)
std::shared_ptr< DAGNode > toDNFEliminateAll (std::shared_ptr< DAGNode > expr)
std::shared_ptr< DAGNode > toDNFEliminateAll (std::shared_ptr< DAGNode > expr, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> &visited, bool &is_changed)
std::shared_ptr< DAGNode > toDNFEliminateXOR (const std::vector< std::shared_ptr< DAGNode >> &children)
std::shared_ptr< DAGNode > toDNFEliminateEq (const std::vector< std::shared_ptr< DAGNode >> &children)
std::shared_ptr< DAGNode > toDNFEliminateDistinct (const std::vector< std::shared_ptr< DAGNode >> &children)
std::shared_ptr< DAGNode > applyDNFDistributiveLaw (std::shared_ptr< DAGNode > expr)
std::shared_ptr< DAGNode > applyDNFDistributiveLawRec (std::shared_ptr< DAGNode > expr, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> &visited)
std::shared_ptr< DAGNode > flattenDNF (std::shared_ptr< DAGNode > expr)
std::shared_ptr< DAGNode > toNNF (std::shared_ptr< DAGNode > expr, bool is_not)
std::shared_ptr< DAGNode > remove (std::shared_ptr< DAGNode > expr, const std::unordered_set< std::shared_ptr< DAGNode >> &nodes, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> &visited)
std::shared_ptr< DAGNode > mkErr (const ERROR_TYPE t)
void err_all (const ERROR_TYPE e, const std::string s="", const size_t ln=0) const
void err_all (const std::shared_ptr< DAGNode > e, const std::string s="", const size_t ln=0) const
void err_unexp_eof () const
void err_sym_mis (const std::string mis, const size_t ln) const
void err_sym_mis (const std::string mis, const std::string nm, const size_t ln) const
void err_unkwn_sym (const std::string nm, const size_t ln) const
void err_param_mis (const std::string nm, const size_t ln) const
void err_param_nbool (const std::string nm, const size_t ln) const
void err_param_nnum (const std::string nm, const size_t ln) const
void err_param_nsame (const std::string nm, const size_t ln) const
void err_logic (const std::string nm, const size_t ln) const
void err_mul_decl (const std::string nm, const size_t ln) const
void err_mul_def (const std::string nm, const size_t ln) const
void err_zero_divisor (const size_t ln) const
void err_arity_mis (const std::string nm, const size_t ln) const
void err_keyword (const std::string nm, const size_t ln) const
void err_type_mis (const std::string nm, const size_t ln) const
void err_neg_param (const size_t ln) const
void err_open_file (const std::string) const
void warn_cmd_nsup (const std::string nm, const size_t ln) const
void collectAtoms (std::shared_ptr< DAGNode > expr, std::unordered_set< std::shared_ptr< DAGNode >> &atoms, std::unordered_set< std::shared_ptr< DAGNode >> &visited)
void collectGroundAtoms (std::shared_ptr< DAGNode > expr, std::unordered_set< std::shared_ptr< DAGNode >> &atoms, std::unordered_set< std::shared_ptr< DAGNode >> &visited)
void collectVars (std::shared_ptr< DAGNode > expr, std::unordered_set< std::shared_ptr< DAGNode >> &vars, std::unordered_set< std::shared_ptr< DAGNode >> &visited)
Private Attributes
char * buffer
unsigned long buflen
char * bufptr
size_t line_number
SCAN_MODE scan_mode
size_t preserving_let_counter
LET_MODE current_let_mode
size_t let_nesting_depth
size_t quant_nesting_depth
bool in_quantifier_scope
bool allow_placeholder_vars
std::shared_ptr< Sort > placeholder_var_sort
bool parsing_file
std::vector< std::string > parse_options
std::unique_ptr< NodeManager > node_manager
std::unique_ptr< SortManager > sort_manager
std::unordered_map< std::string, std::shared_ptr< DAGNode > > let_key_map
std::unordered_map< std::string, std::shared_ptr< DAGNode > > preserving_let_key_map
std::unordered_map< std::string, std::shared_ptr< DAGNode > > fun_key_map
std::unordered_map< std::string, std::shared_ptr< DAGNode > > fun_var_map
std::unordered_map< std::string, std::shared_ptr< Sort > > sort_key_map
std::unordered_map< std::string, std::vector< std::shared_ptr< DAGNode > > > quant_var_map
std::unordered_map< std::string, size_t > fun_dup_count_map
std::vector< std::shared_ptr< DAGNode > > static_functions
std::vector< std::vector< DTTypeDecl > > datatype_blocks
std::unordered_set< std::string > datatype_sort_names
std::unordered_set< std::string > datatype_function_names
std::unordered_map< std::string, size_t > var_names
size_t temp_var_counter
std::unordered_map< std::string, size_t > temp_var_names
std::unordered_map< std::string, size_t > placeholder_var_names
std::vector< std::string > function_names
std::shared_ptr< GlobalOptions > options
std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode > > cnf_map
std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode > > cnf_atom_map
std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode > > cnf_bool_var_map
std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode > > dnf_map
std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode > > nnf_map
RESULT_TYPE result_type
std::shared_ptr< DAGNode > result_node
size_t num_quant_vars = 0
Detailed Description
Definition at line 163 of file parser.h.
Constructor & Destructor Documentation
Parser() [1/2]
stabilizer::parser::Parser::Parser (const std::string & filename)
Constructor with filename.
Creates a Parser object and immediately tries to parse the specified SMT-LIB2 file.
Parameters
filename Path to the SMT-LIB2 file to parse
Definition at line 83 of file base_parser.cpp.
References allow_placeholder_vars, buffer, buflen, bufptr, fun_key_map, fun_var_map, function_names, in_quantifier_scope, let_key_map, let_nesting_depth, line_number, node_manager, options, parseSmtlib2File(), parsing_file, placeholder_var_sort, preserving_let_counter, preserving_let_key_map, quant_nesting_depth, quant_var_map, scan_mode, stabilizer::parser::SM_COMMON, sort_key_map, sort_manager, static_functions, temp_var_counter, temp_var_names, and var_names.
Parser() [2/2]
stabilizer::parser::Parser::Parser ()
Default constructor.
Creates an empty Parser object, parse method must be called later to parse a file.
Definition at line 48 of file base_parser.cpp.
References allow_placeholder_vars, buffer, buflen, bufptr, fun_key_map, fun_var_map, function_names, in_quantifier_scope, let_key_map, let_nesting_depth, line_number, node_manager, options, parsing_file, placeholder_var_sort, preserving_let_counter, preserving_let_key_map, quant_nesting_depth, quant_var_map, scan_mode, stabilizer::parser::SM_COMMON, sort_key_map, sort_manager, static_functions, temp_var_counter, temp_var_names, and var_names.
~Parser()
stabilizer::parser::Parser::~Parser ()
Destructor.
Releases all resources used by the Parser
Definition at line 116 of file base_parser.cpp.
Member Function Documentation
applyDNFDistributiveLaw()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::applyDNFDistributiveLaw (std::shared_ptr< DAGNode > expr) private
applyDNFDistributiveLawRec()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::applyDNFDistributiveLawRec (std::shared_ptr< DAGNode > expr, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> & visited) private
applyFun()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::applyFun (std::shared_ptr< DAGNode > fun, const std::vector< std::shared_ptr< DAGNode >> & params)
Apply a function to a list of parameters.
Parameters
fun Function node
params List of parameters
Returns
Applied function (fun(p1, p2, ..., pn))
Definition at line 2060 of file base_parser.cpp.
References applyFunPostOrder(), datatype_function_names, stabilizer::parser::ERR_PARAM_MIS, mkApplyDTFun(), mkApplyFunc(), mkApplyRecFunc(), mkApplyUF(), mkErr(), node_manager, stabilizer::parser::NT_UF_APPLY, and options.
Referenced by applyFunPostOrder(), and parseOper().
applyFunPostOrder()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::applyFunPostOrder (std::shared_ptr< DAGNode > node, std::unordered_map< std::string, std::shared_ptr< DAGNode >> & params) private
Definition at line 2128 of file base_parser.cpp.
References applyFun(), stabilizer::parser::ERR_FUN_LOCAL_VAR, mkApplyDTFun(), mkApplyRecFunc(), mkApplyUF(), mkErr(), mkOper(), and options.
Referenced by applyFun().
assert() [1/2]
bool stabilizer::parser::Parser::assert (const std::string & constraint)
Assert a constraint.
Asserts the specified constraint and builds internal data structures.
Note
Any variables in the constraint must be declared before assertion.
Parameters
constraint Constraint to assert
Returns
True if assertion was successful, false otherwise
Definition at line 717 of file base_parser.cpp.
References assertions, mkExpr(), and parsing_file.
assert() [2/2]
bool stabilizer::parser::Parser::assert (std::shared_ptr< DAGNode > node)
Assert a constraint.
Asserts the specified constraint and builds internal data structures.
Parameters
node Constraint to assert
Returns
True if assertion was successful, false otherwise
Definition at line 724 of file base_parser.cpp.
References assertions.
attemptParseKeywords()
KEYWORD stabilizer::parser::Parser::attemptParseKeywords () private
Definition at line 33 of file opt_parser.cpp.
References bufptr, stabilizer::parser::KW_NULL, and parseKeyword().
Referenced by parseCommand(), and parseExpr().
bindFunVar()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::bindFunVar (const std::string & key, std::shared_ptr< DAGNode > expr) private
bindLetVar()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::bindLetVar (const std::string & key, std::shared_ptr< DAGNode > expr) private
checkSat()
RESULT_TYPE stabilizer::parser::Parser::checkSat ()
Check satisfiability.
Returns
True if satisfiable, false otherwise
Definition at line 122 of file base_parser.cpp.
References assertions, result_type, stabilizer::parser::RT_ERROR, stabilizer::parser::RT_SAT, stabilizer::parser::RT_UNKNOWN, and stabilizer::parser::RT_UNSAT.
clear_let_key_map()
void stabilizer::parser::Parser::clear_let_key_map () inline
Definition at line 332 of file parser.h.
References preserving_let_key_map.
Referenced by rebuildLetBindings().
collectAtoms()
void stabilizer::parser::Parser::collectAtoms (std::shared_ptr< DAGNode > expr, std::unordered_set< std::shared_ptr< DAGNode >> & atoms, std::unordered_set< std::shared_ptr< DAGNode >> & visited) private
collectGroundAtoms()
void stabilizer::parser::Parser::collectGroundAtoms (std::shared_ptr< DAGNode > expr, std::unordered_set< std::shared_ptr< DAGNode >> & atoms, std::unordered_set< std::shared_ptr< DAGNode >> & visited) private
collectVars()
void stabilizer::parser::Parser::collectVars (std::shared_ptr< DAGNode > expr, std::unordered_set< std::shared_ptr< DAGNode >> & vars, std::unordered_set< std::shared_ptr< DAGNode >> & visited) private
declareVar() [1/2]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::declareVar (const std::string & name, const std::shared_ptr< Sort > & sort)
Declare a variable.
Parameters
name Variable name
sort Sort
Definition at line 624 of file op_parser.cpp.
References mkVar().
declareVar() [2/2]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::declareVar (const std::string & name, const std::string & sort)
Declare a variable.
Parameters
name Variable name
sort Sort
Definition at line 620 of file op_parser.cpp.
References mkVar(), and sort_key_map.
dumpSMT2() [1/2]
std::string stabilizer::parser::Parser::dumpSMT2 ()
Dump the SMT2 representation of the parsed expressions.
Returns
String representation of the SMT2
Definition at line 2851 of file base_parser.cpp.
References assertions, datatype_blocks, stabilizer::parser::dumpFuncDec(), stabilizer::parser::dumpFuncRec(), stabilizer::parser::dumpSMTLIB2(), getFunctions(), getVariables(), options, parse_options, rebuildLetBindings(), and sort_key_map.
Referenced by dumpSMT2().
dumpSMT2() [2/2]
std::string stabilizer::parser::Parser::dumpSMT2 (const std::string & filename)
Dump the SMT2 representation of the parsed expressions to a file.
Parameters
filename Filename to save the SMT2
Returns
Filename
Definition at line 2981 of file base_parser.cpp.
References dumpSMT2().
ensureNumberValue()
void stabilizer::parser::Parser::ensureNumberValue (std::shared_ptr< DAGNode > expr)
ensure the expression is a number
Parameters
expr Expression to ensure
Definition at line 336 of file base_parser.cpp.
References err_all(), stabilizer::parser::TypeChecker::isInt(), stabilizer::parser::TypeChecker::isReal(), and line_number.
Referenced by toInt(), and toReal().
err_all() [1/2]
void stabilizer::parser::Parser::err_all (const ERROR_TYPE e, const std::string s = "", const size_t ln = 0) const private
Definition at line 2516 of file base_parser.cpp.
References stabilizer::parser::ERR_ARI_MIS, err_arity_mis(), stabilizer::parser::ERR_FUN_LOCAL_VAR, stabilizer::parser::ERR_LOGIC, err_logic(), stabilizer::parser::ERR_MUL_DECL, err_mul_decl(), stabilizer::parser::ERR_MUL_DEF, err_mul_def(), stabilizer::parser::ERR_NEG_PARAM, err_neg_param(), stabilizer::parser::ERR_PARAM_MIS, err_param_mis(), stabilizer::parser::ERR_PARAM_NBOOL, err_param_nbool(), stabilizer::parser::ERR_PARAM_NNUM, err_param_nnum(), stabilizer::parser::ERR_PARAM_NSAME, err_param_nsame(), stabilizer::parser::ERR_SYM_MIS, err_sym_mis(), stabilizer::parser::ERR_TYPE_MIS, err_type_mis(), stabilizer::parser::ERR_UNEXP_EOF, err_unexp_eof(), stabilizer::parser::ERR_UNKWN_SYM, err_unkwn_sym(), stabilizer::parser::ERR_ZERO_DIVISOR, and err_zero_divisor().
Referenced by ensureNumberValue(), err_all(), mkAbs(), mkAdd(), mkBvAdd(), mkBvAnd(), mkBvAshr(), mkBvConcat(), mkBvExtract(), mkBvLshr(), mkBvMul(), mkBvNot(), mkBvOr(), mkBvRepeat(), mkBvRotateLeft(), mkBvRotateRight(), mkBvSdiv(), mkBvSge(), mkBvSgt(), mkBvShl(), mkBvSignExt(), mkBvSle(), mkBvSlt(), mkBvSmod(), mkBvSrem(), mkBvToInt(), mkBvToNat(), mkBvUdiv(), mkBvUge(), mkBvUgt(), mkBvUle(), mkBvUlt(), mkBvUmod(), mkBvUrem(), mkBvXor(), mkBvZeroExt(), mkCeil(), mkConstArray(), mkDistinct(), mkDivInt(), mkDivReal(), mkEq(), mkFact(), mkFpAbs(), mkFpAdd(), mkFpConst(), mkFpDiv(), mkFpFma(), mkFpIsInf(), mkFpIsNaN(), mkFpIsNeg(), mkFpIsNormal(), mkFpIsPos(), mkFpIsSubnormal(), mkFpIsZero(), mkFpMul(), mkFpNeg(), mkFpRem(), mkFpRoundToIntegral(), mkFpSqrt(), mkFpSub(), mkFpToReal(), mkFpToSbv(), mkFpToUbv(), mkFuncDef(), mkFuncRec(), mkGcd(), mkGe(), mkGt(), mkIand(), mkImplies(), mkIndexofReg(), mkInfinity(), mkIntToBv(), mkIsDivisible(), mkIsEven(), mkIsInt(), mkIsOdd(), mkIsPrime(), mkIte(), mkLcm(), mkLe(), mkLog(), mkLt(), mkMax(), mkMin(), mkMod(), mkMul(), mkNatToBv(), mkNegInfinity(), mkNot(), mkOper(), mkPosInfinity(), mkRegComplement(), mkRegConcat(), mkRegDiff(), mkRegInter(), mkRegLoop(), mkRegOpt(), mkRegPlus(), mkRegRange(), mkRegRepeat(), mkRegStar(), mkRegUnion(), mkReplaceReg(), mkReplaceRegAll(), mkSafeSqrt(), mkSbvToInt(), mkSelect(), mkSqrt(), mkStrCharat(), mkStrConcat(), mkStrContains(), mkStrFromCode(), mkStrFromInt(), mkStrIndexof(), mkStrIndexofReg(), mkStrInReg(), mkStrIsDigit(), mkStrLen(), mkStrNumSplits(), mkStrNumSplitsRe(), mkStrPrefixof(), mkStrReplace(), mkStrReplaceAll(), mkStrReplaceReg(), mkStrReplaceRegAll(), mkStrRev(), mkStrSplit(), mkStrSplitAt(), mkStrSplitAtRe(), mkStrSplitRest(), mkStrSplitRestRe(), mkStrSubstr(), mkStrSuffixof(), mkStrToCode(), mkStrToInt(), mkStrToLower(), mkStrToReg(), mkStrToUpper(), mkStrUpdate(), mkSub(), mkTempVar(), mkToFp(), mkToFpUnsigned(), mkToInt(), mkToReal(), mkUbvToInt(), parseCommand(), parseExpr(), parseLet(), parsePreservingLet(), parseSort(), and rewrite().
err_all() [2/2]
void stabilizer::parser::Parser::err_all (const std::shared_ptr< DAGNode > e, const std::string s = "", const size_t ln = 0) const private
Definition at line 2568 of file base_parser.cpp.
References err_all().
err_arity_mis()
void stabilizer::parser::Parser::err_arity_mis (const std::string nm, const size_t ln) const private
Definition at line 2633 of file base_parser.cpp.
Referenced by err_all().
err_keyword()
void stabilizer::parser::Parser::err_keyword (const std::string nm, const size_t ln) const private
Definition at line 2647 of file base_parser.cpp.
err_logic()
void stabilizer::parser::Parser::err_logic (const std::string nm, const size_t ln) const private
Definition at line 2613 of file base_parser.cpp.
Referenced by err_all().
err_mul_decl()
void stabilizer::parser::Parser::err_mul_decl (const std::string nm, const size_t ln) const private
Definition at line 2618 of file base_parser.cpp.
Referenced by err_all(), and parseCommand().
err_mul_def()
void stabilizer::parser::Parser::err_mul_def (const std::string nm, const size_t ln) const private
Definition at line 2623 of file base_parser.cpp.
Referenced by err_all(), and parseCommand().
err_neg_param()
void stabilizer::parser::Parser::err_neg_param (const size_t ln) const private
Definition at line 2642 of file base_parser.cpp.
Referenced by err_all().
err_open_file()
void stabilizer::parser::Parser::err_open_file (const std::string filename) const private
Definition at line 2655 of file base_parser.cpp.
Referenced by parseSmtlib2File().
err_param_mis()
void stabilizer::parser::Parser::err_param_mis (const std::string nm, const size_t ln) const private
Definition at line 2594 of file base_parser.cpp.
Referenced by err_all(), and parseOper().
err_param_nbool()
void stabilizer::parser::Parser::err_param_nbool (const std::string nm, const size_t ln) const private
Definition at line 2599 of file base_parser.cpp.
Referenced by err_all().
err_param_nnum()
void stabilizer::parser::Parser::err_param_nnum (const std::string nm, const size_t ln) const private
Definition at line 2603 of file base_parser.cpp.
Referenced by err_all().
err_param_nsame()
void stabilizer::parser::Parser::err_param_nsame (const std::string nm, const size_t ln) const private
Definition at line 2608 of file base_parser.cpp.
Referenced by err_all().
err_sym_mis() [1/2]
void stabilizer::parser::Parser::err_sym_mis (const std::string mis, const size_t ln) const private
Definition at line 2578 of file base_parser.cpp.
Referenced by err_all(), parseLet(), parseLpar(), parsePreservingLet(), and parseRpar().
err_sym_mis() [2/2]
void stabilizer::parser::Parser::err_sym_mis (const std::string mis, const std::string nm, const size_t ln) const private
Definition at line 2582 of file base_parser.cpp.
err_type_mis()
void stabilizer::parser::Parser::err_type_mis (const std::string nm, const size_t ln) const private
Definition at line 2638 of file base_parser.cpp.
Referenced by err_all(), mkAnd(), and mkOr().
err_unexp_eof()
void stabilizer::parser::Parser::err_unexp_eof () const private
Definition at line 2573 of file base_parser.cpp.
Referenced by err_all(), err_unkwn_sym(), and getSymbol().
err_unkwn_sym()
void stabilizer::parser::Parser::err_unkwn_sym (const std::string nm, const size_t ln) const private
Definition at line 2587 of file base_parser.cpp.
References err_unexp_eof().
Referenced by err_all(), parseCommand(), parseConstFunc(), parseExpr(), parseKeyword(), parseOper(), and parseSort().
err_zero_divisor()
void stabilizer::parser::Parser::err_zero_divisor (const size_t ln) const private
Definition at line 2628 of file base_parser.cpp.
Referenced by err_all().
expandLet()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::expandLet (std::shared_ptr< DAGNode > expr)
Expand a let expression.
Parameters
expr Let expression to expand
Returns
Expanded expression
flattenDNF()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::flattenDNF (std::shared_ptr< DAGNode > expr) private
getAddOp()
NODE_KIND stabilizer::parser::Parser::getAddOp (std::shared_ptr< Sort > sort)
Get the add operator for a sort.
Parameters
sort Sort
Returns
Add operator for the sort
Definition at line 2467 of file base_parser.cpp.
References stabilizer::parser::NT_ADD, stabilizer::parser::NT_BV_ADD, stabilizer::parser::NT_ERROR, and stabilizer::parser::NT_FP_ADD.
getArity()
int stabilizer::parser::Parser::getArity (NODE_KIND k) const
Get the arity of a node kind.
Parameters
k Node kind
Returns
Arity of the node kind
Definition at line 4044 of file op_parser.cpp.
References stabilizer::parser::NT_ABS, stabilizer::parser::NT_ACOS, stabilizer::parser::NT_ACOSH, stabilizer::parser::NT_ACOT, stabilizer::parser::NT_ACOTH, stabilizer::parser::NT_ACSC, stabilizer::parser::NT_ACSCH, stabilizer::parser::NT_ADD, stabilizer::parser::NT_AND, stabilizer::parser::NT_ASEC, stabilizer::parser::NT_ASECH, stabilizer::parser::NT_ASIN, stabilizer::parser::NT_ASINH, stabilizer::parser::NT_ATAN, stabilizer::parser::NT_ATAN2, stabilizer::parser::NT_ATANH, stabilizer::parser::NT_BV_ADD, stabilizer::parser::NT_BV_AND, stabilizer::parser::NT_BV_ASHR, stabilizer::parser::NT_BV_COMP, stabilizer::parser::NT_BV_CONCAT, stabilizer::parser::NT_BV_EXTRACT, stabilizer::parser::NT_BV_LSHR, stabilizer::parser::NT_BV_MUL, stabilizer::parser::NT_BV_NAND, stabilizer::parser::NT_BV_NEG, stabilizer::parser::NT_BV_NEGO, stabilizer::parser::NT_BV_NOR, stabilizer::parser::NT_BV_NOT, stabilizer::parser::NT_BV_OR, stabilizer::parser::NT_BV_REPEAT, stabilizer::parser::NT_BV_ROTATE_LEFT, stabilizer::parser::NT_BV_ROTATE_RIGHT, stabilizer::parser::NT_BV_SADDO, stabilizer::parser::NT_BV_SDIV, stabilizer::parser::NT_BV_SDIVO, stabilizer::parser::NT_BV_SGE, stabilizer::parser::NT_BV_SGT, stabilizer::parser::NT_BV_SHL, stabilizer::parser::NT_BV_SIGN_EXT, stabilizer::parser::NT_BV_SLE, stabilizer::parser::NT_BV_SLT, stabilizer::parser::NT_BV_SMOD, stabilizer::parser::NT_BV_SMODO, stabilizer::parser::NT_BV_SMULO, stabilizer::parser::NT_BV_SREM, stabilizer::parser::NT_BV_SREMO, stabilizer::parser::NT_BV_SUB, stabilizer::parser::NT_BV_TO_INT, stabilizer::parser::NT_BV_TO_NAT, stabilizer::parser::NT_BV_UADDO, stabilizer::parser::NT_BV_UDIV, stabilizer::parser::NT_BV_UDIVO, stabilizer::parser::NT_BV_UGE, stabilizer::parser::NT_BV_UGT, stabilizer::parser::NT_BV_ULE, stabilizer::parser::NT_BV_ULT, stabilizer::parser::NT_BV_UMOD, stabilizer::parser::NT_BV_UMODO, stabilizer::parser::NT_BV_UMULO, stabilizer::parser::NT_BV_UREM, stabilizer::parser::NT_BV_UREMO, stabilizer::parser::NT_BV_XNOR, stabilizer::parser::NT_BV_XOR, stabilizer::parser::NT_BV_ZERO_EXT, stabilizer::parser::NT_CEIL, stabilizer::parser::NT_CONST, stabilizer::parser::NT_CONST_ARRAY, stabilizer::parser::NT_CONST_E, stabilizer::parser::NT_CONST_FALSE, stabilizer::parser::NT_CONST_PI, stabilizer::parser::NT_CONST_TRUE, stabilizer::parser::NT_COS, stabilizer::parser::NT_COSH, stabilizer::parser::NT_COT, stabilizer::parser::NT_COTH, stabilizer::parser::NT_CSC, stabilizer::parser::NT_CSCH, stabilizer::parser::NT_DISTINCT, stabilizer::parser::NT_DISTINCT_BOOL, stabilizer::parser::NT_DISTINCT_OTHER, stabilizer::parser::NT_DIV_INT, stabilizer::parser::NT_DIV_REAL, stabilizer::parser::NT_EPSILON, stabilizer::parser::NT_EQ, stabilizer::parser::NT_EQ_BOOL, stabilizer::parser::NT_EQ_OTHER, stabilizer::parser::NT_EXISTS, stabilizer::parser::NT_EXP, stabilizer::parser::NT_FACT, stabilizer::parser::NT_FLOOR, stabilizer::parser::NT_FORALL, stabilizer::parser::NT_FP_ABS, stabilizer::parser::NT_FP_ADD, stabilizer::parser::NT_FP_DIV, stabilizer::parser::NT_FP_EQ, stabilizer::parser::NT_FP_FMA, stabilizer::parser::NT_FP_GE, stabilizer::parser::NT_FP_GT, stabilizer::parser::NT_FP_IS_INF, stabilizer::parser::NT_FP_IS_NAN, stabilizer::parser::NT_FP_IS_NEG, stabilizer::parser::NT_FP_IS_NORMAL, stabilizer::parser::NT_FP_IS_POS, stabilizer::parser::NT_FP_IS_SUBNORMAL, stabilizer::parser::NT_FP_IS_ZERO, stabilizer::parser::NT_FP_LE, stabilizer::parser::NT_FP_LT, stabilizer::parser::NT_FP_MAX, stabilizer::parser::NT_FP_MIN, stabilizer::parser::NT_FP_MUL, stabilizer::parser::NT_FP_NEG, stabilizer::parser::NT_FP_REM, stabilizer::parser::NT_FP_ROUND_TO_INTEGRAL, stabilizer::parser::NT_FP_SQRT, stabilizer::parser::NT_FP_SUB, stabilizer::parser::NT_FP_TO_FP, stabilizer::parser::NT_FP_TO_REAL, stabilizer::parser::NT_FP_TO_SBV, stabilizer::parser::NT_FP_TO_UBV, stabilizer::parser::NT_GCD, stabilizer::parser::NT_GE, stabilizer::parser::NT_GT, stabilizer::parser::NT_IAND, stabilizer::parser::NT_IMPLIES, stabilizer::parser::NT_INFINITY, stabilizer::parser::NT_INT_TO_BV, stabilizer::parser::NT_IS_DIVISIBLE, stabilizer::parser::NT_IS_EVEN, stabilizer::parser::NT_IS_INT, stabilizer::parser::NT_IS_ODD, stabilizer::parser::NT_IS_PRIME, stabilizer::parser::NT_ITE, stabilizer::parser::NT_LB, stabilizer::parser::NT_LCM, stabilizer::parser::NT_LE, stabilizer::parser::NT_LG, stabilizer::parser::NT_LN, stabilizer::parser::NT_LOG, stabilizer::parser::NT_LT, stabilizer::parser::NT_MAX, stabilizer::parser::NT_MIN, stabilizer::parser::NT_MOD, stabilizer::parser::NT_MUL, stabilizer::parser::NT_NAN, stabilizer::parser::NT_NAT_TO_BV, stabilizer::parser::NT_NEG, stabilizer::parser::NT_NEG_EPSILON, stabilizer::parser::NT_NEG_INFINITY, stabilizer::parser::NT_NOT, stabilizer::parser::NT_NULL, stabilizer::parser::NT_OR, stabilizer::parser::NT_POS_EPSILON, stabilizer::parser::NT_POS_INFINITY, stabilizer::parser::NT_POW, stabilizer::parser::NT_POW2, stabilizer::parser::NT_QUANT_VAR, stabilizer::parser::NT_REG_ALL, stabilizer::parser::NT_REG_ALLCHAR, stabilizer::parser::NT_REG_COMPLEMENT, stabilizer::parser::NT_REG_CONCAT, stabilizer::parser::NT_REG_DIFF, stabilizer::parser::NT_REG_INTER, stabilizer::parser::NT_REG_LOOP, stabilizer::parser::NT_REG_NONE, stabilizer::parser::NT_REG_OPT, stabilizer::parser::NT_REG_PLUS, stabilizer::parser::NT_REG_RANGE, stabilizer::parser::NT_REG_REPEAT, stabilizer::parser::NT_REG_STAR, stabilizer::parser::NT_REG_UNION, stabilizer::parser::NT_ROUND, stabilizer::parser::NT_SAFESQRT, stabilizer::parser::NT_SBV_TO_INT, stabilizer::parser::NT_SEC, stabilizer::parser::NT_SECH, stabilizer::parser::NT_SELECT, stabilizer::parser::NT_SIN, stabilizer::parser::NT_SINH, stabilizer::parser::NT_SQRT, stabilizer::parser::NT_STORE, stabilizer::parser::NT_STR_CHARAT, stabilizer::parser::NT_STR_CONCAT, stabilizer::parser::NT_STR_CONTAINS, stabilizer::parser::NT_STR_FROM_CODE, stabilizer::parser::NT_STR_FROM_INT, stabilizer::parser::NT_STR_GE, stabilizer::parser::NT_STR_GT, stabilizer::parser::NT_STR_IN_REG, stabilizer::parser::NT_STR_INDEXOF, stabilizer::parser::NT_STR_INDEXOF_REG, stabilizer::parser::NT_STR_IS_DIGIT, stabilizer::parser::NT_STR_LE, stabilizer::parser::NT_STR_LEN, stabilizer::parser::NT_STR_LT, stabilizer::parser::NT_STR_NUM_SPLITS_RE, stabilizer::parser::NT_STR_PREFIXOF, stabilizer::parser::NT_STR_REPLACE, stabilizer::parser::NT_STR_REPLACE_ALL, stabilizer::parser::NT_STR_REPLACE_REG, stabilizer::parser::NT_STR_REPLACE_REG_ALL, stabilizer::parser::NT_STR_REV, stabilizer::parser::NT_STR_SPLIT, stabilizer::parser::NT_STR_SPLIT_AT, stabilizer::parser::NT_STR_SPLIT_AT_RE, stabilizer::parser::NT_STR_SPLIT_REST, stabilizer::parser::NT_STR_SPLIT_REST_RE, stabilizer::parser::NT_STR_SUBSTR, stabilizer::parser::NT_STR_SUFFIXOF, stabilizer::parser::NT_STR_TO_CODE, stabilizer::parser::NT_STR_TO_INT, stabilizer::parser::NT_STR_TO_LOWER, stabilizer::parser::NT_STR_TO_REG, stabilizer::parser::NT_STR_TO_UPPER, stabilizer::parser::NT_STR_UPDATE, stabilizer::parser::NT_SUB, stabilizer::parser::NT_TAN, stabilizer::parser::NT_TANH, stabilizer::parser::NT_TEMP_VAR, stabilizer::parser::NT_TO_INT, stabilizer::parser::NT_TO_REAL, stabilizer::parser::NT_UBV_TO_INT, stabilizer::parser::NT_VAR, and stabilizer::parser::NT_XOR.
Referenced by rewrite_oper().
getAssertions()
std::vector< std::shared_ptr< DAGNode > > stabilizer::parser::Parser::getAssertions () const
Get all assertions.
Returns
Vector of all assertions
Definition at line 201 of file base_parser.cpp.
References assertions.
getAssumptions()
std::vector< std::vector< std::shared_ptr< DAGNode > > > stabilizer::parser::Parser::getAssumptions () const
Get assumptions.
Returns a vector of all assumptions. Use (check-sat-assuming (assumptions)) to check satisfiability under the given assumptions.
Returns
Vector of all assumptions
Definition at line 209 of file base_parser.cpp.
References assumptions.
getDatatypeBlocks()
std::vector<std::vector<DTTypeDecl> >& stabilizer::parser::Parser::getDatatypeBlocks () inline
Definition at line 329 of file parser.h.
References datatype_blocks.
getDeclaredVariables()
std::vector< std::shared_ptr< DAGNode > > stabilizer::parser::Parser::getDeclaredVariables () const
Get declared variables.
Returns
Vector of all declared variables
Definition at line 254 of file base_parser.cpp.
References node_manager, and var_names.
getEvaluatePrecision()
mpfr_prec_t stabilizer::parser::Parser::getEvaluatePrecision () const
Get the precision for evaluation.
Returns
Precision
Definition at line 281 of file base_parser.cpp.
References options.
Referenced by toReal().
getEvaluateUseFloating()
bool stabilizer::parser::Parser::getEvaluateUseFloating () const
Get the use floating for evaluation.
Returns
Use floating
Definition at line 287 of file base_parser.cpp.
References options.
Referenced by rewrite().
getFunctionNames()
std::vector<std::string>& stabilizer::parser::Parser::getFunctionNames () inline
Definition at line 325 of file parser.h.
References function_names.
getFunctions()
std::vector< std::shared_ptr< DAGNode > > stabilizer::parser::Parser::getFunctions () const
Get functions.
Returns a vector of all functions. Use (define-fun name (params) body) to define a function.
Returns
Vector of all functions
Definition at line 270 of file base_parser.cpp.
References fun_key_map, and function_names.
Referenced by dumpSMT2().
getFunKeyMap()
std::unordered_map<std::string, std::shared_ptr<DAGNode> >& stabilizer::parser::Parser::getFunKeyMap () inline
Definition at line 322 of file parser.h.
References fun_key_map.
getGroupedAssertions()
std::unordered_map< std::string, std::unordered_set< size_t > > stabilizer::parser::Parser::getGroupedAssertions () const
Get grouped assertions.
Returns assertion groups map. Use (assert expr :id group_name) to assign assertions to groups. Assertions without an ID go to the default group.
Returns
Map from group names to sets of assertion indices
Definition at line 205 of file base_parser.cpp.
References assertion_groups.
getGroupedSoftAssertions()
std::unordered_map< std::string, std::unordered_set< size_t > > stabilizer::parser::Parser::getGroupedSoftAssertions () const
Get grouped soft assertions.
Returns a map of soft assertion groups. Use (assert-soft expr :weight weight :id group_name) to group and weight them.
Returns
Map from group names to sets of soft assertion indices
Definition at line 219 of file base_parser.cpp.
References soft_assertion_groups.
getKind() [1/2]
NODE_KIND stabilizer::parser::Parser::getKind (const std::shared_ptr< DAGNode > & node)
Get kind.
Parameters
node Node
Returns
NODE_KIND
getKind() [2/2]
NODE_KIND stabilizer::parser::Parser::getKind (const std::string & s)
Get kind.
Parameters
s String token
Returns
NODE_KIND
Definition at line 897 of file expr_parser.cpp.
References fun_key_map, stabilizer::parser::getOperKind(), stabilizer::parser::NT_FUNC_APPLY, and stabilizer::parser::NT_UNKNOWN.
getNegatedKind()
NODE_KIND stabilizer::parser::Parser::getNegatedKind (NODE_KIND kind)
Get the opposite kind of a node kind.
Parameters
kind Node kind
Returns
Opposite kind of the node kind
Definition at line 2481 of file base_parser.cpp.
References stabilizer::parser::getNegatedKind().
getNodeCount()
size_t stabilizer::parser::Parser::getNodeCount ()
Get node count.
Returns
Node count
Definition at line 157 of file base_parser.cpp.
References assertions, assumptions, soft_assertions, and soft_weights.
getNodeManager()
std::unique_ptr<NodeManager> stabilizer::parser::Parser::getNodeManager () inline
Definition at line 764 of file parser.h.
References node_manager.
getOptions()
std::shared_ptr< GlobalOptions > stabilizer::parser::Parser::getOptions () const
Get global options.
Returns
Pointer to global options
Definition at line 235 of file base_parser.cpp.
References options.
Referenced by stabilizer::api::SMTStabilizer::configure_parser().
getResult()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::getResult ()
Get result.
Returns
Result
Definition at line 120 of file base_parser.cpp.
References result_node.
getResultType()
RESULT_TYPE stabilizer::parser::Parser::getResultType ()
Get result type.
Returns
Result type
Definition at line 118 of file base_parser.cpp.
References result_type.
getSoftAssertions()
std::vector< std::shared_ptr< DAGNode > > stabilizer::parser::Parser::getSoftAssertions () const
Get soft assertions.
Returns soft assertions. Use (assert-soft expr :weight weight :id group_name) to group and weight them.
Returns
Vector of all soft assertions
Definition at line 212 of file base_parser.cpp.
References soft_assertions.
getSoftWeights()
std::vector< std::shared_ptr< DAGNode > > stabilizer::parser::Parser::getSoftWeights () const
Get soft assertion weights.
Returns
Vector of all soft assertion weights
Definition at line 215 of file base_parser.cpp.
References soft_weights.
getSort() [1/4]
std::shared_ptr< Sort > stabilizer::parser::Parser::getSort (const std::vector< std::shared_ptr< DAGNode >> & params)
Get sort.
Parameters
params Vector of parameters
Returns
Sort
Definition at line 131 of file op_parser.cpp.
References stabilizer::parser::SortManager::INT_SORT, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by getSort(), mkAdd(), mkBvAdd(), mkBvAnd(), mkBvMul(), mkBvNand(), mkBvNor(), mkBvOr(), mkBvSub(), mkBvXnor(), mkBvXor(), mkDistinct(), mkEq(), mkFpAdd(), mkFpDiv(), mkFpFma(), mkFpMax(), mkFpMin(), mkFpMul(), mkFpSub(), mkIand(), mkMax(), mkMin(), mkMul(), mkSub(), and parseOper().
getSort() [2/4]
std::shared_ptr< Sort > stabilizer::parser::Parser::getSort (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Get sort.
Parameters
l Left operand
r Right operand
Returns
Sort
Definition at line 162 of file op_parser.cpp.
References getSort().
getSort() [3/4]
std::shared_ptr< Sort > stabilizer::parser::Parser::getSort (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > m)
Get sort.
Parameters
l First operand
r Second operand
m Third operand
Returns
Sort
Definition at line 166 of file op_parser.cpp.
References getSort().
getSort() [4/4]
std::shared_ptr< Sort > stabilizer::parser::Parser::getSort (std::shared_ptr< DAGNode > param)
Get sort.
Parameters
param Parameter
Returns
Sort
Definition at line 159 of file op_parser.cpp.
getSortNames()
std::unordered_map<std::string, std::shared_ptr<Sort> >& stabilizer::parser::Parser::getSortNames () inline
Definition at line 326 of file parser.h.
References sort_key_map.
getSplitLemmas()
std::vector<std::shared_ptr<DAGNode> > stabilizer::parser::Parser::getSplitLemmas ()
Get the split lemmas.
Note
Return the split lemmas generated by splitOp last time.
Returns
Split lemmas
getSymbol()
std::string stabilizer::parser::Parser::getSymbol () private
Definition at line 367 of file base_parser.cpp.
References buffer, buflen, bufptr, condAssert, err_unexp_eof(), stabilizer::parser::TypeChecker::isBV(), stabilizer::parser::TypeChecker::isFP(), stabilizer::parser::TypeChecker::isInt(), stabilizer::parser::TypeChecker::isNumber(), stabilizer::parser::TypeChecker::isReal(), stabilizer::parser::TypeChecker::isScientificNotation(), stabilizer::parser::TypeChecker::isString(), line_number, parsing_file, scan_mode, scanToNextSymbol(), stabilizer::parser::SM_COMP_SYM, stabilizer::parser::SM_STRING, and stabilizer::parser::SM_SYMBOL.
Referenced by parseCommand(), parseExpr(), parseKeyword(), parseLet(), parsePreservingLet(), parseQuant(), parseSort(), and peekSymbol().
getTempVarNames()
std::unordered_map<std::string, size_t>& stabilizer::parser::Parser::getTempVarNames () inline
Definition at line 318 of file parser.h.
References temp_var_names.
getVariable()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::getVariable (const std::string & var_name)
Get variable.
Parameters
var_name Variable name
Returns
Variable node
Definition at line 261 of file base_parser.cpp.
References node_manager, stabilizer::parser::NodeManager::NULL_NODE, temp_var_names, and var_names.
getVariables()
std::vector< std::shared_ptr< DAGNode > > stabilizer::parser::Parser::getVariables () const
Get variables.
Returns
Vector of all variables
Definition at line 236 of file base_parser.cpp.
References node_manager, temp_var_names, and var_names.
Referenced by dumpSMT2().
getVarNames()
std::unordered_map<std::string, size_t>& stabilizer::parser::Parser::getVarNames () inline
Definition at line 321 of file parser.h.
References var_names.
getZero()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::getZero (std::shared_ptr< Sort > sort)
Get the zero for a sort.
Parameters
sort Sort
Returns
Zero for the sort
Definition at line 2484 of file base_parser.cpp.
References stabilizer::parser::ERR_UNKWN_SYM, mkConstBv(), mkConstFp(), mkConstInt(), mkConstReal(), mkConstStr(), and mkErr().
isCommutative()
bool stabilizer::parser::Parser::isCommutative (NODE_KIND t) static
Check whether an operation kind is treated as commutative.
Definition at line 84 of file op_parser.cpp.
References stabilizer::parser::NT_ADD, stabilizer::parser::NT_AND, stabilizer::parser::NT_BV_ADD, stabilizer::parser::NT_BV_AND, stabilizer::parser::NT_BV_COMP, stabilizer::parser::NT_BV_MUL, stabilizer::parser::NT_BV_NAND, stabilizer::parser::NT_BV_NOR, stabilizer::parser::NT_BV_OR, stabilizer::parser::NT_BV_SADDO, stabilizer::parser::NT_BV_UADDO, stabilizer::parser::NT_BV_UMULO, stabilizer::parser::NT_BV_XNOR, stabilizer::parser::NT_BV_XOR, stabilizer::parser::NT_DISTINCT, stabilizer::parser::NT_EQ, stabilizer::parser::NT_EXISTS, stabilizer::parser::NT_FORALL, stabilizer::parser::NT_FP_ADD, stabilizer::parser::NT_FP_EQ, stabilizer::parser::NT_FP_MAX, stabilizer::parser::NT_FP_MIN, stabilizer::parser::NT_FP_MUL, stabilizer::parser::NT_IAND, stabilizer::parser::NT_MAX, stabilizer::parser::NT_MIN, stabilizer::parser::NT_MUL, stabilizer::parser::NT_OR, and stabilizer::parser::NT_XOR.
Referenced by mkInternalOper(), and mkNode().
isDeclaredFunction()
bool stabilizer::parser::Parser::isDeclaredFunction (const std::string & func_name) const
Check if a function is declared.
Parameters
func_name Function name
Returns
True if the function is declared, false otherwise
Definition at line 2508 of file base_parser.cpp.
References fun_key_map.
isDeclaredVariable()
bool stabilizer::parser::Parser::isDeclaredVariable (const std::string & var_name) const
Check if a variable is declared.
Parameters
var_name Variable name
Returns
True if the variable is declared, false otherwise
Definition at line 2505 of file base_parser.cpp.
References var_names.
isOne()
bool stabilizer::parser::Parser::isOne (std::shared_ptr< DAGNode > expr)
Check if an expression is one.
Parameters
expr Expression to check
Returns
true if the expression is one, false otherwise
Definition at line 317 of file base_parser.cpp.
References toInt(), toReal(), and stabilizer::parser::HighPrecisionInteger::toString().
Referenced by mkMul(), and rewrite().
isOnes()
bool stabilizer::parser::Parser::isOnes (std::shared_ptr< DAGNode > expr)
Definition at line 328 of file base_parser.cpp.
Referenced by rewrite().
isZero()
bool stabilizer::parser::Parser::isZero (std::shared_ptr< DAGNode > expr)
Check if an expression is zero.
Parameters
expr Expression to check
Returns
true if the expression is zero, false otherwise
Definition at line 306 of file base_parser.cpp.
References toInt(), toReal(), and stabilizer::parser::HighPrecisionInteger::toString().
Referenced by mkAdd(), mkMul(), mkSub(), and rewrite().
mkAbs()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAbs (std::shared_ptr< DAGNode > param)
Create an abs node.
Parameters
param Parameter
Returns
Abs node (|param|)
Definition at line 1435 of file op_parser.cpp.
References err_all(), stabilizer::parser::isIntParam(), stabilizer::parser::isRealParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_ABS.
Referenced by parseOper().
mkAcos()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAcos (std::shared_ptr< DAGNode > param)
Create an acos node.
Note
assert(param >= -1 && param <= 1)
Parameters
param Parameter
Returns
Acos node (acos(param))
Definition at line 1573 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ACOS, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAcosh()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAcosh (std::shared_ptr< DAGNode > param)
Create an acosh node.
Note
assert(param >= 1)
Parameters
param Parameter
Returns
Acosh node (acosh(param))
Definition at line 1645 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ACOSH, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAcot()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAcot (std::shared_ptr< DAGNode > param)
Create an acot node.
Parameters
param Parameter
Returns
Acot node (acot(param))
Definition at line 1597 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ACOT, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAcoth()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAcoth (std::shared_ptr< DAGNode > param)
Create an acoth node.
Note
assert(param < -1 || param > 1)
Parameters
param Parameter
Returns
Acoth node (acoth(param))
Definition at line 1669 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ACOTH, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAcsc()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAcsc (std::shared_ptr< DAGNode > param)
Create an acsc node.
Note
assert(param <= -1 || param >= 1)
Parameters
param Parameter
Returns
Acsc node (acsc(param))
Definition at line 1585 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ACSC, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAcsch()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAcsch (std::shared_ptr< DAGNode > param)
Create an acsch node.
Note
assert(param != 0)
Parameters
param Parameter
Returns
Acsch node (acsch(param))
Definition at line 1663 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ACSCH, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAdd()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAdd (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an add node.
Parameters
params Parameters
Returns
Add node (l + r + ...)
Definition at line 1120 of file op_parser.cpp.
References stabilizer::parser::canExempt(), condAssert, err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::SortManager::INT_SORT, isZero(), line_number, mkConstInt(), mkConstReal(), mkOper(), mkUnknown(), stabilizer::parser::NT_ADD, options, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseExpr(), and parseOper().
mkAnd()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAnd (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an and node.
Parameters
params Parameters
Returns
And node (l and m and r and ...)
Definition at line 927 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_type_mis(), stabilizer::parser::isBoolParam(), line_number, mkFalse(), mkOper(), mkTrue(), mkUnknown(), and stabilizer::parser::NT_AND.
Referenced by parseExpr(), and parseOper().
mkApplyDTFun()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkApplyDTFun (const std::shared_ptr< Sort > & sort, const std::string & name, const std::vector< std::shared_ptr< DAGNode >> & params)
Definition at line 2292 of file base_parser.cpp.
References node_manager, and stabilizer::parser::NT_UF_APPLY.
Referenced by applyFun(), applyFunPostOrder(), and parseConstFunc().
mkApplyFunc()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkApplyFunc (std::shared_ptr< DAGNode > fun, const std::vector< std::shared_ptr< DAGNode >> & params)
Create a function application node.
Parameters
fun Function node
params List of parameters
Returns
Function application node (fun(p1, p2, ..., pn))
Definition at line 2244 of file base_parser.cpp.
References stabilizer::parser::NT_FUNC_APPLY, and static_functions.
Referenced by applyFun().
mkApplyRecFunc()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkApplyRecFunc (std::shared_ptr< DAGNode > fun, const std::vector< std::shared_ptr< DAGNode >> & params)
Create a recursive function application.
Parameters
fun Recursive function symbol node
params Argument list
Returns
Recursive function application node
Definition at line 2254 of file base_parser.cpp.
References stabilizer::parser::NT_FUNC_REC_APPLY, and static_functions.
Referenced by applyFun(), and applyFunPostOrder().
mkApplyUF()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkApplyUF (const std::shared_ptr< Sort > & sort, const std::string & name, const std::vector< std::shared_ptr< DAGNode >> & params)
Apply an uninterpreted function.
Parameters
sort Sort
name Function name
params Parameters
Returns
Uninterpreted function application node
Definition at line 2287 of file base_parser.cpp.
References node_manager, and stabilizer::parser::NT_UF_APPLY.
Referenced by applyFun(), applyFunPostOrder(), and parseOper().
mkArray()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkArray (const std::string & name, std::shared_ptr< Sort > index, std::shared_ptr< Sort > elem)
Create an array.
Parameters
name Array name
index Index sort
elem Element sort
Returns
Array node
Definition at line 877 of file op_parser.cpp.
References mkVar(), sort_key_map, and sort_manager.
mkArraySort()
std::shared_ptr< Sort > stabilizer::parser::Parser::mkArraySort (std::shared_ptr< Sort > index, std::shared_ptr< Sort > elem)
Create an array sort.
Parameters
index Index sort
elem Element sort
Returns
Array sort
Definition at line 506 of file op_parser.cpp.
References sort_manager.
mkAsec()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAsec (std::shared_ptr< DAGNode > param)
Create an asec node.
Note
assert(param <= -1 || param >= 1)
Parameters
param Parameter
Returns
Asec node (asec(param))
Definition at line 1579 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ASEC, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAsech()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAsech (std::shared_ptr< DAGNode > param)
Create an asech node.
Note
assert(param > 0 && param <= 1)
Parameters
param Parameter
Returns
Asech node (asech(param))
Definition at line 1657 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ASECH, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAsin()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAsin (std::shared_ptr< DAGNode > param)
Create an asin node.
Note
assert(param >= -1 && param <= 1)
Parameters
param Parameter
Returns
Asin node (asin(param))
Definition at line 1567 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ASIN, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAsinh()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAsinh (std::shared_ptr< DAGNode > param)
Create an asinh node.
Parameters
param Parameter
Returns
Asinh node (asinh(param))
Definition at line 1639 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ASINH, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAtan()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAtan (std::shared_ptr< DAGNode > param)
Create an atan node.
Parameters
param Parameter
Returns
Atan node (atan(param))
Definition at line 1591 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ATAN, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAtan2()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAtan2 (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an atan2 node.
Note
Represents the angle in radians between the positive x-axis and the ray to point (r, l)
atan2(l, r) = atan(l/r) with appropriate quadrant adjustment
Parameters
l Left parameter (y-coordinate)
r Right parameter (x-coordinate)
Returns
Atan2 node (atan2(l, r))
Definition at line 1675 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ATAN2, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAtanh()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAtanh (std::shared_ptr< DAGNode > param)
Create an atanh node.
Note
assert(param > -1 && param < 1)
Parameters
param Parameter
Returns
Atanh node (atanh(param))
Definition at line 1651 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_ATANH, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkAttribute()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkAttribute (const std::shared_ptr< Sort > & sort, const std::string & name, const std::vector< std::shared_ptr< DAGNode >> & params)
Definition at line 2283 of file base_parser.cpp.
References node_manager, and stabilizer::parser::NT_ATTRIBUTE.
Referenced by parseExpr().
mkBoolSort()
std::shared_ptr< Sort > stabilizer::parser::Parser::mkBoolSort ()
Create a boolean sort.
Returns
Boolean sort
Definition at line 493 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT.
mkBvAdd()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvAdd (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a bitvector addition node.
Parameters
params Parameters
Returns
Bitvector addition node (l + r + ...)
Definition at line 2072 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_ADD.
Referenced by parseOper().
mkBvAnd()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvAnd (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a bitvector and node.
Parameters
params Parameters
Returns
Bitvector and node (l & r & ...)
Definition at line 1934 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::isBvParam(), line_number, mkOper(), mkTrue(), mkUnknown(), and stabilizer::parser::NT_BV_AND.
Referenced by parseOper().
mkBvAshr()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvAshr (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector arithmetic shift right node.
Parameters
l Left parameter
r Right parameter
Returns
Bitvector arithmetic shift right node (l >> r)
Definition at line 2229 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_ASHR.
Referenced by parseOper().
mkBvComp()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvComp (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a bitvector comparison node.
Parameters
params Operand list; the first two operands are compared.
Returns
Bitvector comparison node (l = r ? #b1 : #b0)
Definition at line 2047 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_BV_COMP, and sort_manager.
Referenced by parseOper().
mkBvConcat()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvConcat (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a bitvector concatenation node.
Parameters
params Parameters
Returns
Bitvector concatenation node (l ++ r ++ ...)
Definition at line 2241 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_BV_CONCAT, and sort_manager.
Referenced by parseOper().
mkBvExtract()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvExtract (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
Create a bitvector extract node.
Creates a bitvector extract node that extracts a range of bits.
Note
assert(r >= s && r < bitwidth(l))
Parameters
l Source bitvector
r Upper index (inclusive)
s Lower index (inclusive)
Returns
Bitvector extract node (l[r:s])
Definition at line 2270 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_BV_EXTRACT, sort_manager, toInt(), and stabilizer::parser::HighPrecisionInteger::toULong().
Referenced by parseOper().
mkBvLshr()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvLshr (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector logical shift right node.
Parameters
l Left parameter
r Right parameter
Returns
Bitvector logical shift right node (l >> r)
Definition at line 2218 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_LSHR.
Referenced by parseOper().
mkBvMul()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvMul (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a bitvector multiplication node.
Parameters
params Parameters
Returns
Bitvector multiplication node (l * r * ...)
Definition at line 2112 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_MUL.
Referenced by parseOper().
mkBvNand()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvNand (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector nand node.
Parameters
l Left operand
r Right operand
Returns
Bitvector nand node (~(l & r & ...))
Definition at line 2026 of file op_parser.cpp.
References getSort(), mkOper(), and stabilizer::parser::NT_BV_NAND.
Referenced by parseOper().
mkBvNeg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvNeg (std::shared_ptr< DAGNode > param)
Create a bitvector negation node.
Parameters
param Parameter
Returns
Bitvector negation node (-param)
Definition at line 2067 of file op_parser.cpp.
References mkOper(), and stabilizer::parser::NT_BV_NEG.
Referenced by parseOper(), and rewrite().
mkBvNor()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvNor (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector nor node.
Parameters
l Left operand
r Right operand
Returns
Bitvector nor node (~(l | r | ...))
Definition at line 2036 of file op_parser.cpp.
References getSort(), mkOper(), and stabilizer::parser::NT_BV_NOR.
Referenced by parseOper().
mkBvNot()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvNot (std::shared_ptr< DAGNode > param)
Create a bitvector not node.
Parameters
param Parameter
Returns
Bitvector not node (~param)
Definition at line 1926 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_NOT.
Referenced by parseOper(), and rewrite().
mkBvOr()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvOr (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a bitvector or node.
Parameters
params Parameters
Returns
Bitvector or node (l | r | ...)
Definition at line 1967 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::isBvParam(), line_number, mkFalse(), mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_OR.
Referenced by parseOper().
mkBvRepeat()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvRepeat (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector repeat node.
Creates a bitvector repeat node that repeats the bitvector r times.
Note
assert(r > 0)
Parameters
l Source bitvector
r Repeat count
Returns
Bitvector repeat node (l repeated r times)
Definition at line 2287 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_BV_REPEAT, sort_manager, toInt(), and stabilizer::parser::HighPrecisionInteger::toULong().
Referenced by parseOper().
mkBvRotateLeft()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvRotateLeft (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector rotate left node.
Parameters
l Source bitvector
r Rotation amount
Returns
Bitvector rotate left node (l <<< r)
Definition at line 2330 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_BV_ROTATE_LEFT, and sort_manager.
Referenced by parseOper().
mkBvRotateRight()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvRotateRight (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector rotate right node.
Parameters
l Source bitvector
r Rotation amount
Returns
Bitvector rotate right node (l >>> r)
Definition at line 2345 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_BV_ROTATE_RIGHT, and sort_manager.
Referenced by parseOper().
mkBvSdiv()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvSdiv (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed division node.
Note
if r == 0, then return all ones bit-vector if l is positive, otherwise 1
Parameters
l Left parameter
r Right parameter
Returns
Bitvector signed division node (l / r)
Definition at line 2174 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_SDIV.
Referenced by parseOper().
mkBvSge()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvSge (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed greater than or equal node.
Parameters
l Left parameter
r Right parameter
Returns
Bitvector signed greater than or equal node (l >= r)
Definition at line 2500 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, stabilizer::parser::BitVectorUtils::bvComp(), err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkFalse(), mkOper(), mkTrue(), mkUnknown(), and stabilizer::parser::NT_BV_SGE.
Referenced by parseExpr(), and parseOper().
mkBvSgt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvSgt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed greater than node.
Parameters
l Left parameter
r Right parameter
Returns
Bitvector signed greater than node (l > r)
Definition at line 2479 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, stabilizer::parser::BitVectorUtils::bvComp(), err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkFalse(), mkOper(), mkTrue(), mkUnknown(), and stabilizer::parser::NT_BV_SGT.
Referenced by parseExpr(), and parseOper().
mkBvShl()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvShl (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector shift left node.
Parameters
l Left parameter
r Right parameter
Returns
Bitvector shift left node (l << r)
Definition at line 2207 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_SHL.
Referenced by parseOper().
mkBvSignExt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvSignExt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector sign extension node.
Creates a bitvector sign extension node that extends the bitvector with r sign bits.
Parameters
l Source bitvector
r Number of bits to extend
Returns
Bitvector sign extension node (l sign_extend r)
Definition at line 2315 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_BV_SIGN_EXT, sort_manager, toInt(), and stabilizer::parser::HighPrecisionInteger::toULong().
Referenced by parseOper().
mkBvSle()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvSle (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed less than or equal node.
Parameters
l Left parameter
r Right parameter
Returns
Bitvector signed less than or equal node (l <= r)
Definition at line 2458 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, stabilizer::parser::BitVectorUtils::bvComp(), err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkFalse(), mkOper(), mkTrue(), mkUnknown(), and stabilizer::parser::NT_BV_SLE.
Referenced by parseExpr(), and parseOper().
mkBvSlt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvSlt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed less than node.
Parameters
l Left parameter
r Right parameter
Returns
Bitvector signed less than node (l < r)
Definition at line 2437 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, stabilizer::parser::BitVectorUtils::bvComp(), err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkFalse(), mkOper(), mkTrue(), mkUnknown(), and stabilizer::parser::NT_BV_SLT.
Referenced by parseExpr(), and parseOper().
mkBvSmod()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvSmod (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed modulo node.
Note
if r == 0, then return l
Parameters
l Left parameter
r Right parameter
Returns
Bitvector signed modulo node (l % r)
Definition at line 2196 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_SMOD.
Referenced by parseOper().
mkBVSort()
std::shared_ptr< Sort > stabilizer::parser::Parser::mkBVSort (const size_t & width)
Create a bit-vector sort.
Parameters
width Width of the bit-vector
Returns
Bit-vector sort
Definition at line 500 of file op_parser.cpp.
References sort_manager.
mkBvSrem()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvSrem (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector signed remainder node.
Note
if r == 0, then return l
Parameters
l Left parameter
r Right parameter
Returns
Bitvector signed remainder node (l % r)
Definition at line 2185 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_SREM.
Referenced by parseOper().
mkBvSub()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvSub (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector subtraction node.
Parameters
l Left operand
r Right operand
Returns
Bitvector subtraction node (l - r - ...)
Definition at line 2100 of file op_parser.cpp.
References getSort(), mkOper(), and stabilizer::parser::NT_BV_SUB.
Referenced by parseOper().
mkBvToInt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvToInt (std::shared_ptr< DAGNode > param)
Create a bitvector to integer conversion node.
Parameters
param Parameter
Returns
Bitvector to integer conversion node (to_int(param))
Definition at line 2546 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_TO_INT.
Referenced by parseOper().
mkBvToNat()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvToNat (std::shared_ptr< DAGNode > param)
Create a bitvector to natural number conversion node.
Parameters
param Parameter
Returns
Bitvector to natural number conversion node (to_nat(param))
Definition at line 2522 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_TO_NAT.
Referenced by parseOper().
mkBvUdiv()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvUdiv (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned division node.
Note
if r == 0, then return all ones bit-vector
Parameters
l Left parameter
r Right parameter
Returns
Bitvector unsigned division node (l / r)
Definition at line 2141 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_UDIV.
Referenced by parseOper().
mkBvUge()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvUge (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned greater than or equal node.
Parameters
l Left parameter
r Right parameter
Returns
Bitvector unsigned greater than or equal node (l >= r)
Definition at line 2416 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, stabilizer::parser::BitVectorUtils::bvComp(), err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkFalse(), mkOper(), mkTrue(), mkUnknown(), and stabilizer::parser::NT_BV_UGE.
Referenced by parseExpr(), and parseOper().
mkBvUgt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvUgt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned greater than node.
Parameters
l Left parameter
r Right parameter
Returns
Bitvector unsigned greater than node (l > r)
Definition at line 2395 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, stabilizer::parser::BitVectorUtils::bvComp(), err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkFalse(), mkOper(), mkTrue(), mkUnknown(), and stabilizer::parser::NT_BV_UGT.
Referenced by parseExpr(), and parseOper().
mkBvUle()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvUle (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned less than or equal node.
Parameters
l Left parameter
r Right parameter
Returns
Bitvector unsigned less than or equal node (l <= r)
Definition at line 2374 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, stabilizer::parser::BitVectorUtils::bvComp(), err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkFalse(), mkOper(), mkTrue(), mkUnknown(), and stabilizer::parser::NT_BV_ULE.
Referenced by parseExpr(), and parseOper().
mkBvUlt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvUlt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned less than node.
Parameters
l Left parameter
r Right parameter
Returns
Bitvector unsigned less than node (l < r)
Definition at line 2360 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkFalse(), mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_ULT.
Referenced by parseExpr(), and parseOper().
mkBvUmod()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvUmod (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned modulo node.
Note
if r == 0, then return l
Parameters
l Left parameter
r Right parameter
Returns
Bitvector unsigned modulo node (l % r)
Definition at line 2163 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_UMOD.
mkBvUrem()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvUrem (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector unsigned remainder node.
Note
if r == 0, then return l
Parameters
l Left parameter
r Right parameter
Returns
Bitvector unsigned remainder node (l % r)
Definition at line 2152 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_UREM.
Referenced by parseOper().
mkBvXnor()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvXnor (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector xnor node.
Parameters
l Left operand
r Right operand
Returns
Bitvector xnor node (~(l ^ r ^ ...))
Definition at line 2053 of file op_parser.cpp.
References getSort(), mkOper(), and stabilizer::parser::NT_BV_XNOR.
Referenced by parseOper().
mkBvXor()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvXor (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a bitvector xor node.
Parameters
params Parameters
Returns
Bitvector xor node (l ^ r ^ ...)
Definition at line 1997 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::isBvParam(), line_number, mkFalse(), mkOper(), mkUnknown(), and stabilizer::parser::NT_BV_XOR.
Referenced by parseOper().
mkBvZeroExt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkBvZeroExt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a bitvector zero extension node.
Creates a bitvector zero extension node that extends the bitvector with r zero bits.
Parameters
l Source bitvector
r Number of bits to extend
Returns
Bitvector zero extension node (l zero_extend r)
Definition at line 2301 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_BV_ZERO_EXT, sort_manager, toInt(), and stabilizer::parser::HighPrecisionInteger::toULong().
Referenced by parseOper(), and rewrite().
mkCeil()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkCeil (std::shared_ptr< DAGNode > param)
Create an ceil node.
Parameters
param Parameter
Returns
Ceil node (ceil(param))
Definition at line 1467 of file op_parser.cpp.
References err_all(), stabilizer::parser::isIntParam(), stabilizer::parser::isRealParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_CEIL.
Referenced by parseOper().
mkConstArray()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstArray (std::shared_ptr< Sort > sort, std::shared_ptr< DAGNode > value)
Create a constant array node.
Parameters
sort Array sort
value Constant value for all elements
Returns
Constant array node
Definition at line 898 of file op_parser.cpp.
References err_all(), line_number, mkUnknown(), node_manager, and stabilizer::parser::NT_CONST_ARRAY.
Referenced by parseExpr().
mkConstBv()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstBv (const std::string & v, const size_t & width)
Create a bit-vector constant.
Parameters
v Value (string)
width Width of the bit-vector
Returns
Bit-vector constant node
Definition at line 727 of file op_parser.cpp.
References stabilizer::parser::BitVectorUtils::natToBv(), node_manager, stabilizer::parser::NT_CONST, sort_key_map, and sort_manager.
Referenced by getZero(), mkFpToSbv(), mkFpToUbv(), parseConstFunc(), parseExpr(), and rewrite().
mkConstFP()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstFP (const std::string & fp_expr)
Create a floating-point constant from expression.
Parameters
fp_expr Floating-point expression string
Returns
Floating-point constant node
Definition at line 758 of file op_parser.cpp.
References node_manager, and stabilizer::parser::NT_CONST.
Referenced by parseConstFunc().
mkConstFp()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstFp (const std::string & v, const size_t & e, const size_t & s)
Create a floating-point constant.
Parameters
v Value (string)
e Exponent size
s Significand size
Returns
Floating-point constant node
Definition at line 742 of file op_parser.cpp.
References node_manager, stabilizer::parser::NT_CONST, sort_key_map, and sort_manager.
Referenced by getZero().
mkConstInt() [1/4]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstInt (const int & v)
Create an integer constant.
Parameters
v Value (int)
Returns
Integer constant node
Definition at line 683 of file op_parser.cpp.
References mkConstInt().
mkConstInt() [2/4]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstInt (const Integer & v)
Create an integer constant.
Parameters
v Value (Integer)
Returns
Integer constant node
Definition at line 674 of file op_parser.cpp.
References stabilizer::parser::SortManager::INTOREAL_SORT, node_manager, stabilizer::parser::NT_CONST, and stabilizer::parser::ConversionUtils::toString().
mkConstInt() [3/4]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstInt (const Number & v)
Create a real constant from number.
Parameters
v Value (Number)
Returns
Real constant node
Definition at line 686 of file op_parser.cpp.
References mkConstInt(), and stabilizer::parser::Number::toInteger().
mkConstInt() [4/4]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstInt (const std::string & v)
Create an integer constant from string.
Parameters
v Value (string)
Returns
Integer constant node
Definition at line 680 of file op_parser.cpp.
Referenced by getZero(), mkAdd(), mkConstInt(), mkIand(), mkMul(), mkRootObj(), mkSub(), parseConstFunc(), and rewrite().
mkConstReal() [1/5]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstReal (const double & v)
Create a real constant from double.
Parameters
v Value (double)
Returns
Real constant node
Definition at line 702 of file op_parser.cpp.
References node_manager, stabilizer::parser::NT_CONST, and stabilizer::parser::SortManager::REAL_SORT.
mkConstReal() [2/5]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstReal (const Integer & v)
Create a real constant from integer.
Parameters
v Value (Integer)
Returns
Real constant node
Definition at line 706 of file op_parser.cpp.
References node_manager, stabilizer::parser::NT_CONST, stabilizer::parser::SortManager::REAL_SORT, and stabilizer::parser::ConversionUtils::toString().
mkConstReal() [3/5]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstReal (const Number & v)
Create a real constant from number.
Parameters
v Value (Number)
Returns
Real constant node
Definition at line 710 of file op_parser.cpp.
References mkConstReal(), and stabilizer::parser::Number::toReal().
mkConstReal() [4/5]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstReal (const Real & v)
Create a real constant.
Parameters
v Value (Real)
Returns
Real constant node
Definition at line 698 of file op_parser.cpp.
References node_manager, stabilizer::parser::NT_CONST, stabilizer::parser::SortManager::REAL_SORT, and stabilizer::parser::ConversionUtils::toString().
mkConstReal() [5/5]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstReal (const std::string & v)
Create a real constant from string.
Parameters
v Value (string)
Returns
Real constant node
Definition at line 689 of file op_parser.cpp.
References condAssert, stabilizer::parser::NodeManager::E_NODE, stabilizer::parser::TypeChecker::isReal(), node_manager, stabilizer::parser::NT_CONST, stabilizer::parser::NodeManager::PI_NODE, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by getZero(), mkAdd(), mkConstReal(), mkMul(), mkSub(), parseConstFunc(), and rewrite().
mkConstReg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstReg (const std::string & v)
Create a regular expression constant.
Parameters
v Value (string)
Returns
Regular expression constant node
Definition at line 761 of file op_parser.cpp.
References node_manager, stabilizer::parser::NT_CONST, and stabilizer::parser::SortManager::REG_SORT.
Referenced by mkRegAll(), mkRegAllChar(), and mkRegNone().
mkConstStr()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkConstStr (const std::string & v)
Create a string constant.
Parameters
v Value (string)
Returns
String constant node
Definition at line 713 of file op_parser.cpp.
References stabilizer::parser::ConversionUtils::escapeString(), node_manager, stabilizer::parser::NT_CONST, stabilizer::parser::SortManager::STR_SORT, and stabilizer::parser::ConversionUtils::unescapeString().
Referenced by getZero(), mkStrConcat(), parseConstFunc(), and rewrite().
mkCos()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkCos (std::shared_ptr< DAGNode > param)
Create an cos node.
Parameters
param Parameter
Returns
Cos node (cos(param))
Definition at line 1537 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_COS, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkCosh()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkCosh (std::shared_ptr< DAGNode > param)
Create a cosh node.
Parameters
param Parameter
Returns
Cosh node (cosh(param))
Definition at line 1609 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_COSH, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkCot()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkCot (std::shared_ptr< DAGNode > param)
Create a cot node.
Note
assert(param != k*pi)
Parameters
param Parameter
Returns
Cot node (cot(param))
Definition at line 1561 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_COT, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkCoth()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkCoth (std::shared_ptr< DAGNode > param)
Create a coth node.
Note
assert(param < -1 || param > 1)
Parameters
param Parameter
Returns
Coth node (coth(param))
Definition at line 1633 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_COTH, and stabilizer::parser::SortManager::REAL_SORT.
mkCsc()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkCsc (std::shared_ptr< DAGNode > param)
Create an csc node.
Parameters
param Parameter
Returns
Csc node (csc(param))
Definition at line 1549 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_CSC, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkCsch()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkCsch (std::shared_ptr< DAGNode > param)
Create a csch node.
Note
assert(param != 0)
Parameters
param Parameter
Returns
Csch node (csch(param))
Definition at line 1627 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_CSCH, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkDistinct()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkDistinct (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a distinct node.
Parameters
params Parameters
Returns
Distinct node
Definition at line 567 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, stabilizer::parser::canExempt(), err_all(), stabilizer::parser::ERR_PARAM_MIS, getSort(), line_number, mkFalse(), mkOper(), mkUnknown(), and stabilizer::parser::NT_DISTINCT.
Referenced by parseExpr(), and parseOper().
mkDiv()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkDiv (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an div node.
Note
This is the real division operator.
Parameters
l Left parameter
r Right parameter
Returns
Div node (l / r / ...)
Definition at line 1405 of file op_parser.cpp.
References mkDivReal().
mkDivInt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkDivInt (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an div node.
Parameters
params Parameters
Returns
Div node (l / r / ...)
Definition at line 1393 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::SortManager::INT_SORT, line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_DIV_INT.
Referenced by parseOper().
mkDivReal()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkDivReal (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an div node.
Parameters
params Parameters
Returns
Div node (l / r / ...)
Definition at line 1410 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_DIV_REAL, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by mkDiv(), and parseOper().
mkE()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkE ()
Create a e node.
Returns
E node (e, i.e., the base of the natural logarithm)
Definition at line 1789 of file op_parser.cpp.
References stabilizer::parser::NodeManager::E_NODE.
Referenced by parseConstFunc().
mkEpsilon()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkEpsilon ()
Create a epsilon node.
Returns
Epsilon node (epsilon, i.e., a infinitesimal number)
Definition at line 1873 of file op_parser.cpp.
References stabilizer::parser::NodeManager::EPSILON_NODE.
Referenced by parseConstFunc().
mkEq()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkEq (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an equality node.
Parameters
params Parameters
Returns
Equality node
Definition at line 513 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, stabilizer::parser::canExempt(), err_all(), stabilizer::parser::ERR_PARAM_MIS, getSort(), line_number, mkOper(), mkTrue(), mkUnknown(), and stabilizer::parser::NT_EQ.
Referenced by parseExpr(), parseOper(), and rewrite().
mkErr()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkErr (const ERROR_TYPE t) private
Definition at line 2513 of file base_parser.cpp.
References node_manager, and stabilizer::parser::NT_ERROR.
Referenced by applyFun(), applyFunPostOrder(), getZero(), mkExpr(), mkLetChain(), parseConstFunc(), parseExpr(), parseLet(), parseOper(), and parsePreservingLet().
mkExists()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkExists (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an exists node.
Parameters
params List of (variable, sort) pairs
Returns
Exists node (exists((var1, sort1), (var2, sort2), ..., body))
Definition at line 2362 of file base_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, mkOper(), and stabilizer::parser::NT_EXISTS.
Referenced by parseQuant().
mkExp()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkExp (std::shared_ptr< DAGNode > param)
Create an exp node.
Parameters
param Parameter
Returns
Exp node (exp(param))
Definition at line 1490 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_EXP, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkExpr()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkExpr (const std::string & expression)
Create a DAG node from a string expression.
Parses the specified string expression and returns the corresponding DAG node.
Parameters
expression String expression to parse
Returns
Parsed DAG node
Definition at line 729 of file base_parser.cpp.
References buffer, buflen, bufptr, stabilizer::parser::ERR_UNEXP_EOF, line_number, mkErr(), parseExpr(), parsing_file, stabilizer::parser::safe_strdup(), and scanToNextSymbol().
Referenced by assert().
mkFact()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFact (std::shared_ptr< DAGNode > param)
Create a factorial node.
Note
assert(param >= 0)
Parameters
param Parameter
Returns
Factorial node (factorial(param))
Definition at line 1915 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FACT.
Referenced by parseOper().
mkFalse()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFalse ()
Create a false node.
Returns
False node
Definition at line 79 of file op_parser.cpp.
References stabilizer::parser::NodeManager::FALSE_NODE.
Referenced by mkAnd(), mkBvOr(), mkBvSge(), mkBvSgt(), mkBvSle(), mkBvSlt(), mkBvUge(), mkBvUgt(), mkBvUle(), mkBvUlt(), mkBvXor(), mkDistinct(), mkOr(), mkXor(), parseConstFunc(), and rewrite().
mkFloor()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFloor (std::shared_ptr< DAGNode > param)
Create an floor node.
Parameters
param Parameter
Returns
Floor node (floor(param))
Definition at line 1477 of file op_parser.cpp.
References stabilizer::parser::SortManager::INT_SORT, mkOper(), and stabilizer::parser::NT_FLOOR.
Referenced by parseOper().
mkForall()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkForall (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a forall node.
Parameters
params List of (variable, sort) pairs
Returns
Forall node (forall((var1, sort1), (var2, sort2), ..., body))
Definition at line 2358 of file base_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, mkOper(), and stabilizer::parser::NT_FORALL.
Referenced by parseQuant().
mkFpAbs()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpAbs (std::shared_ptr< DAGNode > param)
Create a floating-point absolute value node.
Parameters
param Parameter
Returns
Floating-point absolute value node (fp.abs(param))
Definition at line 2759 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_ABS.
Referenced by parseOper().
mkFpAdd()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpAdd (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a floating-point addition node.
Parameters
params Parameters
Returns
Floating-point addition node (fp.add(l, r, ...))
Definition at line 2588 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_ADD.
Referenced by parseOper().
mkFpConst()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpConst (std::shared_ptr< DAGNode > sign, std::shared_ptr< DAGNode > exp, std::shared_ptr< DAGNode > mant)
Definition at line 3173 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkUnknown(), node_manager, stabilizer::parser::NT_CONST, and sort_manager.
Referenced by parseExpr().
mkFpDiv()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpDiv (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a floating-point division node.
Note
Division by zero results in appropriate IEEE-754 behavior
Parameters
params Parameters
Returns
Floating-point division node (fp.div(l, r, ...))
Definition at line 2717 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_DIV.
Referenced by parseOper().
mkFpEq()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpEq (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a floating-point equality node.
Note
This is IEEE-754 equality (NaN != NaN)
Parameters
params Parameters
Returns
Floating-point equality node (fp.eq(params))
Definition at line 2974 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, mkOper(), and stabilizer::parser::NT_FP_EQ.
Referenced by parseOper().
mkFpFma()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpFma (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a floating-point fused multiply-add node.
Note
The operation (a * b + c) performed with only one rounding
Parameters
params Parameters (should have exactly 3 elements)
Returns
Floating-point fused multiply-add node (fp.fma(a, b, c) = a * b + c)
Definition at line 2794 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_FMA.
Referenced by parseOper().
mkFpGe()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpGe (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a floating-point greater than or equal node.
Parameters
params Parameters
Returns
Floating-point greater than or equal node (fp.geq(params)
Definition at line 2948 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, mkOper(), and stabilizer::parser::NT_FP_GE.
Referenced by parseOper().
mkFpGt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpGt (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a floating-point greater than node.
Parameters
params Parameters
Returns
Floating-point greater than node (fp.gt(params))
Definition at line 2961 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, mkOper(), and stabilizer::parser::NT_FP_GT.
Referenced by parseOper().
mkFpIsInf()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpIsInf (std::shared_ptr< DAGNode > param)
Create a floating-point is-infinity check node.
Parameters
param Parameter to check
Returns
Is-infinity check node (fp.isInf(param))
Definition at line 3238 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_IS_INF.
Referenced by parseOper().
mkFpIsNaN()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpIsNaN (std::shared_ptr< DAGNode > param)
Create a floating-point is-NaN check node.
Parameters
param Parameter to check
Returns
Is-NaN check node (fp.isNaN(param))
Definition at line 3249 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_IS_NAN.
Referenced by parseOper().
mkFpIsNeg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpIsNeg (std::shared_ptr< DAGNode > param)
Create a floating-point is-negative check node.
Parameters
param Parameter to check
Returns
Is-negative check node (fp.isNegative(param))
Definition at line 3260 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_IS_NEG.
Referenced by parseOper().
mkFpIsNormal()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpIsNormal (std::shared_ptr< DAGNode > param)
Create a floating-point is-normal check node.
Parameters
param Parameter to check
Returns
Is-normal check node (fp.isNormal(param))
Definition at line 3204 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_IS_NORMAL.
Referenced by parseOper().
mkFpIsPos()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpIsPos (std::shared_ptr< DAGNode > param)
Create a floating-point is-positive check node.
Parameters
param Parameter to check
Returns
Is-positive check node (fp.isPositive(param))
Definition at line 3271 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_IS_POS.
Referenced by parseOper().
mkFpIsSubnormal()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpIsSubnormal (std::shared_ptr< DAGNode > param)
Create a floating-point is-subnormal check node.
Parameters
param Parameter to check
Returns
Is-subnormal check node (fp.isSubnormal(param))
Definition at line 3216 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_IS_SUBNORMAL.
Referenced by parseOper().
mkFpIsZero()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpIsZero (std::shared_ptr< DAGNode > param)
Create a floating-point is-zero check node.
Parameters
param Parameter to check
Returns
Is-zero check node (fp.isZero(param))
Definition at line 3227 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_IS_ZERO.
Referenced by parseOper().
mkFpLe()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpLe (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a floating-point less than or equal node.
Parameters
params Parameters
Returns
Floating-point less than or equal node (fp.leq(params))
Definition at line 2920 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, mkOper(), and stabilizer::parser::NT_FP_LE.
Referenced by parseOper().
mkFpLt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpLt (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a floating-point less than node.
Parameters
params Parameters
Returns
Floating-point less than node (fp.lt(params))
Definition at line 2934 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, mkOper(), and stabilizer::parser::NT_FP_LT.
Referenced by parseOper().
mkFpMax()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpMax (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a floating-point maximum node.
Parameters
l Left operand
r Right operand
Returns
Floating-point maximum node (fp.max(params))
Definition at line 2905 of file op_parser.cpp.
References getSort(), mkOper(), and stabilizer::parser::NT_FP_MAX.
Referenced by parseOper().
mkFpMin()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpMin (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a floating-point minimum node.
Parameters
l Left operand
r Right operand
Returns
Floating-point minimum node (fp.min(params))
Definition at line 2892 of file op_parser.cpp.
References getSort(), mkOper(), and stabilizer::parser::NT_FP_MIN.
Referenced by parseOper().
mkFpMul()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpMul (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a floating-point multiplication node.
Parameters
params Parameters
Returns
Floating-point multiplication node (fp.mul(l, r, ...))
Definition at line 2674 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_MUL.
Referenced by parseOper().
mkFpNeg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpNeg (std::shared_ptr< DAGNode > param)
Create a floating-point negation node.
Parameters
param Parameter
Returns
Floating-point negation node (fp.neg(param))
Definition at line 2770 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_NEG.
Referenced by parseOper().
mkFpRem()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpRem (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a floating-point remainder node.
Note
IEEE-754 remainder operation
Parameters
l Left parameter
r Right parameter
Returns
Floating-point remainder node (fp.rem(l, r))
Definition at line 2781 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_REM.
Referenced by parseOper().
mkFpRoundToIntegral() [1/2]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpRoundToIntegral (std::shared_ptr< DAGNode > param)
Definition at line 2881 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_ROUND_TO_INTEGRAL.
mkFpRoundToIntegral() [2/2]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpRoundToIntegral (std::shared_ptr< DAGNode > rm, std::shared_ptr< DAGNode > param)
Create a floating-point round to integral node.
Parameters
rm Rounding mode
param Operand
Returns
Floating-point round to integral node (fp.roundToIntegral(param))
Definition at line 2865 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_ROUND_TO_INTEGRAL.
Referenced by parseOper().
mkFPSort()
std::shared_ptr< Sort > stabilizer::parser::Parser::mkFPSort (const size_t & e, const size_t & s)
Create a floating-point sort.
Parameters
e Exponent size
s Significand size
Returns
Floating-point sort
Definition at line 503 of file op_parser.cpp.
References sort_manager.
mkFpSqrt() [1/2]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpSqrt (std::shared_ptr< DAGNode > param)
Definition at line 2853 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_SQRT.
mkFpSqrt() [2/2]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpSqrt (std::shared_ptr< DAGNode > rm, std::shared_ptr< DAGNode > param)
Create a floating-point square root node.
Note
Returns NaN for negative values
Parameters
rm Rounding mode
param Operand
Returns
Floating-point square root node (fp.sqrt(param))
Definition at line 2838 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_SQRT.
Referenced by parseOper().
mkFpSub()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpSub (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a floating-point subtraction node.
Parameters
params Parameters
Returns
Floating-point subtraction node (fp.sub(l, r, ...))
Definition at line 2631 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_FP_SUB.
Referenced by parseOper().
mkFpToReal()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpToReal (std::shared_ptr< DAGNode > param)
Create a floating-point to real conversion node.
Note
NaN and infinity cannot be converted to real
Parameters
param Floating-point value
Returns
Floating-point to real conversion node (fp.to_real(param))
Definition at line 3028 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isFpParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_FP_TO_REAL, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkFpToSbv()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpToSbv (std::shared_ptr< DAGNode > rm, std::shared_ptr< DAGNode > param, std::shared_ptr< DAGNode > size)
Create a floating-point to signed bitvector conversion node.
Note
Rounds toward zero, returns max/min representable value if out of range
Parameters
param Floating-point value
size Size of resulting bitvector
Returns
Floating-point to signed bitvector conversion node (fp.to_sbv(param, size))
Definition at line 3008 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::FloatingPointUtils::fpToSbv(), stabilizer::parser::isFpParam(), stabilizer::parser::isIntParam(), line_number, mkConstBv(), mkOper(), mkUnknown(), stabilizer::parser::NT_FP_TO_SBV, sort_manager, and toInt().
Referenced by parseOper().
mkFpToUbv()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFpToUbv (std::shared_ptr< DAGNode > rm, std::shared_ptr< DAGNode > param, std::shared_ptr< DAGNode > size)
Create a floating-point to unsigned bitvector conversion node.
Note
Rounds toward zero, returns max representable value if out of range
Parameters
param Floating-point value
size Size of resulting bitvector
Returns
Floating-point to unsigned bitvector conversion node (fp.to_ubv(param, size))
Definition at line 2988 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::FloatingPointUtils::fpToUbv(), stabilizer::parser::isFpParam(), stabilizer::parser::isIntParam(), line_number, mkConstBv(), mkOper(), mkUnknown(), stabilizer::parser::NT_FP_TO_UBV, sort_manager, and toInt().
Referenced by parseOper().
mkFuncDec()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFuncDec (const std::string & name, const std::vector< std::shared_ptr< Sort >> & params, std::shared_ptr< Sort > out_sort)
Create a function declaration.
Parameters
name Function name
params Parameters
out_sort Output sort
Returns
Function declaration node
Definition at line 346 of file op_parser.cpp.
References fun_dup_count_map, fun_key_map, node_manager, stabilizer::parser::NT_FUNC_DEC, stabilizer::parser::NT_FUNC_PARAM, and stabilizer::parser::NodeManager::NULL_NODE.
Referenced by parseCommand().
mkFuncDef()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFuncDef (const std::string & name, const std::vector< std::shared_ptr< DAGNode >> & params, std::shared_ptr< Sort > out_sort, std::shared_ptr< DAGNode > body)
Create a function definition.
Parameters
name Function name
params Parameters
out_sort Output sort
body Body
Returns
Function definition node
Definition at line 397 of file op_parser.cpp.
References condAssert, err_all(), stabilizer::parser::ERR_MUL_DEF, fun_key_map, line_number, mkUnknown(), node_manager, stabilizer::parser::NT_FUNC_DEC, and stabilizer::parser::NT_FUNC_DEF.
Referenced by parseCommand().
mkFuncRec()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFuncRec (const std::string & name, const std::vector< std::shared_ptr< DAGNode >> & params, std::shared_ptr< Sort > out_sort, std::shared_ptr< DAGNode > body)
Create a recursive function definition.
Parameters
name Function name
params Parameters
out_sort Output sort
body Body
Returns
Recursive function definition node
Definition at line 438 of file op_parser.cpp.
References condAssert, err_all(), stabilizer::parser::ERR_MUL_DEF, fun_key_map, line_number, mkUnknown(), node_manager, stabilizer::parser::NT_FUNC_DEC, and stabilizer::parser::NT_FUNC_REC.
Referenced by parseCommand().
mkFunParamVar()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkFunParamVar (std::shared_ptr< Sort > sort, const std::string & name)
Create a function parameter variable.
Parameters
sort Sort
name Variable name
Returns
Function parameter variable node
Definition at line 868 of file op_parser.cpp.
References node_manager, and stabilizer::parser::NT_FUNC_PARAM.
Referenced by parseCommand().
mkGcd()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkGcd (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a gcd node.
Note
assert(l != 0 || r != 0)
Parameters
l Left parameter
r Right parameter
Returns
Gcd node (gcd(l, r))
Definition at line 1893 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_GCD.
Referenced by parseOper().
mkGe()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkGe (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a ge node.
Parameters
params Parameters
Returns
Ge node (l >= r >= ... >= s)
Definition at line 1697 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_PARAM_MIS, line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_GE.
Referenced by parseExpr(), and parseOper().
mkGt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkGt (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a gt node.
Parameters
params Parameters
Returns
Gt node (l > r > ... > s)
Definition at line 1707 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_PARAM_MIS, line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_GT.
Referenced by parseExpr(), and parseOper().
mkIand()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkIand (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an iand node.
Parameters
params Parameters
Returns
Iand node (l & r & ...)
Definition at line 1274 of file op_parser.cpp.
References stabilizer::parser::canExempt(), condAssert, err_all(), stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::SortManager::INT_SORT, line_number, mkConstInt(), mkOper(), mkUnknown(), stabilizer::parser::NT_IAND, options, stabilizer::parser::SortManager::REAL_SORT, and toInt().
Referenced by parseOper().
mkImplies()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkImplies (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an implies node.
Parameters
params Parameters
Returns
Implies node (l -> r -> ...)
Definition at line 1022 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_PARAM_MIS, line_number, mkOper(), mkTrue(), mkUnknown(), and stabilizer::parser::NT_IMPLIES.
Referenced by parseExpr(), and parseOper().
mkIndexofReg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkIndexofReg (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string index-of-regex node.
Creates a node that returns the index of the first match of a regex pattern.
Parameters
l String
r Regex pattern
Returns
String index-of-regex node (str.indexof(l, r))
Definition at line 3968 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isRegParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_INDEXOF_REG.
mkInfinity()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkInfinity (std::shared_ptr< Sort > sort)
Create a infinity node.
Returns
Infinity node (infinity)
Definition at line 1790 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::NodeManager::INT_INF_NODE, stabilizer::parser::SortManager::INT_SORT, line_number, mkUnknown(), stabilizer::parser::NodeManager::REAL_INF_NODE, stabilizer::parser::SortManager::REAL_SORT, stabilizer::parser::NodeManager::STR_INF_NODE, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseConstFunc().
mkInternalOper()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkInternalOper (const std::shared_ptr< Sort > & sort, const NODE_KIND & t, const std::vector< std::shared_ptr< DAGNode >> & p) private
Definition at line 294 of file op_parser.cpp.
References isCommutative(), stabilizer::parser::kindToString(), node_manager, stabilizer::parser::NT_EXISTS, stabilizer::parser::NT_FORALL, stabilizer::parser::NT_FP_ADD, stabilizer::parser::NT_FP_MUL, rewrite_oper(), and sortParams().
Referenced by mkOper().
mkIntSort()
std::shared_ptr< Sort > stabilizer::parser::Parser::mkIntSort ()
Create an integer sort.
Returns
Integer sort
Definition at line 491 of file op_parser.cpp.
References stabilizer::parser::SortManager::INT_SORT.
mkIntToBv()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkIntToBv (std::shared_ptr< DAGNode > param, std::shared_ptr< DAGNode > width)
Create an integer to bitvector conversion node.
Note
assert(width > 0 && param >= -2^(width-1) && param < 2^(width-1))
Parameters
param Parameter (integer number)
width Width of the resulting bitvector
Returns
Integer to bitvector conversion node (to_bv(param, width))
Definition at line 2572 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_INT_TO_BV, sort_manager, and toInt().
Referenced by parseOper().
mkIsDivisible()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkIsDivisible (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a is_divisible node.
Parameters
l Left parameter
r Right parameter
Returns
Is_divisible node (is_divisible(l, r), l divides r)
Definition at line 1749 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_IS_DIVISIBLE.
Referenced by parseOper().
mkIsEven()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkIsEven (std::shared_ptr< DAGNode > param)
Create a is_even node.
Parameters
param Parameter
Returns
Is_even node (is_even(param))
Definition at line 1770 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_IS_EVEN.
Referenced by parseOper().
mkIsInt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkIsInt (std::shared_ptr< DAGNode > param)
Create a is_int node.
Parameters
param Parameter
Returns
Is_int node (is_int(param))
Definition at line 1739 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRealParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_IS_INT.
Referenced by parseOper().
mkIsOdd()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkIsOdd (std::shared_ptr< DAGNode > param)
Create a is_odd node.
Parameters
param Parameter
Returns
Is_odd node (is_odd(param))
Definition at line 1780 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_IS_ODD.
Referenced by parseOper().
mkIsPrime()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkIsPrime (std::shared_ptr< DAGNode > param)
Create a is_prime node.
Parameters
param Parameter
Returns
Is_prime node (is_prime(param))
Definition at line 1760 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_IS_PRIME.
Referenced by parseOper().
mkIte() [1/2]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkIte (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an ite node.
Note
It only accepts 3 parameters.
Parameters
params Parameters
Returns
Ite node (cond ? l : r)
Definition at line 1109 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, line_number, mkIte(), and mkUnknown().
mkIte() [2/2]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkIte (std::shared_ptr< DAGNode > cond, std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an ite node.
Parameters
cond Condition
l Left parameter
r Right parameter
Returns
Ite node (cond ? l : r)
Definition at line 1097 of file op_parser.cpp.
References mkOper(), and stabilizer::parser::NT_ITE.
Referenced by mkIte(), parseExpr(), and parseOper().
mkLb()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkLb (std::shared_ptr< DAGNode > param)
Create an lb/log2 node.
Note
assert(param > 0)
Parameters
param Parameter
Returns
Lb node (lb(param))
Definition at line 1502 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_LB, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkLcm()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkLcm (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a lcm node.
Note
assert(l != 0 && r != 0)
Parameters
l Left parameter
r Right parameter
Returns
Lcm node (lcm(l, r))
Definition at line 1904 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_LCM.
Referenced by parseOper().
mkLe()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkLe (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a le node.
Parameters
params Parameters
Returns
Le node (l <= r <= ... <= s)
Definition at line 1681 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_PARAM_MIS, line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_LE.
Referenced by parseExpr(), and parseOper().
mkLet()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::mkLet (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a let node.
Parameters
params List of (key, value) pairs
Returns
Let node (let((key1, val1), (key2, val2), ...))
mkLetBindVar()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkLetBindVar (const std::string & name, const std::shared_ptr< DAGNode > & expr) private
Definition at line 631 of file op_parser.cpp.
References node_manager, stabilizer::parser::NT_LET_BIND_VAR, and preserving_let_key_map.
Referenced by parsePreservingLet(), and rebuildLetBindings().
mkLetBindVarList()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkLetBindVarList (const std::vector< std::shared_ptr< DAGNode >> & bind_vars) private
Definition at line 648 of file op_parser.cpp.
References node_manager, and stabilizer::parser::NT_LET_BIND_VAR_LIST.
Referenced by parsePreservingLet(), and rebuildLetBindings().
mkLetChain()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkLetChain (const std::vector< std::shared_ptr< DAGNode >> & bind_var_lists, const std::shared_ptr< DAGNode > & body) private
Definition at line 658 of file op_parser.cpp.
References stabilizer::parser::ERR_UNKWN_SYM, mkErr(), node_manager, and stabilizer::parser::NT_LET_CHAIN.
Referenced by parsePreservingLet(), and rebuildLetBindings().
mkLg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkLg (std::shared_ptr< DAGNode > param)
Create an lg/log10 node.
Note
assert(param > 0)
Parameters
param Parameter
Returns
Lg node (lg(param))
Definition at line 1508 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_LG, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkLn()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkLn (std::shared_ptr< DAGNode > param)
Create an ln node.
Note
assert(param > 0)
Parameters
param Parameter
Returns
Ln node (ln(param))
Definition at line 1496 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_LN, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkLog()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkLog (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an log node.
Note
r is the base, l is the argument
assert(r > 0 && r != 1 && l > 0)
Parameters
l Left parameter
r Right parameter
Returns
Log node (log_r(l))
Definition at line 1514 of file op_parser.cpp.
References stabilizer::parser::canExempt(), err_all(), stabilizer::parser::ERR_TYPE_MIS, line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_LOG, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkLt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkLt (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a lt node.
Parameters
params Parameters
Returns
Lt node (l < r < ... < s)
Definition at line 1689 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_PARAM_MIS, line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_LT.
Referenced by parseExpr(), and parseOper().
mkMax()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkMax (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a max node.
Parameters
params List of parameters
Returns
Max node (max(p1, p2, ...))
Definition at line 3980 of file op_parser.cpp.
References stabilizer::parser::canExempt(), err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, getSort(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_MAX.
mkMin()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkMin (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a min node.
Parameters
params List of parameters
Returns
Min node (min(p1, p2, ...))
Definition at line 4012 of file op_parser.cpp.
References stabilizer::parser::canExempt(), err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, getSort(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_MIN.
mkMod()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkMod (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an mod node.
Parameters
l Left parameter
r Right parameter
Returns
Mod node (l % r)
Definition at line 1423 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_MOD.
Referenced by parseOper().
mkMul()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkMul (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an mul node.
Parameters
params Parameters
Returns
Mul node (l * r * ...)
Definition at line 1190 of file op_parser.cpp.
References stabilizer::parser::canExempt(), condAssert, err_all(), stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::SortManager::INT_SORT, isOne(), isZero(), line_number, mkConstInt(), mkConstReal(), mkOper(), mkUnknown(), stabilizer::parser::NT_MUL, options, stabilizer::parser::SortManager::REAL_SORT, toInt(), and toReal().
Referenced by parseExpr(), and parseOper().
mkNaN()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkNaN (std::shared_ptr< Sort > sort = nullptr)
Create a NaN node.
Parameters
sort Optional sort (for FP types, will include eb sb in name)
Returns
NaN node (nan, i.e., Not a Number)
Definition at line 1857 of file op_parser.cpp.
References stabilizer::parser::NodeManager::NAN_NODE, node_manager, and stabilizer::parser::NT_NAN.
Referenced by parseConstFunc(), and parseExpr().
mkNatSort()
std::shared_ptr< Sort > stabilizer::parser::Parser::mkNatSort ()
Create a natural sort.
Returns
Natural sort
Definition at line 499 of file op_parser.cpp.
References stabilizer::parser::SortManager::NAT_SORT.
mkNatToBv()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkNatToBv (std::shared_ptr< DAGNode > param, std::shared_ptr< DAGNode > width)
Create a natural number to bitvector conversion node.
Note
assert(param >= 0 && width > 0 && param < 2^width)
Parameters
param Parameter (natural number)
width Width of the resulting bitvector
Returns
Natural number to bitvector conversion node (to_bv(param, width))
Definition at line 2533 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_NAT_TO_BV, sort_manager, and toInt().
Referenced by parseOper().
mkNeg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkNeg (std::shared_ptr< DAGNode > param)
Create an neg node.
Parameters
param Parameter
Returns
Neg node (-param)
Definition at line 1388 of file op_parser.cpp.
References mkOper(), and stabilizer::parser::NT_NEG.
Referenced by mkSub(), and parseOper().
mkNegEpsilon()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkNegEpsilon ()
Create a negative epsilon node.
Returns
Negative epsilon node (-epsilon)
Definition at line 1879 of file op_parser.cpp.
References stabilizer::parser::NodeManager::NEG_EPSILON_NODE.
Referenced by parseConstFunc().
mkNegInfinity()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkNegInfinity (std::shared_ptr< Sort > sort = nullptr)
Create a negative infinity node.
Parameters
sort Optional sort (for FP types, will include eb sb in name)
Returns
Negative infinity node (-infinity)
Definition at line 1831 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::NodeManager::INT_NEG_INF_NODE, stabilizer::parser::SortManager::INT_SORT, line_number, mkUnknown(), node_manager, stabilizer::parser::NT_NEG_INFINITY, stabilizer::parser::NodeManager::REAL_NEG_INF_NODE, stabilizer::parser::SortManager::REAL_SORT, stabilizer::parser::NodeManager::STR_NEG_INF_NODE, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseConstFunc(), and parseExpr().
mkNode()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::mkNode (std::shared_ptr< Sort > sort, NODE_KIND t, std::string name, std::vector< std::shared_ptr< DAGNode >> params) inline
Definition at line 771 of file parser.h.
References isCommutative(), node_manager, stabilizer::parser::NT_EXISTS, stabilizer::parser::NT_FORALL, stabilizer::parser::NT_FP_ADD, stabilizer::parser::NT_FP_MUL, rewrite_oper(), and sortParams().
mkNoPattern()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkNoPattern (const std::shared_ptr< Sort > & sort, const std::string & name, std::shared_ptr< DAGNode > param)
Definition at line 2270 of file base_parser.cpp.
References node_manager, and stabilizer::parser::NT_NO_PATTERN.
Referenced by parseExpr().
mkNot()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkNot (std::shared_ptr< DAGNode > param)
Create a not node.
Parameters
param Parameter
Returns
Not node (not param)
Definition at line 916 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::isBoolParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_NOT.
Referenced by parseExpr(), and parseOper().
mkOper() [1/4]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkOper (const std::shared_ptr< Sort > & sort, const NODE_KIND & t, const std::vector< std::shared_ptr< DAGNode >> & p)
Create an operation.
Parameters
sort Sort
t Operation kind
p Parameters
Returns
Operation Node
Definition at line 233 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, line_number, mkInternalOper(), mkUnknown(), stabilizer::parser::NT_BV_SGE, stabilizer::parser::NT_BV_SGT, stabilizer::parser::NT_BV_SLE, stabilizer::parser::NT_BV_SLT, stabilizer::parser::NT_BV_UGE, stabilizer::parser::NT_BV_UGT, stabilizer::parser::NT_BV_ULE, stabilizer::parser::NT_BV_ULT, stabilizer::parser::NT_EXISTS, stabilizer::parser::NT_FORALL, stabilizer::parser::NT_FP_GE, stabilizer::parser::NT_FP_GT, stabilizer::parser::NT_FP_LE, stabilizer::parser::NT_FP_LT, stabilizer::parser::NT_GE, stabilizer::parser::NT_GT, stabilizer::parser::NT_LE, stabilizer::parser::NT_LT, stabilizer::parser::NT_STR_GE, stabilizer::parser::NT_STR_GT, stabilizer::parser::NT_STR_LE, and stabilizer::parser::NT_STR_LT.
mkOper() [2/4]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkOper (const std::shared_ptr< Sort > & sort, const NODE_KIND & t, std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > m, std::shared_ptr< DAGNode > r)
Create an operation.
Parameters
sort Sort
t Operation kind
l Left parameter
m Middle parameter
r Right parameter
Returns
Operation Node
Definition at line 221 of file op_parser.cpp.
References mkOper().
mkOper() [3/4]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkOper (const std::shared_ptr< Sort > & sort, const NODE_KIND & t, std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an operation.
Parameters
sort Sort
t Operation kind
l Left parameter
r Right parameter
Returns
Operation Node
Definition at line 212 of file op_parser.cpp.
References mkOper().
mkOper() [4/4]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkOper (const std::shared_ptr< Sort > & sort, const NODE_KIND & t, std::shared_ptr< DAGNode > p)
Create an operation.
Parameters
sort Sort
t Operation kind
p Parameters
Returns
Operation Node
Definition at line 205 of file op_parser.cpp.
Referenced by applyFunPostOrder(), mkAbs(), mkAcos(), mkAcosh(), mkAcot(), mkAcoth(), mkAcsc(), mkAcsch(), mkAdd(), mkAnd(), mkAsec(), mkAsech(), mkAsin(), mkAsinh(), mkAtan(), mkAtan2(), mkAtanh(), mkBvAdd(), mkBvAnd(), mkBvAshr(), mkBvComp(), mkBvConcat(), mkBvExtract(), mkBvLshr(), mkBvMul(), mkBvNand(), mkBvNeg(), mkBvNor(), mkBvNot(), mkBvOr(), mkBvRepeat(), mkBvRotateLeft(), mkBvRotateRight(), mkBvSdiv(), mkBvSge(), mkBvSgt(), mkBvShl(), mkBvSignExt(), mkBvSle(), mkBvSlt(), mkBvSmod(), mkBvSrem(), mkBvSub(), mkBvToInt(), mkBvToNat(), mkBvUdiv(), mkBvUge(), mkBvUgt(), mkBvUle(), mkBvUlt(), mkBvUmod(), mkBvUrem(), mkBvXnor(), mkBvXor(), mkBvZeroExt(), mkCeil(), mkCos(), mkCosh(), mkCot(), mkCoth(), mkCsc(), mkCsch(), mkDistinct(), mkDivInt(), mkDivReal(), mkEq(), mkExists(), mkExp(), mkFact(), mkFloor(), mkForall(), mkFpAbs(), mkFpAdd(), mkFpDiv(), mkFpEq(), mkFpFma(), mkFpGe(), mkFpGt(), mkFpIsInf(), mkFpIsNaN(), mkFpIsNeg(), mkFpIsNormal(), mkFpIsPos(), mkFpIsSubnormal(), mkFpIsZero(), mkFpLe(), mkFpLt(), mkFpMax(), mkFpMin(), mkFpMul(), mkFpNeg(), mkFpRem(), mkFpRoundToIntegral(), mkFpSqrt(), mkFpSub(), mkFpToReal(), mkFpToSbv(), mkFpToUbv(), mkGcd(), mkGe(), mkGt(), mkIand(), mkImplies(), mkIndexofReg(), mkIntToBv(), mkIsDivisible(), mkIsEven(), mkIsInt(), mkIsOdd(), mkIsPrime(), mkIte(), mkLb(), mkLcm(), mkLe(), mkLg(), mkLn(), mkLog(), mkLt(), mkMax(), mkMin(), mkMod(), mkMul(), mkNatToBv(), mkNeg(), mkNot(), mkOper(), mkOr(), mkPow(), mkPow2(), mkRegComplement(), mkRegConcat(), mkRegDiff(), mkRegInter(), mkRegLoop(), mkRegOpt(), mkRegPlus(), mkRegRange(), mkRegRepeat(), mkRegStar(), mkRegUnion(), mkReplaceReg(), mkReplaceRegAll(), mkRound(), mkSafeSqrt(), mkSbvToInt(), mkSec(), mkSech(), mkSelect(), mkSin(), mkSinh(), mkSqrt(), mkStore(), mkStrCharat(), mkStrConcat(), mkStrContains(), mkStrFromCode(), mkStrFromInt(), mkStrGe(), mkStrGt(), mkStrIndexof(), mkStrIndexofReg(), mkStrInReg(), mkStrIsDigit(), mkStrLe(), mkStrLen(), mkStrLt(), mkStrNumSplits(), mkStrNumSplitsRe(), mkStrPrefixof(), mkStrReplace(), mkStrReplaceAll(), mkStrReplaceReg(), mkStrReplaceRegAll(), mkStrRev(), mkStrSplit(), mkStrSplitAt(), mkStrSplitAtRe(), mkStrSplitRest(), mkStrSplitRestRe(), mkStrSubstr(), mkStrSuffixof(), mkStrToCode(), mkStrToInt(), mkStrToLower(), mkStrToReg(), mkStrToUpper(), mkStrUpdate(), mkSub(), mkTan(), mkTanh(), mkToFp(), mkToFpUnsigned(), mkToInt(), mkToReal(), mkUbvToInt(), mkXor(), and substitute().
mkOr()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkOr (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an or node.
Parameters
params Parameters
Returns
Or node (l or m or r or ...)
Definition at line 975 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_type_mis(), stabilizer::parser::isBoolParam(), line_number, mkFalse(), mkOper(), mkTrue(), mkUnknown(), and stabilizer::parser::NT_OR.
Referenced by parseExpr(), and parseOper().
mkPattern()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkPattern (const std::shared_ptr< Sort > & sort, const std::string & name, const std::vector< std::shared_ptr< DAGNode >> & params)
Definition at line 2266 of file base_parser.cpp.
References node_manager, and stabilizer::parser::NT_PATTERN.
Referenced by parseExpr().
mkPi()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkPi ()
Create a pi node.
Returns
Pi node (pi, i.e., the ratio of the circumference of a circle to its diameter)
Definition at line 1788 of file op_parser.cpp.
References stabilizer::parser::NodeManager::PI_NODE.
Referenced by parseConstFunc().
mkPlaceholderVar()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkPlaceholderVar (const std::string & name)
Definition at line 799 of file op_parser.cpp.
References condAssert, node_manager, stabilizer::parser::NT_PLACEHOLDER_VAR, placeholder_var_names, placeholder_var_sort, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseConstFunc().
mkPosEpsilon()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkPosEpsilon ()
Create a positive epsilon node.
Returns
Positive epsilon node (+epsilon)
Definition at line 1876 of file op_parser.cpp.
References stabilizer::parser::NodeManager::POS_EPSILON_NODE.
Referenced by parseConstFunc().
mkPosInfinity()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkPosInfinity (std::shared_ptr< Sort > sort = nullptr)
Create a positive infinity node.
Parameters
sort Optional sort (for FP types, will include eb sb in name)
Returns
Positive infinity node (+infinity)
Definition at line 1805 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::NodeManager::INT_POS_INF_NODE, stabilizer::parser::SortManager::INT_SORT, line_number, mkUnknown(), node_manager, stabilizer::parser::NT_POS_INFINITY, stabilizer::parser::NodeManager::REAL_POS_INF_NODE, stabilizer::parser::SortManager::REAL_SORT, stabilizer::parser::NodeManager::STR_POS_INF_NODE, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseConstFunc(), and parseExpr().
mkPow()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkPow (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an pow node.
Parameters
l Left parameter
r Right parameter
Returns
Pow node (l^r)
Definition at line 1322 of file op_parser.cpp.
References mkOper(), and stabilizer::parser::NT_POW.
Referenced by parseOper().
mkPow2()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkPow2 (std::shared_ptr< DAGNode > param)
Create an pow2 node.
Parameters
param Parameter
Returns
Pow2 node (2^param)
Definition at line 1319 of file op_parser.cpp.
References mkOper(), and stabilizer::parser::NT_POW2.
Referenced by parseOper().
mkQuantVar()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkQuantVar (const std::string & name, std::shared_ptr< Sort > sort)
Create a quantifier variable node.
Parameters
name Variable name
sort Variable sort
Returns
Quantifier variable node (var1, sort1)
Definition at line 2298 of file base_parser.cpp.
References node_manager, stabilizer::parser::NT_QUANT_VAR, num_quant_vars, and quant_var_map.
Referenced by parseQuant().
mkRealSort()
std::shared_ptr< Sort > stabilizer::parser::Parser::mkRealSort ()
Create a real sort.
Returns
Real sort
Definition at line 492 of file op_parser.cpp.
References stabilizer::parser::SortManager::REAL_SORT.
mkRegAll()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegAll ()
Create a regex all node.
Creates a regex node that matches any string.
Returns
Regex all node (re.all)
Definition at line 3747 of file op_parser.cpp.
References mkConstReg().
Referenced by parseConstFunc().
mkRegAllChar()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegAllChar ()
Create a regex allchar node.
Creates a regex node that matches any single character.
Returns
Regex allchar node (re.allchar)
Definition at line 3748 of file op_parser.cpp.
References mkConstReg().
Referenced by parseConstFunc().
mkRegComplement()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegComplement (std::shared_ptr< DAGNode > param)
Create a regex complement node.
Creates a regex complement node that matches strings not matching the pattern.
Parameters
param Regex pattern
Returns
Regex complement node (re.complement(param), i.e., ~param)
Definition at line 3926 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRegParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_REG_COMPLEMENT, and stabilizer::parser::SortManager::REG_SORT.
Referenced by parseOper().
mkRegConcat()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegConcat (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a regex concatenation node.
Creates a regex concatenation node that matches the concatenation of patterns.
Parameters
params Regex patterns
Returns
Regex concatenation node (re.++(l, r, ...))
Definition at line 3756 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRegParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_REG_CONCAT, and stabilizer::parser::SortManager::REG_SORT.
Referenced by parseOper().
mkRegDiff()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegDiff (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a regex difference node.
Creates a regex difference node that matches strings matching the first pattern but not subsequent patterns.
Parameters
params Regex patterns
Returns
Regex difference node (re.diff(l, r, ...))
Definition at line 3834 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRegParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_REG_DIFF, and stabilizer::parser::SortManager::REG_SORT.
Referenced by parseOper().
mkRegInter()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegInter (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a regex intersection node.
Creates a regex intersection node that matches strings that match all patterns.
Parameters
params Regex patterns
Returns
Regex intersection node (re.inter(l, r, ...))
Definition at line 3808 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRegParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_REG_INTER, and stabilizer::parser::SortManager::REG_SORT.
Referenced by parseOper().
mkRegLoop()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegLoop (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
Create a regex loop node.
Creates a regex loop node that matches between r and s occurrences of the pattern.
Parameters
l Regex pattern
r Minimum number of repetitions
s Maximum number of repetitions
Returns
Regex loop node (re.loop(l, r, s), i.e., l{r,s})
Definition at line 3910 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), stabilizer::parser::isRegParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_REG_LOOP, and stabilizer::parser::SortManager::REG_SORT.
Referenced by parseOper().
mkRegNone()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegNone ()
Create a regex none node.
Creates a regex node that matches nothing.
Returns
Regex none node (re.none)
Definition at line 3746 of file op_parser.cpp.
References mkConstReg().
Referenced by parseConstFunc().
mkRegOpt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegOpt (std::shared_ptr< DAGNode > param)
Create a regex option node.
Creates a regex option node that matches zero or one occurrence of the pattern.
Parameters
param Regex pattern
Returns
Regex option node (re.?(param)/re.opt(param), i.e., param?)
Definition at line 3873 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRegParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_REG_OPT, and stabilizer::parser::SortManager::REG_SORT.
Referenced by parseOper().
mkRegPlus()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegPlus (std::shared_ptr< DAGNode > param)
Create a regex plus node.
Creates a regex plus node that matches one or more occurrences of the pattern.
Parameters
param Regex pattern
Returns
Regex plus node (re.+(param), i.e., param+)
Definition at line 3862 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRegParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_REG_PLUS, and stabilizer::parser::SortManager::REG_SORT.
Referenced by parseOper().
mkRegRange()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegRange (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a regex range node.
Creates a regex range node that matches characters in the specified range.
Parameters
l Lower bound (inclusive)
r Upper bound (inclusive)
Returns
Regex range node (re.range(l, r), i.e., l..r)
Definition at line 3884 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_REG_RANGE, and stabilizer::parser::SortManager::REG_SORT.
Referenced by parseOper().
mkRegRepeat()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegRepeat (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a regex repeat node.
Creates a regex repeat node that matches exactly r occurrences of the pattern.
Parameters
l Regex pattern
r Number of repetitions
Returns
Regex repeat node (re.^(n, l), i.e., l^n)
Definition at line 3896 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), stabilizer::parser::isRegParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_REG_REPEAT, and stabilizer::parser::SortManager::REG_SORT.
Referenced by parseOper().
mkRegSort()
std::shared_ptr< Sort > stabilizer::parser::Parser::mkRegSort ()
Create a regular expression sort.
Returns
Regular expression sort
Definition at line 495 of file op_parser.cpp.
References stabilizer::parser::SortManager::REG_SORT.
mkRegStar()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegStar (std::shared_ptr< DAGNode > param)
Create a regex star node.
Creates a regex star node that matches zero or more occurrences of the pattern.
Parameters
param Regex pattern
Returns
Regex star node (re.*(param), i.e., param*)
Definition at line 3851 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRegParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_REG_STAR, and stabilizer::parser::SortManager::REG_SORT.
Referenced by parseOper().
mkRegUnion()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRegUnion (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a regex union node.
Creates a regex union node that matches any of the patterns.
Parameters
params Regex patterns
Returns
Regex union node (re.union(l, r, ...))
Definition at line 3782 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRegParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_REG_UNION, and stabilizer::parser::SortManager::REG_SORT.
Referenced by parseOper().
mkReplaceReg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkReplaceReg (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string replace-regex node.
Creates a node that replaces the first match of a regex pattern.
Parameters
l String
r Regex pattern
v Replacement string
Returns
String replace-regex node (str.replace_re(l, r, v))
Definition at line 3938 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRegParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_REPLACE_REG, and stabilizer::parser::SortManager::STR_SORT.
mkReplaceRegAll()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkReplaceRegAll (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string replace-all-regex node.
Creates a node that replaces all matches of a regex pattern.
Parameters
l String
r Regex pattern
v Replacement string
Returns
String replace-all-regex node (str.replace_all_re(l, r, v))
Definition at line 3953 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRegParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_REPLACE_REG_ALL, and stabilizer::parser::SortManager::STR_SORT.
mkRootObj()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRootObj (std::shared_ptr< DAGNode > expr, int index)
Definition at line 4296 of file op_parser.cpp.
References mkConstInt(), node_manager, stabilizer::parser::NT_ROOT_OBJ, stabilizer::parser::SortManager::REAL_SORT, and toString().
Referenced by parseExpr(), and parseOper().
mkRootOfWithInterval()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRootOfWithInterval (const std::vector< std::shared_ptr< DAGNode >> & coeffs, std::shared_ptr< DAGNode > lower_bound, std::shared_ptr< DAGNode > upper_bound)
Definition at line 4313 of file op_parser.cpp.
References node_manager, stabilizer::parser::NT_ROOT_OF_WITH_INTERVAL, stabilizer::parser::SortManager::REAL_SORT, and toString().
Referenced by parseExpr().
mkRound()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRound (std::shared_ptr< DAGNode > param)
Create an round node.
Parameters
param Parameter
Returns
Round node (round(param))
Definition at line 1483 of file op_parser.cpp.
References stabilizer::parser::SortManager::INT_SORT, mkOper(), and stabilizer::parser::NT_ROUND.
Referenced by parseOper().
mkRoundingMode()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkRoundingMode (const std::string & mode)
Create a rounding mode constant.
Parameters
mode Rounding mode string (RNE, RNA, RTP, RTN, RTZ)
Returns
Rounding mode constant node
Definition at line 765 of file op_parser.cpp.
References node_manager, stabilizer::parser::NT_CONST, and stabilizer::parser::SortManager::ROUNDING_MODE_SORT.
Referenced by parseConstFunc().
mkRoundingModeSort()
std::shared_ptr< Sort > stabilizer::parser::Parser::mkRoundingModeSort ()
Create a rounding mode sort.
Returns
Rounding mode sort
Definition at line 496 of file op_parser.cpp.
References stabilizer::parser::SortManager::ROUNDING_MODE_SORT.
mkSafeSqrt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkSafeSqrt (std::shared_ptr< DAGNode > param)
Create an safeSqrt node.
Note
if param < 0, return 0
Parameters
param Parameter
Returns
Safesqrt node (safeSqrt(param))
Definition at line 1457 of file op_parser.cpp.
References err_all(), stabilizer::parser::isIntParam(), stabilizer::parser::isRealParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_SAFESQRT.
Referenced by parseOper().
mkSbvToInt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkSbvToInt (std::shared_ptr< DAGNode > param)
Definition at line 2562 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_SBV_TO_INT.
mkSec()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkSec (std::shared_ptr< DAGNode > param)
Create an sec node.
Parameters
param Parameter
Returns
Sec node (sec(param))
Definition at line 1543 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_SEC, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkSech()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkSech (std::shared_ptr< DAGNode > param)
Create a sech node.
Parameters
param Parameter
Returns
Sech node (sech(param))
Definition at line 1621 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_SECH, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkSelect()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkSelect (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create an array select node.
Parameters
l Array
r Index
Returns
Array select node (l[r])
Definition at line 3283 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isArrayParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_SELECT.
Referenced by parseOper().
mkSin()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkSin (std::shared_ptr< DAGNode > param)
Create an sin node.
Parameters
param Parameter
Returns
Sin node (sin(param))
Definition at line 1531 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_SIN, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkSinh()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkSinh (std::shared_ptr< DAGNode > param)
Create a sinh node.
Parameters
param Parameter
Returns
Sinh node (sinh(param))
Definition at line 1603 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_SINH, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkSortDec()
std::shared_ptr< Sort > stabilizer::parser::Parser::mkSortDec (const std::string & name, const size_t & arity)
Create a sort declaration.
Parameters
name Sort name
arity Arity
Returns
Sort declaration node
Definition at line 480 of file op_parser.cpp.
References sort_manager.
Referenced by parseCommand().
mkSortDef()
std::shared_ptr< Sort > stabilizer::parser::Parser::mkSortDef (const std::string & name, const std::vector< std::shared_ptr< Sort >> & params, std::shared_ptr< Sort > out_sort)
Create a sort definition.
Parameters
name Sort name
params Parameters
out_sort Output sort
Returns
Sort definition node
Definition at line 486 of file op_parser.cpp.
References sort_manager.
Referenced by parseCommand().
mkSqrt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkSqrt (std::shared_ptr< DAGNode > param)
Create an sqrt node.
Note
assert(param >= 0)
Parameters
param Parameter
Returns
Sqrt node (sqrt(param))
Definition at line 1446 of file op_parser.cpp.
References err_all(), stabilizer::parser::isIntParam(), stabilizer::parser::isRealParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_SQRT.
Referenced by parseOper().
mkStore()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStore (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create an array store node.
Note
Returns a new array, the original array is not modified
Parameters
l Array
r Index
v Value
Returns
Array store node (l[r] = v)
Definition at line 3295 of file op_parser.cpp.
References mkOper(), and stabilizer::parser::NT_STORE.
Referenced by parseOper().
mkStrCharat()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrCharat (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string char-at node.
Parameters
l String
r Index
Returns
String char-at node (str.at(l, r))
Definition at line 3406 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_CHARAT, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseOper().
mkStrConcat()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrConcat (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a string concatenation node.
Parameters
params Strings to concatenate
Returns
String concatenation node (str.++(param1, param2, ...))
Definition at line 3323 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isStrParam(), line_number, mkConstStr(), mkOper(), mkUnknown(), stabilizer::parser::NT_STR_CONCAT, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseOper().
mkStrContains()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrContains (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string contains check node.
Parameters
l String
r Substring
Returns
String contains check node (str.contains(l, r))
Definition at line 3672 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_CONTAINS.
Referenced by parseOper().
mkStrFromCode()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrFromCode (std::shared_ptr< DAGNode > param)
Create a string from-code conversion node.
Creates a node that converts an ASCII code to a string.
Parameters
param ASCII code
Returns
String from-code conversion node (str.from_code(param))
Definition at line 3737 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_FROM_CODE, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseOper().
mkStrFromInt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrFromInt (std::shared_ptr< DAGNode > param)
Create a string from-integer conversion node.
Parameters
param Integer
Returns
String from-integer conversion node (str.from_int(param))
Definition at line 3693 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_FROM_INT, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseOper().
mkStrGe()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrGe (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a string greater-than-or-equal node.
Parameters
params Operand list containing two strings
Returns
String greater-than-or-equal node (str.>=(l, r))
Definition at line 3649 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, mkOper(), and stabilizer::parser::NT_STR_GE.
Referenced by parseOper().
mkStrGt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrGt (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a string greater-than node.
Parameters
params Operand list containing two strings
Returns
String greater-than node (str.>(l, r))
Definition at line 3642 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, mkOper(), and stabilizer::parser::NT_STR_GT.
Referenced by parseOper().
mkStrIndexof()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrIndexof (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
Create a string index-of node.
Parameters
l String
r Substring to find
s Start index
Returns
String index-of node (str.indexof(l, r, s))
Definition at line 3391 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isIntParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_INDEXOF.
Referenced by parseOper().
mkStrIndexofReg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrIndexofReg (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string indexof-regex node.
Parameters
l String
r Regular expression
Returns
String indexof-regex node (str.indexof_re(l, r))
Definition at line 3499 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isRegParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_INDEXOF_REG.
Referenced by parseOper().
mkStrInReg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrInReg (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string in-regex check node.
Parameters
l String
r Regular expression
Returns
String in-regex check node (str.in_re(l, r))
Definition at line 3657 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::isRegParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_IN_REG.
Referenced by parseOper().
mkStrIsDigit()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrIsDigit (std::shared_ptr< DAGNode > param)
Create a string is-digit check node.
Parameters
param String
Returns
String is-digit check node (str.is_digit(param))
Definition at line 3684 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_IS_DIGIT.
Referenced by parseOper().
mkStrLe()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrLe (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a string less-than-or-equal node.
Parameters
params Operand list containing two strings
Returns
String less-than-or-equal node (str.<=(l, r))
Definition at line 3635 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, mkOper(), and stabilizer::parser::NT_STR_LE.
Referenced by parseOper().
mkStrLen()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrLen (std::shared_ptr< DAGNode > param)
Create a string length node.
Parameters
param String
Returns
String length node (str.len(param))
Definition at line 3311 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_LEN.
Referenced by parseOper().
mkStrLt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrLt (const std::vector< std::shared_ptr< DAGNode >> & params)
Create a string less-than node.
Parameters
params Operand list containing two strings
Returns
String less-than node (str.<(l, r))
Definition at line 3624 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, mkOper(), and stabilizer::parser::NT_STR_LT.
Referenced by parseOper().
mkStrNumSplits()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrNumSplits (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Definition at line 3576 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_NUM_SPLITS.
Referenced by parseOper().
mkStrNumSplitsRe()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrNumSplitsRe (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Definition at line 3611 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isRegParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_NUM_SPLITS_RE.
Referenced by parseOper().
mkStrPrefixof()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrPrefixof (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string prefix check node.
Parameters
l Prefix
r String
Returns
String prefix check node (str.prefixof(l, r))
Definition at line 3367 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_PREFIXOF.
Referenced by parseOper().
mkStrReplace()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrReplace (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string replace node.
Parameters
l String
r Substring to replace
v Replacement string
Returns
String replace node (str.replace(l, r, v))
Definition at line 3433 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_REPLACE.
Referenced by parseOper().
mkStrReplaceAll()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrReplaceAll (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string replace-all node.
Parameters
l String
r Substring to replace
v Replacement string
Returns
String replace-all node (str.replace_all(l, r, v))
Definition at line 3448 of file op_parser.cpp.
References err_all(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_REPLACE_ALL.
Referenced by parseOper().
mkStrReplaceReg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrReplaceReg (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string replace-regex node.
Parameters
l String
r Regular expression
v Replacement string
Returns
String replace-regex node (str.replace_re(l, r, v))
Definition at line 3468 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRegParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_REPLACE_REG.
Referenced by parseOper().
mkStrReplaceRegAll()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrReplaceRegAll (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string replace-regex-all node.
Parameters
l String
r Regular expression
v Replacement string
Returns
String replace-regex-all node (str.replace_re_all(l, r, v))
Definition at line 3484 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isRegParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_REPLACE_REG_ALL.
Referenced by parseOper().
mkStrRev()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrRev (std::shared_ptr< DAGNode > param)
Create a string reverse node.
Parameters
param String
Returns
String reverse node (str.rev(param))
Definition at line 3535 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_REV, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseOper().
mkStrSort()
std::shared_ptr< Sort > stabilizer::parser::Parser::mkStrSort ()
Create a string sort.
Returns
String sort
Definition at line 494 of file op_parser.cpp.
References stabilizer::parser::SortManager::STR_SORT.
mkStrSplit()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrSplit (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string split node.
Parameters
l String
r Delimiter
Returns
String split node (str.split(l, r))
Definition at line 3546 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_SPLIT, sort_manager, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseOper().
mkStrSplitAt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrSplitAt (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
Definition at line 3558 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_SPLIT_AT, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseOper().
mkStrSplitAtRe()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrSplitAtRe (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
Definition at line 3587 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), stabilizer::parser::isRegParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_SPLIT_AT_RE, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseOper().
mkStrSplitRest()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrSplitRest (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
Definition at line 3567 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_SPLIT_REST, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseOper().
mkStrSplitRestRe()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrSplitRestRe (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
Definition at line 3599 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), stabilizer::parser::isRegParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_SPLIT_REST_RE, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseOper().
mkStrSubstr()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrSubstr (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > s)
Create a string substring node.
Parameters
l String
r Start index
s Length
Returns
String substring node (str.substr(l, r, s), i.e., l[r, r+s))
Definition at line 3352 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_SUBSTR.
Referenced by parseOper().
mkStrSuffixof()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrSuffixof (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r)
Create a string suffix check node.
Parameters
l Suffix
r String
Returns
String suffix check node (str.suffixof(l, r))
Definition at line 3379 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_SUFFIXOF.
Referenced by parseOper().
mkStrToCode()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrToCode (std::shared_ptr< DAGNode > param)
Create a string to-code conversion node.
Creates a node that converts a string to its ASCII code.
Note
Assumes the string has exactly one character
Parameters
param String
Returns
String to-code conversion node (str.to_code(param))
Definition at line 3726 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_TO_CODE.
Referenced by parseOper().
mkStrToInt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrToInt (std::shared_ptr< DAGNode > param)
Create a string to-integer conversion node.
Note
Returns -1 if the string does not represent a valid integer
Parameters
param String
Returns
String to-integer conversion node (str.to_int(param))
Definition at line 3704 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_TO_INT.
Referenced by parseOper().
mkStrToLower()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrToLower (std::shared_ptr< DAGNode > param)
Create a string to-lower node.
Parameters
param String
Returns
String to-lower node (str.to_lower(param))
Definition at line 3513 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_TO_LOWER, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseOper().
mkStrToReg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrToReg (std::shared_ptr< DAGNode > param)
Create a string to-regex conversion node.
Parameters
param String
Returns
String to-regex conversion node (str.to_reg(param))
Definition at line 3715 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_TO_REG, and stabilizer::parser::SortManager::REG_SORT.
Referenced by parseOper().
mkStrToUpper()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrToUpper (std::shared_ptr< DAGNode > param)
Create a string to-upper node.
Parameters
param String
Returns
String to-upper node (str.to_upper(param))
Definition at line 3524 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_STR_TO_UPPER, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseOper().
mkStrUpdate()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkStrUpdate (std::shared_ptr< DAGNode > l, std::shared_ptr< DAGNode > r, std::shared_ptr< DAGNode > v)
Create a string update node.
Parameters
l String
r Index
v New character
Returns
String update node (str.update(l, r, v), i.e., l[r] = v)
Definition at line 3418 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), stabilizer::parser::isStrParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_STR_UPDATE.
Referenced by parseOper().
mkSub()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkSub (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an sub node.
Parameters
params Parameters
Returns
Sub node (l - r - ...)
Definition at line 1328 of file op_parser.cpp.
References stabilizer::parser::canExempt(), err_all(), stabilizer::parser::ERR_PARAM_MIS, stabilizer::parser::ERR_TYPE_MIS, getSort(), stabilizer::parser::SortManager::INT_SORT, isZero(), line_number, mkConstInt(), mkConstReal(), mkNeg(), mkOper(), mkUnknown(), stabilizer::parser::NT_SUB, options, stabilizer::parser::SortManager::REAL_SORT, toInt(), and toReal().
Referenced by parseExpr(), and parseOper().
mkTan()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkTan (std::shared_ptr< DAGNode > param)
Create an tan node.
Note
assert(param != (pi/2) + k*pi)
Parameters
param Parameter
Returns
Tan node (tan(param))
Definition at line 1555 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_TAN, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkTanh()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkTanh (std::shared_ptr< DAGNode > param)
Create a tanh node.
Parameters
param Parameter
Returns
Tanh node (tanh(param))
Definition at line 1615 of file op_parser.cpp.
References mkOper(), stabilizer::parser::NT_TANH, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkTempVar()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkTempVar (const std::shared_ptr< Sort > & sort)
Create a temporary variable.
Parameters
sort Sort
Returns
Temporary variable node
Definition at line 772 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_PARAM_MIS, line_number, mkUnknown(), node_manager, stabilizer::parser::NT_TEMP_VAR, temp_var_counter, and temp_var_names.
mkToFp() [1/2]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkToFp (std::shared_ptr< DAGNode > eb, std::shared_ptr< DAGNode > sb, std::shared_ptr< DAGNode > param)
Definition at line 3092 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_FP_TO_FP, sort_manager, toInt(), and stabilizer::parser::HighPrecisionInteger::toULong().
mkToFp() [2/2]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkToFp (std::shared_ptr< DAGNode > eb, std::shared_ptr< DAGNode > sb, std::shared_ptr< DAGNode > rm, std::shared_ptr< DAGNode > param)
Create a value to floating-point conversion node.
Parameters
eb Exponent bit width
sb Significand bit width
param Value to convert
Returns
Value to floating-point conversion node (to_fp(eb, sb, param))
Definition at line 3045 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), stabilizer::parser::isFpParam(), stabilizer::parser::isRealParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_FP_TO_FP, sort_manager, toInt(), and stabilizer::parser::HighPrecisionInteger::toULong().
Referenced by parseOper().
mkToFpUnsigned()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkToFpUnsigned (std::shared_ptr< DAGNode > eb, std::shared_ptr< DAGNode > sb, std::shared_ptr< DAGNode > rm, std::shared_ptr< DAGNode > param)
Definition at line 3130 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_FP_TO_FP_UNSIGNED, sort_manager, toInt(), and stabilizer::parser::HighPrecisionInteger::toULong().
Referenced by parseOper().
mkToInt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkToInt (std::shared_ptr< DAGNode > param)
Create a to_int node.
Parameters
param Parameter
Returns
To_int node (to_int(param))
Definition at line 1718 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isRealParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_TO_INT.
Referenced by parseOper().
mkToReal()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkToReal (std::shared_ptr< DAGNode > param)
Create a to_real node.
Parameters
param Parameter
Returns
To_real node (to_real(param))
Definition at line 1728 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::isIntParam(), line_number, mkOper(), mkUnknown(), stabilizer::parser::NT_TO_REAL, and stabilizer::parser::SortManager::REAL_SORT.
Referenced by parseOper().
mkTrue()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkTrue ()
Create a true node.
Returns
True node
Definition at line 78 of file op_parser.cpp.
References stabilizer::parser::NodeManager::TRUE_NODE.
Referenced by mkAnd(), mkBvAnd(), mkBvSge(), mkBvSgt(), mkBvSle(), mkBvSlt(), mkBvUge(), mkBvUgt(), mkBvUle(), mkEq(), mkImplies(), mkOr(), parseConstFunc(), and rewrite().
mkUbvToInt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkUbvToInt (std::shared_ptr< DAGNode > param)
Definition at line 2554 of file op_parser.cpp.
References err_all(), stabilizer::parser::ERR_TYPE_MIS, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::isBvParam(), line_number, mkOper(), mkUnknown(), and stabilizer::parser::NT_UBV_TO_INT.
Referenced by parseOper().
mkUFVNode()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::mkUFVNode (const std::string & name, const std::shared_ptr< Sort > & sort) inline
Definition at line 311 of file parser.h.
References node_manager, and stabilizer::parser::NT_UF_NAME.
mkUnknown()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkUnknown ()
Create an unknown node.
Returns
Unknown node
Definition at line 80 of file op_parser.cpp.
References stabilizer::parser::NodeManager::UNKNOWN_NODE.
Referenced by mkAbs(), mkAdd(), mkAnd(), mkBvAdd(), mkBvAnd(), mkBvAshr(), mkBvConcat(), mkBvExtract(), mkBvLshr(), mkBvMul(), mkBvNot(), mkBvOr(), mkBvRepeat(), mkBvRotateLeft(), mkBvRotateRight(), mkBvSdiv(), mkBvSge(), mkBvSgt(), mkBvShl(), mkBvSignExt(), mkBvSle(), mkBvSlt(), mkBvSmod(), mkBvSrem(), mkBvToInt(), mkBvToNat(), mkBvUdiv(), mkBvUge(), mkBvUgt(), mkBvUle(), mkBvUlt(), mkBvUmod(), mkBvUrem(), mkBvXor(), mkBvZeroExt(), mkCeil(), mkConstArray(), mkDistinct(), mkDivInt(), mkDivReal(), mkEq(), mkFact(), mkFpAbs(), mkFpAdd(), mkFpConst(), mkFpDiv(), mkFpFma(), mkFpIsInf(), mkFpIsNaN(), mkFpIsNeg(), mkFpIsNormal(), mkFpIsPos(), mkFpIsSubnormal(), mkFpIsZero(), mkFpMul(), mkFpNeg(), mkFpRem(), mkFpRoundToIntegral(), mkFpSqrt(), mkFpSub(), mkFpToReal(), mkFpToSbv(), mkFpToUbv(), mkFuncDef(), mkFuncRec(), mkGcd(), mkGe(), mkGt(), mkIand(), mkImplies(), mkIndexofReg(), mkInfinity(), mkIntToBv(), mkIsDivisible(), mkIsEven(), mkIsInt(), mkIsOdd(), mkIsPrime(), mkIte(), mkLcm(), mkLe(), mkLog(), mkLt(), mkMax(), mkMin(), mkMod(), mkMul(), mkNatToBv(), mkNegInfinity(), mkNot(), mkOper(), mkOr(), mkPosInfinity(), mkRegComplement(), mkRegConcat(), mkRegDiff(), mkRegInter(), mkRegLoop(), mkRegOpt(), mkRegPlus(), mkRegRange(), mkRegRepeat(), mkRegStar(), mkRegUnion(), mkReplaceReg(), mkReplaceRegAll(), mkSafeSqrt(), mkSbvToInt(), mkSelect(), mkSqrt(), mkStrCharat(), mkStrConcat(), mkStrContains(), mkStrFromCode(), mkStrFromInt(), mkStrIndexof(), mkStrIndexofReg(), mkStrInReg(), mkStrIsDigit(), mkStrLen(), mkStrNumSplits(), mkStrNumSplitsRe(), mkStrPrefixof(), mkStrReplace(), mkStrReplaceAll(), mkStrReplaceReg(), mkStrReplaceRegAll(), mkStrRev(), mkStrSplit(), mkStrSplitAt(), mkStrSplitAtRe(), mkStrSplitRest(), mkStrSplitRestRe(), mkStrSubstr(), mkStrSuffixof(), mkStrToCode(), mkStrToInt(), mkStrToLower(), mkStrToReg(), mkStrToUpper(), mkStrUpdate(), mkSub(), mkTempVar(), mkToFp(), mkToFpUnsigned(), mkToInt(), mkToReal(), and mkUbvToInt().
mkVar()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkVar (const std::shared_ptr< Sort > & sort, const std::string & name)
Create a variable.
Parameters
sort Sort
name Variable name
Returns
Variable node
Definition at line 784 of file op_parser.cpp.
References node_manager, stabilizer::parser::NT_VAR, and var_names.
Referenced by declareVar(), mkArray(), mkVarBool(), mkVarBv(), mkVarFp(), mkVarInt(), mkVarReal(), mkVarReg(), mkVarRoundingMode(), mkVarStr(), and parseCommand().
mkVarBool()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkVarBool (const std::string & name)
Create a boolean variable.
Parameters
name Variable name
Returns
Boolean variable node
Definition at line 817 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, and mkVar().
mkVarBv()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkVarBv (const std::string & name, const size_t & width)
Create a bit-vector variable.
Parameters
name Variable name
width Width of the bit-vector
Returns
Bit-vector variable node
Definition at line 826 of file op_parser.cpp.
References mkVar(), sort_key_map, and sort_manager.
mkVarFp()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkVarFp (const std::string & name, const size_t & e, const size_t & s)
Create a floating-point variable.
Parameters
name Variable name
e Exponent size
s Significand size
Returns
Floating-point variable node
Definition at line 840 of file op_parser.cpp.
References mkVar(), sort_key_map, and sort_manager.
mkVarInt()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkVarInt (const std::string & name)
Create an integer variable.
Parameters
name Variable name
Returns
Integer variable node
Definition at line 820 of file op_parser.cpp.
References stabilizer::parser::SortManager::INT_SORT, and mkVar().
mkVarReal()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkVarReal (const std::string & name)
Create a real variable.
Parameters
name Variable name
Returns
Real variable node
Definition at line 823 of file op_parser.cpp.
References mkVar(), and stabilizer::parser::SortManager::REAL_SORT.
mkVarReg()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkVarReg (const std::string & name)
Create a regular expression variable.
Parameters
name Variable name
Returns
Regular expression variable node
Definition at line 859 of file op_parser.cpp.
References mkVar(), and stabilizer::parser::SortManager::REG_SORT.
mkVarRoundingMode()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkVarRoundingMode (const std::string & name)
Create a rounding mode variable.
Parameters
name Variable name
Returns
Rounding mode variable node
Definition at line 862 of file op_parser.cpp.
References mkVar(), and stabilizer::parser::SK_ROUNDING_MODE.
mkVarStr()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkVarStr (const std::string & name)
Create a string variable.
Parameters
name Variable name
Returns
String variable node
Definition at line 856 of file op_parser.cpp.
References mkVar(), and stabilizer::parser::SortManager::STR_SORT.
mkWeight()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkWeight (const std::shared_ptr< Sort > & sort, const std::string & name, std::shared_ptr< DAGNode > weight)
Definition at line 2276 of file base_parser.cpp.
References node_manager, and stabilizer::parser::NT_WEIGHT.
Referenced by parseExpr().
mkXor()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::mkXor (const std::vector< std::shared_ptr< DAGNode >> & params)
Create an xor node.
Parameters
params Parameters
Returns
Xor node (l xor m xor r xor ...)
Definition at line 1060 of file op_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, mkFalse(), mkOper(), and stabilizer::parser::NT_XOR.
Referenced by parseOper().
optionToString()
std::string stabilizer::parser::Parser::optionToString ()
Print the options.
Returns
String representation of the options
Definition at line 2688 of file base_parser.cpp.
References options.
parse()
bool stabilizer::parser::Parser::parse (const std::string & filename)
Parse SMT-LIB2 file.
Parses the specified SMT-LIB2 file and builds internal data structures.
Parameters
filename Path to the SMT-LIB2 file to parse
Returns
True if parsing was successful, false otherwise
Definition at line 79 of file base_parser.cpp.
References parseSmtlib2File().
Referenced by stabilizer::api::SMTStabilizer::apply_file().
parseCommand()
CMD_TYPE stabilizer::parser::Parser::parseCommand () private
Definition at line 800 of file base_parser.cpp.
References stabilizer::parser::Parser::DTTypeDecl::arity, assertion_groups, assertions, assumptions, attemptParseKeywords(), bufptr, stabilizer::parser::CT_ASSERT, stabilizer::parser::CT_CHECK_SAT, stabilizer::parser::CT_CHECK_SAT_ASSUMING, stabilizer::parser::CT_DECLARE_CONST, stabilizer::parser::CT_DECLARE_FUN, stabilizer::parser::CT_DECLARE_SORT, stabilizer::parser::CT_DEFINE_FUN, stabilizer::parser::CT_DEFINE_FUN_REC, stabilizer::parser::CT_DEFINE_FUNS_REC, stabilizer::parser::CT_DEFINE_SORT, stabilizer::parser::CT_ECHO, stabilizer::parser::CT_EXISTS, stabilizer::parser::CT_EXIT, stabilizer::parser::CT_FORALL, stabilizer::parser::CT_GET_ASSERTIONS, stabilizer::parser::CT_GET_ASSIGNMENT, stabilizer::parser::CT_GET_INFO, stabilizer::parser::CT_GET_MODEL, stabilizer::parser::CT_GET_OPTION, stabilizer::parser::CT_GET_PROOF, stabilizer::parser::CT_GET_UNSAT_ASSUMPTIONS, stabilizer::parser::CT_GET_UNSAT_CORE, stabilizer::parser::CT_GET_VALUE, stabilizer::parser::CT_POP, stabilizer::parser::CT_PUSH, stabilizer::parser::CT_RESET, stabilizer::parser::CT_RESET_ASSERTIONS, stabilizer::parser::CT_SET_INFO, stabilizer::parser::CT_SET_LOGIC, stabilizer::parser::CT_SET_OPTION, stabilizer::parser::CT_UNKNOWN, stabilizer::parser::Parser::DTTypeDecl::ctors, datatype_blocks, datatype_function_names, datatype_sort_names, err_all(), err_mul_decl(), err_mul_def(), err_unkwn_sym(), fun_key_map, fun_var_map, function_names, getSymbol(), in_quantifier_scope, stabilizer::parser::KW_ID, stabilizer::parser::KW_NAMED, line_number, mkFuncDec(), mkFuncDef(), mkFuncRec(), mkFunParamVar(), mkSortDec(), mkSortDef(), mkVar(), stabilizer::parser::Parser::DTConstructorDecl::name, stabilizer::parser::Parser::DTTypeDecl::name, named_assertions, stabilizer::parser::NT_FUNC_DEF, options, parse_options, parseExpr(), parseLpar(), parseQuant(), parseRpar(), parseSort(), quant_nesting_depth, scan_mode, scanToNextSymbol(), stabilizer::parser::Parser::DTConstructorDecl::selectors, skipToRpar(), stabilizer::parser::SM_COMMENT, stabilizer::parser::SM_COMMON, stabilizer::parser::SM_COMP_SYM, stabilizer::parser::SM_STRING, sort_key_map, sort_manager, and warn_cmd_nsup().
Referenced by parseSmtlib2File(), and parseStr().
parseConstFunc()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::parseConstFunc (const std::string & s) private
Definition at line 696 of file expr_parser.cpp.
References allow_placeholder_vars, current_let_mode, datatype_function_names, stabilizer::parser::ERR_UNKWN_SYM, err_unkwn_sym(), fun_key_map, fun_var_map, in_quantifier_scope, stabilizer::parser::SortManager::INT_SORT, stabilizer::parser::TypeChecker::isBV(), stabilizer::parser::TypeChecker::isFP(), stabilizer::parser::TypeChecker::isInt(), stabilizer::parser::TypeChecker::isNumber(), stabilizer::parser::TypeChecker::isReal(), stabilizer::parser::TypeChecker::isScientificNotation(), stabilizer::parser::TypeChecker::isString(), let_key_map, line_number, stabilizer::parser::LM_NON_LET, mkApplyDTFun(), mkConstBv(), mkConstFP(), mkConstInt(), mkConstReal(), mkConstStr(), mkE(), mkEpsilon(), mkErr(), mkFalse(), mkInfinity(), mkNaN(), mkNegEpsilon(), mkNegInfinity(), mkPi(), mkPlaceholderVar(), mkPosEpsilon(), mkPosInfinity(), mkRegAll(), mkRegAllChar(), mkRegNone(), mkRoundingMode(), mkTrue(), node_manager, options, stabilizer::parser::ConversionUtils::parseScientificNotation(), placeholder_var_names, stabilizer::parser::PRESERVING_LET_BIND_VAR_SUFFIX, preserving_let_counter, preserving_let_key_map, quant_var_map, stabilizer::parser::SortManager::REAL_SORT, stabilizer::parser::HighPrecisionInteger::toString(), and var_names.
Referenced by parseExpr().
parseExpr()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::parseExpr () private
Definition at line 85 of file expr_parser.cpp.
References allow_placeholder_vars, attemptParseKeywords(), bufptr, condAssert, current_let_mode, err_all(), stabilizer::parser::ERR_UNKWN_SYM, err_unkwn_sym(), stabilizer::parser::Finish, stabilizer::parser::ExprFrame::func_args, stabilizer::parser::SortManager::getNull(), getSymbol(), stabilizer::parser::ExprFrame::headSymbol, in_quantifier_scope, stabilizer::parser::KW_LBLNEG, stabilizer::parser::KW_LBLPOS, stabilizer::parser::KW_NAMED, stabilizer::parser::KW_NO_PATTERN, stabilizer::parser::KW_NULL, stabilizer::parser::KW_PATTERN, stabilizer::parser::KW_QID, stabilizer::parser::KW_SKOLEMID, stabilizer::parser::KW_WEIGHT, let_nesting_depth, stabilizer::parser::ExprFrame::line, line_number, stabilizer::parser::LM_IN_LET, stabilizer::parser::LM_NON_LET, stabilizer::parser::LM_START_LET, mkAdd(), mkAnd(), mkAttribute(), mkBvSge(), mkBvSgt(), mkBvSle(), mkBvSlt(), mkBvUge(), mkBvUgt(), mkBvUle(), mkBvUlt(), mkConstArray(), mkConstBv(), mkDistinct(), mkEq(), mkErr(), mkFpConst(), mkGe(), mkGt(), mkImplies(), mkIte(), mkLe(), mkLt(), mkMul(), mkNaN(), mkNegInfinity(), mkNoPattern(), mkNot(), mkOr(), mkPattern(), mkPosInfinity(), mkRootObj(), mkRootOfWithInterval(), mkSub(), mkWeight(), named_assertions, node_manager, stabilizer::parser::NT_CONST, stabilizer::parser::ExprFrame::oper_params, options, stabilizer::parser::ParamFunc, parseConstFunc(), parseLet(), parseLpar(), parseOper(), parsePreservingLet(), parseQuant(), parseRpar(), parseSort(), placeholder_var_sort, preserving_let_counter, stabilizer::parser::ProcessingParamFuncArgs, stabilizer::parser::ProcessingParamFuncParams, stabilizer::parser::ProcessingParams, quant_nesting_depth, stabilizer::parser::SortManager::REAL_SORT, stabilizer::parser::ExprFrame::result, scanToNextSymbol(), stabilizer::parser::ExprFrame::second_symbol, sort_manager, stabilizer::parser::ExprFrame::special_type, stabilizer::parser::Start, and stabilizer::parser::ExprFrame::state.
Referenced by mkExpr(), parseCommand(), parseLet(), parseParams(), parsePreservingLet(), and parseQuant().
parseGroup()
std::string stabilizer::parser::Parser::parseGroup () private
parseKeyword()
KEYWORD stabilizer::parser::Parser::parseKeyword () private
Definition at line 753 of file base_parser.cpp.
References err_unkwn_sym(), getSymbol(), stabilizer::parser::KW_COMP, stabilizer::parser::KW_EPSILON, stabilizer::parser::KW_ID, stabilizer::parser::KW_LBLNEG, stabilizer::parser::KW_LBLPOS, stabilizer::parser::KW_M, stabilizer::parser::KW_NAMED, stabilizer::parser::KW_NO_PATTERN, stabilizer::parser::KW_NULL, stabilizer::parser::KW_PATTERN, stabilizer::parser::KW_QID, stabilizer::parser::KW_SKOLEMID, stabilizer::parser::KW_WEIGHT, and line_number.
Referenced by attemptParseKeywords().
parseLet()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::parseLet () private
Definition at line 1927 of file base_parser.cpp.
References bufptr, condAssert, err_all(), err_sym_mis(), stabilizer::parser::ERR_UNEXP_EOF, getSymbol(), let_key_map, line_number, mkErr(), parseExpr(), parseLpar(), parseRpar(), and peekSymbol().
Referenced by parseExpr().
parseLpar()
void stabilizer::parser::Parser::parseLpar () private
Definition at line 573 of file base_parser.cpp.
References bufptr, err_sym_mis(), line_number, and scanToNextSymbol().
Referenced by parseCommand(), parseExpr(), parseLet(), parsePreservingLet(), parseQuant(), parseSmtlib2File(), parseSort(), and parseStr().
parseOper()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::parseOper (const std::string & s, const std::vector< std::shared_ptr< DAGNode >> & func_args, const std::vector< std::shared_ptr< DAGNode >> & oper_params) private
Definition at line 907 of file expr_parser.cpp.
References applyFun(), stabilizer::parser::SortManager::BOOL_SORT, condAssert, stabilizer::parser::ERR_PARAM_MIS, err_param_mis(), stabilizer::parser::ERR_UNKWN_SYM, err_unkwn_sym(), fun_key_map, stabilizer::parser::getOperKind(), getSort(), line_number, mkAbs(), mkAcos(), mkAcosh(), mkAcot(), mkAcoth(), mkAcsc(), mkAcsch(), mkAdd(), mkAnd(), mkApplyUF(), mkAsec(), mkAsech(), mkAsin(), mkAsinh(), mkAtan(), mkAtan2(), mkAtanh(), mkBvAdd(), mkBvAnd(), mkBvAshr(), mkBvComp(), mkBvConcat(), mkBvExtract(), mkBvLshr(), mkBvMul(), mkBvNand(), mkBvNeg(), mkBvNor(), mkBvNot(), mkBvOr(), mkBvRepeat(), mkBvRotateLeft(), mkBvRotateRight(), mkBvSdiv(), mkBvSge(), mkBvSgt(), mkBvShl(), mkBvSignExt(), mkBvSle(), mkBvSlt(), mkBvSmod(), mkBvSrem(), mkBvSub(), mkBvToInt(), mkBvToNat(), mkBvUdiv(), mkBvUge(), mkBvUgt(), mkBvUle(), mkBvUlt(), mkBvUrem(), mkBvXnor(), mkBvXor(), mkBvZeroExt(), mkCeil(), mkCos(), mkCosh(), mkCot(), mkCsc(), mkCsch(), mkDistinct(), mkDivInt(), mkDivReal(), mkEq(), mkErr(), mkExp(), mkFact(), mkFloor(), mkFpAbs(), mkFpAdd(), mkFpDiv(), mkFpEq(), mkFpFma(), mkFpGe(), mkFpGt(), mkFpIsInf(), mkFpIsNaN(), mkFpIsNeg(), mkFpIsNormal(), mkFpIsPos(), mkFpIsSubnormal(), mkFpIsZero(), mkFpLe(), mkFpLt(), mkFpMax(), mkFpMin(), mkFpMul(), mkFpNeg(), mkFpRem(), mkFpRoundToIntegral(), mkFpSqrt(), mkFpSub(), mkFpToReal(), mkFpToSbv(), mkFpToUbv(), mkGcd(), mkGe(), mkGt(), mkIand(), mkImplies(), mkIntToBv(), mkIsDivisible(), mkIsEven(), mkIsInt(), mkIsOdd(), mkIsPrime(), mkIte(), mkLb(), mkLcm(), mkLe(), mkLg(), mkLn(), mkLog(), mkLt(), mkMod(), mkMul(), mkNatToBv(), mkNeg(), mkNot(), mkOr(), mkPow(), mkPow2(), mkRegComplement(), mkRegConcat(), mkRegDiff(), mkRegInter(), mkRegLoop(), mkRegOpt(), mkRegPlus(), mkRegRange(), mkRegRepeat(), mkRegStar(), mkRegUnion(), mkRootObj(), mkRound(), mkSafeSqrt(), mkSec(), mkSech(), mkSelect(), mkSin(), mkSinh(), mkSqrt(), mkStore(), mkStrCharat(), mkStrConcat(), mkStrContains(), mkStrFromCode(), mkStrFromInt(), mkStrGe(), mkStrGt(), mkStrIndexof(), mkStrIndexofReg(), mkStrInReg(), mkStrIsDigit(), mkStrLe(), mkStrLen(), mkStrLt(), mkStrNumSplits(), mkStrNumSplitsRe(), mkStrPrefixof(), mkStrReplace(), mkStrReplaceAll(), mkStrReplaceReg(), mkStrReplaceRegAll(), mkStrRev(), mkStrSplit(), mkStrSplitAt(), mkStrSplitAtRe(), mkStrSplitRest(), mkStrSplitRestRe(), mkStrSubstr(), mkStrSuffixof(), mkStrToCode(), mkStrToInt(), mkStrToLower(), mkStrToReg(), mkStrToUpper(), mkStrUpdate(), mkSub(), mkTan(), mkTanh(), mkToFp(), mkToFpUnsigned(), mkToInt(), mkToReal(), mkUbvToInt(), mkXor(), node_manager, stabilizer::parser::NT_ABS, stabilizer::parser::NT_ACOS, stabilizer::parser::NT_ACOSH, stabilizer::parser::NT_ACOT, stabilizer::parser::NT_ACOTH, stabilizer::parser::NT_ACSC, stabilizer::parser::NT_ACSCH, stabilizer::parser::NT_ADD, stabilizer::parser::NT_AND, stabilizer::parser::NT_ASEC, stabilizer::parser::NT_ASECH, stabilizer::parser::NT_ASIN, stabilizer::parser::NT_ASINH, stabilizer::parser::NT_ATAN, stabilizer::parser::NT_ATAN2, stabilizer::parser::NT_ATANH, stabilizer::parser::NT_BV_ADD, stabilizer::parser::NT_BV_AND, stabilizer::parser::NT_BV_ASHR, stabilizer::parser::NT_BV_COMP, stabilizer::parser::NT_BV_CONCAT, stabilizer::parser::NT_BV_EXTRACT, stabilizer::parser::NT_BV_LSHR, stabilizer::parser::NT_BV_MUL, stabilizer::parser::NT_BV_NAND, stabilizer::parser::NT_BV_NEG, stabilizer::parser::NT_BV_NOR, stabilizer::parser::NT_BV_NOT, stabilizer::parser::NT_BV_OR, stabilizer::parser::NT_BV_REPEAT, stabilizer::parser::NT_BV_ROTATE_LEFT, stabilizer::parser::NT_BV_ROTATE_RIGHT, stabilizer::parser::NT_BV_SDIV, stabilizer::parser::NT_BV_SGE, stabilizer::parser::NT_BV_SGT, stabilizer::parser::NT_BV_SHL, stabilizer::parser::NT_BV_SIGN_EXT, stabilizer::parser::NT_BV_SLE, stabilizer::parser::NT_BV_SLT, stabilizer::parser::NT_BV_SMOD, stabilizer::parser::NT_BV_SREM, stabilizer::parser::NT_BV_SUB, stabilizer::parser::NT_BV_TO_INT, stabilizer::parser::NT_BV_TO_NAT, stabilizer::parser::NT_BV_UDIV, stabilizer::parser::NT_BV_UGE, stabilizer::parser::NT_BV_UGT, stabilizer::parser::NT_BV_ULE, stabilizer::parser::NT_BV_ULT, stabilizer::parser::NT_BV_UREM, stabilizer::parser::NT_BV_XNOR, stabilizer::parser::NT_BV_XOR, stabilizer::parser::NT_BV_ZERO_EXT, stabilizer::parser::NT_CEIL, stabilizer::parser::NT_CONST, stabilizer::parser::NT_CONST_ARRAY, stabilizer::parser::NT_CONST_FALSE, stabilizer::parser::NT_CONST_TRUE, stabilizer::parser::NT_COS, stabilizer::parser::NT_COSH, stabilizer::parser::NT_COT, stabilizer::parser::NT_CSC, stabilizer::parser::NT_CSCH, stabilizer::parser::NT_DISTINCT, stabilizer::parser::NT_DIV_INT, stabilizer::parser::NT_DIV_REAL, stabilizer::parser::NT_DT_TESTER, stabilizer::parser::NT_DT_UPDATER, stabilizer::parser::NT_EQ, stabilizer::parser::NT_ERROR, stabilizer::parser::NT_EXISTS, stabilizer::parser::NT_EXP, stabilizer::parser::NT_FACT, stabilizer::parser::NT_FLOOR, stabilizer::parser::NT_FORALL, stabilizer::parser::NT_FP_ABS, stabilizer::parser::NT_FP_ADD, stabilizer::parser::NT_FP_DIV, stabilizer::parser::NT_FP_EQ, stabilizer::parser::NT_FP_FMA, stabilizer::parser::NT_FP_GE, stabilizer::parser::NT_FP_GT, stabilizer::parser::NT_FP_IS_INF, stabilizer::parser::NT_FP_IS_NAN, stabilizer::parser::NT_FP_IS_NEG, stabilizer::parser::NT_FP_IS_NORMAL, stabilizer::parser::NT_FP_IS_POS, stabilizer::parser::NT_FP_IS_SUBNORMAL, stabilizer::parser::NT_FP_IS_ZERO, stabilizer::parser::NT_FP_LE, stabilizer::parser::NT_FP_LT, stabilizer::parser::NT_FP_MAX, stabilizer::parser::NT_FP_MIN, stabilizer::parser::NT_FP_MUL, stabilizer::parser::NT_FP_NEG, stabilizer::parser::NT_FP_REM, stabilizer::parser::NT_FP_ROUND_TO_INTEGRAL, stabilizer::parser::NT_FP_SQRT, stabilizer::parser::NT_FP_SUB, stabilizer::parser::NT_FP_TO_FP, stabilizer::parser::NT_FP_TO_FP_UNSIGNED, stabilizer::parser::NT_FP_TO_REAL, stabilizer::parser::NT_FP_TO_SBV, stabilizer::parser::NT_FP_TO_UBV, stabilizer::parser::NT_FUNC_PARAM, stabilizer::parser::NT_GCD, stabilizer::parser::NT_GE, stabilizer::parser::NT_GT, stabilizer::parser::NT_IAND, stabilizer::parser::NT_IMPLIES, stabilizer::parser::NT_INT_TO_BV, stabilizer::parser::NT_IS_DIVISIBLE, stabilizer::parser::NT_IS_EVEN, stabilizer::parser::NT_IS_INT, stabilizer::parser::NT_IS_ODD, stabilizer::parser::NT_IS_PRIME, stabilizer::parser::NT_ITE, stabilizer::parser::NT_LB, stabilizer::parser::NT_LCM, stabilizer::parser::NT_LE, stabilizer::parser::NT_LET, stabilizer::parser::NT_LET_BIND_VAR, stabilizer::parser::NT_LET_BIND_VAR_LIST, stabilizer::parser::NT_LET_CHAIN, stabilizer::parser::NT_LG, stabilizer::parser::NT_LN, stabilizer::parser::NT_LOG, stabilizer::parser::NT_LT, stabilizer::parser::NT_MAX, stabilizer::parser::NT_MIN, stabilizer::parser::NT_MOD, stabilizer::parser::NT_MUL, stabilizer::parser::NT_NAT_TO_BV, stabilizer::parser::NT_NEG, stabilizer::parser::NT_NOT, stabilizer::parser::NT_NULL, stabilizer::parser::NT_OR, stabilizer::parser::NT_POW, stabilizer::parser::NT_POW2, stabilizer::parser::NT_QUANT_VAR, stabilizer::parser::NT_REG_COMPLEMENT, stabilizer::parser::NT_REG_CONCAT, stabilizer::parser::NT_REG_DIFF, stabilizer::parser::NT_REG_INTER, stabilizer::parser::NT_REG_LOOP, stabilizer::parser::NT_REG_OPT, stabilizer::parser::NT_REG_PLUS, stabilizer::parser::NT_REG_RANGE, stabilizer::parser::NT_REG_REPEAT, stabilizer::parser::NT_REG_STAR, stabilizer::parser::NT_REG_UNION, stabilizer::parser::NT_ROUND, stabilizer::parser::NT_SAFESQRT, stabilizer::parser::NT_SBV_TO_INT, stabilizer::parser::NT_SEC, stabilizer::parser::NT_SECH, stabilizer::parser::NT_SELECT, stabilizer::parser::NT_SIN, stabilizer::parser::NT_SINH, stabilizer::parser::NT_SQRT, stabilizer::parser::NT_STORE, stabilizer::parser::NT_STR_CHARAT, stabilizer::parser::NT_STR_CONCAT, stabilizer::parser::NT_STR_CONTAINS, stabilizer::parser::NT_STR_FROM_CODE, stabilizer::parser::NT_STR_FROM_INT, stabilizer::parser::NT_STR_GE, stabilizer::parser::NT_STR_GT, stabilizer::parser::NT_STR_IN_REG, stabilizer::parser::NT_STR_INDEXOF, stabilizer::parser::NT_STR_INDEXOF_REG, stabilizer::parser::NT_STR_IS_DIGIT, stabilizer::parser::NT_STR_LE, stabilizer::parser::NT_STR_LEN, stabilizer::parser::NT_STR_LT, stabilizer::parser::NT_STR_NUM_SPLITS, stabilizer::parser::NT_STR_NUM_SPLITS_RE, stabilizer::parser::NT_STR_PREFIXOF, stabilizer::parser::NT_STR_REPLACE, stabilizer::parser::NT_STR_REPLACE_ALL, stabilizer::parser::NT_STR_REPLACE_REG, stabilizer::parser::NT_STR_REPLACE_REG_ALL, stabilizer::parser::NT_STR_REV, stabilizer::parser::NT_STR_SPLIT, stabilizer::parser::NT_STR_SPLIT_AT, stabilizer::parser::NT_STR_SPLIT_AT_RE, stabilizer::parser::NT_STR_SPLIT_REST, stabilizer::parser::NT_STR_SPLIT_REST_RE, stabilizer::parser::NT_STR_SUBSTR, stabilizer::parser::NT_STR_SUFFIXOF, stabilizer::parser::NT_STR_TO_CODE, stabilizer::parser::NT_STR_TO_INT, stabilizer::parser::NT_STR_TO_LOWER, stabilizer::parser::NT_STR_TO_REG, stabilizer::parser::NT_STR_TO_UPPER, stabilizer::parser::NT_STR_UPDATE, stabilizer::parser::NT_SUB, stabilizer::parser::NT_TAN, stabilizer::parser::NT_TANH, stabilizer::parser::NT_TEMP_VAR, stabilizer::parser::NT_TO_INT, stabilizer::parser::NT_TO_REAL, stabilizer::parser::NT_TUPLE_CONSTRUCTOR, stabilizer::parser::NT_TUPLE_PROJECT, stabilizer::parser::NT_TUPLE_SELECT, stabilizer::parser::NT_TUPLE_UNIT, stabilizer::parser::NT_TUPLE_UPDATE, stabilizer::parser::NT_UBV_TO_INT, stabilizer::parser::NT_UNKNOWN, stabilizer::parser::NT_VAR, stabilizer::parser::NT_XOR, stabilizer::parser::SortManager::NULL_SORT, stabilizer::parser::NUM_KINDS, and sort_manager.
Referenced by parseExpr().
parseParams()
std::vector< std::shared_ptr< DAGNode > > stabilizer::parser::Parser::parseParams () private
Definition at line 1768 of file base_parser.cpp.
References bufptr, and parseExpr().
parsePreservingLet()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::parsePreservingLet () private
Definition at line 1801 of file base_parser.cpp.
References bufptr, condAssert, err_all(), err_sym_mis(), stabilizer::parser::ERR_UNEXP_EOF, getSymbol(), line_number, mkErr(), mkLetBindVar(), mkLetBindVarList(), mkLetChain(), parseExpr(), parseLpar(), parseRpar(), peekSymbol(), stabilizer::parser::PRESERVING_LET_BIND_VAR_SUFFIX, preserving_let_counter, and preserving_let_key_map.
Referenced by parseExpr().
parseQuant()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::parseQuant (const std::string & type) private
Definition at line 2312 of file base_parser.cpp.
References bufptr, condAssert, getSymbol(), mkExists(), mkForall(), mkQuantVar(), stabilizer::parser::NodeManager::NULL_NODE, parseExpr(), parseLpar(), parseRpar(), parseSort(), and quant_var_map.
Referenced by parseCommand(), and parseExpr().
parseRpar()
void stabilizer::parser::Parser::parseRpar () private
Definition at line 583 of file base_parser.cpp.
References bufptr, err_sym_mis(), line_number, and scanToNextSymbol().
Referenced by parseCommand(), parseExpr(), parseLet(), parsePreservingLet(), parseQuant(), parseSmtlib2File(), parseSort(), and parseStr().
parseSmtlib2File()
bool stabilizer::parser::Parser::parseSmtlib2File (const std::string filename)
Parse an SMT-LIB2 file.
Parses an SMT-LIB2 file and returns a boolean indicating success.
Parameters
filename Path to the SMT-LIB2 file
Returns
Boolean indicating success
Definition at line 633 of file base_parser.cpp.
References buffer, buflen, bufptr, stabilizer::parser::CT_EXIT, err_open_file(), line_number, parseCommand(), parseLpar(), parseRpar(), parsing_file, and scanToNextSymbol().
Referenced by parse(), and Parser().
parseSort()
std::shared_ptr< Sort > stabilizer::parser::Parser::parseSort () private
Definition at line 1605 of file base_parser.cpp.
References stabilizer::parser::SortManager::BOOL_SORT, bufptr, err_all(), stabilizer::parser::ERR_TYPE_MIS, err_unkwn_sym(), stabilizer::parser::SortManager::FLOAT16_SORT, stabilizer::parser::SortManager::FLOAT32_SORT, stabilizer::parser::SortManager::FLOAT64_SORT, getSymbol(), stabilizer::parser::SortManager::INT_SORT, line_number, stabilizer::parser::SortManager::NULL_SORT, parseLpar(), parseRpar(), stabilizer::parser::SortManager::REAL_SORT, stabilizer::parser::SortManager::REG_SORT, stabilizer::parser::SortManager::ROUNDING_MODE_SORT, scanToNextSymbol(), sort_key_map, sort_manager, and stabilizer::parser::SortManager::STR_SORT.
Referenced by parseCommand(), parseExpr(), and parseQuant().
parseStr()
bool stabilizer::parser::Parser::parseStr (const std::string & constraint)
Parse a constraint.
Parses the specified constraint and builds internal data structures.
Parameters
constraint Constraint to parse
Returns
True if parsing was successful, false otherwise
Definition at line 698 of file base_parser.cpp.
References buffer, buflen, bufptr, stabilizer::parser::CT_EXIT, line_number, parseCommand(), parseLpar(), parseRpar(), stabilizer::parser::safe_strdup(), and scanToNextSymbol().
Referenced by stabilizer::api::SMTStabilizer::apply_text().
parseWeight()
std::string stabilizer::parser::Parser::parseWeight () private
peekSymbol()
std::string stabilizer::parser::Parser::peekSymbol () private
Definition at line 2036 of file base_parser.cpp.
References bufptr, getSymbol(), line_number, scan_mode, and scanToNextSymbol().
Referenced by parseLet(), and parsePreservingLet().
rebuild_node_manager()
void stabilizer::parser::Parser::rebuild_node_manager () inline
Definition at line 767 of file parser.h.
References node_manager.
rebuildLetBindings()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::rebuildLetBindings (const std::shared_ptr< DAGNode > & root)
Definition at line 2691 of file base_parser.cpp.
References clear_let_key_map(), mkLetBindVar(), mkLetBindVarList(), mkLetChain(), stabilizer::parser::NT_EXISTS, and stabilizer::parser::NT_FORALL.
Referenced by dumpSMT2().
remove() [1/2]
std::shared_ptr<DAGNode> stabilizer::parser::Parser::remove (std::shared_ptr< DAGNode > expr, const std::unordered_set< std::shared_ptr< DAGNode >> & nodes)
Remove all the nodes in the expression.
Parameters
expr Expression to remove nodes from
nodes Nodes to remove
Returns
Expression with removed nodes
remove() [2/2]
std::shared_ptr<DAGNode> stabilizer::parser::Parser::remove (std::shared_ptr< DAGNode > expr, const std::unordered_set< std::shared_ptr< DAGNode >> & nodes, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> & visited) private
removeFuns()
size_t stabilizer::parser::Parser::removeFuns (const std::vector< std::string > & funcNames)
Remove functions by name.
Parameters
funcNames Vector of function names to remove
Returns
Number of functions actually removed
Definition at line 2988 of file base_parser.cpp.
References fun_key_map, and function_names.
rename()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::rename (std::shared_ptr< DAGNode > expr, const std::string & new_name)
Rename a node.
Parameters
expr Expression to rename
new_name New name
Returns
Expression with renamed node
Definition at line 2659 of file base_parser.cpp.
References condAssert, temp_var_names, and var_names.
replaceAssertions()
void stabilizer::parser::Parser::replaceAssertions (const std::vector< std::shared_ptr< DAGNode >> & new_assertions) inline
Definition at line 307 of file parser.h.
References assertions.
replaceAtoms()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::replaceAtoms (std::shared_ptr< DAGNode > expr, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> & atom_map, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> & visited, bool & is_changed) private
replaceNodes()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::replaceNodes (std::shared_ptr< DAGNode > expr, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> & node_map, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> & visited, bool & is_changed) private
rewrite() [1/5]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::rewrite (NODE_KIND & t, std::shared_ptr< DAGNode > & l, std::shared_ptr< DAGNode > & m, std::shared_ptr< DAGNode > & r)
Rewrite ternary operation node when simplification rule applies.
Parameters
t Operation kind (may be updated during rewrite).
l First operand.
m Second operand.
r Third operand.
Returns
Rewritten node, or nullptr when no rewrite is applied.
Definition at line 932 of file rewrite_parser.cpp.
References stabilizer::parser::BitVectorUtils::bvExtract(), stabilizer::parser::echo_error(), isZero(), mkConstBv(), mkConstInt(), mkConstStr(), stabilizer::parser::NT_BV_EXTRACT, stabilizer::parser::NT_FP_ADD, stabilizer::parser::NT_FP_DIV, stabilizer::parser::NT_FP_MUL, stabilizer::parser::NT_FP_SUB, stabilizer::parser::NT_FP_TO_SBV, stabilizer::parser::NT_FP_TO_UBV, stabilizer::parser::NT_ITE, stabilizer::parser::NT_REG_LOOP, stabilizer::parser::NT_STORE, stabilizer::parser::NT_STR_INDEXOF, stabilizer::parser::NT_STR_INDEXOF_REG, stabilizer::parser::NT_STR_REPLACE, stabilizer::parser::NT_STR_REPLACE_ALL, stabilizer::parser::NT_STR_REPLACE_REG, stabilizer::parser::NT_STR_REPLACE_REG_ALL, stabilizer::parser::NT_STR_SPLIT_AT, stabilizer::parser::NT_STR_SPLIT_AT_RE, stabilizer::parser::NT_STR_SPLIT_REST, stabilizer::parser::NT_STR_SPLIT_REST_RE, stabilizer::parser::NT_STR_SUBSTR, stabilizer::parser::NT_STR_UPDATE, rewrite(), stabilizer::parser::StringUtils::strIndexof(), stabilizer::parser::StringUtils::strReplace(), stabilizer::parser::StringUtils::strReplaceAll(), stabilizer::parser::StringUtils::strSubstr(), stabilizer::parser::StringUtils::strUpdate(), toInt(), and stabilizer::parser::HighPrecisionInteger::toString().
rewrite() [2/5]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::rewrite (NODE_KIND & t, std::shared_ptr< DAGNode > & l, std::shared_ptr< DAGNode > & ml, std::shared_ptr< DAGNode > & mr, std::shared_ptr< DAGNode > & r)
Rewrite four-operand operation node when simplification rule applies.
Parameters
t Operation kind (may be updated during rewrite).
l First operand.
ml Second operand.
mr Third operand.
r Fourth operand.
Returns
Rewritten node, or nullptr when no rewrite is applied.
Definition at line 1007 of file rewrite_parser.cpp.
References stabilizer::parser::echo_error(), and stabilizer::parser::NT_FP_FMA.
rewrite() [3/5]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::rewrite (NODE_KIND & t, std::shared_ptr< DAGNode > & l, std::shared_ptr< DAGNode > & r)
Rewrite binary operation node when simplification rule applies.
Parameters
t Operation kind (may be updated during rewrite).
l Left operand.
r Right operand.
Returns
Rewritten node, or nullptr when no rewrite is applied.
Definition at line 531 of file rewrite_parser.cpp.
References stabilizer::parser::HighPrecisionReal::atan2(), stabilizer::parser::BitVectorUtils::bvAshr(), stabilizer::parser::BitVectorUtils::bvComp(), stabilizer::parser::BitVectorUtils::bvCompareToUint(), stabilizer::parser::BitVectorUtils::bvIsMaxSigned(), stabilizer::parser::BitVectorUtils::bvIsMaxUnsigned(), stabilizer::parser::BitVectorUtils::bvIsMinSigned(), stabilizer::parser::BitVectorUtils::bvIsNegOne(), stabilizer::parser::BitVectorUtils::bvLshr(), stabilizer::parser::BitVectorUtils::bvNand(), stabilizer::parser::BitVectorUtils::bvNor(), stabilizer::parser::BitVectorUtils::bvRepeat(), stabilizer::parser::BitVectorUtils::bvRotateLeft(), stabilizer::parser::BitVectorUtils::bvRotateRight(), stabilizer::parser::BitVectorUtils::bvSdiv(), stabilizer::parser::BitVectorUtils::bvShl(), stabilizer::parser::BitVectorUtils::bvSignExtend(), stabilizer::parser::BitVectorUtils::bvSmod(), stabilizer::parser::BitVectorUtils::bvSrem(), stabilizer::parser::BitVectorUtils::bvSub(), stabilizer::parser::BitVectorUtils::bvUdiv(), stabilizer::parser::BitVectorUtils::bvUrem(), stabilizer::parser::BitVectorUtils::bvXnor(), stabilizer::parser::BitVectorUtils::bvZeroExtend(), err_all(), stabilizer::parser::MathUtils::gcd(), getEvaluateUseFloating(), stabilizer::parser::BitVectorUtils::intToBv(), isOne(), isOnes(), isZero(), stabilizer::parser::MathUtils::lcm(), line_number, mkBvNeg(), mkBvNot(), mkConstBv(), mkConstInt(), mkConstReal(), mkConstStr(), mkEq(), mkFalse(), stabilizer::parser::BitVectorUtils::mkOnes(), mkTrue(), stabilizer::parser::BitVectorUtils::natToBv(), stabilizer::parser::NT_ATAN2, stabilizer::parser::NT_BV_ASHR, stabilizer::parser::NT_BV_LSHR, stabilizer::parser::NT_BV_NAND, stabilizer::parser::NT_BV_NOR, stabilizer::parser::NT_BV_REPEAT, stabilizer::parser::NT_BV_ROTATE_LEFT, stabilizer::parser::NT_BV_ROTATE_RIGHT, stabilizer::parser::NT_BV_SDIV, stabilizer::parser::NT_BV_SDIVO, stabilizer::parser::NT_BV_SGE, stabilizer::parser::NT_BV_SGT, stabilizer::parser::NT_BV_SHL, stabilizer::parser::NT_BV_SIGN_EXT, stabilizer::parser::NT_BV_SLE, stabilizer::parser::NT_BV_SLT, stabilizer::parser::NT_BV_SMOD, stabilizer::parser::NT_BV_SMODO, stabilizer::parser::NT_BV_SREM, stabilizer::parser::NT_BV_SREMO, stabilizer::parser::NT_BV_SUB, stabilizer::parser::NT_BV_UDIV, stabilizer::parser::NT_BV_UDIVO, stabilizer::parser::NT_BV_UGE, stabilizer::parser::NT_BV_UGT, stabilizer::parser::NT_BV_ULE, stabilizer::parser::NT_BV_ULT, stabilizer::parser::NT_BV_UMOD, stabilizer::parser::NT_BV_UMODO, stabilizer::parser::NT_BV_UREM, stabilizer::parser::NT_BV_UREMO, stabilizer::parser::NT_BV_XNOR, stabilizer::parser::NT_BV_ZERO_EXT, stabilizer::parser::NT_FP_MAX, stabilizer::parser::NT_FP_MIN, stabilizer::parser::NT_FP_REM, stabilizer::parser::NT_FP_ROUND_TO_INTEGRAL, stabilizer::parser::NT_FP_SQRT, stabilizer::parser::NT_GCD, stabilizer::parser::NT_INT_TO_BV, stabilizer::parser::NT_IS_DIVISIBLE, stabilizer::parser::NT_LCM, stabilizer::parser::NT_LOG, stabilizer::parser::NT_MOD, stabilizer::parser::NT_NAT_TO_BV, stabilizer::parser::NT_POW, stabilizer::parser::NT_REG_RANGE, stabilizer::parser::NT_REG_REPEAT, stabilizer::parser::NT_SELECT, stabilizer::parser::NT_STR_CHARAT, stabilizer::parser::NT_STR_CONTAINS, stabilizer::parser::NT_STR_IN_REG, stabilizer::parser::NT_STR_NUM_SPLITS_RE, stabilizer::parser::NT_STR_PREFIXOF, stabilizer::parser::NT_STR_SPLIT, stabilizer::parser::NT_STR_SUFFIXOF, rewrite(), stabilizer::parser::StringUtils::strCharAt(), stabilizer::parser::StringUtils::strContains(), stabilizer::parser::StringUtils::strPrefixof(), stabilizer::parser::StringUtils::strSuffixof(), toInt(), and toReal().
rewrite() [4/5]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::rewrite (NODE_KIND & t, std::shared_ptr< DAGNode > & p)
Rewrite unary operation node when simplification rule applies.
Parameters
t Operation kind (may be updated during rewrite).
p Operand node.
Returns
Rewritten node, or nullptr when no rewrite is applied.
Definition at line 39 of file rewrite_parser.cpp.
References stabilizer::parser::BitVectorUtils::bvNeg(), stabilizer::parser::BitVectorUtils::bvNot(), stabilizer::parser::BitVectorUtils::bvToInt(), stabilizer::parser::BitVectorUtils::bvToNat(), stabilizer::parser::echo_error(), err_all(), stabilizer::parser::MathUtils::factorial(), getEvaluateUseFloating(), stabilizer::parser::MathUtils::isEven(), stabilizer::parser::TypeChecker::isInt(), stabilizer::parser::MathUtils::isOdd(), stabilizer::parser::MathUtils::isPrime(), line_number, mkConstBv(), mkConstInt(), mkConstReal(), mkConstStr(), mkFalse(), mkTrue(), stabilizer::parser::NodeManager::NAN_NODE, stabilizer::parser::NT_ABS, stabilizer::parser::NT_ACOS, stabilizer::parser::NT_ACOSH, stabilizer::parser::NT_ACOT, stabilizer::parser::NT_ACOTH, stabilizer::parser::NT_ACSC, stabilizer::parser::NT_ACSCH, stabilizer::parser::NT_ASEC, stabilizer::parser::NT_ASECH, stabilizer::parser::NT_ASIN, stabilizer::parser::NT_ASINH, stabilizer::parser::NT_ATAN, stabilizer::parser::NT_ATANH, stabilizer::parser::NT_BV_NEG, stabilizer::parser::NT_BV_NEGO, stabilizer::parser::NT_BV_NOT, stabilizer::parser::NT_BV_TO_INT, stabilizer::parser::NT_BV_TO_NAT, stabilizer::parser::NT_CEIL, stabilizer::parser::NT_CONST_ARRAY, stabilizer::parser::NT_COS, stabilizer::parser::NT_COSH, stabilizer::parser::NT_COT, stabilizer::parser::NT_COTH, stabilizer::parser::NT_CSC, stabilizer::parser::NT_CSCH, stabilizer::parser::NT_EXP, stabilizer::parser::NT_FACT, stabilizer::parser::NT_FLOOR, stabilizer::parser::NT_FP_ABS, stabilizer::parser::NT_FP_IS_INF, stabilizer::parser::NT_FP_IS_NAN, stabilizer::parser::NT_FP_IS_NEG, stabilizer::parser::NT_FP_IS_NORMAL, stabilizer::parser::NT_FP_IS_POS, stabilizer::parser::NT_FP_IS_SUBNORMAL, stabilizer::parser::NT_FP_IS_ZERO, stabilizer::parser::NT_FP_NEG, stabilizer::parser::NT_FP_TO_REAL, stabilizer::parser::NT_IS_EVEN, stabilizer::parser::NT_IS_INT, stabilizer::parser::NT_IS_ODD, stabilizer::parser::NT_IS_PRIME, stabilizer::parser::NT_LB, stabilizer::parser::NT_LG, stabilizer::parser::NT_LN, stabilizer::parser::NT_NEG, stabilizer::parser::NT_NOT, stabilizer::parser::NT_POW2, stabilizer::parser::NT_REG_COMPLEMENT, stabilizer::parser::NT_REG_OPT, stabilizer::parser::NT_REG_PLUS, stabilizer::parser::NT_REG_STAR, stabilizer::parser::NT_ROUND, stabilizer::parser::NT_SAFESQRT, stabilizer::parser::NT_SBV_TO_INT, stabilizer::parser::NT_SEC, stabilizer::parser::NT_SECH, stabilizer::parser::NT_SIN, stabilizer::parser::NT_SINH, stabilizer::parser::NT_SQRT, stabilizer::parser::NT_STR_FROM_CODE, stabilizer::parser::NT_STR_FROM_INT, stabilizer::parser::NT_STR_IS_DIGIT, stabilizer::parser::NT_STR_LEN, stabilizer::parser::NT_STR_REV, stabilizer::parser::NT_STR_TO_CODE, stabilizer::parser::NT_STR_TO_INT, stabilizer::parser::NT_STR_TO_LOWER, stabilizer::parser::NT_STR_TO_REG, stabilizer::parser::NT_STR_TO_UPPER, stabilizer::parser::NT_TAN, stabilizer::parser::NT_TANH, stabilizer::parser::NT_TO_INT, stabilizer::parser::NT_TO_REAL, stabilizer::parser::NT_UBV_TO_INT, stabilizer::parser::MathUtils::pow(), stabilizer::parser::StringUtils::strRev(), stabilizer::parser::StringUtils::strToLower(), stabilizer::parser::StringUtils::strToUpper(), stabilizer::parser::StringUtils::strUnquate(), toInt(), and toReal().
Referenced by rewrite(), and rewrite_oper().
rewrite() [5/5]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::rewrite (NODE_KIND & t, std::vector< std::shared_ptr< DAGNode >> & p)
Rewrite variadic operation node when simplification rule applies.
Parameters
t Operation kind (may be updated during rewrite).
p Operand list.
Returns
Rewritten node, or nullptr when no rewrite is applied.
Definition at line 1019 of file rewrite_parser.cpp.
References stabilizer::parser::BitVectorUtils::bvAdd(), stabilizer::parser::BitVectorUtils::bvAnd(), stabilizer::parser::BitVectorUtils::bvConcat(), stabilizer::parser::BitVectorUtils::bvMul(), stabilizer::parser::BitVectorUtils::bvOr(), stabilizer::parser::BitVectorUtils::bvXor(), stabilizer::parser::echo_error(), getEvaluateUseFloating(), stabilizer::parser::BitVectorUtils::intToBv(), isOne(), isOnes(), isZero(), stabilizer::parser::kindToString(), mkBvZeroExt(), mkConstBv(), mkConstInt(), mkConstReal(), mkConstStr(), mkFalse(), stabilizer::parser::BitVectorUtils::mkOnes(), mkTrue(), stabilizer::parser::NT_ADD, stabilizer::parser::NT_AND, stabilizer::parser::NT_BV_ADD, stabilizer::parser::NT_BV_AND, stabilizer::parser::NT_BV_COMP, stabilizer::parser::NT_BV_CONCAT, stabilizer::parser::NT_BV_MUL, stabilizer::parser::NT_BV_OR, stabilizer::parser::NT_BV_SADDO, stabilizer::parser::NT_BV_SMULO, stabilizer::parser::NT_BV_UADDO, stabilizer::parser::NT_BV_UMULO, stabilizer::parser::NT_BV_XOR, stabilizer::parser::NT_DISTINCT, stabilizer::parser::NT_DISTINCT_BOOL, stabilizer::parser::NT_DISTINCT_OTHER, stabilizer::parser::NT_DIV_INT, stabilizer::parser::NT_DIV_REAL, stabilizer::parser::NT_EQ, stabilizer::parser::NT_EQ_BOOL, stabilizer::parser::NT_EQ_OTHER, stabilizer::parser::NT_EXISTS, stabilizer::parser::NT_FORALL, stabilizer::parser::NT_FP_EQ, stabilizer::parser::NT_FP_GE, stabilizer::parser::NT_FP_GT, stabilizer::parser::NT_FP_LE, stabilizer::parser::NT_FP_LT, stabilizer::parser::NT_GE, stabilizer::parser::NT_GT, stabilizer::parser::NT_IAND, stabilizer::parser::NT_IMPLIES, stabilizer::parser::NT_LE, stabilizer::parser::NT_LT, stabilizer::parser::NT_MAX, stabilizer::parser::NT_MIN, stabilizer::parser::NT_MUL, stabilizer::parser::NT_OR, stabilizer::parser::NT_REG_CONCAT, stabilizer::parser::NT_REG_DIFF, stabilizer::parser::NT_REG_INTER, stabilizer::parser::NT_REG_UNION, stabilizer::parser::NT_STR_CONCAT, stabilizer::parser::NT_STR_GE, stabilizer::parser::NT_STR_GT, stabilizer::parser::NT_STR_LE, stabilizer::parser::NT_STR_LT, stabilizer::parser::NT_SUB, stabilizer::parser::NT_XOR, rewrite(), toInt(), and toReal().
rewrite_oper()
std::shared_ptr< DAGNode > stabilizer::parser::Parser::rewrite_oper (NODE_KIND & t, std::vector< std::shared_ptr< DAGNode >> & p)
Core operation rewrite helper used before node-manager creation.
Parameters
t Operation kind (may be updated during rewrite).
p Operand list.
Returns
Rewritten node, or nullptr when caller should create a fresh node.
Definition at line 1865 of file rewrite_parser.cpp.
References getArity(), stabilizer::parser::NT_ABS, stabilizer::parser::NT_ACOS, stabilizer::parser::NT_ACOSH, stabilizer::parser::NT_ACOT, stabilizer::parser::NT_ACOTH, stabilizer::parser::NT_ACSC, stabilizer::parser::NT_ACSCH, stabilizer::parser::NT_ADD, stabilizer::parser::NT_AND, stabilizer::parser::NT_ASEC, stabilizer::parser::NT_ASECH, stabilizer::parser::NT_ASIN, stabilizer::parser::NT_ASINH, stabilizer::parser::NT_ATAN, stabilizer::parser::NT_ATAN2, stabilizer::parser::NT_ATANH, stabilizer::parser::NT_BV_ADD, stabilizer::parser::NT_BV_AND, stabilizer::parser::NT_BV_ASHR, stabilizer::parser::NT_BV_COMP, stabilizer::parser::NT_BV_CONCAT, stabilizer::parser::NT_BV_EXTRACT, stabilizer::parser::NT_BV_LSHR, stabilizer::parser::NT_BV_MUL, stabilizer::parser::NT_BV_NAND, stabilizer::parser::NT_BV_NEG, stabilizer::parser::NT_BV_NEGO, stabilizer::parser::NT_BV_NOR, stabilizer::parser::NT_BV_NOT, stabilizer::parser::NT_BV_OR, stabilizer::parser::NT_BV_REPEAT, stabilizer::parser::NT_BV_ROTATE_LEFT, stabilizer::parser::NT_BV_ROTATE_RIGHT, stabilizer::parser::NT_BV_SADDO, stabilizer::parser::NT_BV_SDIV, stabilizer::parser::NT_BV_SDIVO, stabilizer::parser::NT_BV_SGE, stabilizer::parser::NT_BV_SGT, stabilizer::parser::NT_BV_SHL, stabilizer::parser::NT_BV_SIGN_EXT, stabilizer::parser::NT_BV_SLE, stabilizer::parser::NT_BV_SLT, stabilizer::parser::NT_BV_SMOD, stabilizer::parser::NT_BV_SMODO, stabilizer::parser::NT_BV_SMULO, stabilizer::parser::NT_BV_SREM, stabilizer::parser::NT_BV_SREMO, stabilizer::parser::NT_BV_SUB, stabilizer::parser::NT_BV_TO_INT, stabilizer::parser::NT_BV_TO_NAT, stabilizer::parser::NT_BV_UADDO, stabilizer::parser::NT_BV_UDIV, stabilizer::parser::NT_BV_UDIVO, stabilizer::parser::NT_BV_UGE, stabilizer::parser::NT_BV_UGT, stabilizer::parser::NT_BV_ULE, stabilizer::parser::NT_BV_ULT, stabilizer::parser::NT_BV_UMOD, stabilizer::parser::NT_BV_UMODO, stabilizer::parser::NT_BV_UMULO, stabilizer::parser::NT_BV_UREM, stabilizer::parser::NT_BV_UREMO, stabilizer::parser::NT_BV_XNOR, stabilizer::parser::NT_BV_XOR, stabilizer::parser::NT_BV_ZERO_EXT, stabilizer::parser::NT_CEIL, stabilizer::parser::NT_CONST, stabilizer::parser::NT_CONST_ARRAY, stabilizer::parser::NT_CONST_E, stabilizer::parser::NT_CONST_FALSE, stabilizer::parser::NT_CONST_PI, stabilizer::parser::NT_CONST_TRUE, stabilizer::parser::NT_COS, stabilizer::parser::NT_COSH, stabilizer::parser::NT_COT, stabilizer::parser::NT_COTH, stabilizer::parser::NT_CSC, stabilizer::parser::NT_CSCH, stabilizer::parser::NT_DISTINCT, stabilizer::parser::NT_DISTINCT_BOOL, stabilizer::parser::NT_DISTINCT_OTHER, stabilizer::parser::NT_DIV_INT, stabilizer::parser::NT_DIV_REAL, stabilizer::parser::NT_EPSILON, stabilizer::parser::NT_EQ, stabilizer::parser::NT_EQ_BOOL, stabilizer::parser::NT_EQ_OTHER, stabilizer::parser::NT_EXISTS, stabilizer::parser::NT_EXP, stabilizer::parser::NT_FACT, stabilizer::parser::NT_FLOOR, stabilizer::parser::NT_FORALL, stabilizer::parser::NT_FP_ABS, stabilizer::parser::NT_FP_ADD, stabilizer::parser::NT_FP_DIV, stabilizer::parser::NT_FP_EQ, stabilizer::parser::NT_FP_FMA, stabilizer::parser::NT_FP_GE, stabilizer::parser::NT_FP_GT, stabilizer::parser::NT_FP_IS_INF, stabilizer::parser::NT_FP_IS_NAN, stabilizer::parser::NT_FP_IS_NEG, stabilizer::parser::NT_FP_IS_NORMAL, stabilizer::parser::NT_FP_IS_POS, stabilizer::parser::NT_FP_IS_SUBNORMAL, stabilizer::parser::NT_FP_IS_ZERO, stabilizer::parser::NT_FP_LE, stabilizer::parser::NT_FP_LT, stabilizer::parser::NT_FP_MAX, stabilizer::parser::NT_FP_MIN, stabilizer::parser::NT_FP_MUL, stabilizer::parser::NT_FP_NEG, stabilizer::parser::NT_FP_REM, stabilizer::parser::NT_FP_ROUND_TO_INTEGRAL, stabilizer::parser::NT_FP_SQRT, stabilizer::parser::NT_FP_SUB, stabilizer::parser::NT_FP_TO_FP, stabilizer::parser::NT_FP_TO_REAL, stabilizer::parser::NT_FP_TO_SBV, stabilizer::parser::NT_FP_TO_UBV, stabilizer::parser::NT_GCD, stabilizer::parser::NT_GE, stabilizer::parser::NT_GT, stabilizer::parser::NT_IAND, stabilizer::parser::NT_IMPLIES, stabilizer::parser::NT_INFINITY, stabilizer::parser::NT_INT_TO_BV, stabilizer::parser::NT_IS_DIVISIBLE, stabilizer::parser::NT_IS_EVEN, stabilizer::parser::NT_IS_INT, stabilizer::parser::NT_IS_ODD, stabilizer::parser::NT_IS_PRIME, stabilizer::parser::NT_ITE, stabilizer::parser::NT_LB, stabilizer::parser::NT_LCM, stabilizer::parser::NT_LE, stabilizer::parser::NT_LG, stabilizer::parser::NT_LN, stabilizer::parser::NT_LOG, stabilizer::parser::NT_LT, stabilizer::parser::NT_MAX, stabilizer::parser::NT_MIN, stabilizer::parser::NT_MOD, stabilizer::parser::NT_MUL, stabilizer::parser::NT_NAN, stabilizer::parser::NT_NAT_TO_BV, stabilizer::parser::NT_NEG, stabilizer::parser::NT_NEG_EPSILON, stabilizer::parser::NT_NEG_INFINITY, stabilizer::parser::NT_NOT, stabilizer::parser::NT_NULL, stabilizer::parser::NT_OR, stabilizer::parser::NT_POS_EPSILON, stabilizer::parser::NT_POS_INFINITY, stabilizer::parser::NT_POW, stabilizer::parser::NT_POW2, stabilizer::parser::NT_QUANT_VAR, stabilizer::parser::NT_REG_ALL, stabilizer::parser::NT_REG_ALLCHAR, stabilizer::parser::NT_REG_COMPLEMENT, stabilizer::parser::NT_REG_CONCAT, stabilizer::parser::NT_REG_DIFF, stabilizer::parser::NT_REG_INTER, stabilizer::parser::NT_REG_LOOP, stabilizer::parser::NT_REG_NONE, stabilizer::parser::NT_REG_OPT, stabilizer::parser::NT_REG_PLUS, stabilizer::parser::NT_REG_RANGE, stabilizer::parser::NT_REG_REPEAT, stabilizer::parser::NT_REG_STAR, stabilizer::parser::NT_REG_UNION, stabilizer::parser::NT_ROUND, stabilizer::parser::NT_SAFESQRT, stabilizer::parser::NT_SBV_TO_INT, stabilizer::parser::NT_SEC, stabilizer::parser::NT_SECH, stabilizer::parser::NT_SELECT, stabilizer::parser::NT_SIN, stabilizer::parser::NT_SINH, stabilizer::parser::NT_SQRT, stabilizer::parser::NT_STORE, stabilizer::parser::NT_STR_CHARAT, stabilizer::parser::NT_STR_CONCAT, stabilizer::parser::NT_STR_CONTAINS, stabilizer::parser::NT_STR_FROM_CODE, stabilizer::parser::NT_STR_FROM_INT, stabilizer::parser::NT_STR_GE, stabilizer::parser::NT_STR_GT, stabilizer::parser::NT_STR_IN_REG, stabilizer::parser::NT_STR_INDEXOF, stabilizer::parser::NT_STR_INDEXOF_REG, stabilizer::parser::NT_STR_IS_DIGIT, stabilizer::parser::NT_STR_LE, stabilizer::parser::NT_STR_LEN, stabilizer::parser::NT_STR_LT, stabilizer::parser::NT_STR_NUM_SPLITS_RE, stabilizer::parser::NT_STR_PREFIXOF, stabilizer::parser::NT_STR_REPLACE, stabilizer::parser::NT_STR_REPLACE_ALL, stabilizer::parser::NT_STR_REPLACE_REG, stabilizer::parser::NT_STR_REPLACE_REG_ALL, stabilizer::parser::NT_STR_REV, stabilizer::parser::NT_STR_SPLIT, stabilizer::parser::NT_STR_SPLIT_AT, stabilizer::parser::NT_STR_SPLIT_AT_RE, stabilizer::parser::NT_STR_SPLIT_REST, stabilizer::parser::NT_STR_SPLIT_REST_RE, stabilizer::parser::NT_STR_SUBSTR, stabilizer::parser::NT_STR_SUFFIXOF, stabilizer::parser::NT_STR_TO_CODE, stabilizer::parser::NT_STR_TO_INT, stabilizer::parser::NT_STR_TO_LOWER, stabilizer::parser::NT_STR_TO_REG, stabilizer::parser::NT_STR_TO_UPPER, stabilizer::parser::NT_STR_UPDATE, stabilizer::parser::NT_SUB, stabilizer::parser::NT_TAN, stabilizer::parser::NT_TANH, stabilizer::parser::NT_TEMP_VAR, stabilizer::parser::NT_TO_INT, stabilizer::parser::NT_TO_REAL, stabilizer::parser::NT_UBV_TO_INT, stabilizer::parser::NT_VAR, stabilizer::parser::NT_XOR, options, and rewrite().
Referenced by mkInternalOper(), and mkNode().
scanToNextSymbol()
void stabilizer::parser::Parser::scanToNextSymbol () private
Definition at line 533 of file base_parser.cpp.
References bufptr, line_number, scan_mode, stabilizer::parser::SM_COMMENT, stabilizer::parser::SM_COMMON, stabilizer::parser::SM_COMP_SYM, stabilizer::parser::SM_STRING, and stabilizer::parser::SM_SYMBOL.
Referenced by getSymbol(), mkExpr(), parseCommand(), parseExpr(), parseLpar(), parseRpar(), parseSmtlib2File(), parseSort(), parseStr(), and peekSymbol().
setEvaluatePrecision()
void stabilizer::parser::Parser::setEvaluatePrecision (mpfr_prec_t precision)
Set the precision for evaluation.
Parameters
precision Precision
Definition at line 278 of file base_parser.cpp.
References options.
setEvaluateUseFloating()
void stabilizer::parser::Parser::setEvaluateUseFloating (bool use_floating)
Set the use floating for evaluation.
Parameters
use_floating Use floating
Definition at line 284 of file base_parser.cpp.
References options.
setOption() [1/4]
void stabilizer::parser::Parser::setOption (const std::string & key, const bool & value)
Definition at line 232 of file base_parser.cpp.
References options.
setOption() [2/4]
void stabilizer::parser::Parser::setOption (const std::string & key, const double & value)
Definition at line 229 of file base_parser.cpp.
References options.
setOption() [3/4]
void stabilizer::parser::Parser::setOption (const std::string & key, const int & value)
Definition at line 226 of file base_parser.cpp.
References options.
setOption() [4/4]
void stabilizer::parser::Parser::setOption (const std::string & key, const std::string & value)
Set global options.
Parameters
key Option name
value Option value
Definition at line 223 of file base_parser.cpp.
References options.
skipToRpar()
void stabilizer::parser::Parser::skipToRpar () private
Definition at line 593 of file base_parser.cpp.
References bufptr, line_number, scan_mode, stabilizer::parser::SM_COMMENT, stabilizer::parser::SM_COMMON, stabilizer::parser::SM_COMP_SYM, and stabilizer::parser::SM_STRING.
Referenced by parseCommand().
sortParams()
std::vector< std::shared_ptr< DAGNode > > stabilizer::parser::Parser::sortParams (const std::vector< std::shared_ptr< DAGNode >> & p) static
Return sorted operand list for deterministic commutative handling.
Definition at line 173 of file op_parser.cpp.
Referenced by mkInternalOper(), and mkNode().
substitute() [1/2]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::substitute (std::shared_ptr< DAGNode > expr, std::unordered_map< std::string, std::shared_ptr< DAGNode >> & params)
Substitute variables in an expression.
Note
This function is used to substitute variables in an expression but not simplify the expression.
Parameters
expr Expression to substitute
params Map of variable names to their corresponding values
Returns
Substituted expression
Definition at line 2366 of file base_parser.cpp.
substitute() [2/2]
std::shared_ptr< DAGNode > stabilizer::parser::Parser::substitute (std::shared_ptr< DAGNode > expr, std::unordered_map< std::string, std::shared_ptr< DAGNode >> & params, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> & visited) private
Definition at line 2374 of file base_parser.cpp.
References mkOper(), and node_manager.
toCNF()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::toCNF (std::shared_ptr< DAGNode > expr) private
toDNFEliminateAll() [1/2]
std::shared_ptr<DAGNode> stabilizer::parser::Parser::toDNFEliminateAll (std::shared_ptr< DAGNode > expr) private
toDNFEliminateAll() [2/2]
std::shared_ptr<DAGNode> stabilizer::parser::Parser::toDNFEliminateAll (std::shared_ptr< DAGNode > expr, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> & visited, bool & is_changed) private
toDNFEliminateDistinct()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::toDNFEliminateDistinct (const std::vector< std::shared_ptr< DAGNode >> & children) private
toDNFEliminateEq()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::toDNFEliminateEq (const std::vector< std::shared_ptr< DAGNode >> & children) private
toDNFEliminateXOR()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::toDNFEliminateXOR (const std::vector< std::shared_ptr< DAGNode >> & children) private
toInt()
Integer stabilizer::parser::Parser::toInt (std::shared_ptr< DAGNode > expr)
Convert an expression to an integer.
Parameters
expr Expression to convert
Returns
Integer
Definition at line 300 of file base_parser.cpp.
References condAssert, and ensureNumberValue().
Referenced by isOne(), isZero(), mkBvExtract(), mkBvRepeat(), mkBvSignExt(), mkBvZeroExt(), mkFpToSbv(), mkFpToUbv(), mkIand(), mkIntToBv(), mkMul(), mkNatToBv(), mkSub(), mkToFp(), mkToFpUnsigned(), and rewrite().
toNNF()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::toNNF (std::shared_ptr< DAGNode > expr, bool is_not) private
toReal()
Real stabilizer::parser::Parser::toReal (std::shared_ptr< DAGNode > expr)
Convert an expression to a real.
Parameters
expr Expression to convert
Returns
Real
Definition at line 290 of file base_parser.cpp.
References condAssert, stabilizer::parser::HighPrecisionReal::e(), ensureNumberValue(), getEvaluatePrecision(), and stabilizer::parser::HighPrecisionReal::pi().
Referenced by isOne(), isZero(), mkMul(), mkSub(), and rewrite().
toString() [1/3]
std::string stabilizer::parser::Parser::toString (const NODE_KIND & kind)
Print a node kind.
Parameters
kind Node kind to print
Returns
String representation of the node kind
Definition at line 2684 of file base_parser.cpp.
References stabilizer::parser::kindToString().
toString() [2/3]
std::string stabilizer::parser::Parser::toString (std::shared_ptr< DAGNode > expr)
Print an expression.
Parameters
expr Expression to print
Returns
String representation of the expression
Definition at line 2676 of file base_parser.cpp.
References stabilizer::parser::dumpSMTLIB2().
Referenced by mkRootObj(), and mkRootOfWithInterval().
toString() [3/3]
std::string stabilizer::parser::Parser::toString (std::shared_ptr< Sort > sort)
Print a sort.
Parameters
sort Sort to print
Returns
String representation of the sort
Definition at line 2680 of file base_parser.cpp.
toTseitinCNF()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::toTseitinCNF (std::shared_ptr< DAGNode > expr, std::unordered_map< std::shared_ptr< DAGNode >, std::shared_ptr< DAGNode >> & visited, std::vector< std::shared_ptr< DAGNode >> & clauses) private
toTseitinDistinct()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::toTseitinDistinct (std::shared_ptr< DAGNode > a, std::shared_ptr< DAGNode > b, std::vector< std::shared_ptr< DAGNode >> & clauses) private
toTseitinEq()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::toTseitinEq (std::shared_ptr< DAGNode > a, std::shared_ptr< DAGNode > b, std::vector< std::shared_ptr< DAGNode >> & clauses) private
toTseitinXor()
std::shared_ptr<DAGNode> stabilizer::parser::Parser::toTseitinXor (std::shared_ptr< DAGNode > a, std::shared_ptr< DAGNode > b, std::vector< std::shared_ptr< DAGNode >> & clauses) private
warn_cmd_nsup()
void stabilizer::parser::Parser::warn_cmd_nsup (const std::string nm, const size_t ln) const private
Definition at line 3015 of file base_parser.cpp.
Referenced by parseCommand().
Member Data Documentation
allow_placeholder_vars
bool stabilizer::parser::Parser::allow_placeholder_vars private
Definition at line 194 of file parser.h.
Referenced by parseConstFunc(), parseExpr(), and Parser().
assertion_groups
std::unordered_map<std::string, std::unordered_set<size_t> > stabilizer::parser::Parser::assertion_groups
Definition at line 266 of file parser.h.
Referenced by getGroupedAssertions(), and parseCommand().
assertions
std::vector<std::shared_ptr<DAGNode> > stabilizer::parser::Parser::assertions
Definition at line 265 of file parser.h.
Referenced by assert(), checkSat(), dumpSMT2(), getAssertions(), getNodeCount(), parseCommand(), and replaceAssertions().
assumptions
std::vector<std::vector<std::shared_ptr<DAGNode> > > stabilizer::parser::Parser::assumptions
Definition at line 273 of file parser.h.
Referenced by getAssumptions(), getNodeCount(), and parseCommand().
buffer
char* stabilizer::parser::Parser::buffer private
Definition at line 184 of file parser.h.
Referenced by getSymbol(), mkExpr(), Parser(), parseSmtlib2File(), and parseStr().
buflen
unsigned long stabilizer::parser::Parser::buflen private
Definition at line 185 of file parser.h.
Referenced by getSymbol(), mkExpr(), Parser(), parseSmtlib2File(), and parseStr().
bufptr
char* stabilizer::parser::Parser::bufptr private
Definition at line 186 of file parser.h.
Referenced by attemptParseKeywords(), getSymbol(), mkExpr(), parseCommand(), parseExpr(), parseLet(), parseLpar(), parseParams(), parsePreservingLet(), parseQuant(), Parser(), parseRpar(), parseSmtlib2File(), parseSort(), parseStr(), peekSymbol(), scanToNextSymbol(), and skipToRpar().
cnf_atom_map
std::unordered_map<std::shared_ptr<DAGNode>, std::shared_ptr<DAGNode> > stabilizer::parser::Parser::cnf_atom_map private
Definition at line 250 of file parser.h.
cnf_bool_var_map
std::unordered_map<std::shared_ptr<DAGNode>, std::shared_ptr<DAGNode> > stabilizer::parser::Parser::cnf_bool_var_map private
Definition at line 252 of file parser.h.
cnf_map
std::unordered_map<std::shared_ptr<DAGNode>, std::shared_ptr<DAGNode> > stabilizer::parser::Parser::cnf_map private
Definition at line 248 of file parser.h.
current_let_mode
LET_MODE stabilizer::parser::Parser::current_let_mode private
Definition at line 190 of file parser.h.
Referenced by parseConstFunc(), and parseExpr().
datatype_blocks
std::vector<std::vector<DTTypeDecl> > stabilizer::parser::Parser::datatype_blocks private
Definition at line 222 of file parser.h.
Referenced by dumpSMT2(), getDatatypeBlocks(), and parseCommand().
datatype_function_names
std::unordered_set<std::string> stabilizer::parser::Parser::datatype_function_names private
Definition at line 227 of file parser.h.
Referenced by applyFun(), parseCommand(), and parseConstFunc().
datatype_sort_names
std::unordered_set<std::string> stabilizer::parser::Parser::datatype_sort_names private
Definition at line 224 of file parser.h.
Referenced by parseCommand().
dnf_map
std::unordered_map<std::shared_ptr<DAGNode>, std::shared_ptr<DAGNode> > stabilizer::parser::Parser::dnf_map private
Definition at line 254 of file parser.h.
fun_dup_count_map
std::unordered_map<std::string, size_t> stabilizer::parser::Parser::fun_dup_count_map private
Definition at line 216 of file parser.h.
Referenced by mkFuncDec().
fun_key_map
std::unordered_map<std::string, std::shared_ptr<DAGNode> > stabilizer::parser::Parser::fun_key_map private
Definition at line 209 of file parser.h.
Referenced by getFunctions(), getFunKeyMap(), getKind(), isDeclaredFunction(), mkFuncDec(), mkFuncDef(), mkFuncRec(), parseCommand(), parseConstFunc(), parseOper(), Parser(), and removeFuns().
fun_var_map
std::unordered_map<std::string, std::shared_ptr<DAGNode> > stabilizer::parser::Parser::fun_var_map private
Definition at line 211 of file parser.h.
Referenced by parseCommand(), parseConstFunc(), and Parser().
function_names
std::vector<std::string> stabilizer::parser::Parser::function_names private
Definition at line 240 of file parser.h.
Referenced by getFunctionNames(), getFunctions(), parseCommand(), Parser(), and removeFuns().
in_quantifier_scope
bool stabilizer::parser::Parser::in_quantifier_scope private
Definition at line 193 of file parser.h.
Referenced by parseCommand(), parseConstFunc(), parseExpr(), and Parser().
let_key_map
std::unordered_map<std::string, std::shared_ptr<DAGNode> > stabilizer::parser::Parser::let_key_map private
Definition at line 206 of file parser.h.
Referenced by parseConstFunc(), parseLet(), and Parser().
let_nesting_depth
size_t stabilizer::parser::Parser::let_nesting_depth private
Definition at line 191 of file parser.h.
Referenced by parseExpr(), and Parser().
line_number
size_t stabilizer::parser::Parser::line_number private
Definition at line 187 of file parser.h.
Referenced by ensureNumberValue(), getSymbol(), mkAbs(), mkAdd(), mkAnd(), mkBvAdd(), mkBvAnd(), mkBvAshr(), mkBvConcat(), mkBvExtract(), mkBvLshr(), mkBvMul(), mkBvNot(), mkBvOr(), mkBvRepeat(), mkBvRotateLeft(), mkBvRotateRight(), mkBvSdiv(), mkBvSge(), mkBvSgt(), mkBvShl(), mkBvSignExt(), mkBvSle(), mkBvSlt(), mkBvSmod(), mkBvSrem(), mkBvToInt(), mkBvToNat(), mkBvUdiv(), mkBvUge(), mkBvUgt(), mkBvUle(), mkBvUlt(), mkBvUmod(), mkBvUrem(), mkBvXor(), mkBvZeroExt(), mkCeil(), mkConstArray(), mkDistinct(), mkDivInt(), mkDivReal(), mkEq(), mkExpr(), mkFact(), mkFpAbs(), mkFpAdd(), mkFpConst(), mkFpDiv(), mkFpFma(), mkFpIsInf(), mkFpIsNaN(), mkFpIsNeg(), mkFpIsNormal(), mkFpIsPos(), mkFpIsSubnormal(), mkFpIsZero(), mkFpMul(), mkFpNeg(), mkFpRem(), mkFpRoundToIntegral(), mkFpSqrt(), mkFpSub(), mkFpToReal(), mkFpToSbv(), mkFpToUbv(), mkFuncDef(), mkFuncRec(), mkGcd(), mkGe(), mkGt(), mkIand(), mkImplies(), mkIndexofReg(), mkInfinity(), mkIntToBv(), mkIsDivisible(), mkIsEven(), mkIsInt(), mkIsOdd(), mkIsPrime(), mkIte(), mkLcm(), mkLe(), mkLog(), mkLt(), mkMax(), mkMin(), mkMod(), mkMul(), mkNatToBv(), mkNegInfinity(), mkNot(), mkOper(), mkOr(), mkPosInfinity(), mkRegComplement(), mkRegConcat(), mkRegDiff(), mkRegInter(), mkRegLoop(), mkRegOpt(), mkRegPlus(), mkRegRange(), mkRegRepeat(), mkRegStar(), mkRegUnion(), mkReplaceReg(), mkReplaceRegAll(), mkSafeSqrt(), mkSbvToInt(), mkSelect(), mkSqrt(), mkStrCharat(), mkStrConcat(), mkStrContains(), mkStrFromCode(), mkStrFromInt(), mkStrIndexof(), mkStrIndexofReg(), mkStrInReg(), mkStrIsDigit(), mkStrLen(), mkStrNumSplits(), mkStrNumSplitsRe(), mkStrPrefixof(), mkStrReplace(), mkStrReplaceAll(), mkStrReplaceReg(), mkStrReplaceRegAll(), mkStrRev(), mkStrSplit(), mkStrSplitAt(), mkStrSplitAtRe(), mkStrSplitRest(), mkStrSplitRestRe(), mkStrSubstr(), mkStrSuffixof(), mkStrToCode(), mkStrToInt(), mkStrToLower(), mkStrToReg(), mkStrToUpper(), mkStrUpdate(), mkSub(), mkTempVar(), mkToFp(), mkToFpUnsigned(), mkToInt(), mkToReal(), mkUbvToInt(), parseCommand(), parseConstFunc(), parseExpr(), parseKeyword(), parseLet(), parseLpar(), parseOper(), parsePreservingLet(), Parser(), parseRpar(), parseSmtlib2File(), parseSort(), parseStr(), peekSymbol(), rewrite(), scanToNextSymbol(), and skipToRpar().
named_assertions
std::unordered_map<std::string, std::shared_ptr<DAGNode> > stabilizer::parser::Parser::named_assertions
Definition at line 268 of file parser.h.
Referenced by parseCommand(), and parseExpr().
nnf_map
std::unordered_map<std::shared_ptr<DAGNode>, std::shared_ptr<DAGNode> > stabilizer::parser::Parser::nnf_map private
Definition at line 256 of file parser.h.
node_manager
std::unique_ptr<NodeManager> stabilizer::parser::Parser::node_manager private
Definition at line 201 of file parser.h.
Referenced by applyFun(), getDeclaredVariables(), getNodeManager(), getVariable(), getVariables(), mkApplyDTFun(), mkApplyUF(), mkAttribute(), mkConstArray(), mkConstBv(), mkConstFp(), mkConstFP(), mkConstInt(), mkConstReal(), mkConstReg(), mkConstStr(), mkErr(), mkFpConst(), mkFuncDec(), mkFuncDef(), mkFuncRec(), mkFunParamVar(), mkInternalOper(), mkLetBindVar(), mkLetBindVarList(), mkLetChain(), mkNaN(), mkNegInfinity(), mkNode(), mkNoPattern(), mkPattern(), mkPlaceholderVar(), mkPosInfinity(), mkQuantVar(), mkRootObj(), mkRootOfWithInterval(), mkRoundingMode(), mkTempVar(), mkUFVNode(), mkVar(), mkWeight(), parseConstFunc(), parseExpr(), parseOper(), Parser(), rebuild_node_manager(), and substitute().
num_quant_vars
size_t stabilizer::parser::Parser::num_quant_vars = 0 private
Definition at line 262 of file parser.h.
Referenced by mkQuantVar().
options
std::shared_ptr<GlobalOptions> stabilizer::parser::Parser::options private
Definition at line 242 of file parser.h.
Referenced by applyFun(), applyFunPostOrder(), dumpSMT2(), getEvaluatePrecision(), getEvaluateUseFloating(), getOptions(), mkAdd(), mkIand(), mkMul(), mkSub(), optionToString(), parseCommand(), parseConstFunc(), parseExpr(), Parser(), rewrite_oper(), setEvaluatePrecision(), setEvaluateUseFloating(), and setOption().
parse_options
std::vector<std::string> stabilizer::parser::Parser::parse_options private
Definition at line 198 of file parser.h.
Referenced by dumpSMT2(), and parseCommand().
parsing_file
bool stabilizer::parser::Parser::parsing_file private
Definition at line 197 of file parser.h.
Referenced by assert(), getSymbol(), mkExpr(), Parser(), and parseSmtlib2File().
pattern_assertions
std::vector<std::pair<std::shared_ptr<DAGNode>, std::vector<std::vector<std::shared_ptr<DAGNode> > > > > stabilizer::parser::Parser::pattern_assertions
Definition at line 272 of file parser.h.
placeholder_var_names
std::unordered_map<std::string, size_t> stabilizer::parser::Parser::placeholder_var_names private
Definition at line 236 of file parser.h.
Referenced by mkPlaceholderVar(), and parseConstFunc().
placeholder_var_sort
std::shared_ptr<Sort> stabilizer::parser::Parser::placeholder_var_sort private
Definition at line 195 of file parser.h.
Referenced by mkPlaceholderVar(), parseExpr(), and Parser().
preserving_let_counter
size_t stabilizer::parser::Parser::preserving_let_counter private
Definition at line 189 of file parser.h.
Referenced by parseConstFunc(), parseExpr(), parsePreservingLet(), and Parser().
preserving_let_key_map
std::unordered_map<std::string, std::shared_ptr<DAGNode> > stabilizer::parser::Parser::preserving_let_key_map private
Definition at line 208 of file parser.h.
Referenced by clear_let_key_map(), mkLetBindVar(), parseConstFunc(), parsePreservingLet(), and Parser().
quant_nesting_depth
size_t stabilizer::parser::Parser::quant_nesting_depth private
Definition at line 192 of file parser.h.
Referenced by parseCommand(), parseExpr(), and Parser().
quant_var_map
std::unordered_map<std::string, std::vector<std::shared_ptr<DAGNode> > > stabilizer::parser::Parser::quant_var_map private
Definition at line 214 of file parser.h.
Referenced by mkQuantVar(), parseConstFunc(), parseQuant(), and Parser().
result_node
std::shared_ptr<DAGNode> stabilizer::parser::Parser::result_node private
Definition at line 260 of file parser.h.
Referenced by getResult().
result_type
RESULT_TYPE stabilizer::parser::Parser::result_type private
Definition at line 259 of file parser.h.
Referenced by checkSat(), and getResultType().
scan_mode
SCAN_MODE stabilizer::parser::Parser::scan_mode private
Definition at line 188 of file parser.h.
Referenced by getSymbol(), parseCommand(), Parser(), peekSymbol(), scanToNextSymbol(), and skipToRpar().
soft_assertion_groups
std::unordered_map<std::string, std::unordered_set<size_t> > stabilizer::parser::Parser::soft_assertion_groups
Definition at line 277 of file parser.h.
Referenced by getGroupedSoftAssertions().
soft_assertions
std::vector<std::shared_ptr<DAGNode> > stabilizer::parser::Parser::soft_assertions
Definition at line 274 of file parser.h.
Referenced by getNodeCount(), and getSoftAssertions().
soft_weights
std::vector<std::shared_ptr<DAGNode> > stabilizer::parser::Parser::soft_weights
Definition at line 275 of file parser.h.
Referenced by getNodeCount(), and getSoftWeights().
sort_key_map
std::unordered_map<std::string, std::shared_ptr<Sort> > stabilizer::parser::Parser::sort_key_map private
Definition at line 212 of file parser.h.
Referenced by declareVar(), dumpSMT2(), getSortNames(), mkArray(), mkConstBv(), mkConstFp(), mkVarBv(), mkVarFp(), parseCommand(), Parser(), and parseSort().
sort_manager
std::unique_ptr<SortManager> stabilizer::parser::Parser::sort_manager private
Definition at line 203 of file parser.h.
Referenced by mkArray(), mkArraySort(), mkBvComp(), mkBvConcat(), mkBvExtract(), mkBvRepeat(), mkBvRotateLeft(), mkBvRotateRight(), mkBvSignExt(), mkBVSort(), mkBvZeroExt(), mkConstBv(), mkConstFp(), mkFpConst(), mkFPSort(), mkFpToSbv(), mkFpToUbv(), mkIntToBv(), mkNatToBv(), mkSortDec(), mkSortDef(), mkStrSplit(), mkToFp(), mkToFpUnsigned(), mkVarBv(), mkVarFp(), parseCommand(), parseExpr(), parseOper(), Parser(), and parseSort().
split_lemmas
std::vector<std::shared_ptr<DAGNode> > stabilizer::parser::Parser::split_lemmas
Definition at line 279 of file parser.h.
static_functions
std::vector<std::shared_ptr<DAGNode> > stabilizer::parser::Parser::static_functions private
Definition at line 218 of file parser.h.
Referenced by mkApplyFunc(), mkApplyRecFunc(), and Parser().
temp_var_counter
size_t stabilizer::parser::Parser::temp_var_counter private
Definition at line 233 of file parser.h.
Referenced by mkTempVar(), and Parser().
temp_var_names
std::unordered_map<std::string, size_t> stabilizer::parser::Parser::temp_var_names private
Definition at line 234 of file parser.h.
Referenced by getTempVarNames(), getVariable(), getVariables(), mkTempVar(), Parser(), and rename().
var_names
std::unordered_map<std::string, size_t> stabilizer::parser::Parser::var_names private
Definition at line 231 of file parser.h.
Referenced by getDeclaredVariables(), getVariable(), getVariables(), getVarNames(), isDeclaredVariable(), mkVar(), parseConstFunc(), Parser(), and rename().
The documentation for this class was generated from the following files:
src/parser/parser.h
src/parser/base_parser.cpp
src/parser/expr_parser.cpp
src/parser/op_parser.cpp
src/parser/opt_parser.cpp
src/parser/rewrite_parser.cpp