SMTStabilizer API: stabilizer::parser::Number Class Reference
stabilizer::parser::Number Class Reference
#include <number.h>
Public Types
enum Type { INT_TYPE, REAL_TYPE, UNKNOWN_TYPE }
Public Member Functions
Number ()
Number (const HighPrecisionInteger &i)
Number (const HighPrecisionReal &r)
Number (int i)
Number (double d, bool asInteger=false)
Number (const std::string &s, bool asInteger=false)
Number (const Number &other)
Number & operator= (const Number &other)
~Number ()
bool isInteger () const
bool isReal () const
bool isUnknown () const
Type getType () const
const HighPrecisionInteger & getInteger () const
const HighPrecisionReal & getReal () const
HighPrecisionInteger toInteger () const
HighPrecisionReal toReal (mpfr_prec_t precision=128) const
bool isZero () const
bool isOne () const
bool isInfinity () const
bool isNegativeInfinity () const
bool isPositiveInfinity () const
Number operator+ (const Number &other) const
Number operator- (const Number &other) const
Number operator- () const
Number operator* (const Number &other) const
Number operator/ (const Number &other) const
Number operator% (const Number &other) const
Number & operator+= (const Number &other)
Number & operator-= (const Number &other)
Number & operator*= (const Number &other)
Number & operator/= (const Number &other)
Number & operator%= (const Number &other)
bool operator== (const Number &other) const
bool operator!= (const Number &other) const
bool operator< (const Number &other) const
bool operator<= (const Number &other) const
bool operator> (const Number &other) const
bool operator>= (const Number &other) const
Number & operator++ ()
Number operator++ (int)
Number & operator-- ()
Number operator-- (int)
Number operator& (const Number &other) const
Number operator| (const Number &other) const
Number operator^ (const Number &other) const
Number operator~ () const
Number operator<< (unsigned long bits) const
Number operator>> (unsigned long bits) const
std::string toString () const
Number abs () const
Number sqrt () const
Number safeSqrt () const
Number pow (const Number &exp) const
Number ceil () const
Number floor () const
Number round () const
Number exp () const
Number ln () const
Number lg () const
Number lb () const
Number log (const Number &base) const
Number sin () const
Number cos () const
Number tan () const
Number cot () const
Number sec () const
Number csc () const
Number asin () const
Number acos () const
Number atan () const
Number acot () const
Number asec () const
Number acsc () const
Number sinh () const
Number cosh () const
Number tanh () const
Number coth () const
Number sech () const
Number csch () const
Number asinh () const
Number acosh () const
Number atanh () const
Number acoth () const
Number asech () const
Number acsch () const
Number nextBelow () const
Number nextAbove () const
bool isNaN () const
Static Public Member Functions
static Number pi (size_t precision=128)
static Number e (size_t precision=128)
static Number phi (size_t precision=128)
static Number ln2 (size_t precision=128)
static Number ln10 (size_t precision=128)
static Number log2_e (size_t precision=128)
static Number log10_e (size_t precision=128)
static Number epsilon (size_t precision=128)
static Number zero ()
static Number one ()
static Number infinity ()
static Number negativeInfinity ()
static Number positiveInfinity ()
static Number atan2 (const Number &y, const Number &x)
Static Public Attributes
static Number ZERO
static Number ONE
static Number INFINITY
Private Attributes
Type type
HighPrecisionInteger intValue
HighPrecisionReal realValue
Detailed Description
Definition at line 271 of file number.h.
Member Enumeration Documentation
Type
enum stabilizer::parser::Number::Type
Enumerator
INT_TYPE
REAL_TYPE
UNKNOWN_TYPE
Definition at line 274 of file number.h.
Constructor & Destructor Documentation
Number() [1/7]
stabilizer::parser::Number::Number ()
Definition at line 1091 of file number.cpp.
Referenced by abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atan2(), atanh(), ceil(), cos(), cosh(), cot(), coth(), csc(), csch(), e(), epsilon(), exp(), floor(), lb(), lg(), ln(), ln10(), ln2(), log(), log10_e(), log2_e(), nextAbove(), nextBelow(), one(), operator%(), operator*(), operator+(), operator-(), operator/(), phi(), pi(), pow(), round(), safeSqrt(), sec(), sech(), sin(), sinh(), sqrt(), tan(), tanh(), and zero().
Number() [2/7]
stabilizer::parser::Number::Number (const HighPrecisionInteger & i)
Definition at line 1093 of file number.cpp.
Number() [3/7]
stabilizer::parser::Number::Number (const HighPrecisionReal & r)
Definition at line 1095 of file number.cpp.
Number() [4/7]
stabilizer::parser::Number::Number (int i)
Definition at line 1097 of file number.cpp.
Number() [5/7]
stabilizer::parser::Number::Number (double d, bool asInteger = false)
Definition at line 1099 of file number.cpp.
References INT_TYPE, intValue, REAL_TYPE, realValue, and type.
Number() [6/7]
stabilizer::parser::Number::Number (const std::string & s, bool asInteger = false)
Definition at line 1110 of file number.cpp.
References INT_TYPE, intValue, REAL_TYPE, realValue, and type.
Number() [7/7]
stabilizer::parser::Number::Number (const Number & other)
Definition at line 1121 of file number.cpp.
References INT_TYPE, intValue, realValue, and type.
~Number()
stabilizer::parser::Number::~Number ()
Definition at line 1145 of file number.cpp.
Member Function Documentation
abs()
Number stabilizer::parser::Number::abs () const
Definition at line 1438 of file number.cpp.
References stabilizer::parser::HighPrecisionInteger::abs(), stabilizer::parser::HighPrecisionReal::abs(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::abs(), stabilizer::parser::Value::abs(), stabilizer::parser::Interval::mod(), and stabilizer::parser::Interval::pow().
acos()
Number stabilizer::parser::Number::acos () const
Definition at line 1598 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::acos(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::acos(), and stabilizer::parser::Value::acos().
acosh()
Number stabilizer::parser::Number::acosh () const
Definition at line 1687 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::acosh(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::acosh(), and stabilizer::parser::Value::acosh().
acot()
Number stabilizer::parser::Number::acot () const
Definition at line 1612 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::acot(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Value::acot().
acoth()
Number stabilizer::parser::Number::acoth () const
Definition at line 1715 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::acoth(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Value::acoth().
acsc()
Number stabilizer::parser::Number::acsc () const
Definition at line 1626 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::acsc(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Value::acsc().
acsch()
Number stabilizer::parser::Number::acsch () const
Definition at line 1708 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::acsch(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Value::acsch().
asec()
Number stabilizer::parser::Number::asec () const
Definition at line 1619 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::asec(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Value::asec().
asech()
Number stabilizer::parser::Number::asech () const
Definition at line 1701 of file number.cpp.
References INT_TYPE, intValue, Number(), realValue, stabilizer::parser::HighPrecisionReal::tanh(), and type.
Referenced by stabilizer::parser::Value::asech().
asin()
Number stabilizer::parser::Number::asin () const
Definition at line 1591 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::asin(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::asin(), and stabilizer::parser::Value::asin().
asinh()
Number stabilizer::parser::Number::asinh () const
Definition at line 1680 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::asinh(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::asinh(), and stabilizer::parser::Value::asinh().
atan()
Number stabilizer::parser::Number::atan () const
Definition at line 1605 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::atan(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::acot(), stabilizer::parser::Interval::atan(), and stabilizer::parser::Value::atan().
atan2()
Number stabilizer::parser::Number::atan2 (const Number & y, const Number & x) static
Definition at line 1633 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::atan2(), Number(), and toReal().
Referenced by stabilizer::parser::Value::atan2(), and stabilizer::parser::Interval::atan2().
atanh()
Number stabilizer::parser::Number::atanh () const
Definition at line 1694 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::atanh(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::atanh(), and stabilizer::parser::Value::atanh().
ceil()
Number stabilizer::parser::Number::ceil () const
Definition at line 1484 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::ceil(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Value::ceil(), stabilizer::parser::Interval::getIntegers(), and stabilizer::parser::Interval::getIntervalIntCount().
cos()
Number stabilizer::parser::Number::cos () const
Definition at line 1556 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::cos(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::cos(), and stabilizer::parser::Value::cos().
cosh()
Number stabilizer::parser::Number::cosh () const
Definition at line 1645 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::cosh(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::cosh(), and stabilizer::parser::Value::cosh().
cot()
Number stabilizer::parser::Number::cot () const
Definition at line 1570 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::cot(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Value::cot().
coth()
Number stabilizer::parser::Number::coth () const
Definition at line 1659 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::coth(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Value::coth().
csc()
Number stabilizer::parser::Number::csc () const
Definition at line 1584 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::csc(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Value::csc().
csch()
Number stabilizer::parser::Number::csch () const
Definition at line 1673 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::csch(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Value::csch().
e()
Number stabilizer::parser::Number::e (size_t precision = 128) static
Definition at line 1235 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::e(), and Number().
epsilon()
Number stabilizer::parser::Number::epsilon (size_t precision = 128) static
Definition at line 1253 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::epsilon(), and Number().
exp()
Number stabilizer::parser::Number::exp () const
Definition at line 1512 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::exp(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::exp(), stabilizer::parser::Value::exp(), and pow().
floor()
Number stabilizer::parser::Number::floor () const
Definition at line 1493 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::floor(), INT_TYPE, intValue, Number(), realValue, and type.
Referenced by stabilizer::parser::Value::floor(), stabilizer::parser::Interval::getIntegers(), and stabilizer::parser::Interval::getIntervalIntCount().
getInteger()
const HighPrecisionInteger & stabilizer::parser::Number::getInteger () const
Definition at line 1151 of file number.cpp.
References INT_TYPE, intValue, and type.
getReal()
const HighPrecisionReal & stabilizer::parser::Number::getReal () const
Definition at line 1158 of file number.cpp.
References REAL_TYPE, realValue, and type.
Referenced by isInteger().
getType()
Type stabilizer::parser::Number::getType () const inline
Definition at line 315 of file number.h.
References type.
infinity()
Number stabilizer::parser::Number::infinity () static
Definition at line 1186 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::getMPFR(), and realValue.
isInfinity()
bool stabilizer::parser::Number::isInfinity () const
Definition at line 1213 of file number.cpp.
References INT_TYPE, stabilizer::parser::HighPrecisionReal::isInfinity(), realValue, and type.
Referenced by stabilizer::parser::Interval::cos(), stabilizer::parser::Interval::getIntegers(), stabilizer::parser::Interval::isLeftUnbounded(), stabilizer::parser::Interval::isRightUnbounded(), stabilizer::parser::Interval::pow(), stabilizer::parser::Interval::sin(), and stabilizer::parser::Interval::tan().
isInteger()
bool stabilizer::parser::Number::isInteger () const inline
Definition at line 310 of file number.h.
References getReal(), INT_TYPE, stabilizer::parser::HighPrecisionReal::isInteger(), isReal(), and type.
Referenced by stabilizer::parser::Interval::getIntervalIntCount(), stabilizer::parser::Interval::pow(), and stabilizer::parser::Interval::pow2().
isNaN()
bool stabilizer::parser::Number::isNaN () const
Definition at line 1740 of file number.cpp.
References INT_TYPE, stabilizer::parser::HighPrecisionReal::isNaN(), realValue, and type.
Referenced by stabilizer::parser::Interval::atan2().
isNegativeInfinity()
bool stabilizer::parser::Number::isNegativeInfinity () const
Definition at line 1220 of file number.cpp.
References INT_TYPE, stabilizer::parser::HighPrecisionReal::isNegativeInfinity(), realValue, and type.
Referenced by stabilizer::parser::Interval::exp(), stabilizer::parser::Interval::pow(), and stabilizer::parser::Interval::pow2().
isOne()
bool stabilizer::parser::Number::isOne () const
Definition at line 1207 of file number.cpp.
References INT_TYPE, intValue, realValue, and type.
isPositiveInfinity()
bool stabilizer::parser::Number::isPositiveInfinity () const
Definition at line 1226 of file number.cpp.
References INT_TYPE, stabilizer::parser::HighPrecisionReal::isPositiveInfinity(), realValue, and type.
Referenced by stabilizer::parser::Interval::exp(), stabilizer::parser::Interval::lb(), stabilizer::parser::Interval::lg(), stabilizer::parser::Interval::ln(), stabilizer::parser::Interval::pow(), stabilizer::parser::Interval::pow2(), stabilizer::parser::Interval::safeSqrt(), and stabilizer::parser::Interval::sqrt().
isReal()
bool stabilizer::parser::Number::isReal () const inline
Definition at line 313 of file number.h.
References REAL_TYPE, and type.
Referenced by isInteger().
isUnknown()
bool stabilizer::parser::Number::isUnknown () const inline
Definition at line 314 of file number.h.
References type, and UNKNOWN_TYPE.
isZero()
bool stabilizer::parser::Number::isZero () const
Definition at line 1201 of file number.cpp.
References INT_TYPE, intValue, realValue, and type.
lb()
Number stabilizer::parser::Number::lb () const
Definition at line 1533 of file number.cpp.
References INT_TYPE, intValue, stabilizer::parser::HighPrecisionReal::lb(), Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::lb(), and stabilizer::parser::Value::lb().
lg()
Number stabilizer::parser::Number::lg () const
Definition at line 1526 of file number.cpp.
References INT_TYPE, intValue, stabilizer::parser::HighPrecisionReal::lg(), Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::lg(), and stabilizer::parser::Value::lg().
ln()
Number stabilizer::parser::Number::ln () const
Definition at line 1519 of file number.cpp.
References INT_TYPE, intValue, stabilizer::parser::HighPrecisionReal::ln(), Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::ln(), and stabilizer::parser::Value::ln().
ln10()
Number stabilizer::parser::Number::ln10 (size_t precision = 128) static
Definition at line 1244 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::ln10(), and Number().
ln2()
Number stabilizer::parser::Number::ln2 (size_t precision = 128) static
Definition at line 1241 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::ln2(), and Number().
log()
Number stabilizer::parser::Number::log (const Number & base) const
Definition at line 1540 of file number.cpp.
References INT_TYPE, intValue, stabilizer::parser::HighPrecisionReal::log(), Number(), realValue, toReal(), and type.
Referenced by stabilizer::parser::Value::log().
log10_e()
Number stabilizer::parser::Number::log10_e (size_t precision = 128) static
Definition at line 1250 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::log10_e(), and Number().
log2_e()
Number stabilizer::parser::Number::log2_e (size_t precision = 128) static
Definition at line 1247 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::log2_e(), and Number().
negativeInfinity()
Number stabilizer::parser::Number::negativeInfinity () static
Definition at line 1191 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::getMPFR(), and realValue.
Referenced by stabilizer::parser::Interval::cot(), stabilizer::parser::Interval::coth(), stabilizer::parser::Interval::csc(), stabilizer::parser::Interval::csch(), stabilizer::parser::Interval::lb(), stabilizer::parser::Interval::lg(), stabilizer::parser::Interval::ln(), stabilizer::parser::Interval::sec(), and stabilizer::parser::Interval::tan().
nextAbove()
Number stabilizer::parser::Number::nextAbove () const
Definition at line 1731 of file number.cpp.
References INT_TYPE, intValue, stabilizer::parser::HighPrecisionInteger::nextAbove(), stabilizer::parser::HighPrecisionReal::nextAbove(), Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::acosh(), stabilizer::parser::Interval::asin(), stabilizer::parser::Interval::asinh(), stabilizer::parser::Interval::atan(), stabilizer::parser::Interval::atan2(), stabilizer::parser::Interval::atanh(), stabilizer::parser::Interval::cos(), stabilizer::parser::Interval::cosh(), stabilizer::parser::Interval::exp(), stabilizer::parser::Interval::lb(), stabilizer::parser::Interval::lg(), stabilizer::parser::Interval::ln(), stabilizer::parser::Interval::pow(), stabilizer::parser::Interval::pow2(), stabilizer::parser::Interval::safeSqrt(), stabilizer::parser::Interval::sin(), stabilizer::parser::Interval::sinh(), stabilizer::parser::Interval::sqrt(), stabilizer::parser::Interval::tan(), and stabilizer::parser::Interval::tanh().
nextBelow()
Number stabilizer::parser::Number::nextBelow () const
Definition at line 1722 of file number.cpp.
References INT_TYPE, intValue, stabilizer::parser::HighPrecisionInteger::nextBelow(), stabilizer::parser::HighPrecisionReal::nextBelow(), Number(), realValue, and type.
Referenced by stabilizer::parser::Interval::acosh(), stabilizer::parser::Interval::asin(), stabilizer::parser::Interval::asinh(), stabilizer::parser::Interval::atan(), stabilizer::parser::Interval::atan2(), stabilizer::parser::Interval::atanh(), stabilizer::parser::Interval::cos(), stabilizer::parser::Interval::cosh(), stabilizer::parser::Interval::exp(), stabilizer::parser::Interval::lb(), stabilizer::parser::Interval::lg(), stabilizer::parser::Interval::ln(), stabilizer::parser::Interval::pow(), stabilizer::parser::Interval::pow2(), stabilizer::parser::Interval::safeSqrt(), stabilizer::parser::Interval::sin(), stabilizer::parser::Interval::sinh(), stabilizer::parser::Interval::sqrt(), stabilizer::parser::Interval::tan(), and stabilizer::parser::Interval::tanh().
one()
Number stabilizer::parser::Number::one () static
Definition at line 1185 of file number.cpp.
References Number().
operator!=()
bool stabilizer::parser::Number::operator!= (const Number & other) const
Definition at line 1397 of file number.cpp.
operator%()
Number stabilizer::parser::Number::operator% (const Number & other) const
Definition at line 1301 of file number.cpp.
References condAssert, INT_TYPE, intValue, Number(), and type.
operator%=()
Number & stabilizer::parser::Number::operator%= (const Number & other)
Definition at line 1347 of file number.cpp.
References condAssert, INT_TYPE, intValue, and type.
operator&()
Number stabilizer::parser::Number::operator& (const Number & other) const
operator*()
Number stabilizer::parser::Number::operator* (const Number & other) const
Definition at line 1281 of file number.cpp.
References INT_TYPE, intValue, Number(), toReal(), and type.
operator*=()
Number & stabilizer::parser::Number::operator*= (const Number & other)
Definition at line 1327 of file number.cpp.
References INT_TYPE, intValue, realValue, toReal(), and type.
operator+()
Number stabilizer::parser::Number::operator+ (const Number & other) const
Definition at line 1258 of file number.cpp.
References INT_TYPE, intValue, Number(), toReal(), and type.
operator++() [1/2]
Number & stabilizer::parser::Number::operator++ ()
Definition at line 1354 of file number.cpp.
References INT_TYPE, intValue, realValue, and type.
Referenced by operator++().
operator++() [2/2]
Number stabilizer::parser::Number::operator++ (int)
Definition at line 1363 of file number.cpp.
References operator++().
operator+=()
Number & stabilizer::parser::Number::operator+= (const Number & other)
Definition at line 1307 of file number.cpp.
References INT_TYPE, intValue, realValue, toReal(), and type.
operator-() [1/2]
Number stabilizer::parser::Number::operator- () const
Definition at line 1274 of file number.cpp.
References INT_TYPE, intValue, Number(), realValue, and type.
operator-() [2/2]
Number stabilizer::parser::Number::operator- (const Number & other) const
Definition at line 1267 of file number.cpp.
References INT_TYPE, intValue, Number(), toReal(), and type.
operator--() [1/2]
Number & stabilizer::parser::Number::operator-- ()
Definition at line 1368 of file number.cpp.
References INT_TYPE, intValue, realValue, and type.
Referenced by operator--().
operator--() [2/2]
Number stabilizer::parser::Number::operator-- (int)
Definition at line 1377 of file number.cpp.
References operator--().
operator-=()
Number & stabilizer::parser::Number::operator-= (const Number & other)
Definition at line 1317 of file number.cpp.
References INT_TYPE, intValue, realValue, toReal(), and type.
operator/()
Number stabilizer::parser::Number::operator/ (const Number & other) const
Definition at line 1288 of file number.cpp.
References INT_TYPE, intValue, Number(), toReal(), and type.
operator/=()
Number & stabilizer::parser::Number::operator/= (const Number & other)
Definition at line 1337 of file number.cpp.
References INT_TYPE, intValue, realValue, toReal(), and type.
operator<()
bool stabilizer::parser::Number::operator< (const Number & other) const
Definition at line 1399 of file number.cpp.
References INT_TYPE, intValue, realValue, toReal(), and type.
operator<<()
Number stabilizer::parser::Number::operator<< (unsigned long bits) const
operator<=()
bool stabilizer::parser::Number::operator<= (const Number & other) const
Definition at line 1411 of file number.cpp.
References INT_TYPE, intValue, realValue, toReal(), and type.
operator=()
Number & stabilizer::parser::Number::operator= (const Number & other)
Definition at line 1131 of file number.cpp.
References INT_TYPE, intValue, realValue, and type.
operator==()
bool stabilizer::parser::Number::operator== (const Number & other) const
Definition at line 1384 of file number.cpp.
References INT_TYPE, intValue, realValue, toReal(), and type.
operator>()
bool stabilizer::parser::Number::operator> (const Number & other) const
Definition at line 1423 of file number.cpp.
operator>=()
bool stabilizer::parser::Number::operator>= (const Number & other) const
Definition at line 1425 of file number.cpp.
operator>>()
Number stabilizer::parser::Number::operator>> (unsigned long bits) const
operator^()
Number stabilizer::parser::Number::operator^ (const Number & other) const
operator|()
Number stabilizer::parser::Number::operator| (const Number & other) const
operator~()
Number stabilizer::parser::Number::operator~ () const
phi()
Number stabilizer::parser::Number::phi (size_t precision = 128) static
Definition at line 1238 of file number.cpp.
References Number(), and stabilizer::parser::HighPrecisionReal::phi().
pi()
Number stabilizer::parser::Number::pi (size_t precision = 128) static
Definition at line 1232 of file number.cpp.
References Number(), and stabilizer::parser::HighPrecisionReal::pi().
Referenced by stabilizer::parser::Interval::acot(), stabilizer::parser::Interval::acsc(), stabilizer::parser::Interval::asec(), stabilizer::parser::Interval::atan2(), stabilizer::parser::Interval::cos(), stabilizer::parser::Interval::sin(), and stabilizer::parser::Interval::tan().
positiveInfinity()
Number stabilizer::parser::Number::positiveInfinity () static
Definition at line 1196 of file number.cpp.
References stabilizer::parser::HighPrecisionReal::getMPFR(), and realValue.
Referenced by stabilizer::parser::Interval::cot(), stabilizer::parser::Interval::coth(), stabilizer::parser::Interval::csc(), stabilizer::parser::Interval::csch(), stabilizer::parser::Interval::exp(), stabilizer::parser::Interval::lb(), stabilizer::parser::Interval::lg(), stabilizer::parser::Interval::ln(), stabilizer::parser::Interval::pow(), stabilizer::parser::Interval::pow2(), stabilizer::parser::Interval::safeSqrt(), stabilizer::parser::Interval::sec(), stabilizer::parser::Interval::sqrt(), and stabilizer::parser::Interval::tan().
pow()
Number stabilizer::parser::Number::pow (const Number & exp) const
Definition at line 1465 of file number.cpp.
References exp(), INT_TYPE, intValue, Number(), stabilizer::parser::HighPrecisionInteger::pow(), toReal(), stabilizer::parser::HighPrecisionInteger::toULong(), and type.
Referenced by stabilizer::parser::Value::pow(), stabilizer::parser::Interval::pow(), and stabilizer::parser::Interval::pow2().
round()
Number stabilizer::parser::Number::round () const
Definition at line 1502 of file number.cpp.
References INT_TYPE, intValue, Number(), realValue, stabilizer::parser::HighPrecisionReal::round(), and type.
Referenced by stabilizer::parser::Value::round().
safeSqrt()
Number stabilizer::parser::Number::safeSqrt () const
Definition at line 1457 of file number.cpp.
References INT_TYPE, intValue, Number(), stabilizer::parser::HighPrecisionInteger::safeSqrt(), toReal(), and type.
Referenced by stabilizer::parser::Interval::safeSqrt(), and stabilizer::parser::Value::safeSqrt().
sec()
Number stabilizer::parser::Number::sec () const
Definition at line 1577 of file number.cpp.
References INT_TYPE, intValue, Number(), realValue, stabilizer::parser::HighPrecisionReal::sec(), and type.
Referenced by stabilizer::parser::Value::sec().
sech()
Number stabilizer::parser::Number::sech () const
Definition at line 1666 of file number.cpp.
References INT_TYPE, intValue, Number(), realValue, stabilizer::parser::HighPrecisionReal::sech(), and type.
Referenced by stabilizer::parser::Value::sech().
sin()
Number stabilizer::parser::Number::sin () const
Definition at line 1549 of file number.cpp.
References INT_TYPE, intValue, Number(), realValue, stabilizer::parser::HighPrecisionReal::sin(), and type.
Referenced by stabilizer::parser::Interval::sin(), and stabilizer::parser::Value::sin().
sinh()
Number stabilizer::parser::Number::sinh () const
Definition at line 1638 of file number.cpp.
References INT_TYPE, intValue, Number(), realValue, stabilizer::parser::HighPrecisionReal::sinh(), and type.
Referenced by stabilizer::parser::Interval::sinh(), and stabilizer::parser::Value::sinh().
sqrt()
Number stabilizer::parser::Number::sqrt () const
Definition at line 1447 of file number.cpp.
References INT_TYPE, intValue, Number(), stabilizer::parser::HighPrecisionInteger::sqrt(), toReal(), and type.
Referenced by stabilizer::parser::Interval::sqrt(), and stabilizer::parser::Value::sqrt().
tan()
Number stabilizer::parser::Number::tan () const
Definition at line 1563 of file number.cpp.
References INT_TYPE, intValue, Number(), realValue, stabilizer::parser::HighPrecisionReal::tan(), and type.
Referenced by stabilizer::parser::Interval::tan(), and stabilizer::parser::Value::tan().
tanh()
Number stabilizer::parser::Number::tanh () const
Definition at line 1652 of file number.cpp.
References INT_TYPE, intValue, Number(), realValue, stabilizer::parser::HighPrecisionReal::tanh(), and type.
Referenced by stabilizer::parser::Interval::coth(), stabilizer::parser::Interval::tanh(), and stabilizer::parser::Value::tanh().
toInteger()
HighPrecisionInteger stabilizer::parser::Number::toInteger () const
Definition at line 1166 of file number.cpp.
References INT_TYPE, intValue, realValue, stabilizer::parser::HighPrecisionReal::toInteger(), and type.
Referenced by stabilizer::parser::Parser::mkConstInt(), stabilizer::parser::Interval::pow(), stabilizer::parser::Interval::pow2(), stabilizer::parser::Value::repeatStr(), and stabilizer::parser::Value::substr().
toReal()
HighPrecisionReal stabilizer::parser::Number::toReal (mpfr_prec_t precision = 128) const
Definition at line 1175 of file number.cpp.
References intValue, REAL_TYPE, realValue, and type.
Referenced by atan2(), log(), stabilizer::parser::Parser::mkConstReal(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator<=(), operator==(), pow(), safeSqrt(), and sqrt().
toString()
std::string stabilizer::parser::Number::toString () const
Definition at line 1428 of file number.cpp.
References INT_TYPE, intValue, realValue, stabilizer::parser::HighPrecisionInteger::toString(), stabilizer::parser::HighPrecisionReal::toString(), and type.
Referenced by stabilizer::parser::Interval::toString(), and stabilizer::parser::Value::toString().
zero()
Number stabilizer::parser::Number::zero () static
Definition at line 1184 of file number.cpp.
References Number().
Member Data Documentation
INFINITY
Number stabilizer::parser::Number::INFINITY static
Definition at line 283 of file number.h.
intValue
HighPrecisionInteger stabilizer::parser::Number::intValue private
Definition at line 431 of file number.h.
Referenced by abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atanh(), ceil(), cos(), cosh(), cot(), coth(), csc(), csch(), exp(), floor(), getInteger(), isOne(), isZero(), lb(), lg(), ln(), log(), nextAbove(), nextBelow(), Number(), operator%(), operator%=(), operator*(), operator*=(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), operator/(), operator/=(), operator<(), operator<=(), operator=(), operator==(), pow(), round(), safeSqrt(), sec(), sech(), sin(), sinh(), sqrt(), tan(), tanh(), toInteger(), toReal(), and toString().
ONE
Number stabilizer::parser::Number::ONE static
Definition at line 282 of file number.h.
realValue
HighPrecisionReal stabilizer::parser::Number::realValue private
Definition at line 432 of file number.h.
Referenced by abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atanh(), ceil(), cos(), cosh(), cot(), coth(), csc(), csch(), exp(), floor(), getReal(), infinity(), isInfinity(), isNaN(), isNegativeInfinity(), isOne(), isPositiveInfinity(), isZero(), lb(), lg(), ln(), log(), negativeInfinity(), nextAbove(), nextBelow(), Number(), operator*=(), operator++(), operator+=(), operator-(), operator--(), operator-=(), operator/=(), operator<(), operator<=(), operator=(), operator==(), positiveInfinity(), round(), sec(), sech(), sin(), sinh(), tan(), tanh(), toInteger(), toReal(), and toString().
type
Type stabilizer::parser::Number::type private
Definition at line 430 of file number.h.
Referenced by abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atanh(), ceil(), cos(), cosh(), cot(), coth(), csc(), csch(), exp(), floor(), getInteger(), getReal(), getType(), isInfinity(), isInteger(), isNaN(), isNegativeInfinity(), isOne(), isPositiveInfinity(), isReal(), isUnknown(), isZero(), lb(), lg(), ln(), log(), nextAbove(), nextBelow(), Number(), operator%(), operator%=(), operator*(), operator*=(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), operator/(), operator/=(), operator<(), operator<=(), operator=(), operator==(), pow(), round(), safeSqrt(), sec(), sech(), sin(), sinh(), sqrt(), tan(), tanh(), toInteger(), toReal(), and toString().
ZERO
Number stabilizer::parser::Number::ZERO static
Definition at line 281 of file number.h.
The documentation for this class was generated from the following files:
src/parser/number.h
src/parser/number.cpp