SMTStabilizer API: stabilizer::parser::Interval Class Reference
stabilizer::parser::Interval Class Reference
#include <interval.h>
Public Member Functions
Interval (Number lower=Number::zero(), Number upper=Number::zero(), bool leftClosed=true, bool rightClosed=true)
Interval (const Interval &other)
Interval & operator= (const Interval &other)
~Interval ()
void setLower (const Number &lower)
void setUpper (const Number &upper)
void setLeftClosed (bool leftClosed)
void setRightClosed (bool rightClosed)
Number getLower () const
Number getUpper () const
bool isLeftClosed () const
bool isRightClosed () const
bool isLeftUnbounded () const
bool isRightUnbounded () const
Number midpoint () const
std::string toString () const
void getIntegers (std::vector< Number > &integers) const
bool isPoint () const
bool isEmpty () const
Number width () const
bool contains (const Number &value) const
bool isSubsetOf (const Interval &other) const
bool isSubsetEqOf (const Interval &other) const
bool isSupersetOf (const Interval &other) const
bool isDisjointFrom (const Interval &other) const
bool isIntersectingWith (const Interval &other) const
Interval intersection (const Interval &other) const
Interval unionWith (const Interval &other) const
std::vector< Interval > difference (const Interval &other) const
size_t getIntervalIntCount () const
Interval operator++ () const
Interval operator-- () const
Interval operator- () const
Interval operator+ () const
Interval operator~ () const
Interval operator! () const
Interval operator++ (int) const
Interval operator-- (int) const
Interval negate () const
Interval abs () const
Interval lb () const
Interval ln () const
Interval lg () const
Interval pow2 () const
Interval exp () const
Interval sqrt () const
Interval safeSqrt () const
Interval sin () const
Interval cos () const
Interval tan () const
Interval cot () const
Interval sec () const
Interval csc () const
Interval asin () const
Interval acos () const
Interval atan () const
Interval acot () const
Interval asec () const
Interval acsc () const
Interval sinh () const
Interval cosh () const
Interval tanh () const
Interval coth () const
Interval sech () const
Interval csch () const
Interval asinh () const
Interval acosh () const
Interval atanh () const
Interval acoth () const
Interval asech () const
Interval acsch () const
Interval operator+ (const Number &value) const
Interval operator- (const Number &value) const
Interval operator* (const Number &value) const
Interval operator/ (const Number &value) const
Interval operator% (const Number &value) const
Interval operator^ (const Number &value) const
Interval operator+ (const Interval &other) const
Interval operator- (const Interval &other) const
Interval operator* (const Interval &other) const
Interval operator/ (const Interval &other) const
Interval operator% (const Interval &other) const
Interval operator^ (const Interval &other) const
Interval add (const Number &value) const
Interval add (const Interval &other) const
Interval sub (const Number &value) const
Interval sub (const Interval &other) const
Interval mul (const Number &value) const
Interval mul (const Interval &other) const
Interval divReal (const Number &value) const
Interval divReal (const Interval &other) const
Interval divInt (const Number &value) const
Interval divInt (const Interval &other) const
Interval mod (const Number &value) const
Interval mod (const Interval &other) const
Interval pow (const Number &exp) const
Interval pow (const Interval &exp) const
Interval atan2 (const Number &x) const
Interval atan2 (const Interval &x) const
Interval log (const Number &base) const
Interval log (const Interval &base) const
Interval operate (const NODE_KIND &kind) const
Interval operate (const NODE_KIND &kind, const Number &value) const
Interval operate (const NODE_KIND &kind, const Interval &other) const
bool operator== (const Interval &other) const
bool operator!= (const Interval &other) const
bool operator< (const Interval &other) const
bool operator<= (const Interval &other) const
bool operator> (const Interval &other) const
bool operator>= (const Interval &other) const
Interval & operator+= (const Number &value)
Interval & operator-= (const Number &value)
Interval & operator*= (const Number &value)
Interval & operator/= (const Number &value)
Static Public Member Functions
static std::vector< Interval > unionMulti (const std::vector< Interval > &intervals)
Private Attributes
Number lower
Number upper
bool leftClosed
bool rightClosed
Detailed Description
Definition at line 41 of file interval.h.
Constructor & Destructor Documentation
Interval() [1/2]
stabilizer::parser::Interval::Interval (Number lower = Number::zero(), Number upper = Number::zero(), bool leftClosed = true, bool rightClosed = true)
Definition at line 35 of file interval.cpp.
Referenced by abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atan2(), atanh(), cos(), cosh(), cot(), coth(), csc(), csch(), difference(), divInt(), divReal(), exp(), intersection(), lb(), lg(), ln(), mod(), negate(), operate(), operator!(), operator*(), operator+(), operator++(), operator-(), operator--(), operator/(), operator~(), pow(), pow2(), safeSqrt(), sec(), sech(), sin(), sinh(), sqrt(), tan(), tanh(), unionMulti(), and unionWith().
Interval() [2/2]
stabilizer::parser::Interval::Interval (const Interval & other)
Definition at line 38 of file interval.cpp.
~Interval()
stabilizer::parser::Interval::~Interval ()
Definition at line 41 of file interval.cpp.
Member Function Documentation
abs()
Interval stabilizer::parser::Interval::abs () const
Definition at line 426 of file interval.cpp.
References stabilizer::parser::Number::abs(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
Referenced by stabilizer::parser::Value::abs(), and operate().
acos()
Interval stabilizer::parser::Interval::acos () const
Definition at line 982 of file interval.cpp.
References stabilizer::parser::Number::acos(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
Referenced by stabilizer::parser::Value::acos(), asec(), and operate().
acosh()
Interval stabilizer::parser::Interval::acosh () const
Definition at line 1260 of file interval.cpp.
References stabilizer::parser::Number::acosh(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), and upper.
Referenced by stabilizer::parser::Value::acosh(), asech(), and operate().
acot()
Interval stabilizer::parser::Interval::acot () const
Definition at line 1018 of file interval.cpp.
References stabilizer::parser::Number::atan(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, stabilizer::parser::Number::pi(), and upper.
Referenced by stabilizer::parser::Value::acot(), and operate().
acoth()
Interval stabilizer::parser::Interval::acoth () const
Definition at line 1306 of file interval.cpp.
References atanh(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, and upper.
Referenced by stabilizer::parser::Value::acoth(), and operate().
acsc()
Interval stabilizer::parser::Interval::acsc () const
Definition at line 1055 of file interval.cpp.
References asin(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, stabilizer::parser::Number::pi(), and upper.
Referenced by stabilizer::parser::Value::acsc(), and operate().
acsch()
Interval stabilizer::parser::Interval::acsch () const
Definition at line 1339 of file interval.cpp.
References asinh(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, and upper.
Referenced by stabilizer::parser::Value::acsch(), and operate().
add() [1/2]
Interval stabilizer::parser::Interval::add (const Interval & other) const
Definition at line 1460 of file interval.cpp.
add() [2/2]
Interval stabilizer::parser::Interval::add (const Number & value) const
Definition at line 1458 of file interval.cpp.
asec()
Interval stabilizer::parser::Interval::asec () const
Definition at line 1032 of file interval.cpp.
References acos(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, stabilizer::parser::Number::pi(), and upper.
Referenced by stabilizer::parser::Value::asec(), and operate().
asech()
Interval stabilizer::parser::Interval::asech () const
Definition at line 1322 of file interval.cpp.
References acosh(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, and upper.
Referenced by stabilizer::parser::Value::asech(), and operate().
asin()
Interval stabilizer::parser::Interval::asin () const
Definition at line 959 of file interval.cpp.
References stabilizer::parser::Number::asin(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), and upper.
Referenced by acsc(), stabilizer::parser::Value::asin(), and operate().
asinh()
Interval stabilizer::parser::Interval::asinh () const
Definition at line 1241 of file interval.cpp.
References stabilizer::parser::Number::asinh(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), and upper.
Referenced by acsch(), stabilizer::parser::Value::asinh(), and operate().
atan()
Interval stabilizer::parser::Interval::atan () const
Definition at line 999 of file interval.cpp.
References stabilizer::parser::Number::atan(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), and upper.
Referenced by stabilizer::parser::Value::atan(), and operate().
atan2() [1/2]
Interval stabilizer::parser::Interval::atan2 (const Interval & x) const
Definition at line 2092 of file interval.cpp.
References stabilizer::parser::Number::atan2(), stabilizer::parser::EmptyInterval, getLower(), getUpper(), Interval(), isEmpty(), isLeftClosed(), isRightClosed(), leftClosed, lower, stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::pi(), rightClosed, and upper.
atan2() [2/2]
Interval stabilizer::parser::Interval::atan2 (const Number & x) const
Definition at line 2044 of file interval.cpp.
References stabilizer::parser::Number::atan2(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), stabilizer::parser::Number::isNaN(), leftClosed, lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::pi(), rightClosed, and upper.
Referenced by operate().
atanh()
Interval stabilizer::parser::Interval::atanh () const
Definition at line 1283 of file interval.cpp.
References stabilizer::parser::Number::atanh(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), and upper.
Referenced by acoth(), stabilizer::parser::Value::atanh(), and operate().
contains()
bool stabilizer::parser::Interval::contains (const Number & value) const
Definition at line 129 of file interval.cpp.
References isEmpty(), leftClosed, lower, rightClosed, and upper.
Referenced by cot(), csc(), divReal(), and sec().
cos()
Interval stabilizer::parser::Interval::cos () const
Definition at line 773 of file interval.cpp.
References stabilizer::parser::Number::cos(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), stabilizer::parser::Number::isInfinity(), leftClosed, lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::pi(), rightClosed, and upper.
Referenced by stabilizer::parser::Value::cos(), operate(), and sec().
cosh()
Interval stabilizer::parser::Interval::cosh () const
Definition at line 1096 of file interval.cpp.
References stabilizer::parser::Number::cosh(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), and upper.
Referenced by stabilizer::parser::Value::cosh(), operate(), and sech().
cot()
Interval stabilizer::parser::Interval::cot () const
Definition at line 905 of file interval.cpp.
References contains(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), stabilizer::parser::Number::negativeInfinity(), stabilizer::parser::Number::positiveInfinity(), and tan().
Referenced by stabilizer::parser::Value::cot(), and operate().
coth()
Interval stabilizer::parser::Interval::coth () const
Definition at line 1173 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, stabilizer::parser::Number::negativeInfinity(), stabilizer::parser::Number::positiveInfinity(), stabilizer::parser::Number::tanh(), and upper.
Referenced by stabilizer::parser::Value::coth(), and operate().
csc()
Interval stabilizer::parser::Interval::csc () const
Definition at line 941 of file interval.cpp.
References contains(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), stabilizer::parser::Number::negativeInfinity(), stabilizer::parser::Number::positiveInfinity(), and sin().
Referenced by stabilizer::parser::Value::csc(), and operate().
csch()
Interval stabilizer::parser::Interval::csch () const
Definition at line 1218 of file interval.cpp.
References stabilizer::parser::EmptyInterval, getLower(), getUpper(), Interval(), isEmpty(), lower, stabilizer::parser::Number::negativeInfinity(), stabilizer::parser::Number::positiveInfinity(), sinh(), and upper.
Referenced by stabilizer::parser::Value::csch(), and operate().
difference()
std::vector< Interval > stabilizer::parser::Interval::difference (const Interval & other) const
Definition at line 269 of file interval.cpp.
References Interval(), isDisjointFrom(), isSubsetOf(), isSupersetOf(), leftClosed, lower, rightClosed, and upper.
divInt() [1/2]
Interval stabilizer::parser::Interval::divInt (const Interval & other) const
Definition at line 1564 of file interval.cpp.
References stabilizer::parser::EmptyInterval, stabilizer::parser::FullInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
divInt() [2/2]
Interval stabilizer::parser::Interval::divInt (const Number & value) const
Definition at line 1548 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
Referenced by operate().
divReal() [1/2]
Interval stabilizer::parser::Interval::divReal (const Interval & other) const
Definition at line 1493 of file interval.cpp.
References condAssert, contains(), stabilizer::parser::EmptyInterval, stabilizer::parser::FullInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
divReal() [2/2]
Interval stabilizer::parser::Interval::divReal (const Number & value) const
Definition at line 1478 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
Referenced by operate(), and operator/().
exp()
Interval stabilizer::parser::Interval::exp () const
Definition at line 577 of file interval.cpp.
References stabilizer::parser::EmptyInterval, stabilizer::parser::Number::exp(), Interval(), isEmpty(), stabilizer::parser::Number::isNegativeInfinity(), stabilizer::parser::Number::isPositiveInfinity(), lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::positiveInfinity(), and upper.
Referenced by stabilizer::parser::Value::exp(), operate(), and pow().
getIntegers()
void stabilizer::parser::Interval::getIntegers (std::vector< Number > & integers) const
Definition at line 106 of file interval.cpp.
References stabilizer::parser::Number::ceil(), stabilizer::parser::Number::floor(), stabilizer::parser::Number::isInfinity(), lower, and upper.
getIntervalIntCount()
size_t stabilizer::parser::Interval::getIntervalIntCount () const
Definition at line 244 of file interval.cpp.
References stabilizer::parser::Number::ceil(), stabilizer::parser::Number::floor(), isEmpty(), stabilizer::parser::Number::isInteger(), isPoint(), leftClosed, lower, rightClosed, and upper.
getLower()
Number stabilizer::parser::Interval::getLower () const
Definition at line 1470 of file interval.cpp.
References lower.
Referenced by atan2(), csch(), pow(), and sech().
getUpper()
Number stabilizer::parser::Interval::getUpper () const
Definition at line 1472 of file interval.cpp.
References upper.
Referenced by atan2(), csch(), pow(), and sech().
intersection()
Interval stabilizer::parser::Interval::intersection (const Interval & other) const
Definition at line 193 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
Referenced by operate().
isDisjointFrom()
bool stabilizer::parser::Interval::isDisjointFrom (const Interval & other) const
Definition at line 170 of file interval.cpp.
References isEmpty(), leftClosed, lower, rightClosed, and upper.
Referenced by difference(), isIntersectingWith(), operate(), unionMulti(), and unionWith().
isEmpty()
bool stabilizer::parser::Interval::isEmpty () const
Definition at line 117 of file interval.cpp.
References leftClosed, lower, rightClosed, and upper.
Referenced by abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atan2(), atanh(), contains(), cos(), cosh(), cot(), coth(), csc(), csch(), divInt(), divReal(), exp(), getIntervalIntCount(), intersection(), isDisjointFrom(), isIntersectingWith(), isSubsetEqOf(), isSubsetOf(), isSupersetOf(), lb(), lg(), ln(), mod(), negate(), operate(), operator!(), operator*(), operator+(), operator++(), operator-(), operator--(), operator/(), operator<(), operator<=(), operator>(), operator>=(), operator~(), pow(), pow2(), safeSqrt(), sec(), sech(), sin(), sinh(), sqrt(), tan(), tanh(), unionWith(), and width().
isIntersectingWith()
bool stabilizer::parser::Interval::isIntersectingWith (const Interval & other) const
Definition at line 185 of file interval.cpp.
References isDisjointFrom(), and isEmpty().
Referenced by operate().
isLeftClosed()
bool stabilizer::parser::Interval::isLeftClosed () const
Definition at line 1474 of file interval.cpp.
References leftClosed.
Referenced by atan2(), pow(), and pow2().
isLeftUnbounded()
bool stabilizer::parser::Interval::isLeftUnbounded () const
Definition at line 82 of file interval.cpp.
References stabilizer::parser::Number::isInfinity(), and lower.
isPoint()
bool stabilizer::parser::Interval::isPoint () const
Definition at line 115 of file interval.cpp.
References lower, and upper.
Referenced by getIntervalIntCount(), and pow().
isRightClosed()
bool stabilizer::parser::Interval::isRightClosed () const
Definition at line 1476 of file interval.cpp.
References rightClosed.
Referenced by atan2(), pow(), and pow2().
isRightUnbounded()
bool stabilizer::parser::Interval::isRightUnbounded () const
Definition at line 84 of file interval.cpp.
References stabilizer::parser::Number::isInfinity(), and upper.
isSubsetEqOf()
bool stabilizer::parser::Interval::isSubsetEqOf (const Interval & other) const
Definition at line 234 of file interval.cpp.
References isEmpty(), leftClosed, lower, rightClosed, and upper.
isSubsetOf()
bool stabilizer::parser::Interval::isSubsetOf (const Interval & other) const
Definition at line 137 of file interval.cpp.
References isEmpty(), leftClosed, lower, rightClosed, and upper.
Referenced by difference().
isSupersetOf()
bool stabilizer::parser::Interval::isSupersetOf (const Interval & other) const
Definition at line 154 of file interval.cpp.
References isEmpty(), leftClosed, lower, rightClosed, and upper.
Referenced by difference().
lb()
Interval stabilizer::parser::Interval::lb () const
Definition at line 444 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), stabilizer::parser::Number::isPositiveInfinity(), stabilizer::parser::Number::lb(), lower, stabilizer::parser::Number::negativeInfinity(), stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::positiveInfinity(), and upper.
Referenced by stabilizer::parser::Value::lb(), and operate().
lg()
Interval stabilizer::parser::Interval::lg () const
Definition at line 534 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), stabilizer::parser::Number::isPositiveInfinity(), stabilizer::parser::Number::lg(), lower, stabilizer::parser::Number::negativeInfinity(), stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::positiveInfinity(), and upper.
Referenced by stabilizer::parser::Value::lg(), and operate().
ln()
Interval stabilizer::parser::Interval::ln () const
Definition at line 491 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), stabilizer::parser::Number::isPositiveInfinity(), stabilizer::parser::Number::ln(), lower, stabilizer::parser::Number::negativeInfinity(), stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::positiveInfinity(), and upper.
Referenced by stabilizer::parser::Value::ln(), and operate().
log() [1/2]
Interval stabilizer::parser::Interval::log (const Interval & base) const
log() [2/2]
Interval stabilizer::parser::Interval::log (const Number & base) const
midpoint()
Number stabilizer::parser::Interval::midpoint () const
Definition at line 86 of file interval.cpp.
References lower, and upper.
mod() [1/2]
Interval stabilizer::parser::Interval::mod (const Interval & other) const
Definition at line 1651 of file interval.cpp.
References stabilizer::parser::Number::abs(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
mod() [2/2]
Interval stabilizer::parser::Interval::mod (const Number & value) const
Definition at line 1617 of file interval.cpp.
References stabilizer::parser::Number::abs(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
Referenced by operate(), stabilizer::parser::Value::operator%(), and operator%().
mul() [1/2]
Interval stabilizer::parser::Interval::mul (const Interval & other) const
Definition at line 1468 of file interval.cpp.
mul() [2/2]
Interval stabilizer::parser::Interval::mul (const Number & value) const
Definition at line 1466 of file interval.cpp.
negate()
Interval stabilizer::parser::Interval::negate () const
Definition at line 420 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
Referenced by stabilizer::parser::Value::neg(), and operate().
operate() [1/3]
Interval stabilizer::parser::Interval::operate (const NODE_KIND & kind) const
Definition at line 2282 of file interval.cpp.
References abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atanh(), cos(), cosh(), cot(), coth(), csc(), csch(), stabilizer::parser::EmptyInterval, exp(), isEmpty(), lb(), lg(), ln(), negate(), stabilizer::parser::NT_ABS, stabilizer::parser::NT_ACOS, stabilizer::parser::NT_ACOSH, stabilizer::parser::NT_ACOT, stabilizer::parser::NT_ACOTH, stabilizer::parser::NT_ACSC, stabilizer::parser::NT_ACSCH, stabilizer::parser::NT_ASEC, stabilizer::parser::NT_ASECH, stabilizer::parser::NT_ASIN, stabilizer::parser::NT_ASINH, stabilizer::parser::NT_ATAN, stabilizer::parser::NT_ATANH, stabilizer::parser::NT_COS, stabilizer::parser::NT_COSH, stabilizer::parser::NT_COT, stabilizer::parser::NT_COTH, stabilizer::parser::NT_CSC, stabilizer::parser::NT_CSCH, stabilizer::parser::NT_EXP, stabilizer::parser::NT_LB, stabilizer::parser::NT_LG, stabilizer::parser::NT_LN, stabilizer::parser::NT_NEG, stabilizer::parser::NT_SAFESQRT, stabilizer::parser::NT_SEC, stabilizer::parser::NT_SECH, stabilizer::parser::NT_SIN, stabilizer::parser::NT_SINH, stabilizer::parser::NT_SQRT, stabilizer::parser::NT_TAN, stabilizer::parser::NT_TANH, safeSqrt(), sec(), sech(), sin(), sinh(), sqrt(), tan(), and tanh().
operate() [2/3]
Interval stabilizer::parser::Interval::operate (const NODE_KIND & kind, const Interval & other) const
Definition at line 2394 of file interval.cpp.
References atan2(), divInt(), divReal(), intersection(), Interval(), isDisjointFrom(), isEmpty(), isIntersectingWith(), lower, mod(), stabilizer::parser::NT_ADD, stabilizer::parser::NT_AND, stabilizer::parser::NT_ATAN2, stabilizer::parser::NT_DISTINCT, stabilizer::parser::NT_DIV_INT, stabilizer::parser::NT_DIV_REAL, stabilizer::parser::NT_EQ, stabilizer::parser::NT_GE, stabilizer::parser::NT_GT, stabilizer::parser::NT_LE, stabilizer::parser::NT_LT, stabilizer::parser::NT_MOD, stabilizer::parser::NT_MUL, stabilizer::parser::NT_OR, stabilizer::parser::NT_POW, stabilizer::parser::NT_SUB, pow(), unionWith(), and upper.
operate() [3/3]
Interval stabilizer::parser::Interval::operate (const NODE_KIND & kind, const Number & value) const
Definition at line 2357 of file interval.cpp.
References atan2(), divInt(), divReal(), stabilizer::parser::EmptyInterval, isEmpty(), mod(), stabilizer::parser::NT_ADD, stabilizer::parser::NT_ATAN2, stabilizer::parser::NT_DISTINCT, stabilizer::parser::NT_DIV_INT, stabilizer::parser::NT_DIV_REAL, stabilizer::parser::NT_EQ, stabilizer::parser::NT_GE, stabilizer::parser::NT_GT, stabilizer::parser::NT_LE, stabilizer::parser::NT_LT, stabilizer::parser::NT_MOD, stabilizer::parser::NT_MUL, stabilizer::parser::NT_POW, stabilizer::parser::NT_SUB, and pow().
operator!()
Interval stabilizer::parser::Interval::operator! () const
Definition at line 402 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
operator!=()
bool stabilizer::parser::Interval::operator!= (const Interval & other) const
Definition at line 58 of file interval.cpp.
operator%() [1/2]
Interval stabilizer::parser::Interval::operator% (const Interval & other) const
Definition at line 1686 of file interval.cpp.
References mod().
operator%() [2/2]
Interval stabilizer::parser::Interval::operator% (const Number & value) const
Definition at line 1690 of file interval.cpp.
References mod().
operator*() [1/2]
Interval stabilizer::parser::Interval::operator* (const Interval & other) const
Definition at line 1412 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
operator*() [2/2]
Interval stabilizer::parser::Interval::operator* (const Number & value) const
Definition at line 1364 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
operator*=()
Interval & stabilizer::parser::Interval::operator*= (const Number & value)
Definition at line 2247 of file interval.cpp.
References leftClosed, lower, rightClosed, and upper.
operator+() [1/3]
Interval stabilizer::parser::Interval::operator+ () const
Definition at line 390 of file interval.cpp.
References stabilizer::parser::EmptyInterval, and isEmpty().
operator+() [2/3]
Interval stabilizer::parser::Interval::operator+ (const Interval & other) const
Definition at line 1398 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
operator+() [3/3]
Interval stabilizer::parser::Interval::operator+ (const Number & value) const
Definition at line 1356 of file interval.cpp.
References Interval(), leftClosed, lower, rightClosed, and upper.
operator++() [1/2]
Interval stabilizer::parser::Interval::operator++ () const
Definition at line 372 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
operator++() [2/2]
Interval stabilizer::parser::Interval::operator++ (int) const
Definition at line 408 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
operator+=()
Interval & stabilizer::parser::Interval::operator+= (const Number & value)
Definition at line 2235 of file interval.cpp.
References lower, and upper.
operator-() [1/3]
Interval stabilizer::parser::Interval::operator- () const
Definition at line 384 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
operator-() [2/3]
Interval stabilizer::parser::Interval::operator- (const Interval & other) const
Definition at line 1405 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
operator-() [3/3]
Interval stabilizer::parser::Interval::operator- (const Number & value) const
Definition at line 1360 of file interval.cpp.
References Interval(), leftClosed, lower, rightClosed, and upper.
operator--() [1/2]
Interval stabilizer::parser::Interval::operator-- () const
Definition at line 378 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
operator--() [2/2]
Interval stabilizer::parser::Interval::operator-- (int) const
Definition at line 414 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
operator-=()
Interval & stabilizer::parser::Interval::operator-= (const Number & value)
Definition at line 2241 of file interval.cpp.
References lower, and upper.
operator/() [1/2]
Interval stabilizer::parser::Interval::operator/ (const Interval & other) const
Definition at line 1454 of file interval.cpp.
References divReal().
operator/() [2/2]
Interval stabilizer::parser::Interval::operator/ (const Number & value) const
Definition at line 1383 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
operator/=()
Interval & stabilizer::parser::Interval::operator/= (const Number & value)
Definition at line 2263 of file interval.cpp.
References leftClosed, lower, rightClosed, and upper.
operator<()
bool stabilizer::parser::Interval::operator< (const Interval & other) const
Definition at line 2191 of file interval.cpp.
References isEmpty(), leftClosed, lower, rightClosed, and upper.
operator<=()
bool stabilizer::parser::Interval::operator<= (const Interval & other) const
Definition at line 2204 of file interval.cpp.
References isEmpty().
operator=()
Interval & stabilizer::parser::Interval::operator= (const Interval & other)
Definition at line 43 of file interval.cpp.
References leftClosed, lower, rightClosed, and upper.
operator==()
bool stabilizer::parser::Interval::operator== (const Interval & other) const
Definition at line 53 of file interval.cpp.
References leftClosed, lower, rightClosed, and upper.
operator>()
bool stabilizer::parser::Interval::operator> (const Interval & other) const
Definition at line 2213 of file interval.cpp.
References isEmpty(), leftClosed, lower, rightClosed, and upper.
operator>=()
bool stabilizer::parser::Interval::operator>= (const Interval & other) const
Definition at line 2226 of file interval.cpp.
References isEmpty().
operator^() [1/2]
Interval stabilizer::parser::Interval::operator^ (const Interval & other) const
Definition at line 1694 of file interval.cpp.
References pow().
operator^() [2/2]
Interval stabilizer::parser::Interval::operator^ (const Number & value) const
Definition at line 1698 of file interval.cpp.
References pow().
operator~()
Interval stabilizer::parser::Interval::operator~ () const
Definition at line 396 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), leftClosed, lower, rightClosed, and upper.
pow() [1/2]
Interval stabilizer::parser::Interval::pow (const Interval & exp) const
Definition at line 1911 of file interval.cpp.
References stabilizer::parser::EmptyInterval, exp(), stabilizer::parser::FullInterval, getLower(), getUpper(), Interval(), isEmpty(), stabilizer::parser::Number::isInteger(), isLeftClosed(), stabilizer::parser::Number::isNegativeInfinity(), isPoint(), stabilizer::parser::Number::isPositiveInfinity(), isRightClosed(), leftClosed, lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::positiveInfinity(), pow(), stabilizer::parser::Number::pow(), pow2(), rightClosed, stabilizer::parser::Number::toInteger(), and upper.
pow() [2/2]
Interval stabilizer::parser::Interval::pow (const Number & exp) const
Definition at line 1755 of file interval.cpp.
References stabilizer::parser::Number::abs(), stabilizer::parser::EmptyInterval, exp(), Interval(), isEmpty(), stabilizer::parser::Number::isInfinity(), leftClosed, lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::positiveInfinity(), stabilizer::parser::Number::pow(), rightClosed, and upper.
Referenced by operate(), operator^(), stabilizer::parser::Value::pow(), and pow().
pow2()
Interval stabilizer::parser::Interval::pow2 () const
Definition at line 1702 of file interval.cpp.
References condAssert, stabilizer::parser::EmptyInterval, Interval(), isEmpty(), stabilizer::parser::Number::isInteger(), isLeftClosed(), stabilizer::parser::Number::isNegativeInfinity(), stabilizer::parser::Number::isPositiveInfinity(), isRightClosed(), lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::positiveInfinity(), stabilizer::parser::Number::pow(), stabilizer::parser::Number::toInteger(), and upper.
Referenced by pow().
safeSqrt()
Interval stabilizer::parser::Interval::safeSqrt () const
Definition at line 654 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), stabilizer::parser::Number::isPositiveInfinity(), leftClosed, lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::positiveInfinity(), rightClosed, stabilizer::parser::Number::safeSqrt(), and upper.
Referenced by operate(), and stabilizer::parser::Value::safeSqrt().
sec()
Interval stabilizer::parser::Interval::sec () const
Definition at line 923 of file interval.cpp.
References contains(), cos(), stabilizer::parser::EmptyInterval, Interval(), isEmpty(), stabilizer::parser::Number::negativeInfinity(), and stabilizer::parser::Number::positiveInfinity().
Referenced by operate(), and stabilizer::parser::Value::sec().
sech()
Interval stabilizer::parser::Interval::sech () const
Definition at line 1191 of file interval.cpp.
References cosh(), stabilizer::parser::EmptyInterval, getLower(), getUpper(), Interval(), and isEmpty().
Referenced by operate(), and stabilizer::parser::Value::sech().
setLeftClosed()
void stabilizer::parser::Interval::setLeftClosed (bool leftClosed)
Definition at line 76 of file interval.cpp.
References leftClosed.
setLower()
void stabilizer::parser::Interval::setLower (const Number & lower)
Definition at line 62 of file interval.cpp.
References lower, and upper.
setRightClosed()
void stabilizer::parser::Interval::setRightClosed (bool rightClosed)
Definition at line 78 of file interval.cpp.
References rightClosed.
setUpper()
void stabilizer::parser::Interval::setUpper (const Number & upper)
Definition at line 69 of file interval.cpp.
References lower, and upper.
sin()
Interval stabilizer::parser::Interval::sin () const
Definition at line 697 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), stabilizer::parser::Number::isInfinity(), leftClosed, lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::pi(), rightClosed, stabilizer::parser::Number::sin(), and upper.
Referenced by csc(), operate(), and stabilizer::parser::Value::sin().
sinh()
Interval stabilizer::parser::Interval::sinh () const
Definition at line 1078 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::sinh(), and upper.
Referenced by csch(), operate(), and stabilizer::parser::Value::sinh().
sqrt()
Interval stabilizer::parser::Interval::sqrt () const
Definition at line 612 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), stabilizer::parser::Number::isPositiveInfinity(), leftClosed, lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::positiveInfinity(), rightClosed, stabilizer::parser::Number::sqrt(), and upper.
Referenced by operate(), and stabilizer::parser::Value::sqrt().
sub() [1/2]
Interval stabilizer::parser::Interval::sub (const Interval & other) const
Definition at line 1464 of file interval.cpp.
sub() [2/2]
Interval stabilizer::parser::Interval::sub (const Number & value) const
Definition at line 1462 of file interval.cpp.
tan()
Interval stabilizer::parser::Interval::tan () const
Definition at line 849 of file interval.cpp.
References stabilizer::parser::EmptyInterval, stabilizer::parser::FullInterval, Interval(), isEmpty(), stabilizer::parser::Number::isInfinity(), leftClosed, lower, stabilizer::parser::Number::negativeInfinity(), stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::pi(), stabilizer::parser::Number::positiveInfinity(), rightClosed, stabilizer::parser::Number::tan(), and upper.
Referenced by cot(), operate(), and stabilizer::parser::Value::tan().
tanh()
Interval stabilizer::parser::Interval::tanh () const
Definition at line 1155 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isEmpty(), lower, stabilizer::parser::Number::nextAbove(), stabilizer::parser::Number::nextBelow(), stabilizer::parser::Number::tanh(), and upper.
Referenced by operate(), and stabilizer::parser::Value::tanh().
toString()
std::string stabilizer::parser::Interval::toString () const
Definition at line 88 of file interval.cpp.
References leftClosed, lower, rightClosed, stabilizer::parser::Number::toString(), and upper.
Referenced by stabilizer::parser::Value::toString().
unionMulti()
std::vector< Interval > stabilizer::parser::Interval::unionMulti (const std::vector< Interval > & intervals) static
Definition at line 324 of file interval.cpp.
References Interval(), isDisjointFrom(), leftClosed, lower, rightClosed, and upper.
unionWith()
Interval stabilizer::parser::Interval::unionWith (const Interval & other) const
Definition at line 209 of file interval.cpp.
References stabilizer::parser::EmptyInterval, Interval(), isDisjointFrom(), isEmpty(), leftClosed, lower, rightClosed, and upper.
Referenced by operate().
width()
Number stabilizer::parser::Interval::width () const
Definition at line 121 of file interval.cpp.
References isEmpty(), lower, and upper.
Member Data Documentation
leftClosed
bool stabilizer::parser::Interval::leftClosed private
Definition at line 45 of file interval.h.
Referenced by abs(), acos(), atan2(), contains(), cos(), difference(), divInt(), divReal(), getIntervalIntCount(), intersection(), isDisjointFrom(), isEmpty(), isLeftClosed(), isSubsetEqOf(), isSubsetOf(), isSupersetOf(), mod(), negate(), operator!(), operator*(), operator*=(), operator+(), operator++(), operator-(), operator--(), operator/(), operator/=(), operator<(), operator=(), operator==(), operator>(), operator~(), pow(), safeSqrt(), setLeftClosed(), sin(), sqrt(), tan(), toString(), unionMulti(), and unionWith().
lower
Number stabilizer::parser::Interval::lower private
Definition at line 43 of file interval.h.
Referenced by abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atan2(), atanh(), contains(), cos(), cosh(), coth(), csch(), difference(), divInt(), divReal(), exp(), getIntegers(), getIntervalIntCount(), getLower(), intersection(), isDisjointFrom(), isEmpty(), isLeftUnbounded(), isPoint(), isSubsetEqOf(), isSubsetOf(), isSupersetOf(), lb(), lg(), ln(), midpoint(), mod(), negate(), operate(), operator!(), operator*(), operator*=(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), operator/(), operator/=(), operator<(), operator=(), operator==(), operator>(), operator~(), pow(), pow2(), safeSqrt(), setLower(), setUpper(), sin(), sinh(), sqrt(), tan(), tanh(), toString(), unionMulti(), unionWith(), and width().
rightClosed
bool stabilizer::parser::Interval::rightClosed private
Definition at line 46 of file interval.h.
Referenced by abs(), acos(), atan2(), contains(), cos(), difference(), divInt(), divReal(), getIntervalIntCount(), intersection(), isDisjointFrom(), isEmpty(), isRightClosed(), isSubsetEqOf(), isSubsetOf(), isSupersetOf(), mod(), negate(), operator!(), operator*(), operator*=(), operator+(), operator++(), operator-(), operator--(), operator/(), operator/=(), operator<(), operator=(), operator==(), operator>(), operator~(), pow(), safeSqrt(), setRightClosed(), sin(), sqrt(), tan(), toString(), unionMulti(), and unionWith().
upper
Number stabilizer::parser::Interval::upper private
Definition at line 44 of file interval.h.
Referenced by abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atan2(), atanh(), contains(), cos(), cosh(), coth(), csch(), difference(), divInt(), divReal(), exp(), getIntegers(), getIntervalIntCount(), getUpper(), intersection(), isDisjointFrom(), isEmpty(), isPoint(), isRightUnbounded(), isSubsetEqOf(), isSubsetOf(), isSupersetOf(), lb(), lg(), ln(), midpoint(), mod(), negate(), operate(), operator!(), operator*(), operator*=(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), operator/(), operator/=(), operator<(), operator=(), operator==(), operator>(), operator~(), pow(), pow2(), safeSqrt(), setLower(), setUpper(), sin(), sinh(), sqrt(), tan(), tanh(), toString(), unionMulti(), unionWith(), and width().
The documentation for this class was generated from the following files:
src/parser/interval.h
src/parser/interval.cpp