SMTStabilizer API: stabilizer::parser::TypeChecker Class Reference
stabilizer::parser::TypeChecker Class Reference
Lexical classifiers for SMT-LIB literals and token shapes.
#include <util.h>
Static Public Member Functions
static bool isInt (const std::string &str)
static bool isReal (const std::string &str)
static bool isBV (const std::string &str)
static bool isFP (const std::string &str)
static bool isString (const std::string &str)
static bool isScientificNotation (const std::string &str)
static bool isNumber (const std::string &str)
Detailed Description
Lexical classifiers for SMT-LIB literals and token shapes.
Definition at line 48 of file util.h.
Member Function Documentation
isBV()
bool stabilizer::parser::TypeChecker::isBV (const std::string & str) static
Definition at line 219 of file util.cpp.
Referenced by stabilizer::parser::Parser::getSymbol(), and stabilizer::parser::Parser::parseConstFunc().
isFP()
bool stabilizer::parser::TypeChecker::isFP (const std::string & str) static
Definition at line 248 of file util.cpp.
Referenced by stabilizer::parser::Parser::getSymbol(), and stabilizer::parser::Parser::parseConstFunc().
isInt()
bool stabilizer::parser::TypeChecker::isInt (const std::string & str) static
Definition at line 47 of file util.cpp.
Referenced by stabilizer::parser::DAGNode::DAGNode(), stabilizer::parser::Parser::ensureNumberValue(), stabilizer::parser::Parser::getSymbol(), isNumber(), stabilizer::parser::Parser::parseConstFunc(), and stabilizer::parser::Parser::rewrite().
isNumber()
bool stabilizer::parser::TypeChecker::isNumber (const std::string & str) static
Definition at line 43 of file util.cpp.
References isInt(), and isReal().
Referenced by stabilizer::parser::Parser::getSymbol(), and stabilizer::parser::Parser::parseConstFunc().
isReal()
bool stabilizer::parser::TypeChecker::isReal (const std::string & str) static
Definition at line 58 of file util.cpp.
Referenced by stabilizer::parser::DAGNode::DAGNode(), stabilizer::parser::Parser::ensureNumberValue(), stabilizer::parser::Parser::getSymbol(), isNumber(), isScientificNotation(), stabilizer::parser::Parser::mkConstReal(), stabilizer::parser::Parser::parseConstFunc(), and stabilizer::parser::ConversionUtils::parseScientificNotation().
isScientificNotation()
bool stabilizer::parser::TypeChecker::isScientificNotation (const std::string & str) static
Definition at line 75 of file util.cpp.
References isReal().
Referenced by stabilizer::parser::Parser::getSymbol(), and stabilizer::parser::Parser::parseConstFunc().
isString()
bool stabilizer::parser::TypeChecker::isString (const std::string & str) static
Definition at line 259 of file util.cpp.
Referenced by stabilizer::parser::DAGNode::DAGNode(), stabilizer::parser::Parser::getSymbol(), and stabilizer::parser::Parser::parseConstFunc().
The documentation for this class was generated from the following files:
src/parser/util.h
src/parser/util.cpp