SMTStabilizer API: stabilizer::util::BitVector Class Reference
stabilizer::util::BitVector Class Reference
#include <bitvector.h>
Public Member Functions
BitVector ()
BitVector (uint64_t size)
BitVector (uint64_t size, const std::string &value, uint32_t base=2)
BitVector (uint64_t size, const mpz_t value, bool truncate=false)
BitVector (const BitVector &other)
BitVector (BitVector &&other)
~BitVector ()
BitVector & operator= (const BitVector &other)
size_t hash () const
bool is_null () const
void iset (uint64_t value)
void iset (const BitVector &bv)
bool operator== (const BitVector &bv) const
bool operator!= (const BitVector &bv) const
std::string str (uint32_t base=2) const
uint64_t to_uint64 (bool truncate=false) const
uint64_t size () const
int32_t compare (const BitVector &bv) const
int32_t signed_compare (const BitVector &bv) const
bool bit (uint64_t idx) const
void set_bit (uint64_t idx, bool value)
void flip_bit (uint64_t idx)
bool lsb () const
bool msb () const
bool is_true () const
bool is_false () const
bool is_zero () const
bool is_ones () const
bool is_one () const
bool is_min_signed () const
bool is_max_signed () const
bool is_power_of_two () const
bool is_neg_overflow () const
bool is_uadd_overflow (const BitVector &bv) const
bool is_sadd_overflow (const BitVector &bv) const
bool is_usub_overflow (const BitVector &bv) const
bool is_ssub_overflow (const BitVector &bv) const
bool is_umul_overflow (const BitVector &bv) const
bool is_smul_overflow (const BitVector &bv) const
bool is_sdiv_overflow (const BitVector &bv) const
uint64_t count_trailing_zeros () const
uint64_t count_trailing_ones () const
uint64_t count_leading_zeros () const
uint64_t count_leading_ones () const
BitVector bvneg () const
BitVector bvnot () const
BitVector bvinc () const
BitVector bvdec () const
BitVector bvredand () const
BitVector bvredor () const
BitVector bvredxor () const
BitVector bvnego () const
BitVector bvadd (const BitVector &bv) const
BitVector bvsub (const BitVector &bv) const
BitVector bvand (const BitVector &bv) const
BitVector bvimplies (const BitVector &bv) const
BitVector bvnand (const BitVector &bv) const
BitVector bvnor (const BitVector &bv) const
BitVector bvor (const BitVector &bv) const
BitVector bvxnor (const BitVector &bv) const
BitVector bvxor (const BitVector &bv) const
BitVector bveq (const BitVector &bv) const
BitVector bvne (const BitVector &bv) const
BitVector bvult (const BitVector &bv) const
BitVector bvule (const BitVector &bv) const
BitVector bvugt (const BitVector &bv) const
BitVector bvuge (const BitVector &bv) const
BitVector bvslt (const BitVector &bv) const
BitVector bvsle (const BitVector &bv) const
BitVector bvsgt (const BitVector &bv) const
BitVector bvsge (const BitVector &bv) const
BitVector bvshl (uint64_t shift) const
BitVector bvshl (const BitVector &bv) const
BitVector bvshr (uint64_t shift) const
BitVector bvshr (const BitVector &bv) const
BitVector bvashr (uint64_t shift) const
BitVector bvashr (const BitVector &bv) const
BitVector bvmul (const BitVector &bv) const
BitVector bvudiv (const BitVector &bv) const
BitVector bvurem (const BitVector &bv) const
BitVector bvsdiv (const BitVector &bv) const
BitVector bvsrem (const BitVector &bv) const
BitVector bvsmod (const BitVector &bv) const
BitVector bvuaddo (const BitVector &bv) const
BitVector bvsaddo (const BitVector &bv) const
BitVector bvusubo (const BitVector &bv) const
BitVector bvssubo (const BitVector &bv) const
BitVector bvumulo (const BitVector &bv) const
BitVector bvsmulo (const BitVector &bv) const
BitVector bvsdivo (const BitVector &bv) const
BitVector bvconcat (const BitVector &bv) const
BitVector bvextract (uint64_t idx_hi, uint64_t idx_lo) const
BitVector bvzext (uint64_t n) const
BitVector bvsext (uint64_t n) const
BitVector bvrepeat (uint64_t n) const
BitVector bvroli (uint64_t n) const
BitVector bvrol (const BitVector &n) const
BitVector bvrori (uint64_t n) const
BitVector bvror (const BitVector &n) const
BitVector bvmodinv () const
BitVector bvpow (const mpz_t exp) const
BitVector & ibvneg (const BitVector &bv)
BitVector & ibvneg ()
BitVector & ibvnot (const BitVector &bv)
BitVector & ibvnot ()
BitVector & ibvinc (const BitVector &bv)
BitVector & ibvinc ()
BitVector & ibvdec (const BitVector &bv)
BitVector & ibvdec ()
BitVector & ibvredand (const BitVector &bv)
BitVector & ibvredand ()
BitVector & ibvredor (const BitVector &bv)
BitVector & ibvredor ()
BitVector & ibvredxor (const BitVector &bv)
BitVector & ibvredxor ()
BitVector & ibvnego (const BitVector &bv)
BitVector & ibvnego ()
BitVector & ibvadd (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvadd (const BitVector &bv)
BitVector & ibvand (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvand (const BitVector &bv)
BitVector & ibvimplies (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvimplies (const BitVector &bv)
BitVector & ibvnand (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvnand (const BitVector &bv)
BitVector & ibvnor (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvnor (const BitVector &bv)
BitVector & ibvor (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvor (const BitVector &bv)
BitVector & ibvsub (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvsub (const BitVector &bv)
BitVector & ibvxnor (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvxnor (const BitVector &bv)
BitVector & ibvxor (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvxor (const BitVector &bv)
BitVector & ibveq (const BitVector &bv0, const BitVector &bv1)
BitVector & ibveq (const BitVector &bv)
BitVector & ibvne (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvne (const BitVector &bv)
BitVector & ibvult (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvult (const BitVector &bv)
BitVector & ibvule (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvule (const BitVector &bv)
BitVector & ibvugt (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvugt (const BitVector &bv)
BitVector & ibvuge (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvuge (const BitVector &bv)
BitVector & ibvslt (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvslt (const BitVector &bv)
BitVector & ibvsle (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvsle (const BitVector &bv)
BitVector & ibvsgt (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvsgt (const BitVector &bv)
BitVector & ibvsge (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvsge (const BitVector &bv)
BitVector & ibvshl (const BitVector &bv, uint64_t shift)
BitVector & ibvshl (uint64_t shift)
BitVector & ibvshl (const BitVector &bv, const BitVector &shift)
BitVector & ibvshl (const BitVector &bv)
BitVector & ibvshr (const BitVector &bv, uint64_t shift)
BitVector & ibvshr (uint64_t shift)
BitVector & ibvshr (const BitVector &bv, const BitVector &shift)
BitVector & ibvshr (const BitVector &bv)
BitVector & ibvashr (const BitVector &bv, uint64_t shift)
BitVector & ibvashr (uint64_t shift)
BitVector & ibvashr (const BitVector &bv, const BitVector &arithmetic)
BitVector & ibvashr (const BitVector &bv)
BitVector & ibvmul (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvmul (const BitVector &bv)
BitVector & ibvudiv (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvudiv (const BitVector &bv)
BitVector & ibvurem (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvurem (const BitVector &bv)
BitVector & ibvsdiv (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvsdiv (const BitVector &bv)
BitVector & ibvsrem (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvsrem (const BitVector &bv)
BitVector & ibvsmod (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvsmod (const BitVector &bv)
BitVector & ibvuaddo (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvuaddo (const BitVector &bv)
BitVector & ibvsaddo (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvsaddo (const BitVector &bv)
BitVector & ibvusubo (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvusubo (const BitVector &bv)
BitVector & ibvssubo (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvssubo (const BitVector &bv)
BitVector & ibvumulo (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvumulo (const BitVector &bv)
BitVector & ibvsmulo (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvsmulo (const BitVector &bv)
BitVector & ibvsdivo (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvsdivo (const BitVector &bv)
BitVector & ibvconcat (const BitVector &bv0, const BitVector &bv1)
BitVector & ibvconcat (const BitVector &bv)
BitVector & ibvextract (const BitVector &bv, uint64_t idx_hi, uint64_t idx_lo)
BitVector & ibvextract (uint64_t idx_hi, uint64_t idx_lo)
BitVector & ibvzext (const BitVector &bv, uint64_t n)
BitVector & ibvzext (uint64_t n)
BitVector & ibvsext (const BitVector &bv, uint64_t n)
BitVector & ibvsext (uint64_t n)
BitVector & ibvrepeat (const BitVector &bv, uint64_t n)
BitVector & ibvrepeat (uint64_t n)
BitVector & ibvroli (const BitVector &bv, uint64_t n)
BitVector & ibvroli (uint64_t n)
BitVector & ibvrori (const BitVector &bv, uint64_t n)
BitVector & ibvrori (uint64_t n)
BitVector & ibvrol (const BitVector &bv, const BitVector &n)
BitVector & ibvrol (const BitVector &n)
BitVector & ibvror (const BitVector &bv, const BitVector &n)
BitVector & ibvror (const BitVector &n)
BitVector & ibvite (const BitVector &c, const BitVector &t, const BitVector &e)
BitVector & ibvmodinv (const BitVector &bv)
BitVector & ibvmodinv ()
BitVector & ibvpow (const BitVector &base, const mpz_t exp)
BitVector & ibvpow (const mpz_t exp)
void bvudivurem (const BitVector &bv, BitVector *quot, BitVector *rem) const
const mpz_t & gmp_value () const
mpz_class to_mpz () const
Static Public Member Functions
static bool fits_in_size (uint64_t size, const std::string &str, uint32_t base)
static bool fits_in_size (uint64_t size, uint64_t value, bool sign=false)
static bool fits_in_size (uint64_t size, const mpz_t value)
static BitVector from_ui (uint64_t size, uint64_t value, bool truncate=false)
static BitVector from_si (uint64_t size, int64_t value, bool truncate=false)
static BitVector mk_true ()
static BitVector mk_false ()
static BitVector mk_zero (uint64_t size)
static BitVector mk_one (uint64_t size)
static BitVector mk_ones (uint64_t size)
static BitVector mk_min_signed (uint64_t size)
static BitVector mk_max_signed (uint64_t size)
static BitVector bvite (const BitVector &c, const BitVector &t, const BitVector &e)
Static Public Attributes
static constexpr size_t s_native_size = sizeof(unsigned long) * 8
Private Member Functions
uint64_t count_leading (bool zeros) const
bool shift_is_uint64 (uint64_t *res) const
uint64_t get_limb (void *limb, uint64_t nbits_rem, bool zeros) const
bool is_gmp () const
Static Private Member Functions
static uint64_t uint64_fdiv_r_2exp (uint64_t size, uint64_t val)
Private Attributes
uint64_t d_size = 0
union {
uint64_t d_val_uint64
mpz_t d_val_gmp
};
Detailed Description
Definition at line 35 of file bitvector.h.
Constructor & Destructor Documentation
BitVector() [1/6]
stabilizer::util::BitVector::BitVector ()
Default constructor.
Definition at line 170 of file bitvector.cpp.
Referenced by bvadd(), bvand(), bvashr(), bvconcat(), bvdec(), bveq(), bvextract(), bvimplies(), bvinc(), bvmul(), bvnand(), bvne(), bvneg(), bvnor(), bvnot(), bvor(), bvredand(), bvredxor(), bvrepeat(), bvrol(), bvroli(), bvror(), bvrori(), bvsaddo(), bvsdiv(), bvsdivo(), bvsext(), bvsge(), bvsgt(), bvshl(), bvshr(), bvsle(), bvslt(), bvsmod(), bvsmulo(), bvsrem(), bvssubo(), bvsub(), bvuaddo(), bvudiv(), bvuge(), bvugt(), bvule(), bvult(), bvumulo(), bvurem(), bvusubo(), bvxnor(), bvxor(), bvzext(), and count_leading_ones().
BitVector() [2/6]
stabilizer::util::BitVector::BitVector (uint64_t size)
Construct a zero bit-vector of given size.
Parameters
size The size of the bit-vector.
Definition at line 172 of file bitvector.cpp.
BitVector() [3/6]
stabilizer::util::BitVector::BitVector (uint64_t size, const std::string & value, uint32_t base = 2)
Construct a bit-vector of given size from given binary string.
Parameters
size The size of the bit-vector, must be >= the length of value.
value A string representing the value of the bit-vector. If the length of this string is > size, the value is zero extended.
base The base the string is given in (2 for binary, 10 for decimal, 16 for hexadecimal).
Definition at line 179 of file bitvector.cpp.
BitVector() [4/6]
stabilizer::util::BitVector::BitVector (uint64_t size, const mpz_t value, bool truncate = false)
Construct a bit-vector of given size from given GMP value.
Parameters
size The size of the bit-vector.
value A GMP value representing the bit-vector value. The value must be representable with size bits if truncate is false.
truncate True to allow truncating the value if it is not representable with size bits.
Definition at line 200 of file bitvector.cpp.
BitVector() [5/6]
stabilizer::util::BitVector::BitVector (const BitVector & other)
Copy constructor.
Definition at line 254 of file bitvector.cpp.
BitVector() [6/6]
stabilizer::util::BitVector::BitVector (BitVector && other)
Move constructor.
Definition at line 272 of file bitvector.cpp.
~BitVector()
stabilizer::util::BitVector::~BitVector ()
Destructor.
Definition at line 295 of file bitvector.cpp.
References d_size, d_val_gmp, and is_gmp().
Member Function Documentation
bit()
bool stabilizer::util::BitVector::bit (uint64_t idx) const
Determine the value of the bit at given index.
Parameters
idx The index of the bit.
Returns
True if the bit at given index is 1, and false otherwise.
Definition at line 480 of file bitvector.cpp.
References d_size, d_val_gmp, is_gmp(), and is_null().
Referenced by count_trailing_ones(), and count_trailing_zeros().
bvadd()
BitVector stabilizer::util::BitVector::bvadd (const BitVector & bv) const
Create a bit-vector representing the addition of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the addition.
Definition at line 789 of file bitvector.cpp.
References BitVector(), and d_size.
bvand()
BitVector stabilizer::util::BitVector::bvand (const BitVector & bv) const
Create a bit-vector representing the bit-wise and of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the bit-wise and.
Definition at line 797 of file bitvector.cpp.
References BitVector(), and d_size.
bvashr() [1/2]
BitVector stabilizer::util::BitVector::bvashr (const BitVector & bv) const
Create a bit-vector representing the arithmetic right shift of this bit-vector by the given bit-vector shift value.
Parameters
bv A bit-vector representing the number of bits to shift this bit-vector to the right.
Returns
A bit-vector representing the result of the arithmetic right shift.
Definition at line 885 of file bitvector.cpp.
References BitVector(), and d_size.
bvashr() [2/2]
BitVector stabilizer::util::BitVector::bvashr (uint64_t shift) const
Create a bit-vector representing the arithmetic right shift of this bit-vector by the given unsigned integer shift value.
Parameters
shift An unsigned integer representing the number of bits to shift this bit-vector to the right.
Returns
A bit-vector representing the result of the arithmetic right shift.
Definition at line 881 of file bitvector.cpp.
References BitVector(), and d_size.
bvconcat()
BitVector stabilizer::util::BitVector::bvconcat (const BitVector & bv) const
Create a bit-vector representing the concatenation of this bit-vector and the given bit-vector. The given bit-vector is concatenated (at the right, the lsb side) to this bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the concatenation.
Definition at line 941 of file bitvector.cpp.
References BitVector(), and d_size.
bvdec()
BitVector stabilizer::util::BitVector::bvdec () const
Create a bit-vector representing the decrement (- 1) of this bit-vector.
Returns
The decrement of this bit-vector.
Definition at line 779 of file bitvector.cpp.
References BitVector().
bveq()
BitVector stabilizer::util::BitVector::bveq (const BitVector & bv) const
Create a bit-vector representing the equality of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the equality.
Definition at line 825 of file bitvector.cpp.
References BitVector().
bvextract()
BitVector stabilizer::util::BitVector::bvextract (uint64_t idx_hi, uint64_t idx_lo) const
Create a bit-vector representing the extract of a given bit range from this bit-vector.
Parameters
idx_hi The upper bit-index of the range (inclusive).
idx_lo The lower bit-index of the range (inclusive).
Returns
A bit-vector representing the extracted bit range.
Definition at line 945 of file bitvector.cpp.
References BitVector(), and d_size.
bvimplies()
BitVector stabilizer::util::BitVector::bvimplies (const BitVector & bv) const
Create a bit-vector representing the implication of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the implication.
Definition at line 801 of file bitvector.cpp.
References BitVector(), and d_size.
bvinc()
BitVector stabilizer::util::BitVector::bvinc () const
Create a bit-vector representing the increment (+ 1) of this bit-vector.
Returns
The increment of this bit-vector.
Definition at line 777 of file bitvector.cpp.
References BitVector().
bvite()
BitVector stabilizer::util::BitVector::bvite (const BitVector & c, const BitVector & t, const BitVector & e) static
Create an if-then-else (ite) over the given bit-vectors.
Parameters
c A bit-vector representing the condition of the ite.
t A bit-vector representing the then branch of the ite.
e A bit-vector representing the else branch of the ite.
Returns
A bit-vector representing the ite.
Definition at line 161 of file bitvector.cpp.
bvmodinv()
BitVector stabilizer::util::BitVector::bvmodinv () const
Calculate modular inverse for this bit-vector by means of the Extended Euclidean Algorithm.
Note
Bit-vector must be odd. The greatest common divisor gcd (c, 2^bw) must be (and is, in this case) always 1.
Returns
A bit-vector representing the modular inverse of this bit-vector.
Definition at line 977 of file bitvector.cpp.
bvmul()
BitVector stabilizer::util::BitVector::bvmul (const BitVector & bv) const
Create a bit-vector representing the multiplication of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the multiplication.
Definition at line 889 of file bitvector.cpp.
References BitVector(), and d_size.
bvnand()
BitVector stabilizer::util::BitVector::bvnand (const BitVector & bv) const
Create a bit-vector representing the bit-wise nand of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the bit-wise nand.
Definition at line 805 of file bitvector.cpp.
References BitVector(), and d_size.
bvne()
BitVector stabilizer::util::BitVector::bvne (const BitVector & bv) const
Create a bit-vector representing the disequality of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the disequality.
Definition at line 829 of file bitvector.cpp.
References BitVector().
bvneg()
BitVector stabilizer::util::BitVector::bvneg () const
Create a bit-vector representing the two's complement negation of this bit-vector.
Returns
The two's complement of this bit-vector.
Definition at line 773 of file bitvector.cpp.
References BitVector().
bvnego()
BitVector stabilizer::util::BitVector::bvnego () const
Create a bit-vector representing a predicate that indicates if bit-vector negation produces an overflow.
Returns
A bit-vector of size 1, representing the result of the overflow check.
Definition at line 787 of file bitvector.cpp.
bvnor()
BitVector stabilizer::util::BitVector::bvnor (const BitVector & bv) const
Create a bit-vector representing the bit-wise nor of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the bit-wise nor.
Definition at line 809 of file bitvector.cpp.
References BitVector(), and d_size.
bvnot()
BitVector stabilizer::util::BitVector::bvnot () const
Create a bit-vector representing the bit-wise negation of this bit-vector.
Returns
The bit-wise negation of this bit-vector.
Definition at line 775 of file bitvector.cpp.
References BitVector().
bvor()
BitVector stabilizer::util::BitVector::bvor (const BitVector & bv) const
Create a bit-vector representing the bit-wise or of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the bit-wise or.
Definition at line 813 of file bitvector.cpp.
References BitVector(), and d_size.
bvpow()
BitVector stabilizer::util::BitVector::bvpow (const mpz_t exp) const
Calculate a bit-vector representing this bit-vector exponentiated by exp.
Parameters
exp The exponent GMP value.
Returns
A bit-vector representing the result of the exponentiation.
Definition at line 981 of file bitvector.cpp.
References d_size, d_val_gmp, ibvnot(), is_gmp(), is_null(), and stabilizer::util::mpz_fdiv_r_2exp_ull().
bvredand()
BitVector stabilizer::util::BitVector::bvredand () const
Create a bit-vector representing the and reduction of this bit-vector.
Returns
A bit-vector of size 1, representing the result of the and reduction of this bit-vector (1 if all bits of this bit-vector are one, and 0 otherwise).
Definition at line 781 of file bitvector.cpp.
References BitVector(), and d_size.
bvredor()
BitVector stabilizer::util::BitVector::bvredor () const
Create a bit-vector representing the or reduction of this bit-vector.
Returns
A bit-vector of size 1, representing the result of the or reduction of this bit-vector (1 if at least one bit of this bit-vector is one, and 0 otherwise).
Definition at line 783 of file bitvector.cpp.
bvredxor()
BitVector stabilizer::util::BitVector::bvredxor () const
Create a bit-vector representing the xor reduction of this bit-vector.
Returns
A bit-vector of size 1, representing the result of the xor reduction of this bit-vector (1 if an uneven number of bits is set to 1, and 0 otherwise).
Definition at line 785 of file bitvector.cpp.
References BitVector(), and d_size.
bvrepeat()
BitVector stabilizer::util::BitVector::bvrepeat (uint64_t n) const
Create a bit-vector representing this bit-vector repeated n times.
Parameters
n The number of times to repeat this bit-vector, must be > 0.
Returns
A bit-vector representing the result of the repeat operation.
Definition at line 957 of file bitvector.cpp.
References BitVector(), and d_size.
bvrol()
BitVector stabilizer::util::BitVector::bvrol (const BitVector & n) const
Create a bit-vector representing this bit-vector rotated left by n bits.
Parameters
n The number of bits to rotate this bit-vector by.
Returns
A bit-vector representing the result of the rotation.
Definition at line 965 of file bitvector.cpp.
References BitVector(), and d_size.
bvroli()
BitVector stabilizer::util::BitVector::bvroli (uint64_t n) const
Create a bit-vector representing this bit-vector rotated left by n bits.
Parameters
n The number of bits to rotate this bit-vector by.
Returns
A bit-vector representing the result of the rotation.
Definition at line 961 of file bitvector.cpp.
References BitVector(), and d_size.
bvror()
BitVector stabilizer::util::BitVector::bvror (const BitVector & n) const
Create a bit-vector representing this bit-vector rotated right by n bits.
Parameters
n The number of bits to rotate this bit-vector by.
Returns
A bit-vector representing the result of the rotation.
Definition at line 973 of file bitvector.cpp.
References BitVector(), and d_size.
bvrori()
BitVector stabilizer::util::BitVector::bvrori (uint64_t n) const
Create a bit-vector representing this bit-vector rotated right by n bits.
Parameters
n The number of bits to rotate this bit-vector by.
Returns
A bit-vector representing the result of the rotation.
Definition at line 969 of file bitvector.cpp.
References BitVector(), and d_size.
bvsaddo()
BitVector stabilizer::util::BitVector::bvsaddo (const BitVector & bv) const
Create a bit-vector representing a predicate that indicates if bit-vector signed addition produces an overflow.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the overflow check.
Definition at line 917 of file bitvector.cpp.
References BitVector(), and d_size.
bvsdiv()
BitVector stabilizer::util::BitVector::bvsdiv (const BitVector & bv) const
Create a bit-vector representing the signed division of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the signed division.
Definition at line 901 of file bitvector.cpp.
References BitVector(), and d_size.
bvsdivo()
BitVector stabilizer::util::BitVector::bvsdivo (const BitVector & bv) const
Create a bit-vector representing a predicate that indicates if bit-vector signed division produces an overflow.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the overflow check.
Definition at line 937 of file bitvector.cpp.
References BitVector(), and d_size.
bvsext()
BitVector stabilizer::util::BitVector::bvsext (uint64_t n) const
Create a bit-vector representing the sign extension of this bit-vector by the given number of bits.
Parameters
n The number of bits to extend this bit-vector with.
Returns
A bit-vector representing the sign extension.
Definition at line 953 of file bitvector.cpp.
References BitVector(), and d_size.
bvsge()
BitVector stabilizer::util::BitVector::bvsge (const BitVector & bv) const
Create a bit-vector representing the signed greater than or equal of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the signed greater than or equal.
Definition at line 861 of file bitvector.cpp.
References BitVector(), and d_size.
bvsgt()
BitVector stabilizer::util::BitVector::bvsgt (const BitVector & bv) const
Create a bit-vector representing the signed greater than of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the signed greater than.
Definition at line 857 of file bitvector.cpp.
References BitVector(), and d_size.
bvshl() [1/2]
BitVector stabilizer::util::BitVector::bvshl (const BitVector & bv) const
Create a bit-vector representing the logical left shift of this bit-vector by the given bit-vector shift value.
Parameters
shift A bit-vector representing he number of bits to shift this bit-vector to the left.
Returns
A bit-vector representing the result of the logical left shift.
Definition at line 869 of file bitvector.cpp.
References BitVector(), and d_size.
bvshl() [2/2]
BitVector stabilizer::util::BitVector::bvshl (uint64_t shift) const
Create a bit-vector representing the logical left shift of this bit-vector by the given unsigned integer shift value.
Parameters
shift An unsigned integer representing the number of bits to shift this bit-vector to the left.
Returns
A bit-vector representing the result of the logical left shift.
Definition at line 865 of file bitvector.cpp.
References BitVector(), and d_size.
bvshr() [1/2]
BitVector stabilizer::util::BitVector::bvshr (const BitVector & bv) const
Create a bit-vector representing the logical right shift of this bit-vector by the given bit-vector shift value.
Parameters
bv A bit-vector representing the number of bits to shift this bit-vector to the right.
Returns
A bit-vector representing the result of the logical right shift.
Definition at line 877 of file bitvector.cpp.
References BitVector(), and d_size.
bvshr() [2/2]
BitVector stabilizer::util::BitVector::bvshr (uint64_t shift) const
Create a bit-vector representing the logical right shift of this bit-vector by the given unsigned integer shift value.
Parameters
shift An unsigned integer representing the number of bits to shift this bit-vector to the right.
Returns
A bit-vector representing the result of the logical right shift.
Definition at line 873 of file bitvector.cpp.
References BitVector(), and d_size.
bvsle()
BitVector stabilizer::util::BitVector::bvsle (const BitVector & bv) const
Create a bit-vector representing the signed less than or equal of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the signed less than or equal.
Definition at line 853 of file bitvector.cpp.
References BitVector().
bvslt()
BitVector stabilizer::util::BitVector::bvslt (const BitVector & bv) const
Create a bit-vector representing the signed less than of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the signed less than.
Definition at line 849 of file bitvector.cpp.
References BitVector().
bvsmod()
BitVector stabilizer::util::BitVector::bvsmod (const BitVector & bv) const
Create a bit-vector representing the signed remainder (sign follows divisor) of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the signed remainder.
Definition at line 909 of file bitvector.cpp.
References BitVector(), and d_size.
bvsmulo()
BitVector stabilizer::util::BitVector::bvsmulo (const BitVector & bv) const
Create a bit-vector representing a predicate that indicates if bit-vector signed multiplication produces an overflow.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the overflow check.
Definition at line 933 of file bitvector.cpp.
References BitVector(), and d_size.
bvsrem()
BitVector stabilizer::util::BitVector::bvsrem (const BitVector & bv) const
Create a bit-vector representing the signed remainder (sign follows dividend) of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the signed remainder.
Definition at line 905 of file bitvector.cpp.
References BitVector(), and d_size.
bvssubo()
BitVector stabilizer::util::BitVector::bvssubo (const BitVector & bv) const
Create a bit-vector representing a predicate that indicates if bit-vector signed subtraction produces an overflow.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the overflow check.
Definition at line 925 of file bitvector.cpp.
References BitVector(), and d_size.
bvsub()
BitVector stabilizer::util::BitVector::bvsub (const BitVector & bv) const
Create a bit-vector representing the subtraction of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the subtraction.
Definition at line 793 of file bitvector.cpp.
References BitVector().
bvuaddo()
BitVector stabilizer::util::BitVector::bvuaddo (const BitVector & bv) const
Create a bit-vector representing a predicate that indicates if bit-vector unsigned addition produces an overflow.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the overflow check.
Definition at line 913 of file bitvector.cpp.
References BitVector(), and d_size.
bvudiv()
BitVector stabilizer::util::BitVector::bvudiv (const BitVector & bv) const
Create a bit-vector representing the unsigned division of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the unsigned division.
Definition at line 893 of file bitvector.cpp.
References BitVector(), and d_size.
bvudivurem()
void stabilizer::util::BitVector::bvudivurem (const BitVector & bv, BitVector * quot, BitVector * rem) const
Merged bit-vector operations. --------------------------------------— Calculate the unsigned division and remainder of this bit-vector with bv. The result of the division is stored in quot, and the result of the remainder operation is stored in rem.
Parameters
bv The bit-vector to divide by.
quot The bit-vector to store the result of the division in.
rem The bit-vector to store the result of the remainder in.
Definition at line 2918 of file bitvector.cpp.
bvuge()
BitVector stabilizer::util::BitVector::bvuge (const BitVector & bv) const
Create a bit-vector representing the unsigned greater than or equal of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the unsigned greater than or equal.
Definition at line 845 of file bitvector.cpp.
References BitVector().
bvugt()
BitVector stabilizer::util::BitVector::bvugt (const BitVector & bv) const
Create a bit-vector representing the unsigned greater than of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the unsigned greater than.
Definition at line 841 of file bitvector.cpp.
References BitVector().
bvule()
BitVector stabilizer::util::BitVector::bvule (const BitVector & bv) const
Create a bit-vector representing the unsigned less than or equal of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the unsigned less than or equal.
Definition at line 837 of file bitvector.cpp.
References BitVector().
bvult()
BitVector stabilizer::util::BitVector::bvult (const BitVector & bv) const
Create a bit-vector representing the unsigned less than of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the unsigned less than.
Definition at line 833 of file bitvector.cpp.
References BitVector().
bvumulo()
BitVector stabilizer::util::BitVector::bvumulo (const BitVector & bv) const
Create a bit-vector representing a predicate that indicates if bit-vector unsigned multiplication produces an overflow.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the overflow check.
Definition at line 929 of file bitvector.cpp.
References BitVector(), and d_size.
bvurem()
BitVector stabilizer::util::BitVector::bvurem (const BitVector & bv) const
Create a bit-vector representing the unsigned remainder of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the unsigned remainder.
Definition at line 897 of file bitvector.cpp.
References BitVector(), and d_size.
Referenced by ibvrol(), and ibvror().
bvusubo()
BitVector stabilizer::util::BitVector::bvusubo (const BitVector & bv) const
Create a bit-vector representing a predicate that indicates if bit-vector unsigned subtraction produces an overflow.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the overflow check.
Definition at line 921 of file bitvector.cpp.
References BitVector(), and d_size.
bvxnor()
BitVector stabilizer::util::BitVector::bvxnor (const BitVector & bv) const
Create a bit-vector representing the bit-wise xnor of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the bit-wise xnor.
Definition at line 817 of file bitvector.cpp.
References BitVector().
bvxor()
BitVector stabilizer::util::BitVector::bvxor (const BitVector & bv) const
Create a bit-vector representing the bit-wise xor of this bit-vector and the given bit-vector.
Parameters
bv The other bit-vector.
Returns
A bit-vector representing the result of the bit-wise xor.
Definition at line 821 of file bitvector.cpp.
References BitVector().
bvzext()
BitVector stabilizer::util::BitVector::bvzext (uint64_t n) const
Create a bit-vector representing the zero extension of this bit-vector by the given number of bits.
Parameters
n The number of bits to extend this bit-vector with.
Returns
A bit-vector representing the zero extension.
Definition at line 949 of file bitvector.cpp.
References BitVector(), and d_size.
compare()
int32_t stabilizer::util::BitVector::compare (const BitVector & bv) const
Compare this bit-vector with given bit-vector (unsigned).
Parameters
bv The bit-vector to compare this bit-vector with.
Returns
0 if the bit-vectors are equal, -1 if their sizes don't match or if this is unsigned less than bv, and 1 if this is unsigned greater than bv.
Definition at line 439 of file bitvector.cpp.
References d_val_gmp.
count_leading()
uint64_t stabilizer::util::BitVector::count_leading (bool zeros) const private
Count leading zeros or ones.
Parameters
zeros True to determine number of leading zeros, false to count number of leading ones.
Returns
The number of leading zeros/ones.
Definition at line 2988 of file bitvector.cpp.
count_leading_ones()
uint64_t stabilizer::util::BitVector::count_leading_ones () const
Returns
The number of leading ones (counted from msb).
Definition at line 764 of file bitvector.cpp.
References BitVector(), and d_size.
count_leading_zeros()
uint64_t stabilizer::util::BitVector::count_leading_zeros () const
Returns
The number of leading zeros (counted from msb).
Definition at line 759 of file bitvector.cpp.
count_trailing_ones()
uint64_t stabilizer::util::BitVector::count_trailing_ones () const
Returns
The number of trailing ones (counted from lsb).
Definition at line 741 of file bitvector.cpp.
References bit(), and d_size.
count_trailing_zeros()
uint64_t stabilizer::util::BitVector::count_trailing_zeros () const
Returns
The number of trailing zeros (counted from lsb).
Definition at line 723 of file bitvector.cpp.
References bit(), and d_size.
fits_in_size() [1/3]
bool stabilizer::util::BitVector::fits_in_size (uint64_t size, const mpz_t value) static
Determine if given GMP value fits into a bit-vector of given size.
Parameters
size The size of the bit-vector.
value The GMP value.
Returns
True if given value fits into a bit-vector of given size.
Definition at line 124 of file bitvector.cpp.
fits_in_size() [2/3]
bool stabilizer::util::BitVector::fits_in_size (uint64_t size, const std::string & str, uint32_t base) static
Determine if given string representation of a value in the given numeric base fits into a bit-vector of given size.
Parameters
size The size of the bit-vector.
str The string represent of the value.
base The numeric base the value is given in.
Returns
True if string in base fits into a bit-vector of given size.
Definition at line 81 of file bitvector.cpp.
References d_val_gmp, d_val_uint64, is_gmp(), and mk_min_signed().
fits_in_size() [3/3]
bool stabilizer::util::BitVector::fits_in_size (uint64_t size, uint64_t value, bool sign = false) static
Determine if given integer value fits into a bit-vector of given size.
Parameters
size The size of the bit-vector.
value The integer value.
sign True if given value is to be interpreted as signed.
Returns
True if given value fits into a bit-vector of given size.
Definition at line 112 of file bitvector.cpp.
flip_bit()
void stabilizer::util::BitVector::flip_bit (uint64_t idx)
Flip the bit at given index (in-place).
Parameters
idx The index of the bit.
Definition at line 510 of file bitvector.cpp.
from_si()
BitVector stabilizer::util::BitVector::from_si (uint64_t size, int64_t value, bool truncate = false) static
Construct a bit-vector of given size from given int64 value.
Truncates value if truncate is true and the value cannot be represented with size bits.
Note
For signed values, always use this function. It guarantees that negative values are sign extended to size if size > 64, which is not the case with from_ui() (which zero extends the value).
Parameters
size The size of the bit-vector.
value A int64 representing the bit-vector value. The value must be representable with size bits if truncate is false.
truncate True to allow truncating the value if it is not representable with size bits.
Definition at line 238 of file bitvector.cpp.
from_ui()
BitVector stabilizer::util::BitVector::from_ui (uint64_t size, uint64_t value, bool truncate = false) static
Construct a bit-vector of given size from given uint64 value.
Truncates value if truncate is true and the value cannot be represented with size bits.
Note
For signed values, use from_si() instead. It guarantees that negative values are sign extended to size if size > 64, which is not the case with from_ui() (which zero extends the value).
Parameters
size The size of the bit-vector.
value A uint64 representing the bit-vector value. The value must be representable with size bits if truncate is false.
truncate True to allow truncating the value if it is not representable with size bits.
Definition at line 222 of file bitvector.cpp.
Referenced by ibvrol(), and ibvror().
get_limb()
uint64_t stabilizer::util::BitVector::get_limb (void * limb, uint64_t nbits_rem, bool zeros) const private
Get the first limb and return the number of limbs needed to represent this bit-vector if all zero limbs are disregarded.
Parameters
limb The result pointer for the first limb.
nbits_rem The number of bits that spill over into the most significant limb, assuming that all bits are represented). Zero if the bit-width is a multiple of n_bits_per_limb.
zeros True for leading zeros, else ones.
Returns
The number of limbs needed to represent this bit-vector.
Definition at line 3019 of file bitvector.cpp.
gmp_value()
const mpz_t & stabilizer::util::BitVector::gmp_value () const
Get mpz_t value from Integer class.
Definition at line 2965 of file bitvector.cpp.
hash()
size_t stabilizer::util::BitVector::hash () const
Returns
The hash value of this bit-vector.
Definition at line 334 of file bitvector.cpp.
ibvadd() [1/2]
BitVector & stabilizer::util::BitVector::ibvadd (const BitVector & bv)
Addition (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the addition of this and the given bit-vector.
Definition at line 2651 of file bitvector.cpp.
ibvadd() [2/2]
BitVector & stabilizer::util::BitVector::ibvadd (const BitVector & bv0, const BitVector & bv1)
Addition (in-place) of given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the addition.
bv1 The second operand of the addition.
Returns
A reference to this bit-vector, overwritten with the result of the addition of the given bit-vectors.
Definition at line 1136 of file bitvector.cpp.
References d_val_gmp.
Referenced by stabilizer::parser::BitVectorUtils::bvAdd().
ibvand() [1/2]
BitVector & stabilizer::util::BitVector::ibvand (const BitVector & bv)
Bit-wise and (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise and of this and the given bit-vector.
Definition at line 2656 of file bitvector.cpp.
ibvand() [2/2]
BitVector & stabilizer::util::BitVector::ibvand (const BitVector & bv0, const BitVector & bv1)
Bit-wise and (in-place) of given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the bit-wise and.
bv1 The second operand of the bit-wise and.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise and of the given bit-vectors.
Definition at line 1186 of file bitvector.cpp.
References d_val_gmp.
ibvashr() [1/4]
BitVector & stabilizer::util::BitVector::ibvashr (const BitVector & bv)
Arithmetic right shift (in-place) of this bit-vector by the given bit-vector shift value.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv A bit-vector representing the number of bits to shift this bit-vector to the right.
Returns
A reference to this bit-vector, overwritten with the result of the arithmetic right shift.
Definition at line 2771 of file bitvector.cpp.
ibvashr() [2/4]
BitVector & stabilizer::util::BitVector::ibvashr (const BitVector & bv, const BitVector & arithmetic)
Arithmetic right shift (in-place) of the given bit-vector by the given bit-vector shift value.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to shift.
shift The bit-vector representing the number of bits to shift bv.
Returns
A reference to this bit-vector, overwritten with the result of the arithmetic right shift.
Definition at line 1704 of file bitvector.cpp.
ibvashr() [3/4]
BitVector & stabilizer::util::BitVector::ibvashr (const BitVector & bv, uint64_t shift)
Arithmetic right shift (in-place) of the given bit-vector by the given unsigned integer shift value.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to shift.
shift The bit-vector representing the number of bits to shift bv.
Returns
A reference to this bit-vector, overwritten with the result of the arithmetic right shift.
Definition at line 1692 of file bitvector.cpp.
Referenced by stabilizer::parser::BitVectorUtils::bvAshr().
ibvashr() [4/4]
BitVector & stabilizer::util::BitVector::ibvashr (uint64_t shift)
Arithmetic right shift (in-place) of this bit-vector by the given unsigned integer shift value.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
shift An unsigned integer representing the number of bits to shift this bit-vector to the right.
Returns
A reference to this bit-vector, overwritten with the result of the arithmetic right shift.
Definition at line 2766 of file bitvector.cpp.
ibvconcat() [1/2]
BitVector & stabilizer::util::BitVector::ibvconcat (const BitVector & bv)
Concatenation (in-place) of this bit-vector and the given bit-vector. Bit-vector bv is concatenated (at the right, the lsb side) to this bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the concatenation of this and the given bit-vector.
Definition at line 2841 of file bitvector.cpp.
ibvconcat() [2/2]
BitVector & stabilizer::util::BitVector::ibvconcat (const BitVector & bv0, const BitVector & bv1)
Concatenation (in-place) of the given bit-vectors. Bit-vector bv1 is concatenated (at the right, the lsb side) to bv0.
Parameters
bv0 The first operand of the concatenation.
bv1 The second operand of the concatenation.
Returns
A reference to this bit-vector, overwritten with the result of the concatenation of the given bit-vectors.
Definition at line 2034 of file bitvector.cpp.
ibvdec() [1/2]
BitVector & stabilizer::util::BitVector::ibvdec ()
Decrement (in-place, chainable) of this bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the decrement of this bit-vector.
Definition at line 2626 of file bitvector.cpp.
ibvdec() [2/2]
BitVector & stabilizer::util::BitVector::ibvdec (const BitVector & bv)
Decrement (in-place) of the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to compute the decrement for.
Returns
A reference to this bit-vector, overwritten with the result of the decrement of bv.
Definition at line 1049 of file bitvector.cpp.
ibveq() [1/2]
BitVector & stabilizer::util::BitVector::ibveq (const BitVector & bv)
Equality (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the equality of this and the given bit-vector.
Definition at line 2696 of file bitvector.cpp.
ibveq() [2/2]
BitVector & stabilizer::util::BitVector::ibveq (const BitVector & bv0, const BitVector & bv1)
Equality (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the equality.
bv1 The second operand of the equality.
Returns
A reference to this bit-vector, overwritten with the result of the equality of the given bit-vectors.
Definition at line 1355 of file bitvector.cpp.
ibvextract() [1/2]
BitVector & stabilizer::util::BitVector::ibvextract (const BitVector & bv, uint64_t idx_hi, uint64_t idx_lo)
Extract a bit range from bit-vector bv (in-place).
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to extract a bit range from.
idx_hi The upper bit-index of the range (inclusive).
idx_lo The lower bit-index of the range (inclusive).
Returns
A reference to this bit-vector, overwritten with the extracted bit range.
Definition at line 2088 of file bitvector.cpp.
ibvextract() [2/2]
BitVector & stabilizer::util::BitVector::ibvextract (uint64_t idx_hi, uint64_t idx_lo)
Extract a bit range from this bit-vector (in-place).
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
idx_hi The upper bit-index of the range (inclusive).
idx_lo The lower bit-index of the range (inclusive).
Returns
A reference to this bit-vector, overwritten with the extracted bit range.
Definition at line 2846 of file bitvector.cpp.
ibvimplies() [1/2]
BitVector & stabilizer::util::BitVector::ibvimplies (const BitVector & bv)
Implication (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the implication of this and the given bit-vector.
Definition at line 2661 of file bitvector.cpp.
ibvimplies() [2/2]
BitVector & stabilizer::util::BitVector::ibvimplies (const BitVector & bv0, const BitVector & bv1)
Implication (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the implication.
bv1 The second operand of the implication.
Returns
A reference to this bit-vector, overwritten with the result of the implication of the given bit-vectors.
Definition at line 1211 of file bitvector.cpp.
ibvinc() [1/2]
BitVector & stabilizer::util::BitVector::ibvinc ()
Increment (in-place, chainable) of this bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the increment of this bit-vector.
Definition at line 2621 of file bitvector.cpp.
ibvinc() [2/2]
BitVector & stabilizer::util::BitVector::ibvinc (const BitVector & bv)
Increment (in-place) of the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to compute the increment for.
Returns
A reference to this bit-vector, overwritten with the result of the increment of bv.
Definition at line 1027 of file bitvector.cpp.
ibvite()
BitVector & stabilizer::util::BitVector::ibvite (const BitVector & c, const BitVector & t, const BitVector & e)
Create an if-then-else over the given bit-vectors (in-place).
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
c A bit-vector representing the condition of the ite.
t A bit-vector representing the then branch of the ite.
e A bit-vector representing the else branch of the ite.
Returns
A reference to this bit-vector, overwritten with the ite.
Definition at line 2461 of file bitvector.cpp.
References d_val_gmp, d_val_uint64, and is_gmp().
ibvmodinv() [1/2]
BitVector & stabilizer::util::BitVector::ibvmodinv ()
Calculate modular inverse of this bit-vector by means of the Extended Euclidean Algorithm (in-place).
Note
This bit-vector must be odd. The greatest common divisor gcd (c, 2^bw) must be (and is, in this case) always 1.
The result of this operation is stored in-place, in this bit-vector.
Returns
A reference to this bit-vector, overwritten with the modular inverse.
Definition at line 2886 of file bitvector.cpp.
ibvmodinv() [2/2]
BitVector & stabilizer::util::BitVector::ibvmodinv (const BitVector & bv)
Calculate modular inverse of the given bit-vector by means of the Extended Euclidean Algorithm (in-place).
Note
Bit-vector bv must be odd. The greatest common divisor gcd (c, 2^bw) must be (and is, in this case) always 1.
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to compute the modular inverse for.
Returns
A reference to this bit-vector, overwritten with the modular inverse.
Definition at line 2502 of file bitvector.cpp.
ibvmul() [1/2]
BitVector & stabilizer::util::BitVector::ibvmul (const BitVector & bv)
Multiplication (in-place) of this bit-vector by the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the multiplication of this and the given bit-vector.
Definition at line 2776 of file bitvector.cpp.
ibvmul() [2/2]
BitVector & stabilizer::util::BitVector::ibvmul (const BitVector & bv0, const BitVector & bv1)
Multiplication (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the multiplication.
bv1 The second operand of the multiplication.
Returns
A reference to this bit-vector, overwritten with the result of the multiplication of the given bit-vectors.
Definition at line 1725 of file bitvector.cpp.
References d_val_gmp.
Referenced by stabilizer::parser::BitVectorUtils::bvMul().
ibvnand() [1/2]
BitVector & stabilizer::util::BitVector::ibvnand (const BitVector & bv)
Bit-wise nand (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise nand of this and the given bit-vector.
Definition at line 2666 of file bitvector.cpp.
ibvnand() [2/2]
BitVector & stabilizer::util::BitVector::ibvnand (const BitVector & bv0, const BitVector & bv1)
Bit-wise nand (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the bit-wise nand.
bv1 The second operand of the bit-wise nand.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise nand of the given bit-vectors.
Definition at line 1227 of file bitvector.cpp.
References d_val_gmp.
ibvne() [1/2]
BitVector & stabilizer::util::BitVector::ibvne (const BitVector & bv)
Disequality (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the disequality of this and the given bit-vector.
Definition at line 2701 of file bitvector.cpp.
ibvne() [2/2]
BitVector & stabilizer::util::BitVector::ibvne (const BitVector & bv0, const BitVector & bv1)
Disequality (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the disequality.
bv1 The second operand of the disequality.
Returns
A reference to this bit-vector, overwritten with the result of the disequality of the given bit-vectors.
Definition at line 1375 of file bitvector.cpp.
ibvneg() [1/2]
BitVector & stabilizer::util::BitVector::ibvneg ()
Two's complement negation (in-place) of this bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the two's complement of this bit-vector.
Definition at line 2611 of file bitvector.cpp.
Referenced by ibvsdiv(), and ibvsrem().
ibvneg() [2/2]
BitVector & stabilizer::util::BitVector::ibvneg (const BitVector & bv)
Two's complement negation (in-place) of the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to compute the two's complement for.
Returns
A reference to this bit-vector, overwritten with the result of the two's complement of bv.
Definition at line 989 of file bitvector.cpp.
Referenced by stabilizer::parser::BitVectorUtils::bvNeg().
ibvnego() [1/2]
BitVector & stabilizer::util::BitVector::ibvnego ()
Bit-vector negation overflow check (in-place, chainable) of this bit-vector.
Result is a bit-vector of size 1, representing the result of the overflow check of the given bit-vector (1 if an overflow occurs, and 0 otherwise).
Note
The result of this operation is stored in-place, in this bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check of this bit-vector.
Definition at line 2646 of file bitvector.cpp.
ibvnego() [2/2]
BitVector & stabilizer::util::BitVector::ibvnego (const BitVector & bv)
Bit-vector negation overflow check (in-place) of the given bit-vector.
Result is a bit-vector of size 1, representing the result of the overflow check of the given bit-vector (1 if an overflow occurs, and 0 otherwise).
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to compute the overflow check for.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check of bv.
Definition at line 1127 of file bitvector.cpp.
References d_size, is_gmp(), is_null(), and size().
ibvnor() [1/2]
BitVector & stabilizer::util::BitVector::ibvnor (const BitVector & bv)
Bit-wise nor (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise nor of this and the given bit-vector.
Definition at line 2671 of file bitvector.cpp.
ibvnor() [2/2]
BitVector & stabilizer::util::BitVector::ibvnor (const BitVector & bv0, const BitVector & bv1)
Bit-wise nor (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the bit-wise nor.
bv1 The second operand of the bit-wise nor.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise nor of the given bit-vectors.
Definition at line 1253 of file bitvector.cpp.
References d_val_gmp.
ibvnot() [1/2]
BitVector & stabilizer::util::BitVector::ibvnot ()
Bit-wise negation (in-place) of this bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise negation of this bit-vector.
Definition at line 2616 of file bitvector.cpp.
Referenced by bvpow().
ibvnot() [2/2]
BitVector & stabilizer::util::BitVector::ibvnot (const BitVector & bv)
Bit-wise negation (in-place) of the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to compute the bit-wise negation for.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise negation of bv.
Definition at line 1005 of file bitvector.cpp.
ibvor() [1/2]
BitVector & stabilizer::util::BitVector::ibvor (const BitVector & bv)
Bit-wise or (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise or of this and the given bit-vector.
Definition at line 2676 of file bitvector.cpp.
ibvor() [2/2]
BitVector & stabilizer::util::BitVector::ibvor (const BitVector & bv0, const BitVector & bv1)
Bit-wise or (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the bit-wise or.
bv1 The second operand of the bit-wise or.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise or of the given bit-vectors.
Definition at line 1279 of file bitvector.cpp.
References d_val_gmp.
ibvpow() [1/2]
BitVector & stabilizer::util::BitVector::ibvpow (const BitVector & base, const mpz_t exp)
Calculate a bit-vector base exponentiated by exp (in-place).
Parameters
base The base bit-vector.
exp The exponent GMP value.
Returns
A bit-vector representing the result of the exponentiation.
Definition at line 2891 of file bitvector.cpp.
References d_val_uint64, is_gmp(), stabilizer::util::mpz_get_ull(), and stabilizer::util::mpz_init_set_ull().
ibvpow() [2/2]
BitVector & stabilizer::util::BitVector::ibvpow (const mpz_t exp)
Calculate a bit-vector representing this bit-vector exponentiated by exp (in-place).
Parameters
exp The exponent GMP value.
Returns
A bit-vector representing the result of the exponentiation.
Definition at line 2911 of file bitvector.cpp.
ibvredand() [1/2]
BitVector & stabilizer::util::BitVector::ibvredand ()
And reduction (in-place, chainable) of this bit-vector.
Result is a bit-vector of size 1, representing the result of the and reduction of this bit-vector (1 if all bits of this bit-vector are one, and 0 otherwise).
Note
The result of this operation is stored in-place, in this bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the and reduction of this bit-vector.
Definition at line 2631 of file bitvector.cpp.
ibvredand() [2/2]
BitVector & stabilizer::util::BitVector::ibvredand (const BitVector & bv)
And reduction (in-place) of the given bit-vector.
Result is a bit-vector of size 1, representing the result of the and reduction of the given bit-vector (1 if all bits of this bit-vector are one, and 0 otherwise).
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to compute the and reduction for.
Returns
A reference to this bit-vector, overwritten with the result of the and reduction of bv.
Definition at line 1071 of file bitvector.cpp.
ibvredor() [1/2]
BitVector & stabilizer::util::BitVector::ibvredor ()
Or reduction (in-place, chainable) of this bit-vector.
Result is a bit-vector of size 1, representing the result of the or reduction of this bit-vector (1 if at least one bit of this bit-vector is one, and 0 otherwise).
Note
The result of this operation is stored in-place, in this bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the or reduction of this bit-vector.
Definition at line 2636 of file bitvector.cpp.
ibvredor() [2/2]
BitVector & stabilizer::util::BitVector::ibvredor (const BitVector & bv)
Or reduction (in-place) of the given bit-vector.
Result is a bit-vector of size 1, representing the result of the or reduction of the given bit-vector (1 if at least one bit of this bit-vector is one, and 0 otherwise).
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to compute the or reduction for.
Returns
A reference to this bit-vector, overwritten with the result of the or reduction of bv.
Definition at line 1084 of file bitvector.cpp.
ibvredxor() [1/2]
BitVector & stabilizer::util::BitVector::ibvredxor ()
Xor reduction (in-place, chainable) of this bit-vector.
Result is a bit-vector of size 1, representing the result of the xor reduction of this bit-vector (1 if an uneven number of bits is set to 1, and 0 otherwise).
Note
The result of this operation is stored in-place, in this bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the xor reduction of this bit-vector.
Definition at line 2641 of file bitvector.cpp.
ibvredxor() [2/2]
BitVector & stabilizer::util::BitVector::ibvredxor (const BitVector & bv)
Xor reduction (in-place) of the given bit-vector.
Result is a bit-vector of size 1, representing the result of the xor reduction of the given bit-vector (1 if an uneven number of bits is set to 1, and 0 otherwise).
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to compute the xor reduction for.
Returns
A reference to this bit-vector, overwritten with the result of the xor reduction of bv.
Definition at line 1107 of file bitvector.cpp.
ibvrepeat() [1/2]
BitVector & stabilizer::util::BitVector::ibvrepeat (const BitVector & bv, uint64_t n)
Repeat (in-place) of the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to repeat.
n The number of times to repeat bit-vector bv, must be > 0.
Returns
A reference to this bit-vector, overwritten with result of the repeat operation.
Definition at line 2274 of file bitvector.cpp.
ibvrepeat() [2/2]
BitVector & stabilizer::util::BitVector::ibvrepeat (uint64_t n)
Repeat (in-place) of this bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
n The number of times to repeat this bit-vector, must be > 0.
Returns
A reference to this bit-vector, overwritten with the result of the repeat operation.
Definition at line 2861 of file bitvector.cpp.
ibvrol() [1/2]
BitVector & stabilizer::util::BitVector::ibvrol (const BitVector & bv, const BitVector & n)
Rotate left (in-place) of the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to rotate.
n The number of bits to rotate bit-vector bv by.
Returns
A reference to this bit-vector, overwritten with result of the rotate left operation.
Definition at line 2375 of file bitvector.cpp.
References bvurem(), from_ui(), shift_is_uint64(), and size().
ibvrol() [2/2]
BitVector & stabilizer::util::BitVector::ibvrol (const BitVector & n)
Rotate left (in-place) of this bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
n The number of bits to rotate bit-vector bv by.
Returns
A reference to this bit-vector, overwritten with result of the rotate left operation.
Definition at line 2871 of file bitvector.cpp.
ibvroli() [1/2]
BitVector & stabilizer::util::BitVector::ibvroli (const BitVector & bv, uint64_t n)
Rotate left (in-place) of the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to rotate.
n The number of bits to rotate bit-vector bv by.
Returns
A reference to this bit-vector, overwritten with result of the rotate left operation.
Definition at line 2327 of file bitvector.cpp.
ibvroli() [2/2]
BitVector & stabilizer::util::BitVector::ibvroli (uint64_t n)
Rotate left (in-place) of this bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
n The number of bits to rotate bit-vector bv by.
Returns
A reference to this bit-vector, overwritten with result of the rotate left operation.
Definition at line 2866 of file bitvector.cpp.
ibvror() [1/2]
BitVector & stabilizer::util::BitVector::ibvror (const BitVector & bv, const BitVector & n)
Rotate right (in-place) of the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to rotate.
n The number of bits to rotate bit-vector bv by.
Returns
A reference to this bit-vector, overwritten with result of the rotate right operation.
Definition at line 2442 of file bitvector.cpp.
References bvurem(), from_ui(), shift_is_uint64(), and size().
ibvror() [2/2]
BitVector & stabilizer::util::BitVector::ibvror (const BitVector & n)
Rotate right (in-place) of this bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
n The number of bits to rotate bit-vector bv by.
Returns
A reference to this bit-vector, overwritten with result of the rotate right operation.
Definition at line 2881 of file bitvector.cpp.
ibvrori() [1/2]
BitVector & stabilizer::util::BitVector::ibvrori (const BitVector & bv, uint64_t n)
Rotate right (in-place) of the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to rotate.
n The number of bits to rotate bit-vector bv by.
Returns
A reference to this bit-vector, overwritten with result of the rotate right operation.
Definition at line 2394 of file bitvector.cpp.
ibvrori() [2/2]
BitVector & stabilizer::util::BitVector::ibvrori (uint64_t n)
Rotate right(in-place) of this bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
n The number of bits to rotate bit-vector bv by.
Returns
A reference to this bit-vector, overwritten with result of the rotate right operation.
Definition at line 2876 of file bitvector.cpp.
ibvsaddo() [1/2]
BitVector & stabilizer::util::BitVector::ibvsaddo (const BitVector & bv)
Signed addition overflow check (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 2811 of file bitvector.cpp.
ibvsaddo() [2/2]
BitVector & stabilizer::util::BitVector::ibvsaddo (const BitVector & bv0, const BitVector & bv1)
Signed addition overflow check (in-place) of given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the addition.
bv1 The second operand of the addition.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 1956 of file bitvector.cpp.
ibvsdiv() [1/2]
BitVector & stabilizer::util::BitVector::ibvsdiv (const BitVector & bv)
Signed division (in-place) of this bit-vector by the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the signed division of this and the given bit-vector.
Definition at line 2791 of file bitvector.cpp.
ibvsdiv() [2/2]
BitVector & stabilizer::util::BitVector::ibvsdiv (const BitVector & bv0, const BitVector & bv1)
Signed division (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the signed division.
bv1 The second operand of the signed division.
Returns
A reference to this bit-vector, overwritten with the result of the signed division of the given bit-vectors.
Definition at line 1821 of file bitvector.cpp.
References ibvneg(), and ibvudiv().
Referenced by stabilizer::parser::BitVectorUtils::bvSdiv().
ibvsdivo() [1/2]
BitVector & stabilizer::util::BitVector::ibvsdivo (const BitVector & bv)
Signed overflow division check (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 2836 of file bitvector.cpp.
ibvsdivo() [2/2]
BitVector & stabilizer::util::BitVector::ibvsdivo (const BitVector & bv0, const BitVector & bv1)
Signed division overflow check (in-place) of given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the division.
bv1 The second operand of the division.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 2021 of file bitvector.cpp.
ibvsext() [1/2]
BitVector & stabilizer::util::BitVector::ibvsext (const BitVector & bv, uint64_t n)
Sign extension (in-place) of the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to sign extend.
n The number of bits to extend bit-vector bv with.
Returns
A reference to this bit-vector, overwritten with the sign extension.
Definition at line 2189 of file bitvector.cpp.
ibvsext() [2/2]
BitVector & stabilizer::util::BitVector::ibvsext (uint64_t n)
Sign extension (in-place) of this bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
n The number of bits to extend bit-vector bv with.
Returns
A reference to this bit-vector, overwritten with the sign extension.
Definition at line 2856 of file bitvector.cpp.
ibvsge() [1/2]
BitVector & stabilizer::util::BitVector::ibvsge (const BitVector & bv)
Signed greater than or equal (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the signed greater than or equal of this and the given bit-vector.
Definition at line 2741 of file bitvector.cpp.
ibvsge() [2/2]
BitVector & stabilizer::util::BitVector::ibvsge (const BitVector & bv0, const BitVector & bv1)
Signed greater than or equal (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the signed greater than or equal.
bv1 The second operand of the signed greater than or equal.
Returns
A reference to this bit-vector, overwritten with the result of the signed greater or equal of the given bit-vectors.
Definition at line 1547 of file bitvector.cpp.
ibvsgt() [1/2]
BitVector & stabilizer::util::BitVector::ibvsgt (const BitVector & bv)
Signed greater than (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the signed greater than of this and the given bit-vector.
Definition at line 2736 of file bitvector.cpp.
ibvsgt() [2/2]
BitVector & stabilizer::util::BitVector::ibvsgt (const BitVector & bv0, const BitVector & bv1)
Signed greater than (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the signed greater than.
bv1 The second operand of the signed greater than.
Returns
A reference to this bit-vector, overwritten with the result of the signed greater than of the given bit-vectors.
Definition at line 1523 of file bitvector.cpp.
ibvshl() [1/4]
BitVector & stabilizer::util::BitVector::ibvshl (const BitVector & bv)
Logical left shift (in-place) of this bit-vector by the given bit-vector shift value.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv A bit-vector representing the number of bits to shift this bit-vector to the left.
Returns
A reference to this bit-vector, overwritten with the result of the logical left shift.
Definition at line 2751 of file bitvector.cpp.
ibvshl() [2/4]
BitVector & stabilizer::util::BitVector::ibvshl (const BitVector & bv, const BitVector & shift)
Logical left shift (in-place) of the given bit-vector by the given bit-vector shift value.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to shift.
shift The bit-vector representing the number of bits to shift bv.
Returns
A reference to this bit-vector, overwritten with the result of the logical left shift.
Definition at line 1603 of file bitvector.cpp.
References ibvshl().
ibvshl() [3/4]
BitVector & stabilizer::util::BitVector::ibvshl (const BitVector & bv, uint64_t shift)
Logical left shift (in-place) of the given bit-vector by the given unsigned integer value.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to shift.
shift An unsigned integer representing the number of bits to shift this bit-vector to the left.
Returns
A reference to this bit-vector, overwritten with the result of the logical left shift.
Definition at line 1571 of file bitvector.cpp.
Referenced by stabilizer::parser::BitVectorUtils::bvShl(), and ibvshl().
ibvshl() [4/4]
BitVector & stabilizer::util::BitVector::ibvshl (uint64_t shift)
Logical left shift (in-place) of this bit-vector by the given unsigned integer value.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
shift An unsigned integer representing the number of bits to shift this bit-vector to the left.
Returns
A reference to this bit-vector, overwritten with the result of the logical left shift.
Definition at line 2746 of file bitvector.cpp.
ibvshr() [1/4]
BitVector & stabilizer::util::BitVector::ibvshr (const BitVector & bv)
Logical right shift (in-place) of this bit-vector by the given bit-vector shift value.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv A bit-vector representing the number of bits to shift this bit-vector to the right.
Returns
A reference to this bit-vector, overwritten with the result of the logical right shift.
Definition at line 2761 of file bitvector.cpp.
ibvshr() [2/4]
BitVector & stabilizer::util::BitVector::ibvshr (const BitVector & bv, const BitVector & shift)
Logical right shift (in-place) of the given bit-vector by the given bit-vector shift value.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to shift.
shift The bit-vector representing the number of bits to shift bv.
Returns
A reference to this bit-vector, overwritten with the result of the logical right shift.
Definition at line 1663 of file bitvector.cpp.
References ibvshr().
ibvshr() [3/4]
BitVector & stabilizer::util::BitVector::ibvshr (const BitVector & bv, uint64_t shift)
Logical right shift (in-place) of of the given bit-vector by the given unsigned integer shift value.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to shift.
shift An unsigned integer representing the number of bits to shift this bit-vector to the right.
Returns
A reference to this bit-vector, overwritten with the result of the logical right shift.
Definition at line 1632 of file bitvector.cpp.
Referenced by stabilizer::parser::BitVectorUtils::bvLshr(), and ibvshr().
ibvshr() [4/4]
BitVector & stabilizer::util::BitVector::ibvshr (uint64_t shift)
Logical right shift (in-place) of this bit-vector by the given unsigned integer value.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
shift An unsigned integer representing the number of bits to shift this bit-vector to the right.
Returns
A reference to this bit-vector, overwritten with the result of the logical right shift.
Definition at line 2756 of file bitvector.cpp.
ibvsle() [1/2]
BitVector & stabilizer::util::BitVector::ibvsle (const BitVector & bv)
Signed less than or equal (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the signed less than or equal of this and the given bit-vector.
Definition at line 2731 of file bitvector.cpp.
ibvsle() [2/2]
BitVector & stabilizer::util::BitVector::ibvsle (const BitVector & bv0, const BitVector & bv1)
Signed less than or equal (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the unsigned less than or equal.
bv1 The second operand of the unsigned less than or equal.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned less or equal of the given bit-vectors.
Definition at line 1499 of file bitvector.cpp.
ibvslt() [1/2]
BitVector & stabilizer::util::BitVector::ibvslt (const BitVector & bv)
Signed less than (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the signed less than or equal of this and the given bit-vector.
Definition at line 2726 of file bitvector.cpp.
ibvslt() [2/2]
BitVector & stabilizer::util::BitVector::ibvslt (const BitVector & bv0, const BitVector & bv1)
Signed less than (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the signed less than.
bv1 The second operand of the signed less than.
Returns
A reference to this bit-vector, overwritten with the result of the signed less than of the given bit-vectors.
Definition at line 1475 of file bitvector.cpp.
ibvsmod() [1/2]
BitVector & stabilizer::util::BitVector::ibvsmod (const BitVector & bv)
Signed remainder (sign follows divisor, in-place) of this bit-vector by the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the signed remainder of this and the given bit-vector.
Definition at line 2801 of file bitvector.cpp.
ibvsmod() [2/2]
BitVector & stabilizer::util::BitVector::ibvsmod (const BitVector & bv0, const BitVector & bv1)
Signed remainder (sign follows divisor, in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the signed remainder.
bv1 The second operand of the signed remainder.
Returns
A reference to this bit-vector, overwritten with the result of the signed remainder of the given bit-vectors.
Definition at line 1894 of file bitvector.cpp.
Referenced by stabilizer::parser::BitVectorUtils::bvSmod().
ibvsmulo() [1/2]
BitVector & stabilizer::util::BitVector::ibvsmulo (const BitVector & bv)
Signed overflow multiplication check (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 2831 of file bitvector.cpp.
ibvsmulo() [2/2]
BitVector & stabilizer::util::BitVector::ibvsmulo (const BitVector & bv0, const BitVector & bv1)
Signed multiplication overflow check (in-place) of given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the multiplication.
bv1 The second operand of the multiplication.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 2008 of file bitvector.cpp.
ibvsrem() [1/2]
BitVector & stabilizer::util::BitVector::ibvsrem (const BitVector & bv)
Signed remainder (sign follows divident, in-place) of this bit-vector by the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the signed remainder of this and the given bit-vector.
Definition at line 2796 of file bitvector.cpp.
ibvsrem() [2/2]
BitVector & stabilizer::util::BitVector::ibvsrem (const BitVector & bv0, const BitVector & bv1)
Signed remainder (sign follows dividend, in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the signed remainder.
bv1 The second operand of the signed remainder.
Returns
A reference to this bit-vector, overwritten with the result of the signed remainder of the given bit-vectors.
Definition at line 1858 of file bitvector.cpp.
References ibvneg(), and ibvurem().
Referenced by stabilizer::parser::BitVectorUtils::bvSrem().
ibvssubo() [1/2]
BitVector & stabilizer::util::BitVector::ibvssubo (const BitVector & bv)
Signed subtraction overflow check (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 2821 of file bitvector.cpp.
ibvssubo() [2/2]
BitVector & stabilizer::util::BitVector::ibvssubo (const BitVector & bv0, const BitVector & bv1)
Signed subtraction overflow check (in-place) of given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the subtraction.
bv1 The second operand of the subtraction.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 1982 of file bitvector.cpp.
ibvsub() [1/2]
BitVector & stabilizer::util::BitVector::ibvsub (const BitVector & bv)
Subtraction (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the subtraction of this and the given bit-vector.
Definition at line 2681 of file bitvector.cpp.
ibvsub() [2/2]
BitVector & stabilizer::util::BitVector::ibvsub (const BitVector & bv0, const BitVector & bv1)
Subtraction (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the subtraction.
bv1 The second operand of the subtraction.
Returns
A reference to this bit-vector, overwritten with the result of the subtraction of the given bit-vectors.
Definition at line 1161 of file bitvector.cpp.
References d_val_gmp.
Referenced by stabilizer::parser::BitVectorUtils::bvSub().
ibvuaddo() [1/2]
BitVector & stabilizer::util::BitVector::ibvuaddo (const BitVector & bv)
Unsigned addition overflow check (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 2806 of file bitvector.cpp.
ibvuaddo() [2/2]
BitVector & stabilizer::util::BitVector::ibvuaddo (const BitVector & bv0, const BitVector & bv1)
Unsigned addition overflow check (in-place) of given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the addition.
bv1 The second operand of the addition.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 1943 of file bitvector.cpp.
ibvudiv() [1/2]
BitVector & stabilizer::util::BitVector::ibvudiv (const BitVector & bv)
Unsigned division (in-place) of this bit-vector by the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned division of this and the given bit-vector.
Definition at line 2781 of file bitvector.cpp.
ibvudiv() [2/2]
BitVector & stabilizer::util::BitVector::ibvudiv (const BitVector & bv0, const BitVector & bv1)
Unsigned division (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the unsigned division.
bv1 The second operand of the unsigned division.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned division of the given bit-vectors.
Definition at line 1750 of file bitvector.cpp.
References d_val_gmp.
Referenced by stabilizer::parser::BitVectorUtils::bvUdiv(), and ibvsdiv().
ibvuge() [1/2]
BitVector & stabilizer::util::BitVector::ibvuge (const BitVector & bv)
Unsigned greater than or equal (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned greater than or equal of this and the given bit-vector.
Definition at line 2721 of file bitvector.cpp.
ibvuge() [2/2]
BitVector & stabilizer::util::BitVector::ibvuge (const BitVector & bv0, const BitVector & bv1)
Unsigned greater than or equal (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the unsigned greater than or equal.
bv1 The second operand of the unsigned greater than or equal.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned greater or equal of the given bit-vectors.
Definition at line 1455 of file bitvector.cpp.
ibvugt() [1/2]
BitVector & stabilizer::util::BitVector::ibvugt (const BitVector & bv)
Unsigned greater than (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned greater than of this and the given bit-vector.
Definition at line 2716 of file bitvector.cpp.
ibvugt() [2/2]
BitVector & stabilizer::util::BitVector::ibvugt (const BitVector & bv0, const BitVector & bv1)
Unsigned greater than (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the unsigned greater than.
bv1 The second operand of the unsigned greater than.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned greater than of the given bit-vectors.
Definition at line 1435 of file bitvector.cpp.
ibvule() [1/2]
BitVector & stabilizer::util::BitVector::ibvule (const BitVector & bv)
Unsigned less than or equal (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned less than or equal of this and the given bit-vector.
Definition at line 2711 of file bitvector.cpp.
ibvule() [2/2]
BitVector & stabilizer::util::BitVector::ibvule (const BitVector & bv0, const BitVector & bv1)
Unsigned less than or equal (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the unsigned less than or equal.
bv1 The second operand of the unsigned less than or equal.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned less or equal of the given bit-vectors.
Definition at line 1415 of file bitvector.cpp.
ibvult() [1/2]
BitVector & stabilizer::util::BitVector::ibvult (const BitVector & bv)
Unsigned less than (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned less than of this and the given bit-vector.
Definition at line 2706 of file bitvector.cpp.
ibvult() [2/2]
BitVector & stabilizer::util::BitVector::ibvult (const BitVector & bv0, const BitVector & bv1)
Unsigned less than (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the unsigned less than.
bv1 The second operand of the unsigned less than.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned less than of the given bit-vectors.
Definition at line 1395 of file bitvector.cpp.
ibvumulo() [1/2]
BitVector & stabilizer::util::BitVector::ibvumulo (const BitVector & bv)
Unsigned multiplication overflow check (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 2826 of file bitvector.cpp.
ibvumulo() [2/2]
BitVector & stabilizer::util::BitVector::ibvumulo (const BitVector & bv0, const BitVector & bv1)
Unsigned multiplication overflow check (in-place) of given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the multiplication.
bv1 The second operand of the multiplication.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 1995 of file bitvector.cpp.
ibvurem() [1/2]
BitVector & stabilizer::util::BitVector::ibvurem (const BitVector & bv)
Unsigned division (in-place) of this bit-vector by the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned remainder of this and the given bit-vector.
Definition at line 2786 of file bitvector.cpp.
ibvurem() [2/2]
BitVector & stabilizer::util::BitVector::ibvurem (const BitVector & bv0, const BitVector & bv1)
Unsigned remainder (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the unsigned remainder.
bv1 The second operand of the unsigned remainder.
Returns
A reference to this bit-vector, overwritten with the result of the unsigned remainder of the given bit-vectors.
Definition at line 1786 of file bitvector.cpp.
References d_val_gmp.
Referenced by stabilizer::parser::BitVectorUtils::bvUrem(), and ibvsrem().
ibvusubo() [1/2]
BitVector & stabilizer::util::BitVector::ibvusubo (const BitVector & bv)
Unsigned subtraction overflow check (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 2816 of file bitvector.cpp.
ibvusubo() [2/2]
BitVector & stabilizer::util::BitVector::ibvusubo (const BitVector & bv0, const BitVector & bv1)
Unsigned subtraction overflow check (in-place) of given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the subtraction.
bv1 The second operand of the subtraction.
Returns
A reference to this bit-vector, overwritten with the result of the overflow check.
Definition at line 1969 of file bitvector.cpp.
ibvxnor() [1/2]
BitVector & stabilizer::util::BitVector::ibvxnor (const BitVector & bv)
Bit-wise xnor (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise xnor of this and the given bit-vector.
Definition at line 2686 of file bitvector.cpp.
ibvxnor() [2/2]
BitVector & stabilizer::util::BitVector::ibvxnor (const BitVector & bv0, const BitVector & bv1)
Bit-wise xnor (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the bit-wise xnor.
bv1 The second operand of the bit-wise xnor.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise xnor of the given bit-vectors.
Definition at line 1304 of file bitvector.cpp.
References d_val_gmp.
ibvxor() [1/2]
BitVector & stabilizer::util::BitVector::ibvxor (const BitVector & bv)
Bit-wise xor (in-place) of this bit-vector and the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The other bit-vector.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise xor of this and the given bit-vector.
Definition at line 2691 of file bitvector.cpp.
ibvxor() [2/2]
BitVector & stabilizer::util::BitVector::ibvxor (const BitVector & bv0, const BitVector & bv1)
Bit-wise xor (in-place) of the given bit-vectors bv0 and bv1.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv0 The first operand of the bit-wise xor.
bv1 The second operand of the bit-wise xor.
Returns
A reference to this bit-vector, overwritten with the result of the bit-wise xor of the given bit-vectors.
Definition at line 1330 of file bitvector.cpp.
References d_val_gmp.
ibvzext() [1/2]
BitVector & stabilizer::util::BitVector::ibvzext (const BitVector & bv, uint64_t n)
Zero extension (in-place) of the given bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
bv The bit-vector to zero extend.
n The number of bits to extend bit-vector bv with.
Returns
A reference to this bit-vector, overwritten with the zero extension.
Definition at line 2140 of file bitvector.cpp.
References d_val_gmp, d_val_uint64, s_native_size, and size().
ibvzext() [2/2]
BitVector & stabilizer::util::BitVector::ibvzext (uint64_t n)
Zero extension (in-place) of this bit-vector.
Note
The result of this operation is stored in-place, in this bit-vector.
Parameters
n The number of bits to extend bit-vector bv with.
Returns
A reference to this bit-vector, overwritten with the zero extension.
Definition at line 2851 of file bitvector.cpp.
is_false()
bool stabilizer::util::BitVector::is_false () const
Returns
True if this bit-vector is zero and of size 1.
Definition at line 537 of file bitvector.cpp.
is_gmp()
bool stabilizer::util::BitVector::is_gmp () const inline private
Determine whether value is stored as GMP value or uint64_t. This check depends on s_native_size, i.e., for 64-bit Windows values exceeding 32 bit are stored as GMP value, for 64-bit Linux and macOS values exceeding 64 bit are stored as GMP value.
Returns
True if bit-vector wraps a mpz_t.
Definition at line 2211 of file bitvector.h.
Referenced by bit(), bvpow(), fits_in_size(), ibvite(), ibvnego(), ibvpow(), is_one(), is_zero(), and ~BitVector().
is_max_signed()
bool stabilizer::util::BitVector::is_max_signed () const
Returns
True if this bit-vector is the maximum signed value.
Definition at line 604 of file bitvector.cpp.
is_min_signed()
bool stabilizer::util::BitVector::is_min_signed () const
Returns
True if this bit-vector is the minimum signed value.
Definition at line 589 of file bitvector.cpp.
is_neg_overflow()
bool stabilizer::util::BitVector::is_neg_overflow () const
Determine if the negation of this bit-vector produces an overflow.
Returns
True if it produces an overflow.
Definition at line 625 of file bitvector.cpp.
References d_val_gmp.
is_null()
bool stabilizer::util::BitVector::is_null () const inline
Returns
True if this is an uninitialized bit-vector.
Definition at line 210 of file bitvector.h.
Referenced by bit(), bvpow(), ibvnego(), is_one(), and is_zero().
is_one()
bool stabilizer::util::BitVector::is_one () const
Returns
True if this bit-vector is one.
Definition at line 581 of file bitvector.cpp.
References d_size, d_val_gmp, d_val_uint64, is_gmp(), and is_null().
is_ones()
bool stabilizer::util::BitVector::is_ones () const
Returns
True if this bit-vector is ones (a bit-vector of all 1 bits).
Definition at line 552 of file bitvector.cpp.
References d_val_gmp.
is_power_of_two()
bool stabilizer::util::BitVector::is_power_of_two () const
Returns
True if this bit-vector is a power of two.
Definition at line 620 of file bitvector.cpp.
is_sadd_overflow()
bool stabilizer::util::BitVector::is_sadd_overflow (const BitVector & bv) const
Determine if the (signed) addition of this and the given bit-vector produces an overflow.
Parameters
bv The bit-vector to add to this bit-vector.
Returns
True if it produces an overflow.
Definition at line 648 of file bitvector.cpp.
is_sdiv_overflow()
bool stabilizer::util::BitVector::is_sdiv_overflow (const BitVector & bv) const
Determine if the (signed) division of this and the given bit-vector produces an overflow.
Parameters
bv The bit-vector to divide this bit-vector by.
Returns
True if it produces an overflow.
Definition at line 717 of file bitvector.cpp.
References d_size, and d_val_gmp.
is_smul_overflow()
bool stabilizer::util::BitVector::is_smul_overflow (const BitVector & bv) const
Determine if the (signed) multiplication of this and the given bit-vector produces an overflow.
Parameters
bv The bit-vector to multiply this bit-vector with.
Returns
True if it produces an overflow.
Definition at line 701 of file bitvector.cpp.
is_ssub_overflow()
bool stabilizer::util::BitVector::is_ssub_overflow (const BitVector & bv) const
Determine if the (signed) subtraction of this and the given bit-vector produces an overflow.
Parameters
bv The bit-vector to add to this bit-vector.
Returns
True if it produces an overflow.
Definition at line 667 of file bitvector.cpp.
is_true()
bool stabilizer::util::BitVector::is_true () const
Returns
True if this bit-vector is one and of size 1.
Definition at line 530 of file bitvector.cpp.
is_uadd_overflow()
bool stabilizer::util::BitVector::is_uadd_overflow (const BitVector & bv) const
Parameters
bv A bit-vector representing the number of bits to shift this bit-vector to the left.
bv The bit-vector to add to this bit-vector.
Returns
True if it produces an overflow.
Definition at line 630 of file bitvector.cpp.
References d_val_uint64.
is_umul_overflow()
bool stabilizer::util::BitVector::is_umul_overflow (const BitVector & bv) const
Determine if the (unsigned) multiplication of this and the given bit-vector produces an overflow.
Parameters
bv The bit-vector to multiply this bit-vector with.
Returns
True if it produces an overflow.
Definition at line 680 of file bitvector.cpp.
is_usub_overflow()
bool stabilizer::util::BitVector::is_usub_overflow (const BitVector & bv) const
Determine if the (unsigned) subtraction of this and the given bit-vector produces an overflow.
Parameters
bv The bit-vector to add to this bit-vector.
Returns
True if it produces an overflow.
Definition at line 661 of file bitvector.cpp.
is_zero()
bool stabilizer::util::BitVector::is_zero () const
Returns
True if this bit-vector is zero.
Definition at line 544 of file bitvector.cpp.
References d_size, d_val_gmp, is_gmp(), and is_null().
iset() [1/2]
void stabilizer::util::BitVector::iset (const BitVector & bv)
Set the value of this bit-vector to the value of bv (in-place).
Parameters
bv A bit-vector representing the value this bit-vector is to between set to.
Definition at line 371 of file bitvector.cpp.
iset() [2/2]
void stabilizer::util::BitVector::iset (uint64_t value)
Set the value of this bit-vector to the given unsigned (in-place).
Parameters
value The value to set.
Definition at line 359 of file bitvector.cpp.
lsb()
bool stabilizer::util::BitVector::lsb () const
Returns
True if the lsb (index 0) is 1, and false otherwise.
Definition at line 520 of file bitvector.cpp.
mk_false()
BitVector stabilizer::util::BitVector::mk_false () static
Create a false bit-vector (value 0 of size 1).
Returns
A bit-vector representing False.
Definition at line 130 of file bitvector.cpp.
References d_val_gmp.
mk_max_signed()
BitVector stabilizer::util::BitVector::mk_max_signed (uint64_t size) static
Create a maximum signed value (01..1) bit-vector of given size.
Parameters
size The size of the bit-vector.
Returns
A bit-vector representing the maximum signed value of given size.
Definition at line 155 of file bitvector.cpp.
mk_min_signed()
BitVector stabilizer::util::BitVector::mk_min_signed (uint64_t size) static
Create a minimum signed value (10..0) bit-vector of given size.
Parameters
size The size of the bit-vector.
Returns
A bit-vector representing the minimum signed value of given size.
Definition at line 149 of file bitvector.cpp.
Referenced by fits_in_size().
mk_one()
BitVector stabilizer::util::BitVector::mk_one (uint64_t size) static
Create a one bit-vector of given size.
Parameters
size The size of the bit-vector.
Returns
A bit-vector representing one of given size.
Definition at line 134 of file bitvector.cpp.
mk_ones()
BitVector stabilizer::util::BitVector::mk_ones (uint64_t size) static
Create a ones bit-vector of given size.
Parameters
size The size of the bit-vector.
Returns
A bit-vector representing ones of given size.
Definition at line 136 of file bitvector.cpp.
mk_true()
BitVector stabilizer::util::BitVector::mk_true () static
Create a true bit-vector (value 1 of size 1).
Returns
A bit-vector representing True.
Definition at line 128 of file bitvector.cpp.
mk_zero()
BitVector stabilizer::util::BitVector::mk_zero (uint64_t size) static
Create a zero bit-vector of given size.
Parameters
size The size of the bit-vector.
Returns
A bit-vector representing zero of given size..
Definition at line 132 of file bitvector.cpp.
msb()
bool stabilizer::util::BitVector::msb () const
Returns
True if the msb (index size - 1) is 1, and false otherwise.
Definition at line 525 of file bitvector.cpp.
operator!=()
bool stabilizer::util::BitVector::operator!= (const BitVector & bv) const
Disequality comparison operator.
Parameters
bv The bit-vector to compare this bit-vector to.
Definition at line 389 of file bitvector.cpp.
References d_val_gmp.
operator=()
BitVector & stabilizer::util::BitVector::operator= (const BitVector & other)
Copy assignment operator.
Definition at line 301 of file bitvector.cpp.
operator==()
bool stabilizer::util::BitVector::operator== (const BitVector & bv) const
Equality comparison operator.
Parameters
bv The bit-vector to compare this bit-vector to.
Definition at line 383 of file bitvector.cpp.
set_bit()
void stabilizer::util::BitVector::set_bit (uint64_t idx, bool value)
Set the bit at given index to the given value.
Parameters
idx The index of the bit.
value The value.
Definition at line 489 of file bitvector.cpp.
shift_is_uint64()
bool stabilizer::util::BitVector::shift_is_uint64 (uint64_t * res) const private
Determine if this bit-vector can be represented with a uint64_t.
Parameters
res If true, uint64_t representation is stored in res.
Returns
True if it can.
Definition at line 3092 of file bitvector.cpp.
Referenced by ibvrol(), and ibvror().
signed_compare()
int32_t stabilizer::util::BitVector::signed_compare (const BitVector & bv) const
Compare this bit-vector with given bit-vector (signed).
Parameters
bv The bit-vector to compare this bit-vector with.
Returns
0 if the bit-vectors are equal, -1 if their sizes don't match or if this is signed less than bv, and 1 if this is signed greater than bv.
Definition at line 460 of file bitvector.cpp.
size()
uint64_t stabilizer::util::BitVector::size () const inline
Returns
the size of this bit-vector.
Definition at line 264 of file bitvector.h.
Referenced by ibvnego(), ibvrol(), ibvror(), ibvzext(), and to_mpz().
str()
std::string stabilizer::util::BitVector::str (uint32_t base = 2) const
Get the string representation of this bit-vector.
Parameters
base 2 for binary representation, 10 for decimal representation, 16 for hexadecimal representation.
Returns
The string representation.
Definition at line 395 of file bitvector.cpp.
References d_size.
Referenced by stabilizer::parser::BitVectorUtils::bvAdd(), stabilizer::parser::BitVectorUtils::bvAshr(), stabilizer::parser::BitVectorUtils::bvLshr(), stabilizer::parser::BitVectorUtils::bvMul(), stabilizer::parser::BitVectorUtils::bvNeg(), stabilizer::parser::BitVectorUtils::bvSdiv(), stabilizer::parser::BitVectorUtils::bvShl(), stabilizer::parser::BitVectorUtils::bvSmod(), stabilizer::parser::BitVectorUtils::bvSrem(), stabilizer::parser::BitVectorUtils::bvSub(), stabilizer::parser::BitVectorUtils::bvUdiv(), and stabilizer::parser::BitVectorUtils::bvUrem().
to_mpz()
mpz_class stabilizer::util::BitVector::to_mpz () const
Convert bit-vector to mpz_class.
Definition at line 2970 of file bitvector.cpp.
References size().
to_uint64()
uint64_t stabilizer::util::BitVector::to_uint64 (bool truncate = false) const
Get the uint64_t representation of this bit-vector.
Parameters
size The size of this bit-vector, must be <= 64.
truncate True to allow truncating the value if it is not representable with 64 bits.
Returns
The uint64_t representation.
Definition at line 428 of file bitvector.cpp.
uint64_fdiv_r_2exp()
uint64_t stabilizer::util::BitVector::uint64_fdiv_r_2exp (uint64_t size, uint64_t val) static private
Normalize uint64_t value for a given bit-width. The equivalent of mpz_fdiv_r_2exp for uint64_t values. Compute the remainder of the division of val by 2^size, implemented with shifts and a bit mask.
Parameters
size The bit-width.
val The value.
Returns
The normalized value.
Definition at line 2981 of file bitvector.cpp.
Member Data Documentation
@1
union { ... }
The bit-vector value.
Note: We use a union instead of std::variant here in order to avoid the overhead of the latter, since we already have a "tracking variable" (the size of the bit-vector, d_size). Further, we do not use a unique_ptr for d_val_gmp because we don't gain anything if it is in a union – we have to manually destruct it anyways.
d_size
uint64_t stabilizer::util::BitVector::d_size = 0 private
The size of this bit-vector.
Definition at line 2214 of file bitvector.h.
Referenced by bit(), bvadd(), bvand(), bvashr(), bvconcat(), bvextract(), bvimplies(), bvmul(), bvnand(), bvnor(), bvor(), bvpow(), bvredand(), bvredxor(), bvrepeat(), bvrol(), bvroli(), bvror(), bvrori(), bvsaddo(), bvsdiv(), bvsdivo(), bvsext(), bvsge(), bvsgt(), bvshl(), bvshr(), bvsmod(), bvsmulo(), bvsrem(), bvssubo(), bvuaddo(), bvudiv(), bvumulo(), bvurem(), bvusubo(), bvzext(), count_leading_ones(), count_trailing_ones(), count_trailing_zeros(), ibvnego(), is_one(), is_sdiv_overflow(), is_zero(), str(), and ~BitVector().
d_val_gmp
mpz_t stabilizer::util::BitVector::d_val_gmp
Definition at line 2226 of file bitvector.h.
Referenced by bit(), bvpow(), compare(), fits_in_size(), ibvadd(), ibvand(), ibvite(), ibvmul(), ibvnand(), ibvnor(), ibvor(), ibvsub(), ibvudiv(), ibvurem(), ibvxnor(), ibvxor(), ibvzext(), is_neg_overflow(), is_one(), is_ones(), is_sdiv_overflow(), is_zero(), mk_false(), operator!=(), and ~BitVector().
d_val_uint64
uint64_t stabilizer::util::BitVector::d_val_uint64
Definition at line 2225 of file bitvector.h.
Referenced by fits_in_size(), ibvite(), ibvpow(), ibvzext(), is_one(), and is_uadd_overflow().
s_native_size
constexpr size_t stabilizer::util::BitVector::s_native_size = sizeof(unsigned long) * 8 static constexpr
Definition at line 52 of file bitvector.h.
Referenced by ibvzext().
The documentation for this class was generated from the following files:
src/util/bitvector.h
src/util/bitvector.cpp