SMTStabilizer API: stabilizer::parser::StringUtils Class Reference
stabilizer::parser::StringUtils Class Reference
String theory helper functions for SMT string operators.
#include <util.h>
Static Public Member Functions
static std::string strSubstr (const std::string &s, const Integer &i, const Integer &j)
static bool strPrefixof (const std::string &s, const std::string &t)
static bool strSuffixof (const std::string &s, const std::string &t)
static bool strContains (const std::string &s, const std::string &t)
static Integer strIndexof (const std::string &s, const std::string &t, const Integer &i)
static std::string strCharAt (const std::string &s, const Integer &i)
static std::string strUpdate (const std::string &s, const Integer &i, const std::string &t)
static std::string strReplace (const std::string &s, const std::string &t, const std::string &u)
static std::string strReplaceAll (const std::string &s, const std::string &t, const std::string &u)
static std::string strToLower (const std::string &s)
static std::string strToUpper (const std::string &s)
static std::string strRev (const std::string &s)
static std::string strUnquate (const std::string &s)
Detailed Description
String theory helper functions for SMT string operators.
Definition at line 150 of file util.h.
Member Function Documentation
strCharAt()
std::string stabilizer::parser::StringUtils::strCharAt (const std::string & s, const Integer & i) static
Definition at line 1024 of file util.cpp.
References stabilizer::parser::HighPrecisionInteger::toULong().
Referenced by stabilizer::parser::Parser::rewrite().
strContains()
bool stabilizer::parser::StringUtils::strContains (const std::string & s, const std::string & t) static
Definition at line 998 of file util.cpp.
Referenced by stabilizer::parser::Parser::rewrite().
strIndexof()
Integer stabilizer::parser::StringUtils::strIndexof (const std::string & s, const std::string & t, const Integer & i) static
Definition at line 1007 of file util.cpp.
References stabilizer::parser::HighPrecisionInteger::toULong().
Referenced by stabilizer::parser::Parser::rewrite().
strPrefixof()
bool stabilizer::parser::StringUtils::strPrefixof (const std::string & s, const std::string & t) static
Definition at line 971 of file util.cpp.
Referenced by stabilizer::parser::Parser::rewrite().
strReplace()
std::string stabilizer::parser::StringUtils::strReplace (const std::string & s, const std::string & t, const std::string & u) static
Definition at line 1042 of file util.cpp.
Referenced by stabilizer::parser::Parser::rewrite().
strReplaceAll()
std::string stabilizer::parser::StringUtils::strReplaceAll (const std::string & s, const std::string & t, const std::string & u) static
Definition at line 1062 of file util.cpp.
Referenced by stabilizer::parser::Parser::rewrite().
strRev()
std::string stabilizer::parser::StringUtils::strRev (const std::string & s) static
Definition at line 1103 of file util.cpp.
Referenced by stabilizer::parser::Parser::rewrite().
strSubstr()
std::string stabilizer::parser::StringUtils::strSubstr (const std::string & s, const Integer & i, const Integer & j) static
Definition at line 950 of file util.cpp.
References stabilizer::parser::HighPrecisionInteger::toULong().
Referenced by stabilizer::parser::Parser::rewrite().
strSuffixof()
bool stabilizer::parser::StringUtils::strSuffixof (const std::string & s, const std::string & t) static
Definition at line 984 of file util.cpp.
Referenced by stabilizer::parser::Parser::rewrite().
strToLower()
std::string stabilizer::parser::StringUtils::strToLower (const std::string & s) static
Definition at line 1085 of file util.cpp.
Referenced by stabilizer::parser::Parser::rewrite().
strToUpper()
std::string stabilizer::parser::StringUtils::strToUpper (const std::string & s) static
Definition at line 1094 of file util.cpp.
Referenced by stabilizer::parser::Parser::rewrite().
strUnquate()
static std::string stabilizer::parser::StringUtils::strUnquate (const std::string & s) inline static
Definition at line 164 of file util.h.
Referenced by stabilizer::parser::Parser::rewrite().
strUpdate()
std::string stabilizer::parser::StringUtils::strUpdate (const std::string & s, const Integer & i, const std::string & t) static
Definition at line 1030 of file util.cpp.
References stabilizer::parser::HighPrecisionInteger::toULong().
Referenced by stabilizer::parser::Parser::rewrite().
The documentation for this class was generated from the following files:
src/parser/util.h
src/parser/util.cpp