SMTStabilizer API: stabilizer::parser::HighPrecisionInteger Class Reference
stabilizer::parser::HighPrecisionInteger Class Reference
#include <number.h>
Public Member Functions
HighPrecisionInteger ()
HighPrecisionInteger (int i)
HighPrecisionInteger (long i)
HighPrecisionInteger (unsigned long i)
HighPrecisionInteger (double d)
HighPrecisionInteger (const std::string &s, int base=10)
HighPrecisionInteger (const char *s, int base=10)
HighPrecisionInteger (const HighPrecisionInteger &other)
HighPrecisionInteger (const mpz_t z)
HighPrecisionInteger & operator= (const HighPrecisionInteger &other)
~HighPrecisionInteger ()=default
HighPrecisionInteger operator+ (const HighPrecisionInteger &other) const
HighPrecisionInteger operator- (const HighPrecisionInteger &other) const
HighPrecisionInteger operator- () const
HighPrecisionInteger operator* (const HighPrecisionInteger &other) const
HighPrecisionInteger operator/ (const HighPrecisionInteger &other) const
HighPrecisionInteger operator% (const HighPrecisionInteger &other) const
HighPrecisionInteger & operator+= (const HighPrecisionInteger &other)
HighPrecisionInteger & operator-= (const HighPrecisionInteger &other)
HighPrecisionInteger & operator*= (const HighPrecisionInteger &other)
HighPrecisionInteger & operator/= (const HighPrecisionInteger &other)
HighPrecisionInteger & operator%= (const HighPrecisionInteger &other)
HighPrecisionInteger & operator++ ()
HighPrecisionInteger operator++ (int)
HighPrecisionInteger & operator-- ()
HighPrecisionInteger operator-- (int)
bool operator== (const HighPrecisionInteger &other) const
bool operator!= (const HighPrecisionInteger &other) const
bool operator< (const HighPrecisionInteger &other) const
bool operator<= (const HighPrecisionInteger &other) const
bool operator> (const HighPrecisionInteger &other) const
bool operator>= (const HighPrecisionInteger &other) const
HighPrecisionInteger operator& (const HighPrecisionInteger &other) const
HighPrecisionInteger operator| (const HighPrecisionInteger &other) const
HighPrecisionInteger operator^ (const HighPrecisionInteger &other) const
HighPrecisionInteger operator~ () const
HighPrecisionInteger operator<< (unsigned long bits) const
HighPrecisionInteger operator>> (unsigned long bits) const
HighPrecisionInteger abs () const
HighPrecisionInteger pow (unsigned long exp) const
HighPrecisionInteger sqrt () const
HighPrecisionInteger safeSqrt () const
HighPrecisionInteger root (unsigned long n) const
bool isProbablePrime (int reps=25) const
bool isDivisibleBy (const HighPrecisionInteger &d) const
std::string toString (int base=10) const
int toInt () const
long toLong () const
unsigned long toULong () const
long long toLongLong () const
double toDouble () const
const mpz_class & getMPZ () const
mpz_class & getMPZ ()
const mpz_t * get_mpz_t () const
HighPrecisionInteger nextBelow () const
HighPrecisionInteger nextAbove () const
Static Public Member Functions
static HighPrecisionInteger factorial (unsigned long n)
static HighPrecisionInteger fibonacci (unsigned long n)
static HighPrecisionInteger gcd (const HighPrecisionInteger &a, const HighPrecisionInteger &b)
static HighPrecisionInteger lcm (const HighPrecisionInteger &a, const HighPrecisionInteger &b)
Private Attributes
mpz_class value
Detailed Description
Definition at line 42 of file number.h.
Constructor & Destructor Documentation
HighPrecisionInteger() [1/9]
stabilizer::parser::HighPrecisionInteger::HighPrecisionInteger ()
Definition at line 753 of file number.cpp.
Referenced by factorial(), fibonacci(), root(), safeSqrt(), and sqrt().
HighPrecisionInteger() [2/9]
stabilizer::parser::HighPrecisionInteger::HighPrecisionInteger (int i)
Definition at line 755 of file number.cpp.
HighPrecisionInteger() [3/9]
stabilizer::parser::HighPrecisionInteger::HighPrecisionInteger (long i)
Definition at line 757 of file number.cpp.
HighPrecisionInteger() [4/9]
stabilizer::parser::HighPrecisionInteger::HighPrecisionInteger (unsigned long i)
Definition at line 759 of file number.cpp.
HighPrecisionInteger() [5/9]
stabilizer::parser::HighPrecisionInteger::HighPrecisionInteger (double d)
Definition at line 761 of file number.cpp.
HighPrecisionInteger() [6/9]
stabilizer::parser::HighPrecisionInteger::HighPrecisionInteger (const std::string & s, int base = 10)
Definition at line 763 of file number.cpp.
References value.
HighPrecisionInteger() [7/9]
stabilizer::parser::HighPrecisionInteger::HighPrecisionInteger (const char * s, int base = 10)
Definition at line 773 of file number.cpp.
References value.
HighPrecisionInteger() [8/9]
stabilizer::parser::HighPrecisionInteger::HighPrecisionInteger (const HighPrecisionInteger & other)
Definition at line 783 of file number.cpp.
HighPrecisionInteger() [9/9]
stabilizer::parser::HighPrecisionInteger::HighPrecisionInteger (const mpz_t z)
Definition at line 707 of file number.cpp.
References value.
~HighPrecisionInteger()
stabilizer::parser::HighPrecisionInteger::~HighPrecisionInteger () default
Member Function Documentation
abs()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::abs () const
Definition at line 970 of file number.cpp.
References value.
Referenced by stabilizer::parser::Number::abs().
factorial()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::factorial (unsigned long n) static
Definition at line 716 of file number.cpp.
References HighPrecisionInteger().
fibonacci()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::fibonacci (unsigned long n) static
Definition at line 724 of file number.cpp.
References HighPrecisionInteger().
gcd()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::gcd (const HighPrecisionInteger & a, const HighPrecisionInteger & b) static
Definition at line 738 of file number.cpp.
References value.
get_mpz_t()
const mpz_t * stabilizer::parser::HighPrecisionInteger::get_mpz_t () const
Definition at line 711 of file number.cpp.
References value.
getMPZ() [1/2]
mpz_class& stabilizer::parser::HighPrecisionInteger::getMPZ ()
getMPZ() [2/2]
mpz_class & stabilizer::parser::HighPrecisionInteger::getMPZ () const
Definition at line 1073 of file number.cpp.
References value.
Referenced by stabilizer::parser::HighPrecisionReal::HighPrecisionReal().
isDivisibleBy()
bool stabilizer::parser::HighPrecisionInteger::isDivisibleBy (const HighPrecisionInteger & d) const
Definition at line 1015 of file number.cpp.
References value.
isProbablePrime()
bool stabilizer::parser::HighPrecisionInteger::isProbablePrime (int reps = 25) const
Definition at line 1011 of file number.cpp.
References value.
lcm()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::lcm (const HighPrecisionInteger & a, const HighPrecisionInteger & b) static
Definition at line 745 of file number.cpp.
References value.
nextAbove()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::nextAbove () const
Definition at line 1083 of file number.cpp.
References value.
Referenced by stabilizer::parser::Number::nextAbove().
nextBelow()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::nextBelow () const
Definition at line 1077 of file number.cpp.
References value.
Referenced by stabilizer::parser::Number::nextBelow().
operator!=()
bool stabilizer::parser::HighPrecisionInteger::operator!= (const HighPrecisionInteger & other) const
Definition at line 907 of file number.cpp.
References value.
operator%()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator% (const HighPrecisionInteger & other) const
Definition at line 834 of file number.cpp.
References value.
operator%=()
HighPrecisionInteger & stabilizer::parser::HighPrecisionInteger::operator%= (const HighPrecisionInteger & other)
Definition at line 871 of file number.cpp.
References value.
operator&()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator& (const HighPrecisionInteger & other) const
Definition at line 929 of file number.cpp.
References value.
operator*()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator* (const HighPrecisionInteger & other) const
Definition at line 817 of file number.cpp.
References value.
operator*=()
HighPrecisionInteger & stabilizer::parser::HighPrecisionInteger::operator*= (const HighPrecisionInteger & other)
Definition at line 856 of file number.cpp.
References value.
operator+()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator+ (const HighPrecisionInteger & other) const
Definition at line 797 of file number.cpp.
References value.
operator++() [1/2]
HighPrecisionInteger & stabilizer::parser::HighPrecisionInteger::operator++ ()
Definition at line 880 of file number.cpp.
References value.
operator++() [2/2]
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator++ (int)
Definition at line 885 of file number.cpp.
References value.
operator+=()
HighPrecisionInteger & stabilizer::parser::HighPrecisionInteger::operator+= (const HighPrecisionInteger & other)
Definition at line 844 of file number.cpp.
References value.
operator-() [1/2]
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator- () const
Definition at line 810 of file number.cpp.
References value.
operator-() [2/2]
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator- (const HighPrecisionInteger & other) const
Definition at line 804 of file number.cpp.
References value.
operator--() [1/2]
HighPrecisionInteger & stabilizer::parser::HighPrecisionInteger::operator-- ()
Definition at line 891 of file number.cpp.
References value.
operator--() [2/2]
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator-- (int)
Definition at line 896 of file number.cpp.
References value.
operator-=()
HighPrecisionInteger & stabilizer::parser::HighPrecisionInteger::operator-= (const HighPrecisionInteger & other)
Definition at line 850 of file number.cpp.
References value.
operator/()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator/ (const HighPrecisionInteger & other) const
Definition at line 824 of file number.cpp.
References value.
operator/=()
HighPrecisionInteger & stabilizer::parser::HighPrecisionInteger::operator/= (const HighPrecisionInteger & other)
Definition at line 862 of file number.cpp.
References value.
operator<()
bool stabilizer::parser::HighPrecisionInteger::operator< (const HighPrecisionInteger & other) const
Definition at line 911 of file number.cpp.
References value.
operator<<()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator<< (unsigned long bits) const
Definition at line 956 of file number.cpp.
References value.
operator<=()
bool stabilizer::parser::HighPrecisionInteger::operator<= (const HighPrecisionInteger & other) const
Definition at line 915 of file number.cpp.
References value.
operator=()
HighPrecisionInteger & stabilizer::parser::HighPrecisionInteger::operator= (const HighPrecisionInteger & other)
Definition at line 788 of file number.cpp.
References value.
operator==()
bool stabilizer::parser::HighPrecisionInteger::operator== (const HighPrecisionInteger & other) const
Definition at line 903 of file number.cpp.
References value.
operator>()
bool stabilizer::parser::HighPrecisionInteger::operator> (const HighPrecisionInteger & other) const
Definition at line 919 of file number.cpp.
References value.
operator>=()
bool stabilizer::parser::HighPrecisionInteger::operator>= (const HighPrecisionInteger & other) const
Definition at line 923 of file number.cpp.
References value.
operator>>()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator>> (unsigned long bits) const
Definition at line 963 of file number.cpp.
References value.
operator^()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator^ (const HighPrecisionInteger & other) const
Definition at line 943 of file number.cpp.
References value.
operator|()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator| (const HighPrecisionInteger & other) const
Definition at line 936 of file number.cpp.
References value.
operator~()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::operator~ () const
Definition at line 949 of file number.cpp.
References value.
pow()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::pow (unsigned long exp) const
Definition at line 976 of file number.cpp.
References value.
Referenced by stabilizer::parser::Number::pow().
root()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::root (unsigned long n) const
Definition at line 999 of file number.cpp.
References HighPrecisionInteger(), and value.
safeSqrt()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::safeSqrt () const
Definition at line 991 of file number.cpp.
References HighPrecisionInteger(), and value.
Referenced by stabilizer::parser::Number::safeSqrt().
sqrt()
HighPrecisionInteger stabilizer::parser::HighPrecisionInteger::sqrt () const
Definition at line 982 of file number.cpp.
References HighPrecisionInteger(), and value.
Referenced by stabilizer::parser::Number::sqrt().
toDouble()
double stabilizer::parser::HighPrecisionInteger::toDouble () const
Definition at line 1070 of file number.cpp.
References value.
toInt()
int stabilizer::parser::HighPrecisionInteger::toInt () const
Definition at line 1033 of file number.cpp.
References value.
Referenced by stabilizer::parser::Value::repeatStr(), and stabilizer::parser::Value::substr().
toLong()
long stabilizer::parser::HighPrecisionInteger::toLong () const
Definition at line 1040 of file number.cpp.
References value.
toLongLong()
long long stabilizer::parser::HighPrecisionInteger::toLongLong () const
Definition at line 1054 of file number.cpp.
References toString(), and value.
toString()
std::string stabilizer::parser::HighPrecisionInteger::toString (int base = 10) const
Definition at line 1023 of file number.cpp.
References value.
Referenced by stabilizer::parser::DAGNode::DAGNode(), stabilizer::parser::decToBv(), stabilizer::parser::BitVectorUtils::intToBv(), stabilizer::parser::Parser::isOne(), stabilizer::parser::Parser::isZero(), stabilizer::parser::BitVectorUtils::natToBv(), stabilizer::parser::Parser::parseConstFunc(), stabilizer::parser::Parser::rewrite(), toLongLong(), stabilizer::parser::ConversionUtils::toString(), and stabilizer::parser::Number::toString().
toULong()
unsigned long stabilizer::parser::HighPrecisionInteger::toULong () const
Definition at line 1047 of file number.cpp.
References value.
Referenced by stabilizer::parser::BitVectorUtils::bvCompareToUint(), stabilizer::parser::BitVectorUtils::bvExtract(), stabilizer::parser::BitVectorUtils::bvRepeat(), stabilizer::parser::BitVectorUtils::bvRotateLeft(), stabilizer::parser::BitVectorUtils::bvRotateRight(), stabilizer::parser::BitVectorUtils::bvSignExtend(), stabilizer::parser::BitVectorUtils::bvZeroExtend(), stabilizer::parser::FloatingPointUtils::fpToSbv(), stabilizer::parser::FloatingPointUtils::fpToUbv(), stabilizer::parser::BitVectorUtils::intToBv(), stabilizer::parser::Parser::mkBvExtract(), stabilizer::parser::Parser::mkBvRepeat(), stabilizer::parser::Parser::mkBvSignExt(), stabilizer::parser::Parser::mkBvZeroExt(), stabilizer::parser::BitVectorUtils::mkOnes(), stabilizer::parser::Parser::mkToFp(), stabilizer::parser::Parser::mkToFpUnsigned(), stabilizer::parser::BitVectorUtils::natToBv(), stabilizer::parser::Number::pow(), stabilizer::parser::StringUtils::strCharAt(), stabilizer::parser::StringUtils::strIndexof(), stabilizer::parser::StringUtils::strSubstr(), and stabilizer::parser::StringUtils::strUpdate().
Member Data Documentation
value
mpz_class stabilizer::parser::HighPrecisionInteger::value private
Definition at line 131 of file number.h.
Referenced by abs(), gcd(), get_mpz_t(), getMPZ(), HighPrecisionInteger(), isDivisibleBy(), isProbablePrime(), lcm(), nextAbove(), nextBelow(), operator!=(), operator%(), operator%=(), operator&(), operator*(), operator*=(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), operator/(), operator/=(), operator<(), operator<<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), operator>>(), operator^(), operator|(), operator~(), pow(), root(), safeSqrt(), sqrt(), toDouble(), toInt(), toLong(), toLongLong(), toString(), and toULong().
The documentation for this class was generated from the following files:
src/parser/number.h
src/parser/number.cpp