SMTStabilizer API: stabilizer::parser::Value Class Reference
stabilizer::parser::Value Class Reference
#include <value.h>
Public Member Functions
Value ()
Value (const Value &other)
Value & operator= (const Value &other)
~Value ()
Value (const std::string &string_value)
Value (const Number &number_value)
Value (const Interval &interval_value)
Value (const bool &boolean_value)
Value (const ValueType &value_type)
void setValue (const std::string &string_value)
void setValue (const Number &number_value)
void setValue (const Interval &interval_value)
void setValue (const bool &boolean_value)
ValueType getType () const
std::string getStringValue () const
Number getNumberValue () const
Interval getIntervalValue () const
bool getBooleanValue () const
Value & operator= (const std::string &string_value)
Value & operator= (const Number &number_value)
Value & operator= (const Interval &interval_value)
Value & operator= (const bool &boolean_value)
bool operator== (const Value &other) const
bool operator!= (const Value &other) const
bool operator< (const Value &other) const
bool operator<= (const Value &other) const
bool operator> (const Value &other) const
bool operator>= (const Value &other) const
Value & operator+= (const Value &other)
Value & operator-= (const Value &other)
Value & operator*= (const Value &other)
Value & operator/= (const Value &other)
Value & operator%= (const Value &other)
Value & operator^= (const Value &other)
Value & operator&= (const Value &other)
Value & operator|= (const Value &other)
Value & operator<<= (const Value &other)
Value & operator>>= (const Value &other)
Value & operator++ ()
Value & operator-- ()
Value operator++ (int)
Value operator-- (int)
bool operator&& (const Value &other) const
bool operator|| (const Value &other) const
bool operator! () const
Value operator+ (const Value &other) const
Value operator- (const Value &other) const
Value operator* (const Value &other) const
Value operator/ (const Value &other) const
Value operator% (const Value &other) const
Value operator^ (const Value &other) const
Value operator& (const Value &other) const
Value operator| (const Value &other) const
Value operator~ () const
Value operator<< (const Value &other) const
Value operator>> (const Value &other) const
Value neg () const
Value abs () const
Value sqrt () const
Value safeSqrt () const
Value pow (const Value &other) const
Value exp () const
Value ln () const
Value lg () const
Value lb () const
Value log (const Value &other) const
Value ceil () const
Value floor () const
Value round () const
Value sin () const
Value cos () const
Value tan () const
Value cot () const
Value sec () const
Value csc () const
Value asin () const
Value acos () const
Value atan () const
Value acot () const
Value asec () const
Value acsc () const
Value atan2 (const Value &other) const
Value sinh () const
Value cosh () const
Value tanh () const
Value coth () const
Value sech () const
Value csch () const
Value asinh () const
Value acosh () const
Value atanh () const
Value acoth () const
Value asech () const
Value acsch () const
Value concatStr (const Value &other) const
Value substr (const Value &start, const Value &end) const
Value repeatStr (const Value &other) const
Value replace (const Value &old, const Value &newVal) const
Value split (const Value &delimiter) const
Value join (const Value &delimiter) const
Value reverse () const
Value sortStr () const
Value unique () const
Value trim () const
Value ltrim () const
Value rtrim () const
Value toLower () const
Value toUpper () const
Value toNumber () const
Value toBoolean () const
Value toBV () const
Value toFP () const
Value toArray () const
std::string toString () const
Private Attributes
std::string string_value
Number number_value
Interval interval_value
bool boolean_value
ValueType value_type
Detailed Description
Definition at line 50 of file value.h.
Constructor & Destructor Documentation
Value() [1/7]
stabilizer::parser::Value::Value ()
Definition at line 38 of file value.cpp.
Referenced by abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atan2(), atanh(), ceil(), concatStr(), cos(), cosh(), cot(), coth(), csc(), csch(), exp(), floor(), lb(), lg(), ln(), log(), ltrim(), neg(), operator%(), operator*(), operator+(), operator-(), operator/(), operator~(), pow(), repeatStr(), replace(), reverse(), round(), rtrim(), safeSqrt(), sec(), sech(), sin(), sinh(), sortStr(), sqrt(), substr(), tan(), tanh(), toBoolean(), toLower(), toNumber(), toUpper(), trim(), and unique().
Value() [2/7]
stabilizer::parser::Value::Value (const Value & other)
Definition at line 41 of file value.cpp.
~Value()
stabilizer::parser::Value::~Value ()
Definition at line 57 of file value.cpp.
Value() [3/7]
stabilizer::parser::Value::Value (const std::string & string_value)
Definition at line 60 of file value.cpp.
Value() [4/7]
stabilizer::parser::Value::Value (const Number & number_value)
Definition at line 63 of file value.cpp.
Value() [5/7]
stabilizer::parser::Value::Value (const Interval & interval_value)
Definition at line 66 of file value.cpp.
Value() [6/7]
stabilizer::parser::Value::Value (const bool & boolean_value)
Definition at line 69 of file value.cpp.
Value() [7/7]
stabilizer::parser::Value::Value (const ValueType & value_type)
Definition at line 72 of file value.cpp.
Member Function Documentation
abs()
Value stabilizer::parser::Value::abs () const
Definition at line 397 of file value.cpp.
References stabilizer::parser::Interval::abs(), stabilizer::parser::Number::abs(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
acos()
Value stabilizer::parser::Value::acos () const
Definition at line 704 of file value.cpp.
References stabilizer::parser::Interval::acos(), stabilizer::parser::Number::acos(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
acosh()
Value stabilizer::parser::Value::acosh () const
Definition at line 849 of file value.cpp.
References stabilizer::parser::Interval::acosh(), stabilizer::parser::Number::acosh(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
acot()
Value stabilizer::parser::Value::acot () const
Definition at line 726 of file value.cpp.
References stabilizer::parser::Interval::acot(), stabilizer::parser::Number::acot(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
acoth()
Value stabilizer::parser::Value::acoth () const
Definition at line 873 of file value.cpp.
References stabilizer::parser::Interval::acoth(), stabilizer::parser::Number::acoth(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
acsc()
Value stabilizer::parser::Value::acsc () const
Definition at line 748 of file value.cpp.
References stabilizer::parser::Interval::acsc(), stabilizer::parser::Number::acsc(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
acsch()
Value stabilizer::parser::Value::acsch () const
Definition at line 897 of file value.cpp.
References stabilizer::parser::Interval::acsch(), stabilizer::parser::Number::acsch(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
asec()
Value stabilizer::parser::Value::asec () const
Definition at line 737 of file value.cpp.
References stabilizer::parser::Interval::asec(), stabilizer::parser::Number::asec(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
asech()
Value stabilizer::parser::Value::asech () const
Definition at line 885 of file value.cpp.
References stabilizer::parser::Interval::asech(), stabilizer::parser::Number::asech(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
asin()
Value stabilizer::parser::Value::asin () const
Definition at line 693 of file value.cpp.
References stabilizer::parser::Interval::asin(), stabilizer::parser::Number::asin(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
asinh()
Value stabilizer::parser::Value::asinh () const
Definition at line 837 of file value.cpp.
References stabilizer::parser::Interval::asinh(), stabilizer::parser::Number::asinh(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
atan()
Value stabilizer::parser::Value::atan () const
Definition at line 715 of file value.cpp.
References stabilizer::parser::Interval::atan(), stabilizer::parser::Number::atan(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
atan2()
Value stabilizer::parser::Value::atan2 (const Value & other) const
Definition at line 759 of file value.cpp.
References stabilizer::parser::Number::atan2(), stabilizer::parser::NUMBER, number_value, Value(), and value_type.
atanh()
Value stabilizer::parser::Value::atanh () const
Definition at line 861 of file value.cpp.
References stabilizer::parser::Interval::atanh(), stabilizer::parser::Number::atanh(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
ceil()
Value stabilizer::parser::Value::ceil () const
Definition at line 622 of file value.cpp.
References stabilizer::parser::Number::ceil(), stabilizer::parser::INTERVAL, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
concatStr()
Value stabilizer::parser::Value::concatStr (const Value & other) const
Definition at line 910 of file value.cpp.
References stabilizer::parser::STRING, string_value, Value(), and value_type.
cos()
Value stabilizer::parser::Value::cos () const
Definition at line 342 of file value.cpp.
References stabilizer::parser::Interval::cos(), stabilizer::parser::Number::cos(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
cosh()
Value stabilizer::parser::Value::cosh () const
Definition at line 780 of file value.cpp.
References stabilizer::parser::Interval::cosh(), stabilizer::parser::Number::cosh(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
cot()
Value stabilizer::parser::Value::cot () const
Definition at line 659 of file value.cpp.
References stabilizer::parser::Interval::cot(), stabilizer::parser::Number::cot(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
coth()
Value stabilizer::parser::Value::coth () const
Definition at line 802 of file value.cpp.
References stabilizer::parser::Interval::coth(), stabilizer::parser::Number::coth(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
csc()
Value stabilizer::parser::Value::csc () const
Definition at line 681 of file value.cpp.
References stabilizer::parser::Interval::csc(), stabilizer::parser::Number::csc(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
csch()
Value stabilizer::parser::Value::csch () const
Definition at line 825 of file value.cpp.
References stabilizer::parser::Interval::csch(), stabilizer::parser::Number::csch(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
exp()
Value stabilizer::parser::Value::exp () const
Definition at line 375 of file value.cpp.
References stabilizer::parser::Interval::exp(), stabilizer::parser::Number::exp(), stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
floor()
Value stabilizer::parser::Value::floor () const
Definition at line 634 of file value.cpp.
References stabilizer::parser::Number::floor(), stabilizer::parser::INTERVAL, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
getBooleanValue()
bool stabilizer::parser::Value::getBooleanValue () const
Definition at line 119 of file value.cpp.
References stabilizer::parser::BOOLEAN, boolean_value, and value_type.
getIntervalValue()
Interval stabilizer::parser::Value::getIntervalValue () const
Definition at line 112 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, and value_type.
getNumberValue()
Number stabilizer::parser::Value::getNumberValue () const
Definition at line 105 of file value.cpp.
References stabilizer::parser::NUMBER, number_value, and value_type.
getStringValue()
std::string stabilizer::parser::Value::getStringValue () const
Definition at line 98 of file value.cpp.
References stabilizer::parser::STRING, string_value, and value_type.
getType()
ValueType stabilizer::parser::Value::getType () const
Definition at line 96 of file value.cpp.
References value_type.
join()
Value stabilizer::parser::Value::join (const Value & delimiter) const
Definition at line 984 of file value.cpp.
lb()
Value stabilizer::parser::Value::lb () const
Definition at line 601 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::Interval::lb(), stabilizer::parser::Number::lb(), stabilizer::parser::NUMBER, number_value, Value(), and value_type.
lg()
Value stabilizer::parser::Value::lg () const
Definition at line 590 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::Interval::lg(), stabilizer::parser::Number::lg(), stabilizer::parser::NUMBER, number_value, Value(), and value_type.
ln()
Value stabilizer::parser::Value::ln () const
Definition at line 386 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::Interval::ln(), stabilizer::parser::Number::ln(), stabilizer::parser::NUMBER, number_value, Value(), and value_type.
log()
Value stabilizer::parser::Value::log (const Value & other) const
Definition at line 612 of file value.cpp.
References stabilizer::parser::Number::log(), stabilizer::parser::NUMBER, number_value, Value(), and value_type.
ltrim()
Value stabilizer::parser::Value::ltrim () const
Definition at line 1032 of file value.cpp.
References stabilizer::parser::STRING, string_value, Value(), and value_type.
neg()
Value stabilizer::parser::Value::neg () const
Definition at line 566 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::Interval::negate(), stabilizer::parser::NUMBER, number_value, Value(), and value_type.
operator!()
bool stabilizer::parser::Value::operator! () const
Definition at line 439 of file value.cpp.
References stabilizer::parser::BOOLEAN, boolean_value, and value_type.
operator!=()
bool stabilizer::parser::Value::operator!= (const Value & other) const
Definition at line 232 of file value.cpp.
operator%()
Value stabilizer::parser::Value::operator% (const Value & other) const
Definition at line 317 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::Interval::mod(), stabilizer::parser::NUMBER, number_value, Value(), and value_type.
operator%=()
Value & stabilizer::parser::Value::operator%= (const Value & other)
Definition at line 467 of file value.cpp.
operator&()
Value stabilizer::parser::Value::operator& (const Value & other) const
Definition at line 481 of file value.cpp.
References stabilizer::parser::NUMBER, and value_type.
operator&&()
bool stabilizer::parser::Value::operator&& (const Value & other) const
Definition at line 425 of file value.cpp.
References stabilizer::parser::BOOLEAN, boolean_value, and value_type.
operator&=()
Value & stabilizer::parser::Value::operator&= (const Value & other)
Definition at line 1141 of file value.cpp.
References stabilizer::parser::NUMBER, and value_type.
operator*()
Value stabilizer::parser::Value::operator* (const Value & other) const
Definition at line 291 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
operator*=()
Value & stabilizer::parser::Value::operator*= (const Value & other)
Definition at line 457 of file value.cpp.
operator+()
Value stabilizer::parser::Value::operator+ (const Value & other) const
Definition at line 262 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::STRING, string_value, Value(), and value_type.
operator++() [1/2]
Value & stabilizer::parser::Value::operator++ ()
Definition at line 514 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, and value_type.
operator++() [2/2]
Value stabilizer::parser::Value::operator++ (int)
Definition at line 540 of file value.cpp.
operator+=()
Value & stabilizer::parser::Value::operator+= (const Value & other)
Definition at line 447 of file value.cpp.
operator-()
Value stabilizer::parser::Value::operator- (const Value & other) const
Definition at line 278 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
operator--() [1/2]
Value & stabilizer::parser::Value::operator-- ()
Definition at line 527 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, and value_type.
operator--() [2/2]
Value stabilizer::parser::Value::operator-- (int)
Definition at line 546 of file value.cpp.
operator-=()
Value & stabilizer::parser::Value::operator-= (const Value & other)
Definition at line 452 of file value.cpp.
operator/()
Value stabilizer::parser::Value::operator/ (const Value & other) const
Definition at line 304 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, Value(), and value_type.
operator/=()
Value & stabilizer::parser::Value::operator/= (const Value & other)
Definition at line 462 of file value.cpp.
operator<()
bool stabilizer::parser::Value::operator< (const Value & other) const
Definition at line 234 of file value.cpp.
References stabilizer::parser::BOOLEAN, boolean_value, stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::STRING, string_value, and value_type.
operator<<()
Value stabilizer::parser::Value::operator<< (const Value & other) const
Definition at line 497 of file value.cpp.
References stabilizer::parser::NUMBER, and value_type.
operator<<=()
Value & stabilizer::parser::Value::operator<<= (const Value & other)
Definition at line 1159 of file value.cpp.
References stabilizer::parser::NUMBER, and value_type.
operator<=()
bool stabilizer::parser::Value::operator<= (const Value & other) const
Definition at line 253 of file value.cpp.
operator=() [1/5]
Value & stabilizer::parser::Value::operator= (const bool & boolean_value)
Definition at line 145 of file value.cpp.
References stabilizer::parser::BOOLEAN, boolean_value, and value_type.
operator=() [2/5]
Value & stabilizer::parser::Value::operator= (const Interval & interval_value)
Definition at line 139 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, and value_type.
operator=() [3/5]
Value & stabilizer::parser::Value::operator= (const Number & number_value)
Definition at line 133 of file value.cpp.
References stabilizer::parser::NUMBER, number_value, and value_type.
operator=() [4/5]
Value & stabilizer::parser::Value::operator= (const std::string & string_value)
Definition at line 127 of file value.cpp.
References stabilizer::parser::STRING, string_value, and value_type.
operator=() [5/5]
Value & stabilizer::parser::Value::operator= (const Value & other)
Definition at line 45 of file value.cpp.
References boolean_value, interval_value, number_value, string_value, and value_type.
operator==()
bool stabilizer::parser::Value::operator== (const Value & other) const
Definition at line 213 of file value.cpp.
References stabilizer::parser::BOOLEAN, boolean_value, stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::STRING, string_value, and value_type.
operator>()
bool stabilizer::parser::Value::operator> (const Value & other) const
Definition at line 257 of file value.cpp.
operator>=()
bool stabilizer::parser::Value::operator>= (const Value & other) const
Definition at line 259 of file value.cpp.
operator>>()
Value stabilizer::parser::Value::operator>> (const Value & other) const
Definition at line 505 of file value.cpp.
References stabilizer::parser::NUMBER, and value_type.
operator>>=()
Value & stabilizer::parser::Value::operator>>= (const Value & other)
Definition at line 1168 of file value.cpp.
References stabilizer::parser::NUMBER, and value_type.
operator^()
Value stabilizer::parser::Value::operator^ (const Value & other) const
Definition at line 473 of file value.cpp.
References stabilizer::parser::NUMBER, and value_type.
operator^=()
Value & stabilizer::parser::Value::operator^= (const Value & other)
Definition at line 1132 of file value.cpp.
References stabilizer::parser::NUMBER, and value_type.
operator|()
Value stabilizer::parser::Value::operator| (const Value & other) const
Definition at line 489 of file value.cpp.
References stabilizer::parser::NUMBER, and value_type.
operator|=()
Value & stabilizer::parser::Value::operator|= (const Value & other)
Definition at line 1150 of file value.cpp.
References stabilizer::parser::NUMBER, and value_type.
operator||()
bool stabilizer::parser::Value::operator|| (const Value & other) const
Definition at line 432 of file value.cpp.
References stabilizer::parser::BOOLEAN, boolean_value, and value_type.
operator~()
Value stabilizer::parser::Value::operator~ () const
Definition at line 553 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, Value(), and value_type.
pow()
Value stabilizer::parser::Value::pow (const Value & other) const
Definition at line 408 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::Interval::pow(), stabilizer::parser::Number::pow(), Value(), and value_type.
repeatStr()
Value stabilizer::parser::Value::repeatStr (const Value & other) const
Definition at line 919 of file value.cpp.
References stabilizer::parser::NUMBER, number_value, stabilizer::parser::STRING, string_value, stabilizer::parser::HighPrecisionInteger::toInt(), stabilizer::parser::Number::toInteger(), Value(), and value_type.
replace()
Value stabilizer::parser::Value::replace (const Value & old, const Value & newVal) const
Definition at line 963 of file value.cpp.
References stabilizer::parser::STRING, string_value, Value(), and value_type.
reverse()
Value stabilizer::parser::Value::reverse () const
Definition at line 989 of file value.cpp.
References stabilizer::parser::STRING, string_value, Value(), and value_type.
round()
Value stabilizer::parser::Value::round () const
Definition at line 646 of file value.cpp.
References stabilizer::parser::INTERVAL, stabilizer::parser::NUMBER, number_value, stabilizer::parser::Number::round(), Value(), and value_type.
rtrim()
Value stabilizer::parser::Value::rtrim () const
Definition at line 1044 of file value.cpp.
References stabilizer::parser::STRING, string_value, Value(), and value_type.
safeSqrt()
Value stabilizer::parser::Value::safeSqrt () const
Definition at line 579 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::Interval::safeSqrt(), stabilizer::parser::Number::safeSqrt(), Value(), and value_type.
sec()
Value stabilizer::parser::Value::sec () const
Definition at line 670 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::Interval::sec(), stabilizer::parser::Number::sec(), Value(), and value_type.
sech()
Value stabilizer::parser::Value::sech () const
Definition at line 814 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::Interval::sech(), stabilizer::parser::Number::sech(), Value(), and value_type.
setValue() [1/4]
void stabilizer::parser::Value::setValue (const bool & boolean_value)
Definition at line 90 of file value.cpp.
References stabilizer::parser::BOOLEAN, boolean_value, and value_type.
setValue() [2/4]
void stabilizer::parser::Value::setValue (const Interval & interval_value)
Definition at line 85 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, and value_type.
setValue() [3/4]
void stabilizer::parser::Value::setValue (const Number & number_value)
Definition at line 80 of file value.cpp.
References stabilizer::parser::NUMBER, number_value, and value_type.
setValue() [4/4]
void stabilizer::parser::Value::setValue (const std::string & string_value)
Definition at line 75 of file value.cpp.
References stabilizer::parser::STRING, string_value, and value_type.
sin()
Value stabilizer::parser::Value::sin () const
Definition at line 331 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::Interval::sin(), stabilizer::parser::Number::sin(), Value(), and value_type.
sinh()
Value stabilizer::parser::Value::sinh () const
Definition at line 769 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::Interval::sinh(), stabilizer::parser::Number::sinh(), Value(), and value_type.
sortStr()
Value stabilizer::parser::Value::sortStr () const
Definition at line 933 of file value.cpp.
References stabilizer::parser::STRING, string_value, Value(), and value_type.
split()
Value stabilizer::parser::Value::split (const Value & delimiter) const
Definition at line 979 of file value.cpp.
sqrt()
Value stabilizer::parser::Value::sqrt () const
Definition at line 364 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::Interval::sqrt(), stabilizer::parser::Number::sqrt(), Value(), and value_type.
substr()
Value stabilizer::parser::Value::substr (const Value & start, const Value & end) const
Definition at line 945 of file value.cpp.
References stabilizer::parser::NUMBER, number_value, stabilizer::parser::STRING, string_value, stabilizer::parser::HighPrecisionInteger::toInt(), stabilizer::parser::Number::toInteger(), Value(), and value_type.
tan()
Value stabilizer::parser::Value::tan () const
Definition at line 353 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::Interval::tan(), stabilizer::parser::Number::tan(), Value(), and value_type.
tanh()
Value stabilizer::parser::Value::tanh () const
Definition at line 791 of file value.cpp.
References stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::Interval::tanh(), stabilizer::parser::Number::tanh(), Value(), and value_type.
toArray()
Value stabilizer::parser::Value::toArray () const
Definition at line 1124 of file value.cpp.
toBoolean()
Value stabilizer::parser::Value::toBoolean () const
Definition at line 1101 of file value.cpp.
References stabilizer::parser::BOOLEAN, stabilizer::parser::NUMBER, number_value, stabilizer::parser::STRING, string_value, Value(), and value_type.
toBV()
Value stabilizer::parser::Value::toBV () const
Definition at line 1116 of file value.cpp.
toFP()
Value stabilizer::parser::Value::toFP () const
Definition at line 1120 of file value.cpp.
toLower()
Value stabilizer::parser::Value::toLower () const
Definition at line 1057 of file value.cpp.
References stabilizer::parser::STRING, string_value, Value(), and value_type.
toNumber()
Value stabilizer::parser::Value::toNumber () const
Definition at line 1080 of file value.cpp.
References stabilizer::parser::BOOLEAN, boolean_value, stabilizer::parser::NUMBER, stabilizer::parser::STRING, string_value, Value(), and value_type.
toString()
std::string stabilizer::parser::Value::toString () const
Definition at line 152 of file value.cpp.
References stabilizer::parser::BOOLEAN, boolean_value, stabilizer::parser::INTERVAL, interval_value, stabilizer::parser::NUMBER, number_value, stabilizer::parser::STRING, string_value, stabilizer::parser::Interval::toString(), stabilizer::parser::Number::toString(), and value_type.
toUpper()
Value stabilizer::parser::Value::toUpper () const
Definition at line 1068 of file value.cpp.
References stabilizer::parser::STRING, string_value, Value(), and value_type.
trim()
Value stabilizer::parser::Value::trim () const
Definition at line 1015 of file value.cpp.
References stabilizer::parser::STRING, string_value, Value(), and value_type.
unique()
Value stabilizer::parser::Value::unique () const
Definition at line 1000 of file value.cpp.
References stabilizer::parser::STRING, string_value, Value(), and value_type.
Member Data Documentation
boolean_value
bool stabilizer::parser::Value::boolean_value private
Definition at line 195 of file value.h.
Referenced by getBooleanValue(), operator!(), operator&&(), operator<(), operator=(), operator==(), operator||(), setValue(), toNumber(), and toString().
interval_value
Interval stabilizer::parser::Value::interval_value private
Definition at line 194 of file value.h.
Referenced by abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atanh(), cos(), cosh(), cot(), coth(), csc(), csch(), exp(), getIntervalValue(), lb(), lg(), ln(), neg(), operator%(), operator*(), operator+(), operator++(), operator-(), operator--(), operator/(), operator<(), operator=(), operator==(), operator~(), pow(), safeSqrt(), sec(), sech(), setValue(), sin(), sinh(), sqrt(), tan(), tanh(), and toString().
number_value
Number stabilizer::parser::Value::number_value private
Definition at line 193 of file value.h.
Referenced by abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atan2(), atanh(), ceil(), cos(), cosh(), cot(), coth(), csc(), csch(), exp(), floor(), getNumberValue(), lb(), lg(), ln(), log(), neg(), operator%(), operator*(), operator+(), operator++(), operator-(), operator--(), operator/(), operator<(), operator=(), operator==(), pow(), repeatStr(), round(), safeSqrt(), sec(), sech(), setValue(), sin(), sinh(), sqrt(), substr(), tan(), tanh(), toBoolean(), and toString().
string_value
std::string stabilizer::parser::Value::string_value private
Definition at line 192 of file value.h.
Referenced by concatStr(), getStringValue(), ltrim(), operator+(), operator<(), operator=(), operator==(), repeatStr(), replace(), reverse(), rtrim(), setValue(), sortStr(), substr(), toBoolean(), toLower(), toNumber(), toString(), toUpper(), trim(), and unique().
value_type
ValueType stabilizer::parser::Value::value_type private
Definition at line 197 of file value.h.
Referenced by abs(), acos(), acosh(), acot(), acoth(), acsc(), acsch(), asec(), asech(), asin(), asinh(), atan(), atan2(), atanh(), ceil(), concatStr(), cos(), cosh(), cot(), coth(), csc(), csch(), exp(), floor(), getBooleanValue(), getIntervalValue(), getNumberValue(), getStringValue(), getType(), lb(), lg(), ln(), log(), ltrim(), neg(), operator!(), operator%(), operator&(), operator&&(), operator&=(), operator*(), operator+(), operator++(), operator-(), operator--(), operator/(), operator<(), operator<<(), operator<<=(), operator=(), operator==(), operator>>(), operator>>=(), operator^(), operator^=(), operator|(), operator|=(), operator||(), operator~(), pow(), repeatStr(), replace(), reverse(), round(), rtrim(), safeSqrt(), sec(), sech(), setValue(), sin(), sinh(), sortStr(), sqrt(), substr(), tan(), tanh(), toBoolean(), toLower(), toNumber(), toString(), toUpper(), trim(), and unique().
The documentation for this class was generated from the following files:
src/parser/value.h
src/parser/value.cpp