SMTStabilizer API: stabilizer::parser::ConversionUtils Class Reference
stabilizer::parser::ConversionUtils Class Reference
Conversion and escaping helpers for parser I/O and literals.
#include <util.h>
Static Public Member Functions
static std::string toString (const Integer &i)
static std::string toString (const Real &r)
static std::string toString (const int &i)
static std::string toString (const double &d)
static std::string toString (const float &f)
static std::string toString (const long &l)
static std::string toString (const short &s)
static std::string toString (const char &c)
static std::string toString (const bool &b)
static std::string parseScientificNotation (const std::string &str)
static std::string escapeString (const std::string &s)
static std::string unescapeString (const std::string &s)
Detailed Description
Conversion and escaping helpers for parser I/O and literals.
Definition at line 176 of file util.h.
Member Function Documentation
escapeString()
std::string stabilizer::parser::ConversionUtils::escapeString (const std::string & s) static
Definition at line 1135 of file util.cpp.
Referenced by stabilizer::parser::Parser::mkConstStr().
parseScientificNotation()
std::string stabilizer::parser::ConversionUtils::parseScientificNotation (const std::string & str) static
Definition at line 148 of file util.cpp.
References stabilizer::parser::TypeChecker::isReal(), stabilizer::parser::MathUtils::pow(), and toString().
Referenced by stabilizer::parser::Parser::parseConstFunc().
toString() [1/9]
std::string stabilizer::parser::ConversionUtils::toString (const bool & b) static
Definition at line 1131 of file util.cpp.
toString() [2/9]
std::string stabilizer::parser::ConversionUtils::toString (const char & c) static
Definition at line 1128 of file util.cpp.
toString() [3/9]
std::string stabilizer::parser::ConversionUtils::toString (const double & d) static
Definition at line 1116 of file util.cpp.
toString() [4/9]
std::string stabilizer::parser::ConversionUtils::toString (const float & f) static
Definition at line 1119 of file util.cpp.
toString() [5/9]
std::string stabilizer::parser::ConversionUtils::toString (const int & i) static
Definition at line 1113 of file util.cpp.
toString() [6/9]
std::string stabilizer::parser::ConversionUtils::toString (const Integer & i) static
Definition at line 1111 of file util.cpp.
References stabilizer::parser::HighPrecisionInteger::toString().
Referenced by stabilizer::parser::Parser::mkConstInt(), stabilizer::parser::Parser::mkConstReal(), and parseScientificNotation().
toString() [7/9]
std::string stabilizer::parser::ConversionUtils::toString (const long & l) static
Definition at line 1122 of file util.cpp.
toString() [8/9]
std::string stabilizer::parser::ConversionUtils::toString (const Real & r) static
Definition at line 1112 of file util.cpp.
References stabilizer::parser::HighPrecisionReal::toString().
toString() [9/9]
std::string stabilizer::parser::ConversionUtils::toString (const short & s) static
Definition at line 1125 of file util.cpp.
unescapeString()
std::string stabilizer::parser::ConversionUtils::unescapeString (const std::string & s) static
Definition at line 1189 of file util.cpp.
Referenced by stabilizer::parser::Parser::mkConstStr().
The documentation for this class was generated from the following files:
src/parser/util.h
src/parser/util.cpp